### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir 'C:/xampp\htdocs\backoffice.yabadabadu.es\http...

### ISSUE THREAD

**Issue by MrFiregore** [icetee/remote-ftp#1000]
[Enter steps to reproduce:]

1. Connect to the remote FTP
2. Open a file

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.2.4

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\xampp\htdocs\backoffice.yabadabadu.es\httpdocs\cms\lib'

```
At C:\Users\firegore\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\xampp\htdocs\backoffice.yabadabadu.es\httpdocs\cms\lib'
    at fs.mkdirSync (fs.js:855:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:670:16)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at ConnectorFTP._getFile (/packages/Remote-FTP/lib/connectors/ftp.js:237:8)
    at /packages/Remote-FTP/lib/connectors/ftp.js:386:14
    at /packages/Remote-FTP/lib/connectors/ftp.js:227:11
    at Object.cb (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:373:5)
    at /packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:127:20)
    at emitTwo (events.js:111:20)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/parser.js:61:10)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Parser.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:298:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-clock 0.1.15 
atom-i18n 0.12.0 
atom-minify 0.8.0 
busy-signal 1.4.3 
color-picker 2.2.5 
data-atom 0.26.0 
docblockr 0.11.0 
docker 0.8.0 
emmet 2.4.3 
highlight-selected 0.13.1 
hyperclick 0.1.5 
intentions 1.1.5 
jquery-snippets 11.0.0 
language-docker 1.1.8 
linter 2.2.0 
linter-bootlint 1.1.0 
linter-jshint 3.1.6 
linter-php 1.5.1 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
php-integrator-annotations 1.2.0 
php-integrator-autocomplete-plus 1.6.0 
php-integrator-base 3.0.1 
php-integrator-navigation 1.2.1 
php-integrator-refactoring 1.4.1 
project-manager 3.3.5 
Remote-FTP 1.2.4 
symbols-tree-view 0.14.0 
```

**Comment by icetee** [comment]
Try v1.2.6!
