### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Desktop\Sts Estetik\diller'

### ISSUE THREAD

**Issue by tozsoft** [icetee/remote-ftp#1010]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.2.4

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\Tooz\Desktop\Sts Estetik\diller'

```
At C:\Users\Tooz\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\Tooz\Desktop\Sts Estetik\diller'
    at fs.mkdirSync (fs.js:855:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:670:16)
    at sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:77:24)
    at Proxy.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at ConnectorFTP._getFile (/packages/Remote-FTP/lib/connectors/ftp.js:237:8)
    at /packages/Remote-FTP/lib/connectors/ftp.js:386:14
    at /packages/Remote-FTP/lib/connectors/ftp.js:215:9
    at tryApply (/packages/Remote-FTP/lib/connectors/ftp.js:12:14)
    at /packages/Remote-FTP/lib/connectors/ftp.js:186:7
    at final (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:507:11)
    at Socket.ondone (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:482:7)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:28.7.0 tree-view:open-selected-entry (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
Remote-FTP 1.2.4 
```

**Comment by icetee** [comment]
Try v1.2.6
