### ISSUE TITLE
Uncaught TypeError: activePane.activateItemforURI is not a function

### ISSUE THREAD

**Issue by shelbyKiraM** [icetee/remote-ftp#1015]
[Enter steps to reproduce:]

1. Packages > Remote-FTP >Toggle

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13.1
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.2.5

### Stack Trace

Uncaught TypeError: activePane.activateItemforURI is not a function

```
At /Users/user/.atom/packages/Remote-FTP/lib/views/tree-view.js:281

TypeError: activePane.activateItemforURI is not a function
    at TreeView.attach (/packages/Remote-FTP/lib/views/tree-view.js:281:18)
    at TreeView.toggle (/packages/Remote-FTP/lib/views/tree-view.js:340:12)
    at HTMLElement.command (/packages/remote-ftp/lib/menus/commands.js:128:28)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1348:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:32.8.0 remote-ftp:create-sftp-config (div.tool-panel.tree-view)
     -1:28.9.0 intentions:highlight (input.hidden-input)
  3x -1:28.8.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -1:18.5.0 core:backspace (input.hidden-input)
     -1:13.5.0 core:save (input.hidden-input)
     -1:08.8.0 remote-ftp:connect (input.hidden-input)
     -0:56.6.0 core:save (input.hidden-input)
     -0:46.8.0 remote-ftp:connect (input.hidden-input)
     -0:41.8.0 intentions:highlight (input.hidden-input)
  2x -0:41.7.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -0:38.5.0 core:move-right (input.hidden-input)
  5x -0:36.8.0 core:backspace (input.hidden-input)
     -0:24 core:save (input.hidden-input)
     -0:20.8.0 remote-ftp:connect (input.hidden-input)
  2x -0:17.1.0 remote-ftp:toggle (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
atom-ctags 5.1.0 
atom-material-syntax 1.0.7 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.5 
atomic-chrome 0.3.2 
auto-indent 0.5.0 
autocomplete-ctags 0.4.1 
base16-tomorrow-night-eighties-syntax 0.12.0 
browser-refresh 0.9.0 
busy-signal 1.4.3 
case-conversion 0.2.0 
color-picker 2.2.5 
ctags-status 1.3.7 
debug 0.0.1 
dict 0.3.1 
editorconfig 2.2.2 
emmet 2.4.3 
environment 1.3.1 
file-type-icons 1.3.4 
file-types 0.5.5 
fold-functions 0.5.0 
git-control 0.9.0 
git-diff-details 1.4.0 
go-config 1.2.4 
hard-wrap 1.1.0 
Hyrule-atom 1.2.1 
intentions 1.1.5 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-ui-default 1.6.10 
marked 0.1.10 
material 2.2.0 
material-ui 1.0.10 
merge-conflicts 1.4.5 
minimap 4.29.7 
my-github-profile 0.2.1 
nucleus-dark-ui 0.12.3 
open-in-github-app 0.2.6 
php-debug 0.2.5 
pigments 0.40.2 
pretty-json 1.6.4 
Remote-FTP 1.2.5 
sass-autocompile 0.13.3 
Sass-Syntax-Highlight 0.1.1 
spacegray-tomorrowdark-ui 2.1.0 
tag 0.5.0 
term3 0.22.1 
tomorrow-evening-syntax 1.1.0 
tomorrow-night-eighties 0.5.0 
tomorrow-night-eighties-syntax 1.0.2 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.4.0 
unity-ui 2.1.11 
url-encode 0.5.0 
vagrant 0.1.0 
```

**Comment by shelbyKiraM** [comment]
Turned off "Use Dock Integration" and it just works.

**Comment by icetee** [comment]
Do you have an open project at this time?
