### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir 'C:/xampp\htdocs\001design\001design.it\002\css'

### ISSUE THREAD

**Issue by baldimario** [icetee/remote-ftp#1018]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.2.5

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\xampp\htdocs\001design\001design.it\002\css'

```
At C:\Users\localghost\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\xampp\htdocs\001design\001design.it\002\css'
    at fs.mkdirSync (fs.js:855:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:670:16)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at ConnectorFTP._getFile (/packages/remote-ftp/lib/connectors/ftp.js:237:8)
    at /packages/remote-ftp/lib/connectors/ftp.js:386:14
    at /packages/remote-ftp/lib/connectors/ftp.js:215:9
    at tryApply (/packages/remote-ftp/lib/connectors/ftp.js:12:14)
    at /packages/remote-ftp/lib/connectors/ftp.js:186:7
    at final (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:507:11)
    at Socket.ondone (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:482:7)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -3:05.9.0 core:copy (input.hidden-input)
     -2:54.7.0 core:select-all (input.hidden-input)
     -2:54.2.0 core:paste (input.hidden-input)
  2x -2:51.4.0 core:delete (input.hidden-input)
     -2:50.3.0 snippets:next-tab-stop (input.hidden-input)
     -2:50.3.0 snippets:expand (input.hidden-input)
     -2:50.3.0 editor:indent (input.hidden-input)
     -2:45.6.0 core:cut (input.hidden-input)
     -2:45.4.0 core:save (input.hidden-input)
  2x -2:42.4.0 editor:newline (input.hidden-input)
     -2:36.2.0 core:save (input.hidden-input)
     -1:46.8.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -1:44.8.0 core:confirm (input.hidden-input)
     -1:37.1.0 remote-ftp:refresh-selected (div.header.list-item)
  2x -1:32.8.0 core:save (input.hidden-input)
     -0:27.6.0 remote-ftp:disconnect (div.header.list-item)
```

### Non-Core Packages

```
Remote-FTP 1.2.5 
```

**Comment by icetee** [comment]
Try v1.2.6!
