### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hostName' of null

### ISSUE THREAD

**Issue by alek10c** [icetee/remote-ftp#1029]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.2.6

### Stack Trace

Uncaught TypeError: Cannot read property 'hostName' of null

```
At C:\Users\alek1\.atom\packages\Remote-FTP\lib\client.js:150

TypeError: Cannot read property 'hostName' of null
    at Client.setProjectName (/packages/Remote-FTP/lib/client.js:150:27)
    at /packages/Remote-FTP/lib/client.js:138:16
    at ~/AppData/Local/atom/app-1.21.1/resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (~/AppData/Local/atom/app-1.21.1/resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (~/AppData/Local/atom/app-1.21.1/resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (~/AppData/Local/atom/app-1.21.1/resources/app/src/config.js:248:20)
    at SettingsPanel.set (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/settings-view/lib/settings-panel.js:237:27)
    at HTMLSelectElement.changeHandler (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/settings-view/lib/settings-panel.js:251:24)
```

### Commands

```
  2x -5:19.2.0 application:open-folder (input.hidden-input)
     -3:22.8.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -2:40.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
language-blade 0.36.0 
language-vue 0.23.1 
laravel 0.7.1 
laravel-snippets 2.1.0 
Remote-FTP 1.2.6 
```

**Comment by icetee** [comment]
How can I reproduce it?

**Comment by TomS-** [comment]
@icetee create a new project, do not create a ftpconfig file. Go to settings and set the page tree name to hostName. Since the ftpconfig file doesn't exist it can't check if hostName exists. 

On another note, hostName isn't automatically added. This is quite good to add a human readable label to FTP connections. It should be automatically in the .ftpconfig file. At the moment you have to manually type it into the json.
