### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by lundmorten** [icetee/remote-ftp#1034]
[Enter steps to reproduce:]

1. Rightclick on file -> Download

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.2.6

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /Users/ml/.atom/packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:909

TypeError: Cannot read property '0' of null
    at Object.cb (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:909:44)
    at /packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:127:20)
    at emitTwo (events.js:111:20)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/parser.js:61:10)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Parser.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:298:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -1:30.4.0 core:close (input.hidden-input)
     -0:10.5.0 remote-ftp:download-selected-local (span.name.icon.html5-icon.medium-orange)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
autocomplete-paths 2.12.1 
file-icons 2.1.13 
language-cshtml 0.3.0 
minimap 4.29.7 
Remote-FTP 1.2.6 
```

**Comment by icetee** [comment]
I think this can happen when the server returns to support extended passive mode, but it does not return the port. Which server do you use?

https://github.com/icetee/node-ftp/blob/07d7d72531f708bcc15f412b7d611cec8f803097/lib/connection.js#L908-L929
