### ISSUE TITLE
Uncaught Error: No `protocol` found in connection credential. Please recreate .ftpconfig file fro...

### ISSUE THREAD

**Issue by alyona-** [icetee/remote-ftp#1038]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.2.6

### Stack Trace

Uncaught Error: No `protocol` found in connection credential. Please recreate .ftpconfig file from Packages -> Remote-FTP -> Create (S)FTP config file.

```
At /Users/connect/.atom/packages/Remote-FTP/lib/client.js:450

Error: No `protocol` found in connection credential. Please recreate .ftpconfig file from Packages -> Remote-FTP -> Create (S)FTP config file.
    at Client.doConnect (/packages/Remote-FTP/lib/client.js:450:17)
    at Client.connect (/packages/Remote-FTP/lib/client.js:355:14)
    at /packages/Remote-FTP/lib/views/tree-view.js:239:32)
    at /packages/Remote-FTP/lib/client.js:230:22
    at tryToString (fs.js:426:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
```

### Commands

```
  2x -2:49.5.0 core:backspace (input.hidden-input)
     -2:24.6.0 core:paste (input.hidden-input)
  3x -2:22.9.0 core:backspace (input.hidden-input)
     -1:53.2.0 core:paste (input.hidden-input)
     -1:49.6.0 core:copy (input.hidden-input)
  2x -1:46.6.0 core:paste (input.hidden-input)
 12x -0:57.7.0 core:backspace (input.hidden-input)
     -0:37.5.0 core:save (input.hidden-input)
  2x -0:27.6.0 core:backspace (input.hidden-input)
     -0:25.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
asciidoc-preview 2.10.3 
atom-beautify 0.30.5 
atom-html-preview 0.2.2 
auto-encoding 0.7.0 
autoclose-html 0.23.0 
color-picker 2.2.5 
emmet 2.4.3 
export-html 3.1.0 
file-icons 2.1.13 
flex-tool-bar 0.12.0 
fold-lines 0.2.2 
gulp-control 0.5.0 
highlight-selected 0.13.1 
indent-guide-improved 1.4.13 
language-qml 1.0.0 
markdown-preview-plus-opener 0.2.0 
markdown-writer 2.7.3 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
minimap-split-diff 0.3.7 
multi-cursor 2.1.5 
multi-wrap-guide 1.0.0 
open-in-browsers 0.0.30 
path-copy 0.14.0 
pdf-view 0.59.0 
remote-atom 1.3.11 
Remote-FTP 1.2.6 
remote-sync 4.1.8 
sass-autocompile 0.13.3 
simple-drag-drop-text 0.3.6 
simplified-russian-menu 1.3.0 
sort-lines 0.18.0 
sorter 1.1.0 
split-diff 1.5.1 
tab-switcher 1.5.6 
toggler 0.3.0 
tool-bar 1.1.0 
```

**Comment by alyona-** [comment]
11
