### ISSUE TITLE
[DEP0022] DeprecationWarning: os.tmpDir() is deprecated.

### ISSUE THREAD

**Issue by darkogerguric** [icetee/remote-ftp#1044]
Hi I have this error when trying to update 
Arch Linux 64
Latest Atom

(node:4635) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

fs.js:648
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/darko/.atom/packages/Remote-FTP/package.json'
    at Object.fs.openSync (fs.js:648:18)
    at Proxy.fs.readFileSync (fs.js:553:33)
    at Proxy.fs.readFileSync (/usr/lib/node_modules/atom-package-manager/node_modules/asar-require/lib/require.js:86:27)
    at /usr/lib/node_modules/atom-package-manager/lib/install.js:476:42
    at fn (/usr/lib/node_modules/atom-package-manager/node_modules/async/lib/async.js:582:34)
    at Immediate._onImmediate (/usr/lib/node_modules/atom-package-manager/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)

**Comment by darkogerguric** [comment]
Actually it got deleted after error and I am not able to install it anymore, same error on install.

**Comment by icetee** [comment]
Maybe related of https://github.com/atom/atom/issues/13476
Remote-FTP no use os.tmpDir function.

**Comment by darkogerguric** [comment]
Worked so far?
Any chance to be fixed?
Can I get an older version and install manually since it worked until I tried to update?

**Comment by icetee** [comment]
The old version install:
```
apm remove remote-ftp
apm install remote-ftp@1.1.3
```

--
Which was the latest version that was still working?

**Comment by darkogerguric** [comment]
Thank you
