### ISSUE TITLE
Uncaught TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by lucianchauvin** [icetee/remote-ftp#1045]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

[Description of the issue]

### Steps to Reproduce

1. [Edit Any File]
2. [Save]

**Expected behavior:** [The file to be saved to my remote server]

**Actual behavior:** [Causes error and timesout]

**Reproduces how often:** [All the time]

### Versions

You can get this information from copy and pasting the output of `atom --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At C:\Users\lucia\.atom\packages\Remote-FTP\lib\connectors\sftp.js:406

TypeError: Cannot read property 'message' of undefined
    at /packages/Remote-FTP/lib/connectors/sftp.js:406:33)
    at emitOne (events.js:101:20)
    at WriteStream.emit (events.js:188:7)
    at /packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:2853:12
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:415:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SFTPStream.Writable.write (_stream_writable.js:245:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3444:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SSH2Stream.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -1:20 command-palette:toggle (atom-pane.pane)
 49x -1:11 core:backspace (input.hidden-input)
     -0:08.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
Remote-FTP 1.3.1 
```

**Comment by circuitcreature** [comment]
Also received this error. After some digging the message that was return from the server was permission denied, that was causing this bug.

**Comment by RebelDesign** [comment]
Just checked permissions and realized that was the error.

**Comment by too-gee** [comment]
I can confirm that this is a permissions issue.  If you're having this issue, try setting the file that's giving you issues to 777 on the remote server.  If that fixes things, you're probably looking at permissions problems as well.

**Comment by Cl0nki** [comment]
It happens if you try to save a file and don't have the permissions to write

**Comment by icetee** [comment]
The next version will include the fix (Supported change permissions in SFTP). I close this issue.

**Comment by wmelton** [comment]
@icetee Updated to latest version. Still getting exception:
`.atom/packages/Remote-FTP/lib/connectors/sftp.js:425`
```
TypeError: Cannot read property 'message' of undefined
    at WriteStream.<anonymous> (/Users/User/.atom/packages/Remote-FTP/lib/connectors/sftp.js:425:28)
    at emitOne (events.js:101:20)
    at WriteStream.emit (events.js:188:7)
    at /Users/User/.atom/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:2853:12
    at SFTPStream._transform (/Users/User/.atom/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:415:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/Users/User/.atom/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SFTPStream.Writable.write (_stream_writable.js:245:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at SSH2Stream.<anonymous> (/Users/User/.atom/packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/Users/User/.atom/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3444:10)
    at SSH2Stream._transform (/Users/User/.atom/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/Users/User/.atom/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SSH2Stream.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)```

**Comment by GalacticSun** [comment]
[Enter steps to reproduce:]

1. Opened a file on sftp server (AWS)
2. Made a change, tried to save the file, but Atom / Remote-FTP crashes...
Please fix!

**Atom**: 1.23.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 2.1.1


### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At /Users/me/.atom/packages/Remote-FTP/lib/connectors/sftp.js:425

TypeError: Cannot read property 'message' of undefined
    at /packages/Remote-FTP/lib/connectors/sftp.js:425:28)
    at emitOne (events.js:101:20)
    at WriteStream.emit (events.js:188:7)
    at /packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:2853:12
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:415:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SFTPStream.Writable.write (_stream_writable.js:245:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3444:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SSH2Stream.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -1:39.5.0 find-and-replace:show (input.hidden-input)
     -1:38.4.0 core:confirm (input.hidden-input)
     -1:37 find-and-replace:find-next (input.hidden-input)
     -1:32.7.0 core:paste (input.hidden-input)
     -1:31.5.0 core:save (input.hidden-input)
     -0:27.7.0 core:close (input.hidden-input)
     -0:21.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
Remote-FTP 2.1.1 
```

**Comment by GalacticSun** [comment]
Might need to re-open this issue.  Thanks!

**Comment by EvanHerman** [comment]
Still encountering this issue after an update.

**Comment by wmelton** [comment]
No - appears to have been resolved!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by GalacticSun** [comment]
Nope, just got it again:

(also, as a side note, when I updated to the most recent update of Remote-FTP, it gave me an error saying "failed to update package", which then removed it from Atom completely.  I had to re-install this package.  Then I tried it again and got this error.  Thanks.)

[Enter steps to reproduce:]

1. Connect to SFTP server
2. Open file from tree view browser on server
3. Edit file
4. Save file.

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package undefined


### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At /Users/me/.atom/packages/Remote-FTP/lib/connectors/sftp.js:425

TypeError: Cannot read property 'message' of undefined
    at /packages/Remote-FTP/lib/connectors/sftp.js:425:28)
    at emitOne (events.js:101:20)
    at WriteStream.emit (events.js:188:7)
    at /packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:2853:12
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:415:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SFTPStream.Writable.write (_stream_writable.js:245:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3444:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SSH2Stream.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -3:19.1.0 core:close (input.hidden-input)
  2x -2:08.5.0 tree-view:toggle (atom-pane.pane)
     -2:03.0 tree-view:unfocus (div.tool-panel.tree-view)
 20x -1:22.8.0 core:backspace (input.hidden-input)
     -0:57.8.0 core:confirm (input.hidden-input)
     -0:05.7.0 core:backspace (input.hidden-input)
     -0:04.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
remote-ftp 2.1.2 
```

**Comment by GalacticSun** [comment]
It looks like it might be due to, at least in part, the permissions of the file being edited.  When trying to edit a file I don't have permission to overwrite it appears to throw this error.  Hope this helps.

**Comment by EvanHerman** [comment]
I thought I was encountering the same issue as well, but deleted my original message because I too was also having permissions issues unrelated to the package.

**Comment by iqmal852** [comment]
Hi guys, I'm solve this issue by giving permission on server side, Good luck

**Comment by juancybexmedia** [comment]
I just want to add that this error can raise if the **disk drive is full** and plugin is unable to save the file content.
