### ISSUE TITLE
Uncaught TypeError: view.dragEventsDestroy is not a function

### ISSUE THREAD

**Issue by rmagnuson** [icetee/remote-ftp#1075]
[Enter steps to reproduce:]

1. Go to Atom settings
2. Open settings for FTP
3. Deselect "Enable Drag and Drop"
4. Bang!

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 2.0.0

### Stack Trace

Uncaught TypeError: view.dragEventsDestroy is not a function

```
At C:\Users\rafe\.atom\packages\Remote-FTP\lib\views\tree-view.js:369

TypeError: view.dragEventsDestroy is not a function
    at /packages/Remote-FTP/lib/views/tree-view.js:369:12
    at Array.forEach (native)
    at TreeView.disposeDragAndDrops (/packages/Remote-FTP/lib/views/tree-view.js:368:26)
    at /packages/Remote-FTP/lib/views/tree-view.js:189:14
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (~/AppData/Local/atom/app-1.22.1/resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (~/AppData/Local/atom/app-1.22.1/resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (~/AppData/Local/atom/app-1.22.1/resources/app/src/config.js:248:20)
    at SettingsPanel.set (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/settings-panel.js:237:27)
    at HTMLInputElement.changeHandler (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/settings-panel.js:174:25)
```

### Commands

```
     -9:23.4.0 application:add-project-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -9:14.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -9:14.8.0 remote-ftp:disconnect (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -9:14.8.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -9:06.8.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -9:06.7.0 remote-ftp:disconnect (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -9:06.7.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
  2x -8:24.1.0 remote-ftp:toggle (div.tool-panel.tree-view)
     -6:05.2.0 application:add-project-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:50.5.0 remote-ftp:disconnect (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -5:50.5.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
  2x -4:13.9.0 remote-ftp:disconnect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
atom-beautify 0.30.9 
atom-clock 0.1.15 
atom-live-server 2.2.0 
atom-music 0.7.0 
atom-runner 2.7.1 
atom-vagrant-manager 1.0.4 
busy-signal 1.4.3 
city-lights-syntax 1.1.4 
city-lights-ui 1.2.0 
color-picker 2.2.5 
file-icons 2.1.14 
flex-tool-bar 0.12.0 
git-plus 7.10.0 
highlight-line 0.12.0 
intentions 1.1.5 
jackhammer-syntax 1.1.0 
jquery-snippets 11.0.0 
linter 2.2.0 
linter-eslint 8.4.0 
linter-php 1.5.1 
linter-ui-default 1.6.10 
markdown-preview-enhanced 0.15.1 
minimap 4.29.7 
noop-syntax 0.5.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
now-syntax 0.2.4 
open-in-browser 0.5.2 
peacocks-in-space-syntax 0.7.0 
platformio-ide-terminal 2.7.0 
project-manager 3.3.5 
Remote-FTP 2.0.0 
spacegray-atom-dark-syntax 1.3.2 
spacegray-dark-ui 0.13.0 
tool-bar 1.1.0 
tool-bar-main 0.0.10 
```

**Comment by icetee** [comment]
Thanks for reported. Included the fix in new version.
