### ISSUE TITLE
Failed to activate the Remote-FTP package [Cannot read property 'destroy' of undefined]

### ISSUE THREAD

**Issue by svvIrkLife** [icetee/remote-ftp#1077]
After update new version remote-ftp 2.1.0

Atom Version: 1.22.1 x64
System: win10
Thrown From: Remote-FTP package, v2.1.0
 TypeError: Cannot read property 'destroy' of undefined
    at Object.deactivate (file:///C:/Users/abrokis/.atom/packages/Remote-FTP/lib/remote-ftp.js:134:29)
    at Object.activate (file:///C:/Users/abrokis/.atom/packages/Remote-FTP/lib/remote-ftp.js:26:12)
    at Package.module.exports.Package.activateNow (C:\Users\abrokis\AppData\Local\atom\app-1.22.1\resources\app\src\package.js:253:25)
    at C:\Users\abrokis\AppData\Local\atom\app-1.22.1\resources\app\src\package.js:225:38
    at Package.module.exports.Package.measure (C:\Users\abrokis\AppData\Local\atom\app-1.22.1\resources\app\src\package.js:99:21)
    at C:\Users\abrokis\AppData\Local\atom\app-1.22.1\resources\app\src\package.js:218:32
    at Package.module.exports.Package.activate (C:\Users\abrokis\AppData\Local\atom\app-1.22.1\resources\app\src\package.js:215:40)
    at PackageManager.activatePackage (C:\Users\abrokis\AppData\Local\atom\app-1.22.1\resources\app\src\package-manager.js:690:42)
    at packagesToEnable.forEach.name (C:\Users\abrokis\AppData\Local\atom\app-1.22.1\resources\app\src\package-manager.js:439:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (C:\Users\abrokis\AppData\Local\atom\app-1.22.1\resources\app\src\package-manager.js:439:30)
    at C:\Users\abrokis\AppData\Local\atom\app-1.22.1\resources\app\src\config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\abrokis\AppData\Local\atom\app-1.22.1\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\abrokis\AppData\Local\atom\app-1.22.1\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\abrokis\AppData\Local\atom\app-1.22.1\resources\app\src\config.js:884:35)
    at Config.module.exports.Config.setRawValue (C:\Users\abrokis\AppData\Local\atom\app-1.22.1\resources\app\src\config.js:670:25)
    at Config.module.exports.Config.set (C:\Users\abrokis\AppData\Local\atom\app-1.22.1\resources\app\src\config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (C:\Users\abrokis\AppData\Local\atom\app-1.22.1\resources\app\src\config.js:407:18)
    at Package.module.exports.Package.enable (C:\Users\abrokis\AppData\Local\atom\app-1.22.1\resources\app\src\package.js:84:32)
    at PackageManager.enablePackage (C:\Users\abrokis\AppData\Local\atom\app-1.22.1\resources\app\src\package-manager.js:245:18)
    at HTMLButtonElement.enablementButtonClickHandler (C:\Users\abrokis\AppData\Local\atom\app-1.22.1\resources\app\node_modules\settings-view\lib\package-card.js:361:31

**Comment by icetee** [comment]
Do you have the opportunity to test this? https://github.com/icetee/remote-ftp/commit/24ed6c2613cfeb0d4e53c156ec3b1923539d8595

**Comment by ginus** [comment]
+1

**Comment by svvIrkLife** [comment]
Thanks, GOD
