### ISSUE TITLE
Uncaught ReferenceError: reentry is not defined

### ISSUE THREAD

**Issue by jaycelcunanan** [icetee/remote-ftp#1078]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 8.1 Single Language
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 2.1.1

### Stack Trace

Uncaught ReferenceError: reentry is not defined

```
At C:\Users\Jaycel Cunanan\.atom\packages\Remote-FTP\node_modules\@icetee\ftp\lib\connection.js:937

ReferenceError: reentry is not defined
    at /packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:937:18
    at /packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:996:7)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -0:50.1.0 tree-view:remove (span.name.icon.icon-file-text)
     -0:42.3.0 remote-ftp:create-ftp-config (div.tool-panel.tree-view)
  3x -0:24.8.0 core:paste (input.hidden-input)
     -0:16.9.0 core:save (input.hidden-input)
     -0:13.5.0 remote-ftp:connect (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
Remote-FTP 2.1.1 
```

**Comment by egirlasm** [comment]
same issue

**Comment by hanzinhee** [comment]
same issue

**Comment by moshebendavid** [comment]
same issue

**Comment by iampatrick** [comment]
Same.  :)

**Comment by antonfeijoomontenegro** [comment]
Same issue.

**Comment by kentaro-a** [comment]
I have the same..

**Comment by ol1s** [comment]
Same issue with AWS server.
Interestingly the exception does not occur when testing with Remote-FTP v1.3.4

**Comment by jovicon** [comment]
@Haylin-chama did you find any solution? I have same issue. :(

**Comment by icetee** [comment]
Can you help reproduction? Create an S3?

**Comment by Haylin-chama** [comment]
@jovicon 
No, because AWS needs a public key and i don't know how to add it to the .ftpconfig file.

**Comment by icetee** [comment]
Create [authorized_keys](https://askubuntu.com/questions/466549/bash-home-user-ssh-authorized-keys-no-such-file-or-directory) file, use SFTP config and set `privatekey` property `~/.ssh/rsa_id` https://github.com/icetee/remote-ftp/issues/1151

**Comment by james090500** [comment]
Any Updates on this? Only does it with one of my servers which works fine in filezilla

**Comment by Ray-Eldath** [comment]
same ((( Any updates ?

**Comment by supraniti** [comment]
+1

**Comment by wolfkang** [comment]
Hi,
I modified line 907 in the connection.js file.

C:\Users\ [User Home] \\.atom\packages\remote-ftp\node_modules\@icetee\ftp\lib\connection.js

Before
`  this._send(pasvCmd, function (err, text) {`

After
`  this._send(pasvCmd, function reentry(err, text) {`

Good luck :)

**Comment by AlejandroMataGuillen** [comment]
I'm experimenting this issue from promise-ftp library, when I use the solution from @wolfkang it works well, is there some workaround for that without edit the file manually because I need to ship my project with docker

**Comment by StockDave** [comment]
> Hi,
> I modified line 907 in the connection.js file.
> 
> C:\Users\ [User Home] \.atom\packages\remote-ftp\node_modules@icetee\ftp\lib\connection.js
> 
> Before
> ` this._send(pasvCmd, function (err, text) {`
> 
> After
> ` this._send(pasvCmd, function reentry(err, text) {`
> 
> Good luck :)

works well on node apps, thanks

**Comment by robertandrews** [comment]
Suddenly appearing.

```
Uncaught ReferenceError: reentry is not defined
/Users/Robert/.atom/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:943
Hide Stack Trace
ReferenceError: reentry is not defined
    at /Users/Robert/.atom/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:943:11
    at Socket.<anonymous> (/Users/Robert/.atom/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:1002:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:554:12)
The error was thrown from the remote-ftp package. This issue has already been reported.
```

@wolfkang's fix seems to work.

**Comment by JLRishe** [comment]
It looks like this issue was [fixed](https://github.com/icetee/node-ftp/commit/a3c0efd2a071c3d822afe5f22711285162391cf8) around version 1.0.6 of @icetee/node-ftp, and this library was updated to use version 1.0.7 about a year ago.

With that in mind, the offending code was in some error handling code that is only run when there is a failure to establish a passive connection. So if you were seeing this error, it may mean that your FTP server is misconfigured (e.g. it is reporting the wrong passive connection IP address).

**Comment by Fogrunner** [comment]
C:\Users\Morgan\.atom\packages\remote-ftp\node_modules\@icetee\ftp\lib\connection.js:947
Hide Stack Trace
ReferenceError: reentry is not defined
    at C:\Users\Morgan\.atom\packages\remote-ftp\node_modules\@icetee\ftp\lib\connection.js:947:11
    at C:\Users\Morgan\.atom\packages\remote-ftp\node_modules\@icetee\ftp\lib\connection.js:972:9

It is still happened to me. After logged, it is hanging on getting list. I am using 2.2.4 version.

It is only happened on specific Amazon server. I have tested to access the ftp server with another application. The application works well without any problem.

**Comment by Fogrunner** [comment]
If someone has the same problem, use sftp connection way with Amazon key-pair.


Below is the sample configuration:

{
    "protocol": "sftp",
    "host": "[YOUR SERVER ADDRESS HERE]",  // example.co.kr
    "port": 22,
    "user": "[YOUR ACCOUNT NAME HERE]",   // steven
    "pass": "pass",
    "promptForPass": false,
    "remote": "[YOUR HOME DIRECTORY ON THE SERVER]",  // /home/steven
    "local": "",
    "agent": "",
    "privatekey": "[YOUR KEY PAIR FILE LOCAL PATH HERE]",  // c:\amazon-keypairs\mykey.pem
    "passphrase": "",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": false,
    "keyboardInteractiveForPass": false,
    "remoteCommand": "",
    "remoteShell": "",
    "watch": [],
    "watchTimeout": 500
}
