### ISSUE TITLE
Failed to activate the Remote-FTP package / Cannot read property 'left' of undefined

### ISSUE THREAD

**Issue by danhil1981** [icetee/remote-ftp#1079]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

Can't install Remote FTP on my Atom Portable Installation

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Unknown Windows Version
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package, v2.1.1

### Stack Trace

Failed to activate the Remote-FTP package

```
At Cannot read property 'left' of undefined

TypeError: Cannot read property 'left' of undefined
    at Object.activate (file:///E:/LM/AtomPortable_1.13.1/Data/atom/packages/remote-ftp-2.1.1/lib/remote-ftp.js:50:36)
    at Package.module.exports.Package.activateNow (E:\LM\AtomPortable_1.13.1\App\Atom\resources\app.asar\src\package.js:191:19)
    at E:\LM\AtomPortable_1.13.1\App\Atom\resources\app.asar\src\package.js:164:32
    at Package.module.exports.Package.measure (E:\LM\AtomPortable_1.13.1\App\Atom\resources\app.asar\src\package.js:94:15)
    at E:\LM\AtomPortable_1.13.1\App\Atom\resources\app.asar\src\package.js:157:26
    at Package.module.exports.Package.activate (E:\LM\AtomPortable_1.13.1\App\Atom\resources\app.asar\src\package.js:154:34)
    at PackageManager.module.exports.PackageManager.activatePackage (E:\LM\AtomPortable_1.13.1\App\Atom\resources\app.asar\src\package-manager.js:550:34)
    at E:\LM\AtomPortable_1.13.1\App\Atom\resources\app.asar\src\package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (E:\LM\AtomPortable_1.13.1\App\Atom\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (E:\LM\AtomPortable_1.13.1\App\Atom\resources\app.asar\src\package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (E:\LM\AtomPortable_1.13.1\App\Atom\resources\app.asar\src\package-manager.js:508:46)
    at E:\LM\AtomPortable_1.13.1\App\Atom\resources\app.asar\src\atom-environment.js:831:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "fileEncoding": "windows1252",
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v2.1.1 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.14.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.33.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.43.2 (inactive)
bracket-matcher, v0.85.1 (inactive)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.2.0 (inactive)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.1 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (inactive)
metrics, v1.1.3 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.5 (inactive)
status-bar, v1.6.0 (inactive)
styleguide, v0.48.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.211.1 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

### Steps to Reproduce

1. Install Atom Portable
2. Install Remote-FTP Plugin

**Expected behavior:** 

Installation of Package

**Actual behavior:** 

Installation Incomplete

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

1.13.1

Windows 7 x64

**Comment by icetee** [comment]
Hallo @danhil1981 the package 2.x version no supported your old Atom version.
https://github.com/icetee/remote-ftp/blob/0d5bb2517da728ed106ab3e6c93f211c0a736d32/package.json#L9-L11

Use 1.x releases. [v1.3.4](https://github.com/icetee/remote-ftp/releases/tag/v1.3.4)
