### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Documents\Atom projects\[sitename\\cdn.[sitename]...

### ISSUE THREAD

**Issue by Duncank** [icetee/remote-ftp#1080]
[Enter steps to reproduce:]

1. Connect to a server with multiple domains (cdn.sitename.nl, app.sitename.nl, dashboard.sitename.nl in this case)
2. Create /js/script.js in one domain, then do the same for another domain.
3. This error occurs.

**Atom**: 1.23.0 ia32
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 2.1.1

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\Duncan\Documents\Atom projects\[sitename]\cdn.[sitename].nl\public_html\js'

```
At C:\Users\Duncan\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\Duncan\Documents\Atom projects\[sitename]\cdn.[sitename].nl\public_html\js'
    at fs.mkdirSync (fs.js:855:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:670:16)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at /packages/Remote-FTP/lib/connectors/sftp.js:294:12
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:501:15)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SFTPStream.Writable.write (_stream_writable.js:245:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3444:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SSH2Stream.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.9 
autoclose-html 0.23.0 
autoprefixer 3.7.1 
highlight-selected 0.13.1 
jshint 1.8.6 
monokai-seti 0.9.0 
project-viewer 1.2.5 
Remote-FTP 2.1.1 
seti-ui 1.9.0 
sync-settings 0.8.3 
```

**Comment by Duncank** [comment]
Update: I've discovered what went wrong:
- I accidentally created a file called "js" when I actually wanted to create a new folder called "js".
- I deleted the file "js" and it dissappeared on the remote host, but apparently it was not deleted locally, causing the above mentioned problem. After deleting the file locally the problem went away.
