### ISSUE TITLE
Update to 2.1.2 fails

### ISSUE THREAD

**Issue by Sternberg** [icetee/remote-ftp#1086]
Can't update from 2.1.1 to 2.1.2:

Updating to “Remote-FTP@2.1.2” failed.Hide output…
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
Error: ENOENT: no such file or directory, open '/Users/xxxxxxxx/.atom/packages/remote-ftp/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/lib/require.js:86:27)
    at /Applications/Atom.app/Contents/Resources/app/apm/lib/install.js:476:42
    at fn (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

### Versions
Mac OS High Sierra 10.13.2. Atom Version 1.23.1. Remote-Ftp Version 2.1.1.

Any help is greatly appreciated.

**Comment by icetee** [comment]
Please try remove and install the plugin. Name change was due to a similar error.

**Comment by Sternberg** [comment]
@icetee That worked! Thanks a lot!
