### ISSUE TITLE
Uncaught Error: The workspace can only contain one instance of item [object Object]

### ISSUE THREAD

**Issue by Sebastianbxa** [icetee/remote-ftp#1090]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 ia32
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.1.2

### Stack Trace

Uncaught Error: The workspace can only contain one instance of item [object Object]

```
At C:\Users\Magnolia Maria\AppData\Local\atom\app-1.23.1\resources\app\src\item-registry.js:11

Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (~/AppData/Local/atom/app-1.23.1/resources/app/src/item-registry.js:11:21)
    at PaneContainer.didAddPaneItem (~/AppData/Local/atom/app-1.23.1/resources/app/src/pane-container.js:269:29)
    at Pane.addItem (~/AppData/Local/atom/app-1.23.1/resources/app/src/pane.js:632:48)
    at TreeView.attach (/packages/remote-ftp/lib/views/tree-view.js:216:29)
    at TreeView.toggle (/packages/remote-ftp/lib/views/tree-view.js:267:12)
    at HTMLElement.command (/packages/remote-ftp/lib/menus/commands.js:131:28)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.1/resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.23.1/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.23.1/resources/app/src/atom-environment.js:1393:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.23.1/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:14.5.0 tabs:close-tab (div.title)
  3x -0:36.7.0 remote-ftp:toggle (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:01.2.0 remote-ftp:disconnect (atom-pane.pane.active)
```

### Non-Core Packages

```
chester-atom-syntax 0.3.0 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.15 
gloom 0.6.4 
pristine-ui 1.1.11 
ramda-syntax 1.0.4 
remote-ftp 2.1.2 
```

**Comment by NoahNok** [comment]
@icetee Im currently getting this bug. It it still a known bug?
