### ISSUE TITLE
SFTP connect for ubuntu server 

### ISSUE THREAD

**Issue by sametsirinel** [icetee/remote-ftp#1097]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At C:\Users\Toshiba\.atom\packages\remote-ftp\lib\connectors\sftp.js:425

TypeError: Cannot read property 'message' of undefined
    at /packages/remote-ftp/lib/connectors/sftp.js:425:28)
    at emitOne (events.js:101:20)
    at WriteStream.emit (events.js:188:7)
    at /packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:2853:12
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:415:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SFTPStream.Writable.write (_stream_writable.js:245:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/remote-ftp/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:3444:10)
    at SSH2Stream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SSH2Stream.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
  2x -3:06.1.0 application:open-folder (input.hidden-input)
     -2:51.6.0 tree-view:remove (div.tool-panel.tree-view)
     -2:41.9.0 remote-ftp:create-sftp-config (atom-pane.pane)
  4x -2:36 core:backspace (input.hidden-input)
     -2:31 core:save (input.hidden-input)
     -2:25.5.0 core:move-down (input.hidden-input)
  2x -2:25.2.0 core:move-left (input.hidden-input)
     -2:24.8.0 editor:select-to-beginning-of-word (input.hidden-input)
     -2:23.8.0 core:backspace (input.hidden-input)
     -2:22.5.0 core:save (input.hidden-input)
     -2:21.3.0 core:close (input.hidden-input)
     -2:17.4.0 remote-ftp:toggle (atom-pane.pane)
  2x -1:54.9.0 remote-ftp:delete-selected (span.name.icon.icon-file-text)
  2x -1:30.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
emmet 2.4.3 
project-manager 3.3.5 
remote-ftp 2.1.2 
```

**Comment by icetee** [comment]
Maybe resolve https://github.com/icetee/remote-ftp/issues/1045#issuecomment-355193612?
