### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Documents\GitHub\MuraCMS'

### ISSUE THREAD

**Issue by jsieber** [icetee/remote-ftp#1099]
[Enter steps to reproduce:]

1. Install and configure remote-ftp. The configuration was working with a previous version.
2. Attempt to download a file to project from remote.

**Atom**: 1.23.1 ia32
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.1.2

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\jsieber\Documents\GitHub\MuraCMS'

```
At C:\Users\jsieber\.atom\packages\remote-ftp\node_modules\mkdirp\index.js:90

Error: EEXIST: file already exists, mkdir 'C:\Users\jsieber\Documents\GitHub\MuraCMS'
    at fs.mkdirSync (fs.js:855:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:670:16)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:77:24)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
    at sync (/packages/remote-ftp/node_modules/mkdirp/index.js:78:17)
```

### Commands

```
     -0:17.5.0 remote-ftp:download-selected-local (span.name.icon.icon-file-text)
     -0:17.5.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:16.5.0 remote-ftp:download-selected-local (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-cfml 0.5.0 
language-cfml 0.17.1 
mura-snippets 0.1.0 
remote-ftp 2.1.2 
```

**Comment by jsieber** [comment]
After digging into this further it appears that it was trying to download the file into a different project. After enabling multiple hosts the error has stopped occurring.
