### ISSUE TITLE
Failed to load the remote-ftp package

### ISSUE THREAD

**Issue by vineetbamania** [icetee/remote-ftp#1104]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.1.4

### Stack Trace

Failed to load the remote-ftp package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.23.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.23.2/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.23.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:11:7)
    at /packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:721:4)
    at /packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:723:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.23.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.23.2/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.23.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/remote-ftp/lib/client.js:11:15)
    at /packages/remote-ftp/lib/client.js:20:28)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.23.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.23.2/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.23.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/remote-ftp/lib/remote-ftp.js:4:24)
    at /packages/remote-ftp/lib/remote-ftp.js:237:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.23.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.23.2/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

### Commands

```
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-beautify 0.30.9 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.1 
atom-typescript 11.0.10 
atom-uikit 1.2.2 
autoclose-html 0.23.0 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
color-picker 2.2.5 
compare-files 0.8.1 
define-jump 1.0.1 
file-icons 2.1.15 
intentions 1.1.5 
language-scala 1.1.9 
linter 2.2.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
platformio-ide-terminal 2.8.0 
python-tools 0.6.9 
remote-ftp 2.1.4 
semantic-ui 1.0.9 
seti-syntax 1.1.3 
seti-ui 1.9.0 
split-diff 1.5.2 
```

**Comment by icetee** [comment]
Try re-install or move to folder in cmd and run this command: `apm install`.
