### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/Desktop/JobSearchBot/node_modules/.bin...

### ISSUE THREAD

**Issue by erniecho** [icetee/remote-ftp#1135]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.1.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/erniecho/Desktop/JobSearchBot/node_modules/.bin/which'

```
At fs.js:912

Error: ENOENT: no such file or directory, stat '/Users/erniecho/Desktop/JobSearchBot/node_modules/.bin/which'
    at fs.statSync (fs.js:912:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:280:16)
    at localFilePrepare (/packages/remote-ftp/lib/helpers.js:110:22)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:142:19)
    at ConnectorSFTP.put (/packages/remote-ftp/lib/connectors/sftp.js:465:9)
    at /packages/remote-ftp/lib/client.js:717:24)
    at Client._next (/packages/remote-ftp/lib/client.js:625:39)
    at Client._enqueue (/packages/remote-ftp/lib/client.js:637:56)
    at /packages/remote-ftp/lib/client.js:716:12)
    at Client.onceConnected (/packages/remote-ftp/lib/client.js:377:17)
    at Client.upload (/packages/remote-ftp/lib/client.js:715:10)
    at /packages/remote-ftp/lib/menus/commands.js:448:18
    at Array.forEach (native)
    at HTMLElement.command (/packages/remote-ftp/lib/menus/commands.js:445:16)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1290:25)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:346:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:06.5.0 remote-ftp:sync-with-local (span.name.icon.icon-file-directory)
  2x -0:36.3.0 remote-ftp:upload-selected (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
remote-ftp 2.1.4 
```

**Comment by martincysiam** [comment]
Fix can be found here: #1374
