### ISSUE TITLE
Uncaught Error: EACCES: permission denied, mkdir '~/Escritorio/Coddy/pruebas.coddy.com.mx/refax'

### ISSUE THREAD

**Issue by angelsalvadormx** [icetee/remote-ftp#1139]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Ubuntu 17.10
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.1.4

### Stack Trace

Uncaught Error: EACCES: permission denied, mkdir '/home/angel/Escritorio/Coddy/pruebas.coddy.com.mx/refax'

```
At /home/angel/.atom/packages/remote-ftp/node_modules/mkdirp/index.js:90

Error: EACCES: permission denied, mkdir '/home/angel/Escritorio/Coddy/pruebas.coddy.com.mx/refax'
    at Object.fs.mkdirSync (fs.js:855:18)
    at Function.sync (/packages/remote-ftp/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at ConnectorFTP._getFile (/packages/remote-ftp/lib/connectors/ftp.js:194:8)
    at /packages/remote-ftp/lib/connectors/ftp.js:358:14
    at /packages/remote-ftp/lib/connectors/ftp.js:185:9
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:373:5)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:127:20)
    at emitTwo (events.js:111:20)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:61:10)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Parser.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:298:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
```

### Non-Core Packages

```
emmet 2.4.3 
remote-ftp 2.1.4 
```

**Comment by icetee** [comment]
You are no permission to create folder.
