### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/Documents\Yun\CV\Profile\RoadSimba\inc...

### ISSUE THREAD

**Issue by ShawnXxy** [icetee/remote-ftp#1153]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.1.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\shawn\Documents\Yun\CV\Profile\RoadSimba\includes\footer.php.baiduyun.uploading.cfg'

```
At fs.js:973

Error: ENOENT: no such file or directory, stat 'C:\Users\shawn\Documents\Yun\CV\Profile\RoadSimba\includes\footer.php.baiduyun.uploading.cfg'
    at fs.statSync (fs.js:973:11)
    at Proxy.fs.statSync (ELECTRON_ASAR.js:280:16)
    at /packages/remote-ftp/lib/connectors/ftp.js:435:32)
    at /packages/remote-ftp/lib/connectors/ftp.js:440:24
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:1018:14
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:942:11)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:127:20)
    at emitTwo (events.js:111:20)
    at Parser.emit (events.js:194:7)
    at Parser._write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:61:10)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at Parser.Writable.write (_stream_writable.js:241:11)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:298:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
```

### Commands

```
     -2:37.2.0 core:paste (input.hidden-input)
     -2:19.2.0 core:copy (input.hidden-input)
     -2:09.7.0 core:save (input.hidden-input)
  2x -2:01.1.0 remote-ftp:upload-selected (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
emmet 2.4.3 
remote-ftp 2.1.4 
teletype 0.13.0 
```

**Comment by icetee** [comment]
Duplicated of #1135
