### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by evilangelmd** [icetee/remote-ftp#1161]
1. put a folder to upload
2. remove some files from that folder

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.1.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/apple/Documents/htdocs/sites/site.com/classes/vendor/illuminate/support/Facades/Redis.php'

```
At fs.js:973

Error: ENOENT: no such file or directory, stat '/Users/apple/Documents/htdocs/sites/site.com/classes/vendor/illuminate/support/Facades/Redis.php'
    at fs.statSync (fs.js:973:11)
    at Proxy.fs.statSync (ELECTRON_ASAR.js:280:16)
    at stats (/packages/remote-ftp/lib/connectors/sftp.js:389:27)
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:415:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at SFTPStream.Writable.write (_stream_writable.js:241:11)
    at Channel.ondata (_stream_readable.js:557:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Channel.Readable.push (_stream_readable.js:136:10)
    at /packages/remote-ftp/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:191:7)
    at parsePacket (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:3444:10)
    at SSH2Stream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at SSH2Stream.Writable.write (_stream_writable.js:241:11)
    at Socket.ondata (_stream_readable.js:557:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
```

### Commands

```
     -5:29.7.0 remote-ftp:upload-active (div.line.cursor-line)
     -4:31.1.0 core:save (input.hidden-input)
     -4:24.2.0 core:close (input.hidden-input)
     -4:22.6.0 core:backspace (input.hidden-input)
     -4:22.2.0 core:move-left (input.hidden-input)
     -4:20 core:backspace (input.hidden-input)
     -4:18.6.0 core:save (input.hidden-input)
     -4:12.2.0 core:close (input.hidden-input)
     -4:08.5.0 remote-ftp:upload-active (span.syntax--punctuation.syntax--terminator.syntax--expression.syntax--php)
  2x -3:43 core:close (input.hidden-input)
     -3:07.6.0 remote-ftp:upload-selected (span.name.icon.icon-file-directory)
     -2:15.9.0 core:backspace (input.hidden-input)
     -2:15.2.0 core:save (input.hidden-input)
     -0:50.3.0 core:backspace (input.hidden-input)
     -0:49.8.0 core:save (input.hidden-input)
     -0:01.3.0 remote-ftp:disconnect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
aligner-javascript 1.3.0 
atom-beautify 0.32.2 
git-plus 7.10.2 
git-time-machine 2.0.1 
highlight-selected 0.13.1 
html-to-javascript 0.2.0 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
platformio-ide-terminal 2.8.1 
remote-ftp 2.1.4 
todo-show 2.3.0 
```

**Comment by icetee** [comment]
Duplicated of #1135
