### ISSUE TITLE
Failed to load the Remote-FTP package

### ISSUE THREAD

**Issue by lswadmin** [icetee/remote-ftp#1180]
![22](https://user-images.githubusercontent.com/39455319/41199903-dddf798c-6ccc-11e8-8936-0537747a513e.jpg)
![22](https://user-images.githubusercontent.com/39455319/41199905-fb990f4c-6ccc-11e8-9732-33a1e55294c4.jpg)

ReferenceError: Proxy is not defined
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\Remote-FTP\node_modules\fs-plus\lib\fs-plus.js:711:24)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\Remote-FTP\node_modules\fs-plus\lib\fs-plus.js:721:4)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\Remote-FTP\lib\client.js:15:15)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:/Users/Administrator/.atom/packages/remote-ftp/lib/remote-ftp.js:4:24)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:715:27)
    at C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:457:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:536:30)
    at C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:463:29
    at exit (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by icetee** [comment]
Your Atom is old.

**Comment by icetee** [comment]
@lswadmin Resolved?
