### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '~/.ssh/id_jackfamsite'

### ISSUE THREAD

**Issue by denezt** [icetee/remote-ftp#120]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.210.0
**System**: Ubuntu 15.04
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.1
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '~/.ssh/id_jackfamsite'

```
At fs.js:519

Error: ENOENT: no such file or directory, open '~/.ssh/id_jackfamsite'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.readFileSync (fs.js:396:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
  at Client.module.exports.Client.connect (/home/denezt/.atom/packages/Remote-FTP/lib/client.js:161:42)
  at Client.<anonymous> (/home/denezt/.atom/packages/Remote-FTP/lib/client.js:102:10)
  at /home/denezt/.atom/packages/Remote-FTP/lib/client.js:87:14
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)

```
### Commands

```
     -7:40.7.0 editor:select-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
  5x -7:34 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:10.8.0 remote-ftp:connect (atom-text-editor.editor.is-focused)
     -5:56.5.0 remote-ftp:navigate-to (atom-text-editor.editor.is-focused)
     -5:43.1.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -5:35.5.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -4:48.2.0 remote-ftp:create-sftp-config (atom-text-editor.editor.is-focused)
     -4:36.8.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -3:12 core:cancel (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  2x -2:59.6.0 remote-ftp:create-sftp-config (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:29.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:28.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:27.9.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:57.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:33.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:11.2.0 core:cancel (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.1
SFTP-deployment, v1.0.0
remote-edit, v1.8.2

# Dev
No dev packages
```

**Comment by jpxd** [comment]
The private key you specified in your .ftpconfig doesn't seem to exist...

**Comment by msj121** [comment]
I actually had the same issue. However, I solved it by avoiding using the tild (~). Instead reference the file as follows:

`/Users/<username>/...`

That is the same as:

`~/...`

Although the former works not the latter. And obviously the file existed, I did not change the path except for the beginning.
