### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir '~/Documents/MylesOfWork/.remote-sync.json'

### ISSUE THREAD

**Issue by myles-banner** [icetee/remote-ftp#1203]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.0

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir '/Users/mylesbanner/Documents/MylesOfWork/.remote-sync.json'

```
At fs.js:904

Error: ENOTDIR: not a directory, scandir '/Users/mylesbanner/Documents/MylesOfWork/.remote-sync.json'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:580:28)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:137:27)
    at ConnectorFTP.put (/packages/remote-ftp/lib/connectors/ftp.js:669:7)
    at /packages/remote-ftp/lib/client.js:741:24)
    at Client._next (/packages/remote-ftp/lib/client.js:643:39)
    at /packages/remote-ftp/lib/client.js:743:16
    at tryApply (/packages/remote-ftp/lib/connectors/ftp.js:12:14)
    at /packages/remote-ftp/lib/connectors/ftp.js:638:9)
    at /packages/remote-ftp/lib/connectors/ftp.js:665:16
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:1084:13)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:122:20)
    at emitTwo (events.js:131:20)
    at Parser.emit (events.js:214:7)
    at Parser.write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:78:12)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:293:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
  2x -9:09.0 tree-view:remove (span.name.icon.icon-file-text)
     -2:48 remote-ftp:create-ftp-config (input.hidden-input)
  2x -2:17 core:paste (input.hidden-input)
     -1:38.7.0 core:save (input.hidden-input)
     -1:03.2.0 remote-ftp:toggle (input.hidden-input)
     -0:55.7.0 remote-ftp:connect (ul.list-inline.tab-bar.inset-panel)
     -0:55.1.0 remote-ftp:upload-selected (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:55.1.0 remote-ftp:sync-with-local (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:22.2.0 remote-ftp:sync-with-remote (li.directory.entry.list-nested-item.selected.expanded)
  2x -0:07.6.0 remote-ftp:upload-selected (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
apm-publish 0.3.2 
atom-runner 2.7.1 
autoclose-html 0.23.0 
emmet 2.4.3 
remote-ftp 2.2.0 
remote-sync 4.1.8 
```

**Comment by myles-banner** [comment]
Figured out a better way thanks to youTube and apologize but don't have the source anymore. Reach out if you need help though and happy to assist.
