### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received false

### ISSUE THREAD

**Issue by erickmorillas** [icetee/remote-ftp#1217]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Unknown Windows version
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.0

### Stack Trace

Uncaught TypeError: Path must be a string. Received false

```
At path.js:28

TypeError: Path must be a string. Received false
    at assertPath (path.js:28:11)
    at Object.relative (path.js:571:5)
    at /packages/remote-ftp/lib/client.js:64:39
    at Array.forEach (<anonymous>)
    at /packages/remote-ftp/lib/client.js:62:31
    at PathWatcher.onNativeEvents (~/AppData/Local/atom/app-1.31.2/resources/app/src/path-watcher.js:533:13)
    at sub.native.onDidChange.events (~/AppData/Local/atom/app-1.31.2/resources/app/src/path-watcher.js:436:64)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at NSFWNativeWatcher.onEvents (~/AppData/Local/atom/app-1.31.2/resources/app/src/path-watcher.js:167:24)
    at handler (~/AppData/Local/atom/app-1.31.2/resources/app/src/path-watcher.js:276:18)
```

### Commands

```
  2x -7:27 intentions:highlight (input.hidden-input)
     -7:26 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-ternjs 0.18.3 
busy-signal 1.4.3 
file-icons 2.1.25 
highlight-selected 0.14.0 
intentions 1.1.5 
platformio-ide-terminal 2.8.4 
remote-ftp 2.2.0 
slack-chat 3.4.2 
teletype 0.13.3 
```

**Comment by DiegoLpVn** [comment]
You have something wrong in your .ftpconfig, probably the "remote" path.
