### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/OneDrive\Grad\00Quon Lab\Atom\2018_Lan...

### ISSUE THREAD

**Issue by yonchoi** [icetee/remote-ftp#1238]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Microsoft Windows 10 Home
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\yc\OneDrive\Grad\00Quon Lab\Atom\2018_Landscape\DeepLearning\VAE\181130_VAE_IntMethodTest\1207\run_test2.sh'

```
At fs.js:954

Error: ENOENT: no such file or directory, stat 'C:\Users\yc\OneDrive\Grad\00Quon Lab\Atom\2018_Landscape\DeepLearning\VAE\181130_VAE_IntMethodTest\1207\run_test2.sh'
    at fs.statSync (fs.js:954:11)
    at Object.fs.statSync (ELECTRON_ASAR.js:295:16)
    at localFilePrepare (/packages/remote-ftp/lib/helpers.js:109:22)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:126:17)
    at ConnectorSFTP.put (/packages/remote-ftp/lib/connectors/sftp.js:621:9)
    at /packages/remote-ftp/lib/client.js:748:24)
    at Client._next (/packages/remote-ftp/lib/client.js:650:39)
    at /packages/remote-ftp/lib/client.js:750:16
    at Object.e (/packages/remote-ftp/lib/connectors/sftp.js:610:22)
    at /packages/remote-ftp/lib/connectors/sftp.js:499:27)
    at emitNone (events.js:111:20)
    at WriteStream.emit (events.js:208:7)
    at finishMaybe (_stream_writable.js:604:14)
    at afterWrite (_stream_writable.js:455:3)
    at onwrite (_stream_writable.js:445:7)
    at /packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:2925:5
    at cb (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:974:15)
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:389:17)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SFTPStream.Writable.write (_stream_writable.js:290:11)
    at Channel.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Channel.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Channel.Readable.push (_stream_readable.js:208:10)
    at /packages/remote-ftp/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:116:13)
    at SSH2Stream.emit (events.js:211:7)
    at parsePacket (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:3445:10)
    at SSH2Stream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:671:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SSH2Stream.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -4:24.4.0 core:backspace (input.hidden-input)
     -4:23.2.0 editor:newline (input.hidden-input)
     -4:22.3.0 core:backspace (input.hidden-input)
     -4:19.5.0 editor:newline (input.hidden-input)
  3x -4:18.8.0 core:backspace (input.hidden-input)
     -4:13.4.0 editor:newline (input.hidden-input)
  6x -4:12.4.0 core:backspace (input.hidden-input)
     -3:28.5.0 editor:toggle-line-comments (input.hidden-input)
 17x -3:28.2.0 core:move-down (input.hidden-input)
  2x -3:26.9.0 core:move-left (input.hidden-input)
     -3:26.6.0 core:move-up (input.hidden-input)
     -3:26.4.0 core:move-down (input.hidden-input)
 14x -3:26.2.0 core:move-left (input.hidden-input)
     -3:25.1.0 core:move-right (input.hidden-input)
  2x -3:24.7.0 core:backspace (input.hidden-input)
 23x -3:21.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
language-r 0.4.2 
remote-ftp 2.2.2 
```

**Comment by icetee** [comment]
Duplicated of #1135
