### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/testphp/testcomposer/vendor/app/Settin...

### ISSUE THREAD

**Issue by elineda** [icetee/remote-ftp#1246]
[Enter steps to reproduce:]

1. Connect FTP first time.
2. Try to sync local->ftp.

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: "Fedora release
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/home/elineda/testphp/testcomposer/vendor/app/Setting.php'

```
At fs.js:954

Error: ENOENT: no such file or directory, stat '/home/elineda/testphp/testcomposer/vendor/app/Setting.php'
    at fs.statSync (fs.js:954:11)
    at Object.fs.statSync (ELECTRON_ASAR.js:295:16)
    at localFilePrepare (/packages/remote-ftp/lib/helpers.js:109:22)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:126:17)
    at ConnectorFTP.put (/packages/remote-ftp/lib/connectors/ftp.js:669:7)
    at /packages/remote-ftp/lib/client.js:748:24)
    at Client._next (/packages/remote-ftp/lib/client.js:650:39)
    at /packages/remote-ftp/lib/client.js:750:16
    at tryApply (/packages/remote-ftp/lib/connectors/ftp.js:12:14)
    at /packages/remote-ftp/lib/connectors/ftp.js:638:9)
    at /packages/remote-ftp/lib/connectors/ftp.js:665:16
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:1061:13)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:117:22)
    at emitTwo (events.js:131:20)
    at Parser.emit (events.js:214:7)
    at Parser.write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:78:12)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:293:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -2:45.2.0 tree-view:add-folder (div.header.list-item)
     -2:43.6.0 core:confirm (input.hidden-input)
     -2:33.8.0 tree-view:add-folder (div.header.list-item)
     -2:33.2.0 core:paste (input.hidden-input)
     -2:32.5.0 core:confirm (input.hidden-input)
     -2:27 core:backspace (input.hidden-input)
     -2:26.7.0 intentions:highlight (input.hidden-input)
     -2:26.4.0 core:save (input.hidden-input)
     -0:49.8.0 remote-ftp:create-ignore-file (div.tool-panel.tree-view)
     -0:43.9.0 remote-ftp:create-ftp-config (input.hidden-input)
     -0:40.4.0 core:move-left (input.hidden-input)
 11x -0:39.8.0 core:delete (input.hidden-input)
  4x -0:37 core:backspace (input.hidden-input)
     -0:17.6.0 intentions:highlight (input.hidden-input)
     -0:17.5.0 core:save (input.hidden-input)
     -0:11.4.0 remote-ftp:connect (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-html-preview 0.2.6 
atom-ide-ui 0.13.0 
atom-phpunit 1.3.0 
atom-python-run 0.9.7 
atom-sass 0.4.0 
composer 0.5.0 
composer-atom-plugin 0.7.1 
Hydrogen 2.7.0 
hyperclick 0.0.0 
ide-php 0.7.18 
intentions 1.1.5 
php-composer-completion 0.3.4 
php-ide-serenata 4.5.1 
php-integrator-annotations 1.2.0 
php-integrator-call-tips-legacy-php56 1.2.3 
php-integrator-linter-legacy-php56 1.3.1 
php-integrator-navigation 1.2.1 
php-integrator-refactoring 1.4.1 
php-integrator-tooltips-legacy-php56 1.1.6 
pigments 0.40.2 
project-manager 3.3.6 
python-indent 1.1.6 
remote-atom 1.3.12 
remote-ftp 2.2.2 
```

**Comment by icetee** [comment]
Duplicated of #1135
