### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'C:/xampp\htdocs\client\comingsoon.php'

### ISSUE THREAD

**Issue by Dieg0Js** [icetee/remote-ftp#1248]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\xampp\htdocs\client\comingsoon.php'

```
At fs.js:954

Error: ENOENT: no such file or directory, stat 'C:\xampp\htdocs\client\comingsoon.php'
    at fs.statSync (fs.js:954:11)
    at Object.fs.statSync (ELECTRON_ASAR.js:295:16)
    at localFilePrepare (/packages/remote-ftp/lib/helpers.js:109:22)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:126:17)
    at ConnectorSFTP.put (/packages/remote-ftp/lib/connectors/sftp.js:621:9)
    at /packages/remote-ftp/lib/client.js:748:24)
    at Client._next (/packages/remote-ftp/lib/client.js:650:39)
    at /packages/remote-ftp/lib/client.js:750:16
    at Object.e (/packages/remote-ftp/lib/connectors/sftp.js:610:22)
    at /packages/remote-ftp/lib/connectors/sftp.js:499:27)
    at emitNone (events.js:111:20)
    at WriteStream.emit (events.js:208:7)
    at finishMaybe (_stream_writable.js:604:14)
    at afterWrite (_stream_writable.js:455:3)
    at onwrite (_stream_writable.js:445:7)
    at /packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:2925:5
    at cb (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:974:15)
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:389:17)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SFTPStream.Writable.write (_stream_writable.js:290:11)
    at Channel.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Channel.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Channel.Readable.push (_stream_readable.js:208:10)
```

### Commands

```
     -2:04.5.0 remote-ftp:create-sftp-config (div.tool-panel.tree-view)
     -1:45.9.0 tree-view:remove (span.name.icon.icon-file-directory)
     -1:34.3.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
  3x -1:16.8.0 core:paste (input.hidden-input)
     -0:49.4.0 core:save (input.hidden-input)
     -0:43.8.0 remote-ftp:toggle (input.hidden-input)
     -0:17.9.0 core:paste (input.hidden-input)
  2x -0:16.8.0 core:select-all (input.hidden-input)
     -0:10.9.0 core:paste (input.hidden-input)
     -0:10.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
color-picker 2.3.0 
remote-ftp 2.2.2 
```

**Comment by icetee** [comment]
Duplicated of #1135
