### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Bandeirex** [icetee/remote-ftp#1252]
[Enter steps to reproduce:]

1. Change local file name
2. Connect to FTP

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'D:\Projectos\Bombeiros Backend\html\assets\js\dispositivos-ajax.js'

```
At fs.js:954

Error: ENOENT: no such file or directory, stat 'D:\Projectos\Bombeiros Backend\html\assets\js\dispositivos-ajax.js'
    at fs.statSync (fs.js:954:11)
    at Object.fs.statSync (ELECTRON_ASAR.js:295:16)
    at localFilePrepare (/packages/remote-ftp/lib/helpers.js:109:22)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:126:17)
    at ConnectorSFTP.put (/packages/remote-ftp/lib/connectors/sftp.js:621:9)
    at /packages/remote-ftp/lib/client.js:748:24)
    at Client._next (/packages/remote-ftp/lib/client.js:650:39)
    at /packages/remote-ftp/lib/client.js:696:16
    at callCompleted (/packages/remote-ftp/lib/connectors/sftp.js:173:53)
    at oneDirCompleted (/packages/remote-ftp/lib/connectors/sftp.js:177:25)
    at /packages/remote-ftp/lib/connectors/sftp.js:258:36
    at Array.forEach (<anonymous>)
    at /packages/remote-ftp/lib/connectors/sftp.js:193:12
    at /packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:1590:13
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:389:17)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SFTPStream.Writable.write (_stream_writable.js:290:11)
    at Channel.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Channel.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Channel.Readable.push (_stream_readable.js:208:10)
    at /packages/remote-ftp/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:116:13)
    at SSH2Stream.emit (events.js:211:7)
    at parsePacket (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:3445:10)
    at SSH2Stream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:671:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SSH2Stream.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -2:59.7.0 tree-view:move (span.name.icon.js-icon.medium-yellow)
  4x -2:56.9.0 core:backspace (input.hidden-input)
     -2:55.2.0 core:confirm (input.hidden-input)
 10x -1:59.1.0 intentions:highlight (input.hidden-input)
     -1:53.4.0 project-find:show (input.hidden-input)
 17x -1:47.3.0 core:backspace (input.hidden-input)
     -1:43.3.0 editor:consolidate-selections (input.hidden-input)
     -1:43.3.0 core:cancel (input.hidden-input)
     -1:38 intentions:highlight (input.hidden-input)
     -1:37.9.0 find-and-replace:show (input.hidden-input)
  9x -1:36 core:backspace (input.hidden-input)
  9x -1:27.4.0 core:confirm (input.hidden-input)
  4x -1:19.7.0 core:backspace (input.hidden-input)
 10x -1:18.1.0 core:confirm (input.hidden-input)
     -0:44.2.0 intentions:highlight (input.hidden-input)
     -0:43.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-alignment 0.13.0 
atom-beautify 0.33.4 
atom-ide-debugger-react-native 0.7.3 
atom-ide-ui 0.13.0 
auto-indent 0.5.0 
autoclose-html 0.23.0 
autocomplete-paths 2.12.2 
busy-signal 2.0.0 
change-case 0.6.5 
docblockr 0.13.7 
double-tag 1.7.0 
editorconfig 2.3.0 
emmet 2.4.3 
expose 0.15.0 
file-icons 2.1.30 
file-watcher 2.0.0 
highlight-selected 0.14.0 
ide-json 0.2.1 
ide-php undefined 
intentions 1.1.5 
linter 2.3.0 
linter-eslint 8.5.2 
linter-php 1.6.0 
linter-ui-default 1.7.1 
local-history 4.3.1 
lorem 4.0.0 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.2.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
multi-cursor 2.1.5 
pigments 0.40.2 
platformio-ide-terminal 2.9.0 
prettier-atom undefined 
project-manager 3.3.6 
react 0.18.0 
remote-ftp 2.2.2 
script 3.18.1 
sort-lines 0.18.0 
sync-settings 0.8.6 
todo-show 2.3.2 
wakatime 7.0.7 
```

**Comment by icetee** [comment]
Duplicated of #1135
