### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/OneDrive/Azienda/FTP/ftp.albergotreste...

### ISSUE THREAD

**Issue by samuelesantoni** [icetee/remote-ftp#1262]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/samuele/OneDrive/Azienda/FTP/ftp.albergotrestelle.com/_ftpconfig'

```
At fs.js:954

Error: ENOENT: no such file or directory, stat '/Users/samuele/OneDrive/Azienda/FTP/ftp.albergotrestelle.com/_ftpconfig'
    at fs.statSync (fs.js:954:11)
    at Object.fs.statSync (ELECTRON_ASAR.js:295:16)
    at localFilePrepare (/packages/remote-ftp/lib/helpers.js:109:22)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:126:17)
    at ConnectorFTP.put (/packages/remote-ftp/lib/connectors/ftp.js:669:7)
    at /packages/remote-ftp/lib/client.js:748:24)
    at Client._next (/packages/remote-ftp/lib/client.js:650:39)
    at /packages/remote-ftp/lib/client.js:696:16
    at tryApply (/packages/remote-ftp/lib/connectors/ftp.js:12:14)
    at /packages/remote-ftp/lib/connectors/ftp.js:153:9
    at final (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:513:11)
    at Object.cb (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:550:11)
    at /packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:122:20)
    at emitTwo (events.js:131:20)
    at Parser.emit (events.js:214:7)
    at Parser.write (/packages/remote-ftp/node_modules/@icetee/ftp/lib/parser.js:78:12)
    at Socket.ondata (/packages/remote-ftp/node_modules/@icetee/ftp/lib/connection.js:293:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -7:30.7.0 application:add-project-folder (input.hidden-input)
     -6:57.5.0 core:backspace (input.hidden-input)
     -6:57.2.0 core:paste (input.hidden-input)
     -6:55.3.0 core:save (input.hidden-input)
     -6:52.1.0 remote-ftp:toggle (ul.list-inline.tab-bar.inset-panel)
     -6:37 tree-view:move (span.name.icon.icon-file-text)
     -6:34.9.0 core:backspace (input.hidden-input)
     -6:34 core:confirm (input.hidden-input)
     -5:55.9.0 core:backspace (input.hidden-input)
     -5:54.8.0 core:paste (input.hidden-input)
     -5:52.2.0 core:save (input.hidden-input)
     -0:16.5.0 core:backspace (input.hidden-input)
     -0:15.6.0 core:paste (input.hidden-input)
     -0:13.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-commander 0.12.0 
atom-uikit 1.2.2 
atom-wrap-in-tag 0.6.0 
auto-indent 0.5.0 
autoclose-html 0.23.0 
color-tabs 0.1.8 
double-tag 1.7.0 
gist 1.1.0 
grammar-tab-colors 0.2.8 
pigments 0.40.2 
remote-ftp 2.2.2 
uikit-atom 0.3.2 
```

**Comment by samuelesantoni** [comment]
Solved.

**Comment by icetee** [comment]
Duplicated of #1135
