### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/Volumes/BKP02/Sites/web/agiliza/public_...

### ISSUE THREAD

**Issue by mnicollette** [icetee/remote-ftp#1276]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.13.5
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Volumes/BKP02/Sites/web/agiliza/public_html/painel/fipe-crawler/web/deps'

```
At fs.js:954

Error: ENOENT: no such file or directory, stat '/Volumes/BKP02/Sites/web/agiliza/public_html/painel/fipe-crawler/web/deps'
    at fs.statSync (fs.js:954:11)
    at Object.fs.statSync (ELECTRON_ASAR.js:295:16)
    at localFilePrepare (/packages/remote-ftp/lib/helpers.js:109:22)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:141:19)
    at ConnectorFTP.put (/packages/remote-ftp/lib/connectors/ftp.js:669:7)
    at /packages/remote-ftp/lib/client.js:748:24)
    at Client._next (/packages/remote-ftp/lib/client.js:650:39)
    at Client._enqueue (/packages/remote-ftp/lib/client.js:661:56)
    at /packages/remote-ftp/lib/client.js:747:12)
    at Client.onceConnected (/packages/remote-ftp/lib/client.js:397:17)
    at Client.upload (/packages/remote-ftp/lib/client.js:746:10)
    at /packages/remote-ftp/lib/menus/commands.js:448:18
    at Array.forEach (<anonymous>)
    at HTMLElement.command (/packages/remote-ftp/lib/menus/commands.js:445:16)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349922)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348397)
    at AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:716242)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:724248)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -0:13 remote-ftp:upload-selected (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-jsx-transform 0.2.0 
Atom-SFTP-sync 2.0.1 
blade-snippets 0.2.0 
busy-signal 2.0.1 
intentions 1.1.5 
jsx-comment 0.2.0 
language-javascript-jsx 0.3.7 
language-styled-jsx 1.0.4 
laravel-5-snippets 0.19.0 
laravel-eloquent-snippets 2.0.0 
laravel-forms-bootstrap-snippets 1.2.0 
laravel-helper 0.3.0 
laravel-snippets 2.1.0 
laravelcollective-html-form-snippets 1.0.0 
linter 2.3.0 
linter-eslint 8.5.5 
linter-ui-default 1.7.1 
react 0.18.0 
remote-ftp 2.2.2 
SFTP-deployment 1.0.2 
```

**Comment by icetee** [comment]
Duplicated of #1135
