### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/Desktop/project/var/mail'

### ISSUE THREAD

**Issue by elliot-alderson-3x** [icetee/remote-ftp#1290]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.5
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/elliotalderson/Desktop/project/var/mail'

```
At fs.js:143

Error: ENOENT: no such file or directory, stat '/Users/elliotalderson/Desktop/project/var/mail'
    at fs.statSync (fs.js:953:3)
    at Object.fs.statSync (ELECTRON_ASAR.js:295:16)
    at localFilePrepare (/packages/remote-ftp/lib/helpers.js:109:22)
    at traverseTree (/packages/remote-ftp/lib/helpers.js:141:19)
    at ConnectorSFTP.put (/packages/remote-ftp/lib/connectors/sftp.js:621:9)
    at /packages/remote-ftp/lib/client.js:748:24)
    at Client._next (/packages/remote-ftp/lib/client.js:650:39)
    at Client._enqueue (/packages/remote-ftp/lib/client.js:661:56)
    at /packages/remote-ftp/lib/client.js:747:12)
    at Client.onceConnected (/packages/remote-ftp/lib/client.js:397:17)
    at Client.upload (/packages/remote-ftp/lib/client.js:746:10)
    at /packages/remote-ftp/lib/client.js:109:18
```

### Commands

```
     -0:58.7.0 pane:close (div.name)
     -0:47.7.0 remote-ftp:toggle (div.tool-panel.tree-view)
     -0:35.8.0 remote-ftp:disconnect (li.directory.entry.list-nested-item.project-root.expanded.selected)
  2x -0:18.5.0 core:backspace (input.hidden-input)
     -0:16.7.0 core:save (input.hidden-input)
  3x -0:09.6.0 editor:newline (input.hidden-input)
  3x -0:08.7.0 core:move-up (input.hidden-input)
  6x -0:05.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
laravel 0.7.1 
remote-ftp 2.2.2 
```

**Comment by icetee** [comment]
Duplicated of #1135
