### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by Nico207** [icetee/remote-ftp#130]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Unknown Windows Version
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.1
### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of undefined

```
At C:\Users\user_directory\.atom\packages\Remote-FTP\lib\client.js:262

TypeError: Cannot read property 'substr' of undefined
    at Client.module.exports.Client.toLocal (C:\Users\user_directory\.atom\packages\Remote-FTP\lib\client.js:262:17)
    at n (C:\Users\user_directory\.atom\packages\Remote-FTP\lib\client.js:449:27)
    at n (C:\Users\user_directory\.atom\packages\Remote-FTP\lib\client.js:446:16)
    at n (C:\Users\user_directory\.atom\packages\Remote-FTP\lib\client.js:446:16)
    at n (C:\Users\user_directory\.atom\packages\Remote-FTP\lib\client.js:446:16)
    at n (C:\Users\user_directory\.atom\packages\Remote-FTP\lib\client.js:446:16)
    at n (C:\Users\user_directory\.atom\packages\Remote-FTP\lib\client.js:446:16)
    at n (C:\Users\user_directory\.atom\packages\Remote-FTP\lib\client.js:446:16)
    at n (C:\Users\user_directory\.atom\packages\Remote-FTP\lib\client.js:446:16)
    at n (C:\Users\user_directory\.atom\packages\Remote-FTP\lib\client.js:446:16)
```
### Commands

```
```
### Config

``` json
{
  "core": {},
  "Remote-FTP": {
    "hideLocalWhenDisplayed": true
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.1

# Dev
No dev packages
```

**Comment by Nico207** [comment]
One more thing : It's only happens when I do a rigth clic on a directory and choose download or sync remote, not on files.
