### ISSUE TITLE
Uncaught TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by 78points** [icetee/remote-ftp#131]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.2
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.1
### Stack Trace

Uncaught TypeError: Cannot read property 'forEach' of undefined

```
At /Users/pawel/.atom/packages/Remote-FTP/lib/connectors/ftp.js:111

TypeError: Cannot read property 'forEach' of undefined
  at /Users/admin/.atom/packages/Remote-FTP/lib/connectors/ftp.js:111:10
  at /Users/admin/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:431:14
  at /Users/admin/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:887:7
  at Socket.<anonymous> (/Users/admin/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:918:5)
  at Socket.g (events.js:257:16)
  at emitNone (events.js:67:13)
  at Socket.emit (events.js:163:7)
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:986:10)

```
### Commands

```
     -7:00.1.0 core:copy (atom-text-editor.editor.is-focused)
     -6:58.1.0 core:paste (atom-text-editor.editor.is-focused)
     -6:50.6.0 core:copy (atom-text-editor.editor.is-focused)
     -6:48.8.0 core:paste (atom-text-editor.editor.is-focused)
     -6:45.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:43.6.0 core:save (atom-text-editor.editor.is-focused)
     -6:02.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:56.5.0 core:save (atom-text-editor.editor.is-focused)
     -4:45.6.0 core:copy (atom-text-editor.editor.is-focused)
     -4:14 core:backspace (atom-text-editor.editor.is-focused)
     -4:12.1.0 core:paste (atom-text-editor.editor.is-focused)
     -4:10.7.0 core:save (atom-text-editor.editor.is-focused)
     -3:28.2.0 core:undo (atom-text-editor.editor.is-focused)
     -3:23.2.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:42.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:30.3.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "ignoredNames": [
      ".DS_Store",
      "._css"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.1
cakephp-snippets, v0.6.1
color-picker, v2.0.7
linter, v1.0.4
linter-php, v0.0.15
minimap, v4.10.0
monokai, v0.14.0
php-twig, v4.0.0
sass-autocompile, v0.7.1

# Dev
No dev packages
```

**Comment by albjeremias** [comment]
I got the same issue, why was it closed?

**Comment by albjeremias** [comment]
?
