### ISSUE TITLE
Uncaught Error: Remote FTP: getConfigPath returned false, but expected a string

### ISSUE THREAD

**Issue by gmedranoh** [icetee/remote-ftp#1313]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2

### Stack Trace

Uncaught Error: Remote FTP: getConfigPath returned false, but expected a string

```
At C:\Users\Luis\.atom\packages\remote-ftp\lib\client.js:220

Error: Remote FTP: getConfigPath returned false, but expected a string
    at Client.readConfig (/packages/remote-ftp/lib/client.js:220:45)
    at /packages/remote-ftp/lib/views/tree-view.js:154:30)
    at HTMLDivElement.dispatch (/packages/remote-ftp/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/remote-ftp/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  3x -2:25.4.0 remote-ftp:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:51.6.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:48.7.0 remote-ftp:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
remote-ftp 2.2.2 
```

**Comment by icetee** [comment]
Duplicated of #621
