### ISSUE TITLE
Uncaught TypeError: Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by K-Otaki** [icetee/remote-ftp#1316]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.1
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.3

### Stack Trace

Uncaught TypeError: Cannot read property 'config' of undefined

```
At /Users/otaki/.atom/packages/remote-ftp/lib/client.js:264

TypeError: Cannot read property 'config' of undefined
    at /packages/remote-ftp/lib/client.js:264:23
    at /packages/remote-ftp/lib/client.js:270:18
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

### Commands

```
  2x -9:33.5.0 core:close (input.hidden-input)
     -7:30.3.0 settings-view:open (input.hidden-input)
     -3:49.3.0 remote-ftp:navigate-to (div.package-detail)
  6x -3:45.8.0 core:cancel (div.package-detail)
     -0:44 remote-ftp:connect (div.package-readme.native-key-bindings)
  4x -0:40.3.0 remote-ftp:toggle (div.package-detail)
     -0:20 remote-ftp:connect (div.package-readme.native-key-bindings)
```

### Non-Core Packages

```
autocomplete-latex-cite 0.3.5 
autocomplete-paths 2.12.2 
japanese-menu 1.15.0 
language-fortran 2.1.9 
language-latex 1.2.0 
latex 0.50.2 
latexer 0.3.0 
markdown-preview-plus 3.11.5 
minimap 4.29.9 
minimap-autohide 0.10.1 
pdf-view 0.72.0 
pigments 0.40.2 
remote-ftp 2.2.3 
split-diff 1.6.1 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by icetee** [comment]
I published new released. Theoretically solves the problem.

**Comment by K-Otaki** [comment]
Thank you for your prompt response.
