### ISSUE TITLE
Update to 2.2.3 - Can't use SFTP

### ISSUE THREAD

**Issue by qbadev** [icetee/remote-ftp#1317]
1. Open Atom, use a project with SFTP connection
2. Try to connect

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 19.04
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.3

### Stack Trace

Uncaught TypeError: Cannot read property 'config' of undefined

```
At ~/.atom/packages/remote-ftp/lib/client.js:264

TypeError: Cannot read property 'config' of undefined
    at /packages/remote-ftp/lib/client.js:264:23
    at /packages/remote-ftp/lib/client.js:270:18
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atom-wrap-in-tag 0.6.0 
autoclose-html 0.23.0 
bracket-matcher-highlight 0.6.1 
busy-signal 2.0.1 
compare-files 0.8.1 
convert-file-encoding 0.1.0 
docblockr 0.13.7 
fold-comments 0.6.0 
fold-functions 0.11.0 
ftp-remote-edit 0.18.0 
git-plus 8.7.1 
grammar-token-limit 0.1.1 
hex-view 0.2.1 
highlight-selected 0.16.0 
insert-my-ip 0.3.0 
intentions 1.1.5 
language-nunjucks 4.2.1 
language-smarty 1.8.0 
language-typo3-fluid 0.2.1 
language-typoscript 0.2.0 
language-vue 0.25.0 
linter 2.3.1 
linter-php 1.6.1 
linter-ui-default 1.8.0 
pigments 0.40.2 
project-manager 3.3.8 
project-plus 1.0.0 
remote-ftp 2.2.3 
simple-drag-drop-text 0.5.0 
tag 0.5.0 
toggle-home 0.3.2 
tree-view-open-files 0.3.0 
```

**Comment by thegr8awais** [comment]
I am facing that problem too. Is there any solution . Also can we downgrade version ?

**Comment by qbadev** [comment]
@thegr8awais if You are on Linux, try `apm install remote-ftp@2.2.2` command. I just did it, and it works

**Comment by thegr8awais** [comment]
Thanks i was just editing my post to write about this i have done it.

**Comment by evanwang1990** [comment]
> @thegr8awais if You are on Linux, try `apm install remote-ftp@2.2.2` command. I just did it, and it works

it works on windows too

**Comment by icetee** [comment]
Duplicated of #1316
