### ISSUE TITLE
Uncaught Error: handle is not a Buffer

### ISSUE THREAD

**Issue by the-evgenii** [icetee/remote-ftp#144]
**Atom Version**: 1.0.2
**System**: Unknown Windows Version
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2
### Stack Trace

Uncaught Error: handle is not a Buffer

```
At C:\Users\Evgeniy\.atom\packages\remote-sync\node_modules\ssh2\lib\SFTP\SFTPv3.js:602

Error: handle is not a Buffer
    at SFTP.readdir (C:\Users\Evgeniy\.atom\packages\remote-sync\node_modules\ssh2\lib\SFTP\SFTPv3.js:602:11)
    at ConnectorSFTP.module.exports.ConnectorSFTP.list (C:\Users\Evgeniy\.atom\packages\Remote-FTP\lib\connectors\sftp.js:154:15)
    at Client.<anonymous> (C:\Users\Evgeniy\.atom\packages\Remote-FTP\lib\client.js:323:20)
    at Client.module.exports.Client._next (C:\Users\Evgeniy\.atom\packages\Remote-FTP\lib\client.js:274:21)
    at Client.module.exports.Client._enqueue (C:\Users\Evgeniy\.atom\packages\Remote-FTP\lib\client.js:285:9)
    at Client.<anonymous> (C:\Users\Evgeniy\.atom\packages\Remote-FTP\lib\client.js:322:9)
    at Client.module.exports.Client.onceConnected (C:\Users\Evgeniy\.atom\packages\Remote-FTP\lib\client.js:98:14)
    at Client.module.exports.Client.list (C:\Users\Evgeniy\.atom\packages\Remote-FTP\lib\client.js:321:8)
    at Directory.module.exports.Directory.open (C:\Users\Evgeniy\.atom\packages\Remote-FTP\lib\directory.js:99:10)
    at ConnectorSFTP.<anonymous> (C:\Users\Evgeniy\.atom\packages\Remote-FTP\lib\client.js:200:15)
```
### Commands

```
  2x -0:23.8.0 remote-ftp:toggle (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "metrics",
      "symbols-view",
      "atom-ctags",
      "goto"
    ]
  },
  "remote-sync": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.9
emmet, v2.3.12
file-type-icons, v0.7.0
file-types, v0.4.1
language-jade, v0.5.1
language-nginx, v0.5.4
linter, v1.2.3
linter-csslint, v0.0.14
linter-jshint, v0.1.7
linter-less, v2.0.3
meteor-api, v2.20.0
project-manager, v1.15.11
Remote-FTP, v0.7.1
remote-sync, v3.1.2
tag, v0.3.0

# Dev
No dev packages
```

Remote-FTP, v0.7.1 conflicts with remote-sync, v3.1.2. remote-ftp can't connect with remote-sync package.

**Comment by jpxd** [comment]
This is an issue from the [remote-sync](https://github.com/yongkangchen/remote-sync) package you use.
They use an old version of the ssh2 package. This error due to incompatible API (see mscdex/ssh2#192). _remote-sync_ pinned its ssh2 version down to an old version (see its `package.json`).
Please submit the issue there.
