### ISSUE TITLE
Uncaught TypeError: Cannot read property 'resolve' of undefined

### ISSUE THREAD

**Issue by RyLeeHarrison** [icetee/remote-ftp#161]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.1
### Stack Trace

Uncaught TypeError: Cannot read property 'resolve' of undefined

```
At /Users/rylee/.atom/packages/Remote-FTP/lib/client.js:261

TypeError: Cannot read property 'resolve' of undefined
  at Client.module.exports.Client.toLocal (/Users/rylee/.atom/packages/Remote-FTP/lib/client.js:261:42)
  at ConnectorFTP.module.exports.ConnectorFTP.get (/Users/rylee/.atom/packages/Remote-FTP/lib/connectors/ftp.js:161:24)
  at Client.<anonymous> (/Users/rylee/.atom/packages/Remote-FTP/lib/client.js:340:20)
  at Client.module.exports.Client._next (/Users/rylee/.atom/packages/Remote-FTP/lib/client.js:274:21)
  at Client.module.exports.Client._enqueue (/Users/rylee/.atom/packages/Remote-FTP/lib/client.js:285:9)
  at Client.<anonymous> (/Users/rylee/.atom/packages/Remote-FTP/lib/client.js:339:9)
  at Client.module.exports.Client.onceConnected (/Users/rylee/.atom/packages/Remote-FTP/lib/client.js:98:14)
  at Client.module.exports.Client.download (/Users/rylee/.atom/packages/Remote-FTP/lib/client.js:338:8)
  at File.module.exports.File.open (/Users/rylee/.atom/packages/Remote-FTP/lib/file.js:59:10)
  at FileView.module.exports.FileView.open (/Users/rylee/.atom/packages/Remote-FTP/lib/views/file-view.js:82:13)
  at space-pen-li.<anonymous> (/Users/rylee/.atom/packages/Remote-FTP/lib/views/file-view.js:71:9)
  at space-pen-li.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-li.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -4:41 core:backspace (atom-text-editor.editor.is-focused)
     -4:40.7.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -4:39.7.0 core:move-right (atom-text-editor.editor.is-focused)
 10x -4:37.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:35.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -4:35.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:34.9.0 core:save (atom-text-editor.editor.is-focused)
     -4:30.1.0 remote-ftp:connect (atom-text-editor.editor.is-focused)
  3x -4:13.7.0 core:copy (atom-text-editor.editor.is-focused)
     -3:28.7.0 core:save (atom-text-editor.editor.is-focused)
     -3:19.9.0 remote-ftp:connect (atom-text-editor.editor.is-focused)
     -1:25.2.0 remote-ftp:create-ftp-config (atom-text-editor.editor.is-focused)
     -0:52 remote-ftp:connect (atom-text-editor.editor.is-focused)
  2x -0:34.9.0 core:undo (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-ax-monokai-syntax.theme-atom-material-ui)
     -0:33.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.8.0 tree-view:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "ax-monokai-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.1
atom-beautify, v0.28.8
atom-material-ui, v0.5.9
ax-monokai-syntax, v0.1.0
node-on-fire, v0.1.0
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by socar-spock** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Ubuntu 16.04.1
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.8.9

### Stack Trace

Uncaught TypeError: Cannot read property 'resolve' of undefined

```
At /home/spock/.atom/packages/Remote-FTP/lib/client.js:90

TypeError: Cannot read property 'resolve' of undefined
    at Client.module.exports.Client.readConfig (/home/spock/.atom/packages/Remote-FTP/lib/client.js:90:47)
    at HTMLAnchorElement.<anonymous> (/home/spock/.atom/packages/Remote-FTP/lib/views/tree-view.js:182:27)
    at HTMLDivElement.jQuery.event.dispatch (/home/spock/.atom/packages/Remote-FTP/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/home/spock/.atom/packages/Remote-FTP/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -4:07.8.0 remote-ftp:toggle (ul.list-inline.tab-bar.inset-panel)
     -3:56.6.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -3:51.7.0 tree-view:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:35.9.0 remote-edit:browse (atom-pane.pane.active)
  8x -0:35.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:18.8.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
     -0:17.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-php",
      "linter-phpcs"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-autocomplete-php, v0.19.2 (active)
autoclose-html, v0.23.0 (active)
autocomplete, v0.47.0 (inactive)
autocomplete-php, v0.3.7 (active)
color-picker, v2.2.2 (active)
docblockr, v0.8.5 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.19 (active)
highlight-line, v0.11.1 (active)
javascript-snippets, v1.2.1 (active)
linter, v1.11.16 (active)
linter-csslint, v1.3.2 (active)
linter-htmlhint, v1.3.0 (active)
linter-js-yaml, v1.2.5 (active)
linter-jshint, v2.1.0 (active)
linter-php, v1.2.0 (inactive)
linter-phpcs, v1.4.0 (inactive)
linter-scss-lint, v3.0.4 (active)
linter-tidy, v2.2.0 (active)
livereload, v0.4.4 (active)
minimap, v4.25.0 (active)
project-manager, v2.9.7 (active)
react, v0.16.0 (active)
remote-edit, v1.8.24 (active)
Remote-FTP, v0.8.9 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (active)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by FocuzJS** [comment]
You guys did not Add a Project Folder first.

**Comment by janazcoj** [comment]
Corrects!! FocuzJS

**Comment by guillaumeMu** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.1.3


### Stack Trace

Uncaught TypeError: Cannot read property 'resolve' of undefined

```
At /Users/guillaume/.atom/packages/Remote-FTP/lib/views/tree-view.js:232

TypeError: Cannot read property 'resolve' of undefined
    at /packages/remote-ftp/lib/views/tree-view.js:232:59)
    at HTMLDivElement.dispatch (/packages/Remote-FTP/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/Remote-FTP/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:11.9.0 remote-ftp:toggle (atom-pane.pane.active)
     -0:42 remote-ftp:create-sftp-config (input.hidden-input)
     -0:37.7.0 remote-ftp:create-ftp-config (input.hidden-input)
```

### Non-Core Packages

```
Remote-FTP 1.1.3 
```

**Comment by icetee** [comment]
@amaradrys Maybe no opened project folder.
