### ISSUE TITLE
Bug - can't browse

### ISSUE THREAD

**Issue by optikalefx** [icetee/remote-ftp#181]
Just installed and getting Atom up and running. I have 1 site still using SSH for editing. When browsing with your plugin I get an event emitter error. Note that the side bar browser does work, but browsing via the pallet does not

```
Uncaught Error: Emitter has been disposed
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:34
Hide Stack Trace
Error: Emitter has been disposed
  at Emitter.module.exports.Emitter.on (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:34:15)
  at InterProcessDataWatcher.module.exports.InterProcessDataWatcher.onDidChange (/Users/sean/.atom/packages/remote-edit/lib/model/inter-process-data-watcher.coffee:88:16)
  at HostsView.module.exports.HostsView.initialize (/Users/sean/.atom/packages/remote-edit/lib/view/hosts-view.coffee:19:30)
  at HostsView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at HostsView.SelectListView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:18:51)
  at new HostsView (/Users/sean/.atom/packages/remote-edit/lib/view/hosts-view.coffee:13:5)
  at Object.module.exports.browse (/Users/sean/.atom/packages/remote-edit/lib/main.coffee:93:16)
  at atom-workspace.<anonymous> (/Users/sean/.atom/packages/remote-edit/lib/main.coffee:70:67)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)
The error was thrown from the remote-edit package. This issue has already been reported.
View Issue
```

**Comment by jpxd** [comment]
The bug apparently is due to the Atom update and comes from the `remote-edit` package, not from `remote-ftp` (see issue here https://github.com/sveale/remote-edit/issues/99)

**FIX:** Just restart Atom :smile:

**Comment by optikalefx** [comment]
Ha, you're right. However, I love to NOT use the mouse as much as I can, is there anyway to browse from the pallet?  I have these large directories and it would be great to fuzzy browser through the FS instead of having to click through on the right.

**Comment by jpxd** [comment]
If you have synced your ftp filesystem completely to your disk (using Filezilla or so; because the folder download seems to be broken in `remote-ftp` at the moment), just use Atom's [fuzzy file finder](https://github.com/atom/fuzzy-finder/blob/master/README.md) (shortcut on Mac `CMD + T`) to navigate. I personally don't use the tree view anymore because its so much faster...

**Comment by optikalefx** [comment]
Trust me, I would if I could. I just have this one project left that I still edit on the server. It's from a few years ago.  Potentially I could go through and make a nice .gitignore and get all the files on my FS. But honestly, I'll just keep using sublime for this 1 project if it isn't added. Not a huge deal, but the sftp plugin for sublime has the sftp browse via the pallet.  If it wasn't a big deal to add, i'd say add it, otherwise, people shouldn't edit on the server anyway.
