### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remote' of null

### ISSUE THREAD

**Issue by JamesCoyle** [icetee/remote-ftp#183]
Possibly something to do with directory renaming.

**Atom Version**: 1.0.7
**System**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.2
### Stack Trace

Uncaught TypeError: Cannot read property 'remote' of null

```
At C:\Users\Solus Softworks\.atom\packages\Remote-FTP\lib\remote-ftp.js:225

TypeError: Cannot read property 'remote' of null
  at C:\Users\Solus Softworks\.atom\packages\Remote-FTP\lib\remote-ftp.js:225:73
  at C:\Users\Solus Softworks\.atom\packages\Remote-FTP\lib\client.js:589:16
  at C:\Users\Solus Softworks\.atom\packages\Remote-FTP\lib\connectors\ftp.js:469:17
  at Object.cb (C:\Users\Solus Softworks\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:368:14)
  at Parser.<anonymous> (C:\Users\Solus Softworks\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:113:22)
  at emitTwo (events.js:87:13)
  at Parser.emit (events.js:169:7)
  at Parser._write (C:\Users\Solus Softworks\.atom\packages\Remote-FTP\node_modules\ftp\lib\parser.js:59:10)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at Parser.Writable.write (_stream_writable.js:210:11)
  at Socket.ondata (C:\Users\Solus Softworks\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:273:20)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at TCP.onread (net.js:517:20)

```
### Commands

```
     -1:01.5.0 core:move-right (atom-text-editor.editor.mini.is-focused)
  9x -1:01.3.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -0:58.9.0 core:save (atom-text-editor.editor.mini.is-focused)
  2x -0:57 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:53.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:46.2.0 core:move-right (atom-text-editor.editor.mini.is-focused)
  9x -0:46.1.0 core:move-left (atom-text-editor.editor.mini.is-focused)
 13x -0:43.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "isotope-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "linter-csslint"
    ]
  },
  "Remote-FTP": {
    "hideLocalWhenDisplayed": true
  }
}
```
### Installed Packages

``` coffee
# User
file-icons, v1.6.6
flex-tool-bar, v0.5.0
isotope-ui, v2.5.1
linter, v1.4.3
linter-cpplint, v0.1.4
linter-htmlhint, v0.1.1
linter-jshint, v1.1.5
linter-php, v1.0.3
minimap, v4.13.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.0
minimap-highlight-selected, v4.3.0
minimap-selection, v4.3.0
Remote-FTP, v0.7.2
save-session, v0.15.7
tool-bar, v0.1.8

# Dev
No dev packages
```

**Comment by jpxd** [comment]
When you can still reproduce the bug, please reopen.

**Comment by minimal2** [comment]
I stumbled upon same error. It accoutred to me when trying sync local -> remote without being connected. Connecting with the server fixed the problem.

**Atom Version**: 1.13.1
**Electron Version**: 1.4.15
**System**: "Arch Linux"
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.10.7

**Comment by JamesCoyle** [comment]
It's probably due to performing a task that requires being connected when there is no connection. There should probably be a check for connectivity in there that is missing.

**Comment by vringar** [comment]
@jpxd please reopen the issue. 
Steps needed to reproduce:

1. Disconnect from your remote FTP-Server
2. Sync local->remote 

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Ubuntu 16.10
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.10.7


### Stack Trace

Uncaught TypeError: Cannot read property 'remote' of null

```
At /home/stefan/.atom/packages/Remote-FTP/lib/client.js:470

TypeError: Cannot read property 'remote' of null
    at Client.toRemote (/home/stefan/.atom/packages/Remote-FTP/lib/client.js:470:18)
    at /home/stefan/.atom/packages/Remote-FTP/lib/menus/commands.js:550:33
    at Array.forEach (native)
    at atom-workspace.command (/home/stefan/.atom/packages/Remote-FTP/lib/menus/commands.js:547:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1181:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:332:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:39.5.0 remote-ftp:sync-with-local (span.name.icon.icon-file-directory)
  2x -0:05.9.0 core:backspace (input.hidden-input)
     -0:04.6.0 core:save (input.hidden-input)
     -0:00.1.0 remote-ftp:sync-with-local (span.name.icon.icon-file-text)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-write-good",
      "remote-sync"
    ],
    "telemetryConsent": "limited"
  },
  "Remote-FTP": {
    "enableTransferNotifications": true
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.22.2 (active)
atom-beautify, v0.29.17 (active)
auto-detect-indentation, v1.3.0 (active)
auto-indent, v0.5.0 (active)
autoclose-html, v0.23.0 (active)
docblockr, v0.9.3 (active)
linter, v1.11.23 (active)
linter-htmlhint, v1.3.2 (active)
linter-jshint, v3.0.3 (active)
linter-write-good, v0.8.0 (inactive)
linter-xmllint, v1.4.1 (active)
php-cs-fixer, v4.1.0 (active)
pigments, v0.39.1 (active)
Remote-FTP, v0.10.7 (active)
remote-sync, v4.1.5 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by mattalexhoward** [comment]
Can confirm that connecting or restarting and connecting will solve this issue.

**Comment by icetee** [comment]
Hi @vringar, do you still have the bug in the last version?
I could not reproduce it.

**Comment by vringar** [comment]
Hi @icetee , sorry for letting you wait this long.
I also can't reproduce the error with the lastest version.
It seems like in the latest version the addon tries to establish a connection if there is none, which seems appropriate behaviour.
