### ISSUE TITLE
Uncaught Error: Protocol version not supported

### ISSUE THREAD

**Issue by tym** [icetee/remote-ftp#185]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.2
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.2
### Stack Trace

Uncaught Error: Protocol version not supported

```
At events.js:141

Error: Protocol version not supported
  at SSH2Stream._transform (/Users/ty/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:376:25)
  at SSH2Stream.Transform._read [as __read] (_stream_transform.js:167:10)
  at SSH2Stream._read (/Users/ty/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:213:15)
  at SSH2Stream.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at SSH2Stream.Writable.write (_stream_writable.js:210:11)
  at Socket.ondata (_stream_readable.js:524:20)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at TCP.onread (net.js:517:20)

```
### Commands

```
  3x -9:39 core:paste (atom-text-editor.editor.is-focused)
  2x -9:13.7.0 core:save (atom-text-editor.editor.is-focused)
     -8:57.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -8:56.3.0 core:save (atom-text-editor.editor.is-focused)
     -8:50.3.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -8:49.1.0 core:save (atom-text-editor.editor.is-focused)
     -7:31.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:15.8.0 core:copy (atom-text-editor.editor.is-focused)
     -1:54 core:save (atom-text-editor.editor.is-focused)
     -0:59.5.0 core:select-all (atom-text-editor.editor.is-focused)
  3x -0:59.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:46.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:25.1.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.2
autoclose-html, v0.18.0
color-picker, v2.0.11
emmet, v2.3.12
less-than-slash, v0.8.0
linter, v1.4.3

# Dev
No dev packages
```

**Comment by jpxd** [comment]
What were you trying to connect to ? And what SSH server is running there ? You could check which protocol version it is using (http://ask.xmodulo.com/check-ssh-protocol-version-linux.html)
