### ISSUE TITLE
Some kind of writeAfterEnd issue

### ISSUE THREAD

**Issue by phawxby** [icetee/remote-ftp#19]
Having put my laptop into standby overnight coming to use Remote FTP the next day I am unable to browse folders. I'm taking a guess the connection dropped as a result of going into standby and has not reconnected on the first request the next day.

```
Error: write after end
  at writeAfterEnd (_stream_writable.js:147:12)
  at ChannelStream.Writable.write (_stream_writable.js:194:5)
  at SFTP._send (c:\Users\z269cjbb\.atom\packages\Remote-FTP\node_modules\ssh2\lib\SFTP\SFTPv3.js:1017:23)
  at SFTP.opendir (c:\Users\z269cjbb\.atom\packages\Remote-FTP\node_modules\ssh2\lib\SFTP\SFTPv3.js:780:15)
  at SFTP.readdir (c:\Users\z269cjbb\.atom\packages\Remote-FTP\node_modules\ssh2\lib\SFTP\SFTPv3.js:677:17)
  at ConnectorSFTP.module.exports.ConnectorSFTP.list (c:\Users\z269cjbb\.atom\packages\Remote-FTP\lib\connectors\sftp.js:145:15)
  at Client.<anonymous> (c:\Users\z269cjbb\.atom\packages\Remote-FTP\lib\client.js:327:20)
  at Client.module.exports.Client._next (c:\Users\z269cjbb\.atom\packages\Remote-FTP\lib\client.js:278:21)
  at Client.module.exports.Client._enqueue (c:\Users\z269cjbb\.atom\packages\Remote-FTP\lib\client.js:289:9)
  at Client.<anonymous> (c:\Users\z269cjbb\.atom\packages\Remote-FTP\lib\client.js:326:9)
  at Client.module.exports.Client.onceConnected (c:\Users\z269cjbb\.atom\packages\Remote-FTP\lib\client.js:124:14)
  at Client.module.exports.Client.list (c:\Users\z269cjbb\.atom\packages\Remote-FTP\lib\client.js:325:8)
  at Directory.module.exports.Directory.open (c:\Users\z269cjbb\.atom\packages\Remote-FTP\lib\directory.js:98:10)
  at DirectoryView.module.exports.DirectoryView.open (c:\Users\z269cjbb\.atom\packages\Remote-FTP\lib\views\directory-view.js:175:13)
  at HTMLLIElement.<anonymous> (c:\Users\z269cjbb\.atom\packages\Remote-FTP\lib\views\directory-view.js:74:12)
  at HTMLLIElement.handler (c:\Users\z269cjbb\AppData\Local\atom\app-0.174.0\resources\app\src\space-pen-extensions.js:112:34)
  at HTMLLIElement.jQuery.event.dispatch (c:\Users\z269cjbb\AppData\Local\atom\app-0.174.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLLIElement.elemData.handle (c:\Users\z269cjbb\AppData\Local\atom\app-0.174.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)
```

**Comment by grenierdev** [comment]
I think that the current `isConnected` check for the SFTP connector is just wrong. Seems like my plugin thinks that SFTP connection is still open and try to execute command.
