### ISSUE TITLE
Uncaught Error: Cannot find module 'ftp'

### ISSUE THREAD

**Issue by o2relax** [icetee/remote-ftp#194]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Unknown Windows Version
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.2
### Stack Trace

Uncaught Error: Cannot find module 'ftp'

```
At module.js:336

Error: Cannot find module 'ftp'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Администратор\AppData\Local\atom\app-1.0.15\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Администратор\.atom\packages\Remote-FTP\lib\connectors\ftp.js:5:8)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\Администратор\AppData\Local\atom\app-1.0.15\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
```
### Commands

```
     -0:02.5.0 remote-ftp:connect (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "laravel"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
remote-edit, v1.8.21
Remote-FTP, v0.7.2

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Please re-install the package. Did you use the apm package manager?

**Comment by o2relax** [comment]
i was re-installed package and atom with clearing folders in the AppData (windows).no, not use22.09.2015, 11:22, "Jan" notifications@github.com:Please re-install the package. Did you use the apm package manager?

**Comment by jpxd** [comment]
Please try to re-install the package using apm.
