### ISSUE TITLE
Uncaught TypeError: buffer.off is not a function

### ISSUE THREAD

**Issue by Braunson** [icetee/remote-ftp#198]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.16
**System**: Microsoft Windows 8.1
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.3
### Stack Trace

Uncaught TypeError: buffer.off is not a function

```
At C:\Users\braunson\AppData\Local\atom\app-1.0.16\resources\app.asar\node_modules\q\q.js:128

TypeError: buffer.off is not a function
    at C:\Users\braunson\Dropbox\.atom\packages\Remote-FTP\lib\remote-ftp.js:387:11
    at C:\Users\braunson\AppData\Local\atom\app-1.0.16\resources\app.asar\src\workspace.js:281:16
    at C:\Users\braunson\AppData\Local\atom\app-1.0.16\resources\app.asar\src\workspace.js:342:18
    at Emitter.module.exports.Emitter.emit (C:\Users\braunson\AppData\Local\atom\app-1.0.16\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (C:\Users\braunson\AppData\Local\atom\app-1.0.16\resources\app.asar\src\pane-container.js:352:27)
    at C:\Users\braunson\AppData\Local\atom\app-1.0.16\resources\app.asar\src\pane-container.js:339:26
    at Emitter.module.exports.Emitter.emit (C:\Users\braunson\AppData\Local\atom\app-1.0.16\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at Pane.module.exports.Pane.addItem (C:\Users\braunson\AppData\Local\atom\app-1.0.16\resources\app.asar\src\pane.js:345:20)
    at Pane.module.exports.Pane.activateItem (C:\Users\braunson\AppData\Local\atom\app-1.0.16\resources\app.asar\src\pane.js:313:14)
    at C:\Users\braunson\AppData\Local\atom\app-1.0.16\resources\app.asar\src\workspace.js:489:16
```
### Commands

```
  2x -2:05.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:05.2.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -2:05.1.0 core:paste (atom-text-editor.editor.is-focused)
     -2:04.3.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
 12x -2:04.2.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -1:59.8.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -1:59.8.0 core:copy (atom-text-editor.editor.is-focused)
     -1:38.5.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -1:38.4.0 core:copy (atom-text-editor.editor.is-focused)
     -1:31.9.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -1:31.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:20.5.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -0:20.3.0 core:close (atom-text-editor.editor.is-focused)
     -0:17.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-one-dark-ui)
     -0:07.6.0 fuzzy-finder:toggle-file-finder (div.settings-view.pane-item)
     -0:07.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "one-dark-ui",
      "atom-light-syntax"
    ]
  },
  "Remote-FTP": {
    "hideLocalWhenDisplayed": true
  }
}
```
### Installed Packages

``` coffee
# User
aligner, v0.16.2
aligner-css, v1.2.0
aligner-php, v1.0.0
aligner-scss, v1.1.0
atom-beautify, vundefined
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
code-links, v0.3.11
color-picker, v2.0.12
devdocs, v0.2.1
docblockr, v0.7.3
editor-stats, v0.17.0
file-icons, v1.6.9
flex-tool-bar, v0.5.0
highlight-line, v0.11.0
highlight-selected, v0.10.1
jshint, v1.8.0
linter, v1.6.0
linter-php, v1.0.3
minimap, v4.13.3
minimap-bookmarks, v0.1.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.6
php-cs-fixer, v2.4.0
pigments, v0.15.0
Remote-FTP, v0.7.3
tabs-to-spaces, v0.11.1
tool-bar, v0.1.9
tool-bar-main, v0.0.8
tree-view-git-modified, v0.5.10

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Patch should be published by now
The error will probably occur again at update
