### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isExpanded' of null

### ISSUE THREAD

**Issue by ikibalnyi** [icetee/remote-ftp#204]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Ubuntu 14.04.3
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.8
### Stack Trace

Uncaught TypeError: Cannot read property 'isExpanded' of null

```
At /home/kiba/.atom/packages/Remote-FTP/lib/views/directory-view.js:150

TypeError: Cannot read property 'isExpanded' of null
  at DirectoryView.module.exports.DirectoryView.setClasses (/home/kiba/.atom/packages/Remote-FTP/lib/views/directory-view.js:150:16)
  at /home/kiba/.atom/packages/Remote-FTP/lib/views/directory-view.js:55:52
  at /home/kiba/.atom/packages/Remote-FTP/node_modules/theorist/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at Behavior.module.exports.Emitter.emitSlow (/home/kiba/.atom/packages/Remote-FTP/node_modules/theorist/node_modules/emissary/lib/emitter.js:154:47)
  at Behavior.module.exports.Emitter.emit (/home/kiba/.atom/packages/Remote-FTP/node_modules/theorist/node_modules/emissary/lib/emitter.js:107:30)
  at Behavior.module.exports.Behavior.emit (/home/kiba/.atom/packages/Remote-FTP/node_modules/theorist/node_modules/emissary/lib/behavior.js:44:38)
  at Behavior.module.exports.Signal.emitValue (/home/kiba/.atom/packages/Remote-FTP/node_modules/theorist/node_modules/emissary/lib/signal.js:82:19)
  at Directory.module.exports.Model.set (/home/kiba/.atom/packages/Remote-FTP/node_modules/theorist/lib/model.js:166:21)
  at Directory.accessor.set (/home/kiba/.atom/packages/Remote-FTP/node_modules/theorist/lib/model.js:57:23)
  at DirectoryView.module.exports.DirectoryView.collapse (/home/kiba/.atom/packages/Remote-FTP/lib/views/directory-view.js:170:24)
  at DirectoryView.module.exports.DirectoryView.toggle (/home/kiba/.atom/packages/Remote-FTP/lib/views/directory-view.js:183:9)
  at space-pen-li.<anonymous> (/home/kiba/.atom/packages/Remote-FTP/lib/views/directory-view.js:83:13)
  at space-pen-li.jQuery.event.dispatch (/home/kiba/.atom/packages/Remote-FTP/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-li.elemData.handle (/home/kiba/.atom/packages/Remote-FTP/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -4:57.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:55.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -3:34.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:31.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:07.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:16.3.0 core:move-left (atom-text-editor.editor.mini.is-focused)
  2x -2:15.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:13.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:53.2.0 core:delete (atom-text-editor.editor.mini.is-focused)
     -1:51.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.8
atom-beautify, v0.28.14
color-picker, v2.0.12
emmet, v2.3.13
minimap, v4.13.4
php-cs-fixer, v2.5.0

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Please reopen if the issue still persists
