### ISSUE TITLE
Throwing `Error: EEXIST: file already exists, mkdir...` and possible cause

### ISSUE THREAD

**Issue by shogerr** [icetee/remote-ftp#206]
This issue seems to have been brought up before or one similar.
### Problem

Remote-FTP sees a file as existing and throws an error if the file is a child of a folder whose name was first used to create a file which was then deleted, and used to create the parent folder. If you try to view a file under these conditions Remote-FTP will be stuck with a cycling status indicator and throw an error. Remote-FTP will happily let you make new files under the non-working directory, but I don't believe any are written to disk.
### Solution

Navigate to the local directory where files from the server are stored, and delete the local file representing the file that was first created and later turned into a folder. Disconnect from server and reconnect, and the file should be available.

It seems that there is a problem writing the folder if a file has been first created with the same name and then deleted.

```
Error: EEXIST: file already exists, mkdir 'G:\share\projects\test\testdir'
  at Error (native)
  at Object.fs.mkdirSync (fs.js:799:18)
  at Function.sync (C:\Users\ekem\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:55:12)
  at Object.fsPlus.makeTreeSync (C:\Users\ekem\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:343:23)
  at C:\Users\ekem\.atom\packages\Remote-FTP\lib\connectors\sftp.js:198:9
  at SFTPStream._transform (C:\Users\ekem\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\sftp.js:470:15)
  at SFTPStream.Transform._read [as __read] (_stream_transform.js:167:10)
  at SFTPStream._read (C:\Users\ekem\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\sftp.js:173:15)
  at SFTPStream.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:291:12)
  at writeOrBuffer (_stream_writable.js:277:5)
  at SFTPStream.Writable.write (_stream_writable.js:206:11)
  at Channel.ondata (_stream_readable.js:521:20)
  at emitOne (events.js:77:13)
  at Channel.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Channel.Readable.push (_stream_readable.js:110:10)
  at SSH2Stream.<anonymous> (C:\Users\ekem\.atom\packages\Remote-FTP\node_modules\ssh2\lib\Channel.js:140:15)
  at emitOne (events.js:77:13)
  at SSH2Stream.emit (events.js:169:7)
  at parsePacket (C:\Users\ekem\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:3168:10)
  at SSH2Stream._transform (C:\Users\ekem\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:555:13)
  at SSH2Stream.Transform._read [as __read] (_stream_transform.js:167:10)
  at SSH2Stream._read (C:\Users\ekem\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:213:15)
  at SSH2Stream.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:291:12)
  at writeOrBuffer (_stream_writable.js:277:5)
  at SSH2Stream.Writable.write (_stream_writable.js:206:11)
  at Socket.ondata (_stream_readable.js:521:20)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:520:20)
```

**Comment by jpxd** [comment]
Link to #112

**Comment by hatzopoulos** [comment]
Closing, in favor of the older #122
