### ISSUE TITLE
Uncaught ReferenceError: NavigateTo is not defined

### ISSUE THREAD

**Issue by scottmberry** [icetee/remote-ftp#217]
1. Install plugin
2. Click on "Navigate To" in Package, RemoteFTP menu

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.8
### Stack Trace

Uncaught ReferenceError: NavigateTo is not defined

```
At /Users/scottberry/.atom/packages/Remote-FTP/lib/remote-ftp.js:372

ReferenceError: NavigateTo is not defined
  at atom-workspace.atom.commands.add.remote-ftp:navigate-to (/Users/scottberry/.atom/packages/Remote-FTP/lib/remote-ftp.js:372:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/scottberry/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (/Users/scottberry/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/scottberry/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
  at EventEmitter.<anonymous> (/Users/scottberry/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```
### Commands

```
  6x -2:04.7.0 remote-ftp:toggle (ul.list)
     -0:48.4.0 remote-ftp:disconnect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:43.5.0 remote-ftp:toggle (atom-workspace.workspace.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui.scrollbars-visible-always)
     -0:36.6.0 timecop:view (atom-workspace.workspace.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui.scrollbars-visible-always)
     -0:23 tree-view:toggle (atom-text-editor.editor.is-focused)
     -0:18.4.0 remote-ftp:toggle (atom-text-editor.editor.is-focused)
     -0:13.7.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -0:01.3.0 remote-ftp:navigate-to (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "minimap"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.8
atom-beautify, v0.28.14
color-picker, v2.0.13
file-icons, v1.6.11
language-cfml, v0.9.0
linter, v1.8.1
linter-cflint, v0.5.0

# Dev
No dev packages
```

**Comment by Arffeh** [comment]
Just got this error today as well.
1. Packages -> Remote-FTP -> Navigate To
2. Profit

**Atom Version**: 1.2.4
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.13

### Stack Trace

Uncaught ReferenceError: NavigateTo is not defined

```
At C:\Users\Arffeh\.atom\packages\Remote-FTP\lib\remote-ftp.js:374

ReferenceError: NavigateTo is not defined
    at atom-workspace.atom.commands.add.remote-ftp:navigate-to (C:\Users\Arffeh\.atom\packages\Remote-FTP\lib\remote-ftp.js:374:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Arffeh\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Arffeh\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Arffeh\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\Arffeh\AppData\Local\atom\app-1.2.4\resources\app.asar\src\atom-environment.js:987:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
```

### Config

``` json
{
  "core": {}
}
```

### Installed Packages

``` coffee
# User
emmet, v2.3.15
emmet-snippets-compatibility, v1.0.1
Remote-FTP, v0.7.13

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Oops, sorry forgot to declare it when fixing >.<
