### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by jbcarey** [icetee/remote-ftp#225]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Microsoft Windows 7 Ultimate N 
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.10
### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined

```
At C:\Users\Laurence.END2END\.atom\packages\Remote-FTP\lib\connectors\ftp.js:248

TypeError: Cannot read property 'name' of undefined
    at n (C:\Users\Laurence.END2END\.atom\packages\Remote-FTP\lib\connectors\ftp.js:248:45)
    at n (C:\Users\Laurence.END2END\.atom\packages\Remote-FTP\lib\connectors\ftp.js:253:10)
    at n (C:\Users\Laurence.END2END\.atom\packages\Remote-FTP\lib\connectors\ftp.js:253:10)
    at C:\Users\Laurence.END2END\.atom\packages\Remote-FTP\lib\connectors\ftp.js:276:19
    at Object.cb (C:\Users\Laurence.END2END\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:606:15)
    at Parser.<anonymous> (C:\Users\Laurence.END2END\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:113:22)
    at emitTwo (events.js:87:13)
    at Parser.emit (events.js:172:7)
    at Parser._write (C:\Users\Laurence.END2END\.atom\packages\Remote-FTP\node_modules\ftp\lib\parser.js:59:10)
    at doWrite (_stream_writable.js:291:12)
    at writeOrBuffer (_stream_writable.js:277:5)
```
### Commands

```
     -1:10.3.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:09.9.0 core:delete (atom-text-editor.editor.is-focused)
     -1:09.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -1:07.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:06.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:06.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:06.1.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:05.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:05.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:05.7.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:05.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:05.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:05.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:05.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:54.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:24.5.0 remote-ftp:download-selected (span.name.icon.icon-file-directory)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai-seti"
    ]
  },
  "Remote-FTP": {
    "hideLocalWhenDisplayed": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-alignment, v0.12.1
file-type-icons, v0.7.3
keyboard-localization, v1.4.10
linter, v1.10.0
linter-less, v2.2.0
minimap, v4.16.0
minimap-hide, v0.3.0
minimap-pigments, v0.1.7
monokai-seti, v0.7.0
pigments, v0.18.1
project-manager, v2.6.5
Remote-FTP, v0.7.10
seti-ui, v0.8.1

# Dev
No dev packages
```

**Comment by jbcarey** [comment]
Duplicate issue

**Comment by AeonFr** [comment]
This error appeared for me after trying to download a folder. (right-click on folder->download)

**Comment by b6t** [comment]
+1

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.1
**System**: Mac OS X 10.10.5
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.10

### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined

```
At /Users/coreybeaumont/.atom/packages/Remote-FTP/lib/connectors/sftp.js:237

TypeError: Cannot read property 'name' of undefined
    at n (/Users/coreybeaumont/.atom/packages/Remote-FTP/lib/connectors/sftp.js:237:44)
    at /Users/coreybeaumont/.atom/packages/Remote-FTP/lib/connectors/sftp.js:254:17
    at /Users/coreybeaumont/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:1049:21
    at SFTPStream._transform (/Users/coreybeaumont/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:379:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/Users/coreybeaumont/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:173:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at SFTPStream.Writable.write (_stream_writable.js:207:11)
    at Channel.ondata (_stream_readable.js:525:20)
```

### Commands

```
  4x -3:23.7.0 remote-ftp:toggle (atom-text-editor.editor.is-focused)
  2x -3:14.3.0 remote-ftp:create-sftp-config (atom-text-editor.editor.is-focused)
     -2:54.8.0 core:paste (atom-text-editor.editor.is-focused)
     -2:49.4.0 remote-ftp:connect (atom-text-editor.editor.is-focused)
  5x -2:45.8.0 remote-ftp:toggle (atom-text-editor.editor.is-focused)
     -2:29.5.0 core:undo (atom-text-editor.editor.is-focused)
     -2:27.3.0 application:open (atom-text-editor.editor.is-focused)
     -1:56 core:paste (atom-text-editor.editor.is-focused)
     -1:54.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:30 remote-ftp:toggle (atom-text-editor.editor.is-focused)
     -1:16.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:53.4.0 remote-ftp:download-selected (span.name.icon.icon-file-directory)
```

### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "spell-check"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.10
linter, v1.11.2
linter-bootlint, v0.0.6
linter-csslint, v1.1.0
linter-jshint, v1.2.1
linter-jsonlint, v1.0.1
minimap, v4.16.1

# Dev
No dev packages
```
