### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir 'F:\Tom\Web\rockerest.xyz\example\src\content\...

### ISSUE THREAD

**Issue by rockerest** [icetee/remote-ftp#226]
[Enter steps to reproduce below:]
1. Create `.json` file in directory as only child node in heirarchy
2. Double click `.json` file in file tree

**Atom Version**: 1.1.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.10
### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'F:\Tom\Web\rockerest.xyz\example\src\content\translations\posts'

```
At C:\Users\tom\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:76

Error: EEXIST: file already exists, mkdir 'F:\Tom\Web\rockerest.xyz\example\src\content\translations\posts'
  at Error (native)
  at Object.fs.mkdirSync (fs.js:799:18)
  at sync (C:\Users\tom\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:55:12)
  at Function.sync (C:\Users\tom\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:61:24)
  at Object.fsPlus.makeTreeSync (C:\Users\tom\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:343:23)
  at C:\Users\tom\.atom\packages\Remote-FTP\lib\connectors\sftp.js:198:9
  at SFTPStream._transform (C:\Users\tom\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\sftp.js:470:15)
  at SFTPStream.Transform._read [as __read] (_stream_transform.js:167:10)
  at SFTPStream._read (C:\Users\tom\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\sftp.js:173:15)
  at SFTPStream.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:291:12)
  at writeOrBuffer (_stream_writable.js:277:5)
  at SFTPStream.Writable.write (_stream_writable.js:206:11)
  at Channel.ondata (_stream_readable.js:521:20)
  at emitOne (events.js:77:13)
  at Channel.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Channel.Readable.push (_stream_readable.js:110:10)
  at SSH2Stream.<anonymous> (C:\Users\tom\.atom\packages\Remote-FTP\node_modules\ssh2\lib\Channel.js:142:15)
  at emitOne (events.js:77:13)
  at SSH2Stream.emit (events.js:169:7)
  at parsePacket (C:\Users\tom\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:3168:10)
  at SSH2Stream._transform (C:\Users\tom\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:555:13)
  at SSH2Stream.Transform._read [as __read] (_stream_transform.js:167:10)
  at SSH2Stream._read (C:\Users\tom\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:213:15)
  at SSH2Stream.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:291:12)
  at writeOrBuffer (_stream_writable.js:277:5)
  at SSH2Stream.Writable.write (_stream_writable.js:206:11)
  at Socket.ondata (_stream_readable.js:521:20)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:520:20)

```
### Commands

```
     -0:30.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".sass-cache",
      ".git",
      "src/assetic-translation-dump",
      "src/js/old"
    ],
    "themes": [
      "isotope-ui",
      "monokai"
    ],
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "linter-php"
    ]
  },
  "Remote-FTP": {
    "hideLocalWhenDisplayed": true
  }
}
```
### Installed Packages

``` coffee
# User
api-workbench, v0.8.6
color-picker, v2.0.13
compare-files, v0.6.2
file-icons, v1.6.11
highlight-line, v0.11.0
isotope-ui, v2.7.0
linter, v1.10.0
linter-eslint, v4.0.0
local-history, v3.2.3
minimap, v4.16.0
minimap-pigments, v0.1.7
monokai, v0.18.0
pigments, v0.18.1
project-manager, v2.6.5
regex-railroad-diagram, v0.10.4
Remote-FTP, v0.7.10
sync-settings, v0.6.0
terminal-plus, v0.14.0

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Are you using FTP or SFTP ?

**Comment by jpxd** [comment]
Oh, I just saw it in the traceback
Looking into it now

**Comment by jpxd** [comment]
Link to #112
