### ISSUE TITLE
Uncaught TypeError: BigInteger is not a function

### ISSUE THREAD

**Issue by BlaM** [icetee/remote-ftp#230]
[Enter steps to reproduce below:]

{
    "protocol": "sftp",
    "host": "blabla.example.com",
    "port": 22,
    "user": "root",
    "promptForPass": false,
    "remote": "/var/www/blabla/",
    "agent": "",
    "privatekey": "C:/Users/..../dd.ppk",
    "passphrase": "",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": false
}

(dd.ppk is a putty private key file)

**Atom Version**: 1.2.1
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.10
### Stack Trace

Uncaught TypeError: BigInteger is not a function

```
At C:\Users\ddeobald\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\utils.js:475

TypeError: BigInteger is not a function
    at Object.convertPPKPrivate (C:\Users\ddeobald\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\utils.js:475:14)
    at module.exports (C:\Users\ddeobald\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\keyParser.js:187:13)
    at Client.connect (C:\Users\ddeobald\.atom\packages\Remote-FTP\node_modules\ssh2\lib\client.js:145:23)
    at ConnectorSFTP.module.exports.ConnectorSFTP.connect (C:\Users\ddeobald\.atom\packages\Remote-FTP\lib\connectors\sftp.js:78:13)
    at Client.module.exports.Client.doConnect (C:\Users\ddeobald\.atom\packages\Remote-FTP\lib\client.js:237:18)
    at Client.module.exports.Client.connect (C:\Users\ddeobald\.atom\packages\Remote-FTP\lib\client.js:155:9)
    at Client.<anonymous> (C:\Users\ddeobald\.atom\packages\Remote-FTP\lib\remote-ftp.js:125:29)
    at C:\Users\ddeobald\.atom\packages\Remote-FTP\lib\client.js:85:15
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```
### Commands

```
     -0:06.3.0 remote-ftp:connect (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-eslint",
      "deprecation-cop",
      "recent-projects",
      "recent-files",
      "conceal",
      "less-than-slash",
      "emmet",
      "autoflow",
      "altgr",
      "nuclide-file-tree",
      "nuclide-language-hack"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "Remote-FTP": {
    "autoUploadOnSave": "only when connected"
  }
}
```
### Installed Packages

``` coffee
# User
aligner, v0.17.1
aligner-css, v1.2.0
aligner-php, v1.0.0
aligner-scss, v1.1.0
atom-beautify, v0.28.18
atom-html-preview, v0.1.13
atom-minify, v0.6.2
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
browser-plus, v0.0.54
color-picker, v2.0.13
color-tabs, v0.1.8
colorful-json, v1.0.0
cson, v2.0.1
devdocs, v0.2.1
docblockr, v0.7.3
documentation-renderer, v0.2.1
drunken-php, v0.2.1
flex-tool-bar, v0.6.0
highlight-selected, v0.11.1
hyperclick, v0.0.32
imdone-atom, v1.2.0
js-hyperclick, v1.4.0
js-refactor, v0.6.0
keyboard-localization, v1.4.10
language-sql-mysql, v0.3.1
language-vue, v0.7.0
less-autocompile, v1.0.0
linter, v1.11.2
linter-jshint, v1.2.1
linter-jsonlint, v1.0.1
linter-php, v1.1.1
linter-stylelint, v1.2.2
minimap, v4.16.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.2
minimap-highlight-selected, v4.3.1
my-github-profile, v0.2.1
navigate, v0.1.13
pretty-json, v0.4.1
project-manager, v2.6.5
refactor, v0.6.0
regex-railroad-diagram, v0.10.4
Remote-FTP, v0.7.10
select-rectangle, v1.0.2
selector-to-tag, v0.4.1
text-manipulation, v0.6.0
tool-bar, v0.1.9
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Duplicate to #220
Please look into #220
