### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by justbane** [icetee/remote-ftp#235]
To reproduce
1. right click on toplevel folder or select al files and folders, then right click
2. select sync local -> remote from context menu

Sync will start and run for a time and then fail. Files do appear to upload but after fail - package must disconnect/reconnect.

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11.1
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.10
### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:356

RangeError: Maximum call stack size exceeded
    at String.indexOf (native)
    at Directory.module.exports.Directory.isPathPrefixOf (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:356:23)
    at Directory.module.exports.Directory.relativize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:196:23)
    at Project.module.exports.Project.relativizePath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:321:40)
    at Project.module.exports.Project.relativize (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:311:19)
    at Client.module.exports.Client.toRemote (/Users/justbane/.atom/packages/Remote-FTP/lib/client.js:293:17)
    at n (/Users/justbane/.atom/packages/Remote-FTP/lib/client.js:549:28)
    at n (/Users/justbane/.atom/packages/Remote-FTP/lib/client.js:565:9)
    at n (/Users/justbane/.atom/packages/Remote-FTP/lib/client.js:565:9)
    at n (/Users/justbane/.atom/packages/Remote-FTP/lib/client.js:547:16)
```
### Commands

```
     -3:00.6.0 atom-commander:add-server (td.icon.icon-file-directory)
  2x -2:58.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -2:46.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:05.8.0 atom-commander:toggle-visible (tbody.atom-commander-list-view.list)
  2x -1:53.4.0 remote-ftp:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:23.4.0 remote-ftp:connect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:12.7.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:08.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:08.6.0 git-plus:new-branch (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:05.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:05.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:05.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:03.1.0 command-palette:toggle (atom-pane.pane.active)
     -0:57.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:57.5.0 git-plus:checkout (atom-pane.pane.active)
     -0:08.1.0 remote-ftp:sync-with-local (span.name.icon.icon-repo)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.10
atom-commander, v0.5.0
autocomplete-php, v0.3.7
color-picker, v2.0.13
git-plus, v5.6.5
highlight-selected, v0.11.1
linter, v1.11.2
linter-flow, v4.0.0
linter-php, v1.1.3
local-history, v3.2.3
remote-edit, v1.8.22

# Dev
No dev packages
```

**Comment by justbane** [comment]
Sorry, forgot to enter a comment on this one.

This error happens when I am trying to sync local -> remote on a large group of files. Or the entirety of a directory. If I do just a few files it works great, whole directory (with quite a lot of files) fails and I have to disconnect/reconnect as it seems to break the package.

However it does seem that the change are put up correctly.

Really great package! Please fix :)

**Comment by aastrong** [comment]
+1 - getting the same error. 
Looking into the issue,

**Comment by mike131** [comment]
+1 some error here.

**Comment by JiNexus** [comment]
+1 same error here.

**Comment by albertmoravec** [comment]
Getting it even when using local <- remote

**Comment by sunnygandhi01** [comment]
+1 Same error , To begain with there was no issue but after installing packages started this bug came up

**Comment by bede214** [comment]
+1 Same error here.

**Comment by souhaiebtar** [comment]
- same error here

**Comment by ASnow** [comment]
+1 Getting it even when using local <- remote. It apeared during `node_modules` copy. It seems didn't handle well directory with many files

**Comment by dmcdaniel12** [comment]
- 1 Just received this error as well about 10 minutes ago.

**Comment by miztizm** [comment]
same++
