### ISSUE TITLE
Uncaught SyntaxError: Unexpected token U

### ISSUE THREAD

**Issue by radupopa2010** [icetee/remote-ftp#252]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.15
### Stack Trace

Uncaught SyntaxError: Unexpected token U

```


SyntaxError: Unexpected token U
    at Object.parse (native)
    at .atom\packages\Remote-FTP\lib\client.js:78:21
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```
### Commands

```
     -7:25.3.0 tree-view:remove (li.file.entry.list-item.selected)
  2x -7:18.6.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -7:03.3.0 remote-ftp:create-sftp-config (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -6:56.8.0 remote-ftp:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -6:51.7.0 application:open-folder (atom-pane.pane.active)
     -6:40.5.0 remote-ftp:toggle (atom-pane.pane.active)
     -5:14.5.0 remote-ftp:connect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:00.7.0 remote-ftp:toggle (atom-pane.pane.active)
     -3:15 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -2:55.1.0 remote-ftp:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:27.2.0 remote-ftp:create-sftp-config (ul.list-inline.tab-bar.inset-panel)
     -2:12.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:57.7.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -1:56.8.0 core:paste (atom-text-editor.editor.is-focused)
  3x -1:41.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.3.0 remote-ftp:connect (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.14
highlight-selected, v0.11.1
minimap-highlight-selected, v4.3.1
remote-edit, v1.8.23
Remote-FTP, v0.7.15
smart-tab-name, v1.0.5

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Please post your .ftpconfig without credentials

**Comment by radupopa2010** [comment]
Fixed this bug. I had to escape the back-slashes in the path to the file.

**Comment by karjac14** [comment]
@radupopa2010 what do you mean escape backslashes? thanks

does the whats the key file format? is it .ppk?
