### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\Pc\Desktop\siteler\www\kanat\applica...

### ISSUE THREAD

**Issue by dogancancelik** [icetee/remote-ftp#260]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Microsoft Windows Embedded 8.1 Industry Enterprise
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.15
### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\Pc\Desktop\siteler\www\kanat\application\views\frontend\haber_blog'

```
At C:\Users\Pc\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:76

Error: EEXIST: file already exists, mkdir 'C:\Users\Pc\Desktop\siteler\www\kanat\application\views\frontend\haber_blog'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:799:18)
    at Function.sync (C:\Users\Pc\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:55:12)
    at Object.fsPlus.makeTreeSync (C:\Users\Pc\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:343:23)
    at C:\Users\Pc\.atom\packages\Remote-FTP\lib\connectors\ftp.js:447:8
    at Object.cb (C:\Users\Pc\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:1017:13)
    at Parser.<anonymous> (C:\Users\Pc\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:117:20)
    at emitTwo (events.js:87:13)
    at Parser.emit (events.js:172:7)
    at Parser._write (C:\Users\Pc\.atom\packages\Remote-FTP\node_modules\ftp\lib\parser.js:59:10)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Parser.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (C:\Users\Pc\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:273:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```
### Commands

```
     -3:02.4.0 command-palette:toggle (atom-pane.pane.active)
     -3:01.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:01.2.0 remote-ftp:connect (atom-pane.pane.active)
  2x -1:40.5.0 remote-ftp:delete-selected (span.name.icon.icon-file-text)
  4x -1:33.3.0 symbols-view:toggle-file-symbols (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:37.8.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:36.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:36.8.0 remote-ftp:connect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:24.6.0 remote-ftp:add-folder (span.name.icon.icon-file-directory)
     -0:16.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -0:03.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "expand-region"
    ]
  },
  "Remote-FTP": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.14
custom-title, v1.0.1
emmet, v2.3.17
file-icons, v1.6.13
Remote-FTP, v0.7.15

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Duplicate #226
