### ISSUE TITLE
Remote FTP wont start

### ISSUE THREAD

**Issue by phawxby** [icetee/remote-ftp#27]
I'm not sure what I can give you to help you debug this but for some reason Remote FTP wont function. Toggle, Connect Disconnect all seem completely non-functional. 
https://www.youtube.com/watch?v=lJ942KxIkyQ

If there's anything I can give you to help debug this let me know.

**Comment by grenierdev** [comment]
1. Atom version?
2. Plugin version?
3. Have you try to live-reload `CTRL+ALT+R` after enabling the project?
4. If you open up the Dev Tool `CTRL+ALT+I` can you type the following commands in the console & copy the results here? :
   - `atom.project.path` _(enter)_
   - `atom.project.remoteftp` _(enter)_

**Comment by hatzopoulos** [comment]
@phawxby 

Have you already created your config file using `Create FTP config file`?  I don't see it in the `W3Dev` folder of your screencast.  It will look like the screenshot below and you need to modify the settings. 

More details in the [Getting Started section](https://github.com/mgrenier/remote-ftp/blob/master/README.md#getting-started).

![screenshot](http://snag.gy/Q2pwC.jpg)

**Comment by phawxby** [comment]
@hatzopoulos sorry yes it's there I just selected the wrong folder, in any case it still doesn't work.
![capture](https://cloud.githubusercontent.com/assets/1090602/5922473/ca86d69e-a643-11e4-9fe7-ba597ef17499.PNG)

@mgrenier:
1. **Atom version:** 0.175.0
2. **Plugin version:** 0.4.5
3. **Have you try to live-reload CTRL+ALT+R after enabling the project:** No effect
4. **If you open up the Dev Tool CTRL+ALT+I can you type the following commands in the console & copy the results here? :**

```
atom.project.path
"c:\Users\z269cjbb\Documents\xxx\AS08"
atom.project.remoteftp
undefined
```

Which is weird, because it's there
![untitled](https://cloud.githubusercontent.com/assets/1090602/5922591/ca322f76-a644-11e4-9a60-80c5be9adfe7.png)

**Comment by grenierdev** [comment]
In your last screenshot there an error preceding the `Window load time: 2062`. Can you post that error here?

Seems like the package had an error while activating : that's why you `atom.project.remoteftp` is undefined. So the error will help me find the solution :)

**Comment by phawxby** [comment]
```
Failed to activate package named 'remote-ftp-0.4.5' Error: Cannot find module 'fs-plus'
  at Module._resolveFilename (module.js:344:15)
  at Function.Module._resolveFilename (c:\Users\z269cjbb\AppData\Local\atom\app-0.176.0\resources\app\src\module-cache.js:383:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.module.exports.activate (c:\Users\z269cjbb\.atom\packages\remote-ftp-0.4.5\lib\remote-ftp.js:23:9)
  at Package.module.exports.Package.activateNow (c:\Users\z269cjbb\AppData\Local\atom\app-0.176.0\resources\app\src\package.js:235:27)
  at c:\Users\z269cjbb\AppData\Local\atom\app-0.176.0\resources\app\src\package.js:221:28
  at Package.module.exports.Package.measure (c:\Users\z269cjbb\AppData\Local\atom\app-0.176.0\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.activate (c:\Users\z269cjbb\AppData\Local\atom\app-0.176.0\resources\app\src\package.js:215:14)
  at PackageManager.module.exports.PackageManager.activatePackage (c:\Users\z269cjbb\AppData\Local\atom\app-0.176.0\resources\app\src\package-manager.js:461:21)
  at c:\Users\z269cjbb\AppData\Local\atom\app-0.176.0\resources\app\src\package-manager.js:442:29
  at Config.module.exports.Config.transact (c:\Users\z269cjbb\AppData\Local\atom\app-0.176.0\resources\app\src\config.js:350:16)
  at PackageManager.module.exports.PackageManager.activatePackages (c:\Users\z269cjbb\AppData\Local\atom\app-0.176.0\resources\app\src\package-manager.js:436:19)
  at PackageManager.module.exports.PackageManager.activate (c:\Users\z269cjbb\AppData\Local\atom\app-0.176.0\resources\app\src\package-manager.js:419:46)
  at Atom.module.exports.Atom.startEditorWindow (c:\Users\z269cjbb\AppData\Local\atom\app-0.176.0\resources\app\src\atom.js:604:21)
  at Object.<anonymous> (c:\Users\z269cjbb\AppData\Local\atom\app-0.176.0\resources\app\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (c:\Users\z269cjbb\AppData\Local\atom\app-0.176.0\resources\app\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (c:\Users\z269cjbb\AppData\Local\atom\app-0.176.0\resources\app\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///C:/Users/z269cjbb/AppData/Local/atom/app-0.176.0/resources/app/static/index.js:49:25)

index.js:54 Window load time: 6251ms
```

**Comment by grenierdev** [comment]
It seems like the Atom installation process skipped dependencies or you install it manually. In either case, in terminal **from** the remote-ftp-0.4.5 folder, execute `apm install` and it should install all dependencies related to remote-ftp.

**Comment by phawxby** [comment]
That fixed it. I'm behind a firewall 50% of the time, being behind it at the time of install this time I had performed a manual install and didn't see any dependency list. Thanks for the help.
