### ISSUE TITLE
Uncaught SyntaxError: Unexpected number

### ISSUE THREAD

**Issue by fseminario** [icetee/remote-ftp#272]
[Enter steps to reproduce below:]
1. Simply trying to connect using package inside tab

**Atom Version**: 1.4.1
**System**: Mac OS X 10.10.4
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.15
### Stack Trace

Uncaught SyntaxError: Unexpected number

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Ffjs%2FSites%2Fportfolio-wordpress-v1%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%7D%5D%2C%22windowInitializationScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Finitialize-application-window.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22appVersion%22%3A%221.4.1%22%2C%22atomHome%22%3A%22%2FUsers%2Ffjs%2F.atom%22%2C%22shellLoadTime%22%3A308%2C%22initialPaths%22%3A%5B%22%2FUsers%2Ffjs%2FSites%2Fportfolio-wordpress-v1%22%5D%7D:6

SyntaxError: Unexpected number
    at Object.parse (native)
    at /Users/fjs/.atom/packages/Remote-FTP/lib/client.js:78:21
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```
### Commands

```
  2x -5:13.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:13.5.0 tree-view:remove (span.name.icon.icon-file-text)
     -4:11.2.0 core:copy (atom-text-editor.editor.is-focused)
     -4:10.9.0 core:close (atom-text-editor.editor.is-focused)
     -4:06.1.0 core:paste (atom-text-editor.editor.is-focused)
     -4:05.6.0 core:save (atom-text-editor.editor.is-focused)
     -3:11.9.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -2:07.2.0 settings-view:open (a.stack-toggle)
     -1:53.1.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:43.6.0 core:cut (atom-text-editor.editor.is-focused)
     -0:40.4.0 tree-view:remove (li.file.entry.list-item.selected)
     -0:10.2.0 remote-ftp:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:07.2.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:06.5.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "emmet",
      "atom-minify",
      "linter-csslint",
      "linter-jshint",
      "linter-htmlhint",
      "linter",
      "minimap"
    ]
  },
  "Remote-FTP": {
    "autoUploadOnSave": "only when connected"
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.15
atom-beautify, vundefined
autoclose-html, v0.19.0
color-picker, v2.0.14
filesize, v0.4.2
highlight-line, v0.11.0
language-liquid, v0.4.0
wordpress, v0.2.0

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Your .ftpconfig file does contain invalid JSON syntax

**Comment by fseminario** [comment]
I request this ticket to be reopened. The JSON is not invalid but rather the password field can't contain certain characters. This password reproduces the error, ";4kxDrGV46\6".

**Comment by jpxd** [comment]
The config file is in JSON format. Replace the "\" with "\" to escape it.

**Comment by fseminario** [comment]
Goes to show how much I know about JSON! pardon the bother. thanks
