### ISSUE TITLE
Uncaught SyntaxError: Unexpected token $

### ISSUE THREAD

**Issue by dotcollective-brendon** [icetee/remote-ftp#299]
1 "user": "gearhostuser\$gearhostuser",

Plugin errors when a dollar sign is used within the username.

**Atom Version**: 1.5.3
**System**: Mac OS X 10.10.5
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.20
### Stack Trace

Uncaught SyntaxError: Unexpected token $

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Felitepsdcoding%2FSites%2FSouth%20South%20West%2Fonehotyoga%2Fwp-content%2Fthemes%2Fonehotyoga%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%7D%5D%2C%22windowInitializationScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Finitialize-application-window.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22windowDimensions%22%3A%7B%22x%22%3A32%2C%22y%22%3A55%2C%22width%22%3A1900%2C%22height%22%3A1037%7D%2C%22appVersion%22%3A%221.5.3%22%2C%22atomHome%22%3A%22%2FUsers%2Felitepsdcoding%2F.atom%22%2C%22initialPaths%22%3A%5B%22%2FUsers%2Felitepsdcoding%2FSites%2FSouth%20South%20West%2Fonehotyoga%2Fwp-content%2Fthemes%2Fonehotyoga%22%5D%7D:5

SyntaxError: Unexpected token $
    at Object.parse (native)
    at /Users/elitepsdcoding/.atom/packages/Remote-FTP/lib/client.js:78:21
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```
### Commands

```
  3x -1:27.5.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -1:25.5.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:24.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:24.8.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:22.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:14.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:42 remote-ftp:toggle (atom-text-editor.editor.is-focused)
     -0:01.4.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "snippets"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.20
atom-beautify, v0.28.22
autoclose-html, v0.21.0
bottom-dock, v0.3.7
gulp-manager, v0.2.18
remote-sync, v3.5.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by jpxd** [comment]
You have to escape the backslash `\$` --> `\\$`
