### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by TheLonelyFox96** [icetee/remote-ftp#303]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.4
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.20
### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:8

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:477:5)
    at /Users/thomasfox/.atom/packages/Remote-FTP/lib/connectors/sftp.js:179:22
    at state.requests.(anonymous function).cb (/Users/thomasfox/.atom/packages/SFTP-deployment/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:1780:16)
    at SFTPStream._transform (/Users/thomasfox/.atom/packages/SFTP-deployment/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:384:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/Users/thomasfox/.atom/packages/SFTP-deployment/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:173:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at SFTPStream.Writable.write (_stream_writable.js:207:11)
    at Channel.ondata (_stream_readable.js:525:20)
    at emitOne (events.js:77:13)
    at Channel.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Channel.Readable.push (_stream_readable.js:110:10)
    at SSH2Stream.<anonymous> (/Users/thomasfox/.atom/packages/SFTP-deployment/node_modules/ssh2/lib/Channel.js:140:15)
    at emitOne (events.js:77:13)
    at SSH2Stream.emit (events.js:169:7)
    at parsePacket (/Users/thomasfox/.atom/packages/SFTP-deployment/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3168:10)
    at SSH2Stream._transform (/Users/thomasfox/.atom/packages/SFTP-deployment/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:555:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/Users/thomasfox/.atom/packages/SFTP-deployment/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:213:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at SSH2Stream.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (_stream_readable.js:525:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```
### Commands

```
     -7:17.3.0 core:paste (atom-text-editor.editor.is-focused)
  8x -7:15.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:07.4.0 core:save (atom-text-editor.editor.is-focused)
     -6:47.7.0 tree-view:add-file (span.name.icon.icon-file-directory)
  2x -6:43.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:40.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:18.2.0 sftp-deployment:uploadSelection (span.name.icon.icon-repo)
     -3:04.1.0 remote-ftp:sync-with-local (div.header.list-item)
     -2:29.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-material-syntax.theme-atom-material-ui)
     -1:58.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:54 remote-ftp:toggle (atom-text-editor.editor.mini.is-focused)
  2x -1:47.8.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-material-syntax.theme-atom-material-ui)
  5x -0:44.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:30 remote-ftp:toggle (atom-text-editor.editor.is-focused)
     -0:22.8.0 remote-ftp:connect (atom-text-editor.editor.is-focused)
     -0:02.7.0 remote-ftp:sync-with-local (div.header.list-item)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.20
atom-material-syntax, v0.2.4
atom-material-ui, v0.6.2
linter, v1.8.1
linter-eslint, v3.1.1

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Should be fixed in the latest release

**Comment by Nerret** [comment]
If it was fixed, its back becuase im getting this long pice of text, very simmelar to the one above. 

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
    at Client.module.exports.Client.toRemote (C:\Users\pete373e.atom\packages\Remote-FTP\lib\client.js:337:15)
    at ConnectorFTP.module.exports.ConnectorFTP.put (C:\Users\pete373e.atom\packages\Remote-FTP\lib\connectors\ftp.js:307:25)
    at Client.<anonymous> (C:\Users\pete373e.atom\packages\Remote-FTP\lib\client.js:444:20)
    at Client.module.exports.Client._next (C:\Users\pete373e.atom\packages\Remote-FTP\lib\client.js:359:21)
    at Client.module.exports.Client._enqueue (C:\Users\pete373e.atom\packages\Remote-FTP\lib\client.js:370:9)
    at Client.<anonymous> (C:\Users\pete373e.atom\packages\Remote-FTP\lib\client.js:443:9)
    at Client.module.exports.Client.onceConnected (C:\Users\pete373e.atom\packages\Remote-FTP\lib\client.js:167:14)
    at Client.module.exports.Client.upload (C:\Users\pete373e.atom\packages\Remote-FTP\lib\client.js:442:8)
    at C:\Users\pete373e.atom\packages\Remote-FTP\lib\remote-ftp.js:308:29
    at Array.forEach (native)
    at atom-workspace.atom.commands.add.remote-ftp:upload-selected (C:\Users\pete373e.atom\packages\Remote-FTP\lib\remote-ftp.js:305:12)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\pete373e\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\pete373e\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\pete373e\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\pete373e\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:1106:28)
    at EventEmitter.outerCallback (C:\Users\pete373e\AppData\Local\atom\app-1.8.0\resources\app.asar\src\application-delegate.js:340:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)

Only package that I installed so far is Remote-FTP. 

Any help is very much appiciated. 

Thanks in advance
