### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir

### ISSUE THREAD

**Issue by orykami** [icetee/remote-ftp#305]
[Enter steps to reproduce below:]
1. Create file named "filename"
2. Delete file named "filename"
3. Create folder named "filename"

**Atom Version**: 1.5.3
**System**: Unknown Windows Version
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.20
### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'D:\Workspace\gdl\application\modules\admin\views\scripts\booking\payment'

```
At C:\Users\Orykami\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:76

Error: EEXIST: file already exists, mkdir 'D:\Workspace\gdl\application\modules\admin\views\scripts\booking\payment'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:799:18)
    at Function.sync (C:\Users\Orykami\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:55:12)
    at Object.fsPlus.makeTreeSync (C:\Users\Orykami\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:343:23)
    at C:\Users\Orykami\.atom\packages\Remote-FTP\lib\connectors\sftp.js:245:8
    at SFTPStream._transform (C:\Users\Orykami\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\sftp.js:474:15)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (C:\Users\Orykami\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\sftp.js:173:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at SFTPStream.Writable.write (_stream_writable.js:207:11)
    at Channel.ondata (_stream_readable.js:525:20)
    at emitOne (events.js:77:13)
    at Channel.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Channel.Readable.push (_stream_readable.js:110:10)
    at SSH2Stream.<anonymous> (C:\Users\Orykami\.atom\packages\Remote-FTP\node_modules\ssh2\lib\Channel.js:140:15)
    at emitOne (events.js:77:13)
    at SSH2Stream.emit (events.js:169:7)
    at parsePacket (C:\Users\Orykami\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:3163:10)
    at SSH2Stream._transform (C:\Users\Orykami\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:552:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (C:\Users\Orykami\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:213:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at SSH2Stream.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (_stream_readable.js:525:20)
    at emitOne (events.js:77:13)
```
### Commands

```
     -1:46.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:45.7.0 core:save (atom-text-editor.editor.is-focused)
     -1:14.6.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:13.9.0 core:copy (atom-text-editor.editor.is-focused)
     -1:05.8.0 core:paste (atom-text-editor.editor.is-focused)
  4x -1:00.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:53 core:save (atom-text-editor.editor.is-focused)
     -0:45.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:44.6.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:36.4.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:33.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:19.5.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
  2x -0:16.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:14.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:10.3.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:09.6.0 core:copy (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "Remote-FTP": {
    "hideLocalWhenDisplayed": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-pair, v2.0.10
Remote-FTP, v0.7.20

# Dev
No dev packages
```

**Comment by orykami** [comment]
1) Create file named "filename"
2) Delete it (it seems the file persist in local workspace)
3) Try to create a directory named "filename"
4) The module throw Exception ^^

This error can be fixed locally by trashing local file named "filename".

Issue with unlink in local repository maybe ?

**Comment by jpxd** [comment]
Link #112

**Comment by hatzopoulos** [comment]
Closing, in favor of the older #122
