### ISSUE TITLE
Uncaught Error: stream.push() after EOF

### ISSUE THREAD

**Issue by theRichu** [icetee/remote-ftp#32]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.4.7
### Stack Trace

Uncaught Error: stream.push() after EOF

```
At events.js:94

Error: stream.push() after EOF
  at readableAddChunk (_stream_readable.js:150:15)
  at SSH2Stream.Readable.push (_stream_readable.js:127:10)
  at SSH2Stream.Transform.push [as __push] (_stream_transform.js:142:32)
  at SSH2Stream.push (/Users/TaeYeongKIM/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:217:18)
  at send (/Users/TaeYeongKIM/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:4812:12)
  at SSH2Stream.channelEOF (/Users/TaeYeongKIM/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:774:10)
  at Channel.eof (/Users/TaeYeongKIM/.atom/packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:306:35)
  at Channel.onFinish (/Users/TaeYeongKIM/.atom/packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:260:10)
  at Channel.emit (events.js:113:17)
  at prefinish (_stream_writable.js:476:12)
  at finishMaybe (_stream_writable.js:484:7)
  at endWritable (_stream_writable.js:495:3)
  at Channel.Writable.end (_stream_writable.js:461:5)
  at SFTPStream.onend (_stream_readable.js:506:10)
  at SFTPStream.g (events.js:202:16)
  at SFTPStream.emit (events.js:138:20)
  at _stream_readable.js:909:16
  at process._tickCallback (node.js:364:11)

```
### Commands

```
     -8:15.1 core:move-down (atom-text-editor.editor)
  4x -8:14.7 core:backspace (atom-text-editor.editor)
     -8:12.9 core:save (atom-text-editor.editor)
     -8:11.9 core:move-down (atom-text-editor.editor)
  2x -8:11.6 core:move-left (atom-text-editor.editor)
     -8:07.6 core:save (atom-text-editor.editor)
     -8:06.7 core:close (atom-text-editor.editor)
     -7:38.8 core:save (atom-text-editor.editor)
     -6:32.1 settings-view:open (atom-text-editor.editor)
     -0:35.4 core:move-right (atom-text-editor.editor)
  5x -0:35.1 core:select-down (atom-text-editor.editor)
     -0:32.6 core:backspace (atom-text-editor.editor)
     -0:32.2 core:save (atom-text-editor.editor)
     -0:10.3 remote-ftp:disonnect (ol.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:07.0 remote-ftp:toggle (ol.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:00.4 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.4.7
highlight-line, v0.9.3
project-manager, v1.15.5

# Dev
No dev packages
```

/cc @atom/core

**Comment by grenierdev** [comment]
Will need something more to chew on here. What did you try to do?

**Comment by ghost** [comment]
I got this error when I tried to connect using SFTP

**Comment by MiquelAdell** [comment]
Hi,

I've been able to reproduce it but I don't know if you'll be able to. I don't know if the error is caused by some particularity of my server.

Anyway, my report:

[Enter steps to reproduce below:]
1. Connect to a SFTP server by using the command: [cmd]+[shift]+[p]: remote ftp: connect
2. Disconnect from the SFTP server by using the command: [cmd]+[shift]+[p]: remote ftp: disconnect

the first time it happened to me I, of course, was uploading saves and all that stuff but right now I'm able to reproduce it with anytime I want by just connecting and disconnecting

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.1
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.6.2

### Stack Trace

Uncaught Error: stream.push() after EOF

```
At events.js:94

Error: stream.push() after EOF
  at readableAddChunk (_stream_readable.js:150:15)
  at SSH2Stream.Readable.push (_stream_readable.js:127:10)
  at SSH2Stream.Transform.push [as __push] (_stream_transform.js:142:32)
  at SSH2Stream.push (/Users/miquel/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:217:18)
  at send (/Users/miquel/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:4825:12)
  at SSH2Stream.channelEOF (/Users/miquel/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:774:10)
  at Channel.eof (/Users/miquel/.atom/packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:271:35)
  at Channel.onFinish (/Users/miquel/.atom/packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:256:10)
  at Channel.emit (events.js:113:17)
  at prefinish (_stream_writable.js:476:12)
  at finishMaybe (_stream_writable.js:484:7)
  at endWritable (_stream_writable.js:495:3)
  at Channel.Writable.end (_stream_writable.js:461:5)
  at SFTPStream.onend (_stream_readable.js:506:10)
  at SFTPStream.g (events.js:202:16)
  at SFTPStream.emit (events.js:138:20)
  at _stream_readable.js:909:16
  at process._tickCallback (node.js:366:11)

```

### Commands

```
     -0:09.5 project-manager:toggle (atom-text-editor.editor)
     -0:08.4 core:confirm (atom-text-editor.editor.mini)
     -0:07.5 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
  4x -0:06.1 core:backspace (atom-text-editor.editor.mini)
     -0:04.2 core:confirm (atom-text-editor.editor.mini)
     -0:04.1 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:02.2 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:00.8 core:confirm (atom-text-editor.editor.mini)
     -0:00.8 remote-ftp:disconnect (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "wrap-guide",
      "whitespace",
      "preview-tabs",
      "term2",
      "atom-ctags",
      "remote-edit"
    ],
    "projectHome": "/Users/miquel/code",
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

``` coffee
# User
Remote-FTP, v0.6.2
Sublime-Style-Column-Selection, v1.2.3
auto-detect-indentation, v0.3.0
autocomplete-plus, v2.5.0
autocomplete-snippets, v1.2.0
color-picker, v1.4.4
compare-files, v0.4.1
git-tab-status, v1.5.3
highlight-selected, v0.9.1
linter, v0.12.0
minimap, v4.6.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.0
minimap-selection, v4.2.0
project-manager, v1.15.5
remember-session, v0.5.1
tabs-to-spaces, v0.8.1

# Dev
No dev packages
```
