### ISSUE TITLE
Invalid host hash algorithm: undefined

### ISSUE THREAD

**Issue by eulogy14** [icetee/remote-ftp#321]
## **Invalid host hash algorithm: undefined**

Just reinstalled Atom and then started firing up my usual plugins and then configuring remote-ftp.
At first I thought a reinstallation of the plugin will fix it but nothing changed.

**Atom Version**: 1.6.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.20
### Stack Trace

Uncaught Error: Invalid host hash algorithm: undefined

```
At C:\Users\isoogy\.atom\packages\Remote-FTP\node_modules\ssh2\lib\client.js:342

Error: Invalid host hash algorithm: undefined
    at Client.connect (C:\Users\isoogy\.atom\packages\Remote-FTP\node_modules\ssh2\lib\client.js:342:13)
    at ConnectorSFTP.module.exports.ConnectorSFTP.connect (C:\Users\isoogy\.atom\packages\Remote-FTP\lib\connectors\sftp.js:79:13)
    at Client.module.exports.Client.doConnect (C:\Users\isoogy\.atom\packages\Remote-FTP\lib\client.js:241:18)
    at space-pen-div.<anonymous> (C:\Users\isoogy\.atom\packages\Remote-FTP\lib\client.js:659:9)
    at space-pen-div.jQuery.event.dispatch (C:\Users\isoogy\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at space-pen-div.elemData.handle (C:\Users\isoogy\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
    at Object.jQuery.event.trigger (C:\Users\isoogy\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4350:12)
    at space-pen-div.<anonymous> (C:\Users\isoogy\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4901:17)
    at Function.jQuery.extend.each (C:\Users\isoogy\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\jquery\dist\jquery.js:374:23)
    at PromptPassDialog.jQuery.fn.jQuery.each (C:\Users\isoogy\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\jquery\dist\jquery.js:139:17)
    at PromptPassDialog.jQuery.fn.extend.trigger [as originalTrigger] (C:\Users\isoogy\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4900:15)
    at PromptPassDialog.$.fn.trigger (C:\Users\isoogy\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:606:19)
    at PromptPassDialog.module.exports.PromptPassDialog.onConfirm (C:\Users\isoogy\.atom\packages\Remote-FTP\lib\dialogs\prompt-pass-dialog.js:50:8)
    at space-pen-div.PromptPassDialog.atom.commands.add.core:confirm (C:\Users\isoogy\.atom\packages\Remote-FTP\lib\dialogs\prompt-pass-dialog.js:44:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\isoogy\AppData\Local\atom\app-1.6.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\isoogy\AppData\Local\atom\app-1.6.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\isoogy\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\isoogy\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\isoogy\AppData\Local\atom\app-1.6.0\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\isoogy\AppData\Local\atom\app-1.6.0\resources\app.asar\src\window-event-handler.js:3:61)
```
### Commands

```
  4x -1:36.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:30.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:07.4.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:07.3.0 core:paste (atom-text-editor.editor.is-focused)
  3x -1:01.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:59.6.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -0:49.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:34.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:32.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:28.7.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:22 core:save (atom-text-editor.editor.is-focused)
     -0:09.3.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:08.5.0 core:save (atom-text-editor.editor.is-focused)
  9x -0:05.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:03.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {},
  "Remote-FTP": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.26
autoclose-html, v0.23.0
css-snippets, v0.9.0
emmet, v2.4.2
file-icons, v1.6.18
highlight-selected, v0.11.2
javascript-snippets, v1.2.1
node-debugger, v1.4.6
open-recent, v5.0.0
pigments, v0.24.5
Remote-FTP, v0.7.20
remote-sync, v3.5.0

# Dev
No dev packages
```

**Comment by xorinzor** [comment]
had the same issue, I just entered "sha1" and it worked

**Comment by cameronwlewis** [comment]
Also have this problem. Entering "sha1" or "md5" after hosthash doesn't do anything for me.

**Comment by radarsu** [comment]
Same here. I had to add: cfg.hostHash = 'sha1'; and then it worked.

**Comment by mattomalley** [comment]
I had the same issue. Updating the hosthash value from null to either 'md5' or 'sha1' on the .ftpconfig file worked for me.

**Comment by GeneralCan** [comment]
adding 'md5' or 'sha1' in lowercase to hosthash value also worked here.

**Comment by jadedcore** [comment]
I copied the ssh2 folder from a known working instance of the package and replaced the broken versions ssh2 folder with it and everything worked as before.

**Comment by jpxd** [comment]
After merging #325 it should work in the latest release
