### ISSUE TITLE
Uncaught Error: Invalid host hash algorithm: undefined

### ISSUE THREAD

**Issue by tretten** [icetee/remote-ftp#326]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.20
### Stack Trace

Uncaught Error: Invalid host hash algorithm: undefined

```
At /Users/tretten/.atom/packages/Remote-FTP/node_modules/ssh2/lib/client.js:342

Error: Invalid host hash algorithm: undefined
    at Client.connect (/Users/tretten/.atom/packages/Remote-FTP/node_modules/ssh2/lib/client.js:342:13)
    at ConnectorSFTP.module.exports.ConnectorSFTP.connect (/Users/tretten/.atom/packages/Remote-FTP/lib/connectors/sftp.js:79:13)
    at Client.module.exports.Client.doConnect (/Users/tretten/.atom/packages/Remote-FTP/lib/client.js:241:18)
    at Client.module.exports.Client.connect (/Users/tretten/.atom/packages/Remote-FTP/lib/client.js:159:9)
    at Client.<anonymous> (/Users/tretten/.atom/packages/Remote-FTP/lib/client.js:136:10)
    at e (/Users/tretten/.atom/packages/Remote-FTP/lib/client.js:69:14)
    at ReadFileContext.callback (/Users/tretten/.atom/packages/Remote-FTP/lib/client.js:74:12)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
```
### Commands

```
     -2:50.4.0 core:paste (input.hidden-input)
     -2:49.9.0 core:save (input.hidden-input)
     -2:47.2.0 settings-view:open (input.hidden-input)
     -2:38.6.0 core:close (input#Remote-FTP.hideLocalWhenDisplayed.)
  2x -2:30.9.0 core:undo (input.hidden-input)
     -2:26.4.0 core:close (input.hidden-input)
  2x -1:52.3.0 find-and-replace:select-next (input.hidden-input)
     -1:50 core:move-right (input.hidden-input)
 15x -1:49.5.0 core:move-left (input.hidden-input)
 10x -1:47.5.0 core:select-left (input.hidden-input)
     -1:45.4.0 core:backspace (input.hidden-input)
     -1:44.9.0 core:save (input.hidden-input)
     -1:37.3.0 tree-view:remove (span.name.icon.icon-file-text)
  2x -1:34.9.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
 10x -0:07.7.0 core:undo (input.hidden-input)
     -0:01.7.0 core:save (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "welcome",
      "timecop",
      "open-on-github",
      "minimap",
      "about"
    ],
    "themes": [
      "spacegray-dark-ui",
      "base16-ocean-dark-spacegray-lighter-invisibles"
    ]
  },
  "Remote-FTP": {
    "showViewOnStartup": false
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.20
atom-beautify, v0.28.26
autoclose-html, v0.23.0
base16-ocean-dark-spacegray-lighter-invisibles, v0.3.0
color-picker, v2.1.1
file-icons, v1.6.18
highlight-line, v0.11.1
pigments, v0.24.5
remote-atom-plus, v0.1.0
spacegray-dark-ui, v0.12.0
tag, v0.3.0

# Dev
No dev packages
```

**Comment by dhyegocalota** [comment]
This is referenced in #325

**Comment by tretten** [comment]
Didn't help

— N

On Tue, Mar 22, 2016 at 08:16 Dhyego Fernando

<
mailto:Dhyego Fernando notifications@github.com

> wrote:

This is referenced in
https://github.com/mgrenier/remote-ftp/pull/325

**Comment by dhyegocalota** [comment]
@tretten what did you exactly do? Did an error occurred? What error?

**Comment by tretten** [comment]
Steps from 
https://github.com/mgrenier/remote-ftp/pull/325
— N

On Wed, Mar 23, 2016 at 12:30 Dhyego Fernando

<
mailto:Dhyego Fernando notifications@github.com

> wrote:

https://github.com/tretten
what did you exactly do?
