### ISSUE TITLE
Uncaught TypeError: Cannot read property 'item' of undefined

### ISSUE THREAD

**Issue by theRichu** [icetee/remote-ftp#33]
[Enter steps to reproduce below:]
1. connect my server
2. create new file

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.4.7
### Stack Trace

Uncaught TypeError: Cannot read property 'item' of undefined

```
At /Users/TaeYeongKIM/.atom/packages/Remote-FTP/lib/remote-ftp.js:127

TypeError: Cannot read property 'item' of undefined
  at HTMLDivElement.<anonymous> (/Users/TaeYeongKIM/.atom/packages/Remote-FTP/lib/remote-ftp.js:127:51)
  at HTMLDivElement.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:110:34)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at AddDialog.jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at AddDialog.module.exports.AddDialog.onConfirm (/Users/TaeYeongKIM/.atom/packages/Remote-FTP/lib/dialogs/add-dialog.js:22:8)
  at HTMLDivElement.<anonymous> (/Users/TaeYeongKIM/.atom/packages/Remote-FTP/lib/dialogs/dialog.js:49:9)
  at HTMLDivElement.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```
### Commands

```
  3x -7:15.6 editor:toggle-line-comments (atom-text-editor.editor)
  4x -7:07.9 tree-view:toggle (atom-text-editor.editor)
     -0:16.1 remote-ftp:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:00.7 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.4.7
highlight-line, v0.9.3
minimap, v4.1.0
project-switcher, v0.1.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by ssnyder** [comment]
I get this error as well on windows.

**Atom Version**: 0.176.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.4.8

### Stack Trace

Uncaught TypeError: Cannot read property 'item' of undefined

```
At c:\Users\sharon_snyder\.atom\packages\Remote-FTP\lib\remote-ftp.js:308

TypeError: Cannot read property 'item' of undefined
  at c:\Users\sharon_snyder\.atom\packages\Remote-FTP\lib\remote-ftp.js:308:20
  at e (c:\Users\sharon_snyder\.atom\packages\Remote-FTP\lib\client.js:472:18)
  at n (c:\Users\sharon_snyder\.atom\packages\Remote-FTP\lib\client.js:479:16)
  at c:\Users\sharon_snyder\.atom\packages\Remote-FTP\lib\client.js:504:7
  at e (c:\Users\sharon_snyder\.atom\packages\Remote-FTP\lib\client.js:363:14)
  at c:\Users\sharon_snyder\.atom\packages\Remote-FTP\lib\client.js:369:13
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
     -8:28.3 core:copy (atom-text-editor.editor)
     -0:58.1 remote-ftp:toggle (atom-text-editor.editor)
     -0:34.2 remote-ftp:disonnect (ol.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:26.8 remote-ftp:connect (ol.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "tualo-git-context"
    ],
    "themes": [
      "atom-dark-ui",
      "quantum-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
color-picker, v1.4.4
column-select, v0.1.0
cucumber, v0.4.1
git-log, v0.2.0
git-tab-status, v1.5.3
jenkins-dashboard, v0.2.0
language-gherkin, v0.3.0
language-gherkin-german, v0.5.2
language-rspec, v0.3.0
language-sql-mysql, v0.3.1
minimap, v4.1.3
open-in-atom, v0.1.8
open-last-project, v0.2.2
project-manager, v1.15.5
quantum-syntax, v0.2.1
Remote-FTP, v0.4.8
ruby-block-converter, v3.1.0
save-session, v0.11.5
ScssBundle, v0.4.0
select-rectangle, v1.0.2
seti-ui, vundefined
SFTP-deployment, v0.5.0
tabs-to-spaces, v0.8.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by inovek** [comment]
1. Rightclick on a CSS file.
2.  Sync Local to Remote
3. Error Message

Manual upload/download works.

OS: Windows 8.1

**Atom Version**: 0.188.0
**System**: WINDOWS
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.6.2

### Stack Trace

Uncaught TypeError: Cannot read property 'item' of undefined

```
At C:\Users\User\.atom\packages\Remote-FTP\lib\remote-ftp.js:333

TypeError: Cannot read property 'item' of undefined
  at C:\Users\User\.atom\packages\Remote-FTP\lib\remote-ftp.js:333:20
  at e (C:\Users\User\.atom\packages\Remote-FTP\lib\client.js:490:18)
  at n (C:\Users\User\.atom\packages\Remote-FTP\lib\client.js:497:16)
  at C:\Users\User\.atom\packages\Remote-FTP\lib\client.js:522:7
  at e (C:\Users\User\.atom\packages\Remote-FTP\lib\client.js:381:14)
  at C:\Users\User\.atom\packages\Remote-FTP\lib\client.js:387:13
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
  2x -7:07.9 core:backspace (atom-text-editor.editor.mini)
     -7:00.4 core:confirm (atom-text-editor.editor.mini)
 12x -6:59.3 core:backspace (atom-text-editor.editor.mini)
     -6:55.0 core:confirm (atom-text-editor.editor.mini)
     -2:56.6 sass-watch:watch (atom-text-editor.editor)
     -2:46.0 core:confirm (atom-text-editor.editor.mini)
     -2:32.9 command-palette:toggle (atom-text-editor.editor)
     -2:30.0 core:move-down (atom-text-editor.editor.mini)
     -2:25.1 core:move-up (atom-text-editor.editor.mini)
     -2:24.9 core:confirm (atom-text-editor.editor.mini)
     -2:24.9 sass-watch:list (atom-text-editor.editor)
  3x -2:16.1 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "SFTP-deployment",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-shellscript",
      "language-toml",
      "language-yaml",
      "language-mustache"
    ]
  },
  "Remote-FTP": {
    "hideLocalWhenDisplayed": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.7.0
autocomplete-snippets, v1.2.0
color-picker, v1.5.0
keyboard-localization, v1.1.6
linter, v0.12.0
linter-php, v0.0.11
linter-phpcs, v0.0.12
minimap, v4.6.0
project-manager, v1.15.5
Remote-FTP, v0.6.2
sass-watch, v0.2.0
save-session, v0.12.4
wordpress-api, v1.2.0

# Dev
No dev packages
```
