### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/Users/gredens/Google Drive/Richard/Site...

### ISSUE THREAD

**Issue by richardaanzee** [icetee/remote-ftp#343]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.1
**System**: Mac OS X 10.11.4
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.20
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/gredens/Google Drive/Richard/Sites/...{removed because of intellectual property}.../submodules/...{removed because of intellectual property}.../fonts'

```
At fs.js:897

Error: ENOENT: no such file or directory, stat '/Users/gredens/Google Drive/Richard/Sites/...{removed because of intellectual property}.../submodules/...{removed because of intellectual property}.../fonts'
    at Error (native)
    at fs.statSync (fs.js:897:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:264:16)
    at /Users/gredens/.atom/packages/Remote-FTP/lib/client.js:441:21
    at Array.forEach (native)
    at /Users/gredens/.atom/packages/Remote-FTP/lib/client.js:436:9
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
     -0:00.9.0 remote-ftp:sync-with-local (span.name.icon.icon-file-directory)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.20
atom-autocomplete-php, v0.18.7
autoclose-html, v0.23.0
hyperclick, v0.0.35
hyperclick-php, v0.2.1
language-cfml, v0.12.0
language-twig, v1.6.3
linter, v1.11.4
linter-cflint, v0.9.2
linter-eslint, v7.2.0
linter-jscs, v3.5.0
linter-php, v1.2.0
linter-twig, v0.1.1
php-debug, v0.2.2
php-hyperclick, v0.3.1
php-twig, v4.0.0
pigments, v0.26.0
react, v0.15.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by samifouad** [comment]
This issue should be resolved with the latest version of the package ( v0.10.6 )

Details can be found in the pull-request here: #697
