### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '\applications\b...

### ISSUE THREAD

**Issue by areoid** [icetee/remote-ftp#344]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.20
### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'D:\KLN\micro\microsite-builder\applications\builder\controllers\couple-challenges\backend'

```
At C:\Users\areoid\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:76

Error: EEXIST: file already exists, mkdir 'D:\KLN\micro\microsite-builder\applications\builder\controllers\couple-challenges\backend'
    at Error (native)
    at fs.mkdirSync (fs.js:842:18)
    at Object.fs.mkdirSync (ATOM_SHELL_ASAR.js:592:16)
    at Function.sync (C:\Users\areoid\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:55:12)
    at Object.fsPlus.makeTreeSync (C:\Users\areoid\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:343:23)
    at C:\Users\areoid\.atom\packages\Remote-FTP\lib\connectors\ftp.js:447:8
    at Object.cb (C:\Users\areoid\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:1017:13)
    at Parser.<anonymous> (C:\Users\areoid\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:117:20)
    at emitTwo (events.js:87:13)
    at Parser.emit (events.js:172:7)
    at Parser._write (C:\Users\areoid\.atom\packages\Remote-FTP\node_modules\ftp\lib\parser.js:59:10)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Parser.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (C:\Users\areoid\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:273:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```
### Commands

```
     -2:37.4.0 remote-ftp:refresh-selected (span.name.icon.icon-file-directory)
     -1:48 remote-ftp:disconnect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:34.2.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-directory)
     -0:53.7.0 remote-ftp:refresh-selected (span.name.icon.icon-file-directory)
     -0:43.7.0 remote-ftp:disconnect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:23.5.0 remote-ftp:add-folder (span.name.icon.icon-file-directory)
     -0:18.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:11.8.0 remote-ftp:add-file (div.header.list-item)
     -0:03.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-alignment, v0.12.1
atom-autocomplete-php, v0.18.7
autoclose-html, v0.23.0
ctrl-last-tab, v0.3.0
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.6.21
highlight-selected, v0.11.2
linter, v1.11.4
linter-csslint, v1.3.2
linter-erb, v1.0.2
linter-htmlhint, v1.1.1
linter-jshint, v2.0.4
linter-xmllint, v1.3.4
php-cs-fixer, v2.5.6
pigments, v0.26.0
Remote-FTP, v0.7.20

# Dev
No dev packages
```

**Comment by sircon-john** [comment]
I just had this issue.
I realized that a local file named the same as the remote folder I was working in needed to be deleted locally.

For me, this was caused by mis-clicking "create file" when I ment to click "create folder", and then deleting that remote file to correct my mistake. (leaving the local file behind)

**Comment by areoid** [comment]
[SOLVED]
@sircon-john yes sir, you right :+1: 

thanks
