### ISSUE TITLE
Cannot read property 'length' of undefined 

### ISSUE THREAD

**Issue by GeneralCan** [icetee/remote-ftp#357]
1. open Atom
2. Try to connect to sftp with username and password

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.8.1
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At buffer.js:554

TypeError: Cannot read property 'length' of undefined
    at Buffer.write (buffer.js:554:13)
    at SFTPStream.stat (/Users/Can/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:1599:7)
    at SFTPWrapper.stat (/Users/Can/.atom/packages/Remote-FTP/node_modules/ssh2/lib/SFTPWrapper.js:87:23)
    at /Users/Can/.atom/packages/Remote-FTP/lib/connectors/sftp.js:154:18
    at state.requests.(anonymous function).cb (/Users/Can/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:1885:16)
    at SFTPStream._transform (/Users/Can/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:387:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/Users/Can/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:170:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at SFTPStream.Writable.write (_stream_writable.js:207:11)
    at Channel.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at Channel.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Channel.Readable.push (_stream_readable.js:110:10)
    at SSH2Stream.<anonymous> (/Users/Can/.atom/packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:146:15)
    at emitOne (events.js:77:13)
    at SSH2Stream.emit (events.js:169:7)
    at parsePacket (/Users/Can/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3163:10)
    at SSH2Stream._transform (/Users/Can/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/Users/Can/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at SSH2Stream.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.8.1

# Dev
No dev packages
```

**Comment by jpxd** [comment]
duplicate #358
