### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir 'D:\projects\blog\public\views'

### ISSUE THREAD

**Issue by CamMakoJ** [icetee/remote-ftp#379]
[Enter steps to reproduce below:]
1. ...created new folder
2. ...created new file in folder
3. ...attempted to open file

**Atom Version**: 1.7.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.8.3
### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'D:\projects\blog\public\views'

```
At C:\Users\Cam\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:76

Error: EEXIST: file already exists, mkdir 'D:\projects\blog\public\views'
    at Error (native)
    at fs.mkdirSync (fs.js:842:18)
    at Object.fs.mkdirSync (ATOM_SHELL_ASAR.js:592:16)
    at Function.sync (C:\Users\Cam\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:55:12)
    at Object.fsPlus.makeTreeSync (C:\Users\Cam\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:343:23)
    at C:\Users\Cam\.atom\packages\Remote-FTP\lib\connectors\sftp.js:221:8
    at SFTPStream._transform (C:\Users\Cam\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\sftp.js:473:15)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (C:\Users\Cam\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\sftp.js:170:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at SFTPStream.Writable.write (_stream_writable.js:207:11)
    at Channel.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at Channel.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Channel.Readable.push (_stream_readable.js:110:10)
    at SSH2Stream.<anonymous> (C:\Users\Cam\.atom\packages\Remote-FTP\node_modules\ssh2\lib\Channel.js:146:15)
    at emitOne (events.js:77:13)
    at SSH2Stream.emit (events.js:169:7)
    at parsePacket (C:\Users\Cam\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:3163:10)
    at SSH2Stream._transform (C:\Users\Cam\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (C:\Users\Cam\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at SSH2Stream.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (_stream_readable.js:528:20)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-terminal-panel",
      "linter-tidy"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autoclose-html, v0.23.0
autocomplete-json, v1.10.0
javascript-snippets, v1.2.1
linter, v1.11.4
linter-htmlhint, v1.1.4
linter-jshint, v2.1.0
Remote-FTP, v0.8.3

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Duplicate to #112
