### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '/Users/mikek/Documents/Web/Staging_Area/dimen...

### ISSUE THREAD

**Issue by ghost** [icetee/remote-ftp#380]
[Enter steps to reproduce below:]
1. Connect via ftps 
2. Download file from [WordPress_Root]/wp-content/themes/[your-theme]

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.4
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.8.3
### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir '/Users/mikek/Documents/Web/Staging_Area/dimensionsed.org/wp-content/themes/dimensions-foundation-web-theme'

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:76

Error: EEXIST: file already exists, mkdir '/Users/mikek/Documents/Web/Staging_Area/dimensionsed.org/wp-content/themes/dimensions-foundation-web-theme'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at Function.sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:55:12)
    at Object.fsPlus.makeTreeSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:343:23)
    at /Users/mikek/.atom/packages/Remote-FTP/lib/connectors/sftp.js:221:8
    at SFTPStream._transform (/Users/mikek/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:473:15)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/Users/mikek/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:170:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at SFTPStream.Writable.write (_stream_writable.js:207:11)
    at Channel.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at Channel.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Channel.Readable.push (_stream_readable.js:110:10)
    at SSH2Stream.<anonymous> (/Users/mikek/.atom/packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:146:15)
    at emitOne (events.js:77:13)
    at SSH2Stream.emit (events.js:169:7)
    at parsePacket (/Users/mikek/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3163:10)
    at SSH2Stream._transform (/Users/mikek/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/Users/mikek/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at SSH2Stream.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
```
### Commands

```
     -0:07.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "php-cs-fixer",
      "css-clean"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.8.3
auto-indent, v0.5.0
markdown-themeable-pdf, v1.0.1

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Duplicate to #112
