### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, mkdir '/Users/mac10/Documents/GitHub/ilcoin/index.html/...

### ISSUE THREAD

**Issue by icacho-dev** [icetee/remote-ftp#401]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.8.3
### Stack Trace

Uncaught Error: ENOTDIR: not a directory, mkdir '/Users/mac10/Documents/GitHub/ilcoin/index.html/www/ilcoin'

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:74

Error: ENOTDIR: not a directory, mkdir '/Users/mac10/Documents/GitHub/ilcoin/index.html/www/ilcoin'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at Function.sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:55:12)
    at Object.fsPlus.makeTreeSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:372:23)
    at /Users/mac10/.atom/packages/Remote-FTP/lib/connectors/ftp.js:175:10
    at Object.cb (/Users/mac10/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:348:5)
    at Parser.<anonymous> (/Users/mac10/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:87:13)
    at Parser.emit (events.js:172:7)
    at Parser._write (/Users/mac10/.atom/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Parser.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (/Users/mac10/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```
### Commands

```
     -1:23.8.0 application:add-project-folder (atom-pane.pane.active)
     -1:10.5.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:07.5.0 core:confirm (input.hidden-input)
     -1:07.5.0 remote-ftp:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:51.7.0 remote-ftp:sync-with-remote (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "Remote-FTP": {}
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.8.3
angularjs, v0.3.4
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.13
highlight-selected, v0.11.2
linter, v1.11.8
linter-php, v1.2.0
linter-stylelint, v2.11.0
linter-tidy, v2.1.1
minimap, v4.24.4
minimap-linter, v1.1.1

# Dev
No dev packages
```

**Comment by jimmaaay** [comment]
See #453
