### ISSUE TITLE
Uncaught Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by lightfront** [icetee/remote-ftp#404]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.0-beta0
**System**: Mac OS X 10.11.5
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.8.3
### Stack Trace

Uncaught Error: EISDIR: illegal operation on a directory, read

```
At fs.js:651

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:651:19)
    at Object.fs.readFileSync (fs.js:472:24)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:426:29)
    at Client.module.exports.Client.doConnect (/Users/xbzhao/.atom/packages/Remote-FTP/lib/client.js:241:42)
    at Client.module.exports.Client.connect (/Users/xbzhao/.atom/packages/Remote-FTP/lib/client.js:196:9)
    at Client.<anonymous> (/Users/xbzhao/.atom/packages/Remote-FTP/lib/views/tree-view.js:182:28)
    at /Users/xbzhao/.atom/packages/Remote-FTP/lib/client.js:109:14
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```
### Commands

```
     -9:50.9.0 remote-ftp:toggle (atom-text-editor.editor.is-focused)
     -9:32.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:13.5.0 core:save (atom-text-editor.editor.is-focused)
     -9:08.1.0 remote-ftp:connect (atom-text-editor.editor.is-focused)
     -5:16.7.0 atom-commander:toggle-visible (atom-text-editor.editor.is-focused)
     -5:00.3.0 core:confirm (atom-text-editor.editor.mini.directory-editor.is-focused)
 18x -4:58.5.0 core:move-left (atom-text-editor.editor.mini.directory-editor.is-focused)
  2x -4:54.9.0 core:confirm (atom-text-editor.editor.mini.directory-editor.is-focused)
     -4:24.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -4:24.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -3:34 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autocomplete-snippets"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
git-plus, v5.15.0 (inactive)
language-latex, v0.6.1 (active)
latex, v0.33.0 (inactive)
latex-autocomplete, v0.5.1 (active)
latex-friend, v0.0.10 (inactive)
latexer, v0.3.0 (active)
linter, v1.11.10 (active)
linter-chktex, v1.3.0 (active)
markdown-preview-plus, v2.4.0 (active)
minimap, v4.24.6 (active)
minimap-bookmarks, v0.3.1 (active)
preview-inline, v1.0.4 (active)
project-manager, v2.9.7 (active)
Remote-FTP, v0.8.3 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by jimmaaay** [comment]
This would have been because you set the private key in `.ftpconfig` to a directory and not a file.
