### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, mkdir '/directory/of/project/'

### ISSUE THREAD

**Issue by ethush** [icetee/remote-ftp#412]
1.Open Editor
2.Open FTP Panel
3. Connect
4. Sync local <- remote

**Atom Version**: 1.8.0
**System**: "Fedora release
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.8.3
### Stack Trace

Uncaught Error: ENOTDIR: not a directory, mkdir '/var/www/html/project/index.html/public_html'

```
At /home/user/.atom/packages/Remote-FTP/node_modules/fs-plus/node_modules/mkdirp/index.js:74

Error: ENOTDIR: not a directory, mkdir '/var/www/html/project/index.html/public_html'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at Function.sync (/home/user/.atom/packages/Remote-FTP/node_modules/fs-plus/node_modules/mkdirp/index.js:55:12)
    at Object.fsPlus.makeTreeSync (/home/user/.atom/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:343:23)
    at /home/ethush/.atom/packages/Remote-FTP/lib/connectors/ftp.js:175:10
    at Object.cb (/home/ethush/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:348:5)
    at Parser.<anonymous> (/home/user/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:87:13)
    at Parser.emit (events.js:172:7)
    at Parser._write (/home/user/.atom/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Parser.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (/home/user/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```
### Commands

```
     -0:20.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-atom-dark-ui)
     -0:01.3.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-text)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ]
  },
  "Remote-FTP": {
    "autoUploadOnSave": "only when connected"
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.8.3
autocomplete-php, v0.3.7
codeigniter-nucleus, v0.4.3
coffee-links, v0.1.0
jquery-snippets, v11.0.0
linter-php, v1.2.0
php-analyser, v0.2.0
php-integrator-navigation, v0.7.1
project-manager, v2.9.7
seti-syntax, v1.0.1

# Dev
No dev packages
```

**Comment by jimmaaay** [comment]
@ethush From what I can see it's trying to make a directory called index.html, which could be what is throwing the error. Can you confirm that this is what's happening?

**Comment by jimmaaay** [comment]
See #453
