### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, mkdir '/Applications/XAMPP/xamppfiles/htdocs/STEMOS/w/s...

### ISSUE THREAD

**Issue by SaiD2z** [icetee/remote-ftp#415]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.8.3
### Stack Trace

Uncaught Error: ENOTDIR: not a directory, mkdir '/Applications/XAMPP/xamppfiles/htdocs/STEMOS/w/symfony24/composer.json/public_html/w/symfony24'

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:74

Error: ENOTDIR: not a directory, mkdir '/Applications/XAMPP/xamppfiles/htdocs/STEMOS/w/symfony24/composer.json/public_html/w/symfony24'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at Function.sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:55:12)
    at Object.fsPlus.makeTreeSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:372:23)
    at /Users/SaiD2z/.atom/packages/Remote-FTP/lib/connectors/ftp.js:175:10
    at Object.cb (/Users/SaiD2z/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:348:5)
    at Parser.<anonymous> (/Users/SaiD2z/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:87:13)
    at Parser.emit (events.js:172:7)
    at Parser._write (/Users/SaiD2z/.atom/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Parser.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (/Users/SaiD2z/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```
### Commands

```
     -0:01.2.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-text)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-autocomplete-php",
      "atom-php-navigation",
      "atom-sort-sass",
      "wrap-guide",
      "whitespace",
      "welcome",
      "open-on-github",
      "language-todo",
      "language-toml",
      "language-sass",
      "language-shellscript",
      "language-ruby",
      "language-ruby-on-rails",
      "language-property-list",
      "language-perl",
      "language-objective-c",
      "language-mustache",
      "language-make",
      "language-less",
      "language-json",
      "language-java",
      "language-go",
      "language-git",
      "language-gfm",
      "language-csharp",
      "language-clojure",
      "language-c",
      "incompatible-packages",
      "grammar-selector",
      "v-bootstrap4",
      "sass-autocompile",
      "remote-sync",
      "quick-query-mssql",
      "minimap",
      "php-composer-completion",
      "linter-coffeescript",
      "laravel-forms-bootstrap-snippets",
      "language-sql-mysql",
      "jquery-snippets",
      "jQuery",
      "composer",
      "coffee-porter",
      "build-sass",
      "bootstrap-3-snippetset",
      "autocomplete-php",
      "pinegrow-atom"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.8.3
atom-formatter-jsbeautify, v1.1.2
formatter-jsbeautify, v1.0.2
formatter-tidy, v1.0.1
php-integrator-autocomplete-plus, v1.0.0

# Dev
No dev packages
```

**Comment by jimmaaay** [comment]
See #453
