### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '/Users/benpritchard/Desktop/public_html/acs2_...

### ISSUE THREAD

**Issue by ben-pritchard** [icetee/remote-ftp#420]
[Enter steps to reproduce below:]
1. I created a file in a folder called _classes
2. Then I got the error

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.3
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.8.3
### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir '/Users/benpritchard/Desktop/public_html/acs2_ben/_classes'

```
At /Users/benpritchard/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:76

Error: EEXIST: file already exists, mkdir '/Users/benpritchard/Desktop/public_html/acs2_ben/_classes'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at Function.sync (/Users/benpritchard/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:55:12)
    at Object.fsPlus.makeTreeSync (/Users/benpritchard/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:372:23)
    at /Users/benpritchard/.atom/packages/Remote-FTP/lib/connectors/ftp.js:175:10
    at Object.cb (/Users/benpritchard/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:348:5)
    at Parser.<anonymous> (/Users/benpritchard/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:87:13)
    at Parser.emit (events.js:172:7)
    at Parser._write (/Users/benpritchard/.atom/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Parser.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (/Users/benpritchard/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```
### Commands

```
     -3:24.6.0 remote-ftp:delete-selected (span.name.icon.icon-file-directory)
     -3:15.2.0 remote-ftp:disconnect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:03.1.0 remote-ftp:delete-selected (span.name.icon.icon-file-directory)
     -2:54.8.0 remote-ftp:add-folder (span.name.icon.icon-file-directory)
     -2:52.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:49 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -2:41.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:49.9.0 remote-ftp:disconnect (ul.progress.tool-panel.panel-top)
     -1:33.1.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -1:29 remote-ftp:add-folder (span.name.icon.icon-file-directory)
     -1:25.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:21.8.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -1:17.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:50.3.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -0:43.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:26.2.0 remote-ftp:disconnect (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.8.3
pigments, v0.29.2

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Duplicate to #112
