### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\***\Documents\MEGA\PE...

### ISSUE THREAD

**Issue by HybridFox** [icetee/remote-ftp#422]
[Enter steps to reproduce below:]
1. Create a folder
2. Create a file
3. Open the file

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Home
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.8.3
### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users***\Documents\MEGA\PER\***\html\admin'

```
At C:\Users\***\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:76

Error: EEXIST: file already exists, mkdir 'C:\Users\***\Documents\MEGA\PER\***\html\admin'
    at Error (native)
    at fs.mkdirSync (fs.js:842:18)
    at Object.fs.mkdirSync (ATOM_SHELL_ASAR.js:592:16)
    at Function.sync (C:\Users\***\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:55:12)
    at Object.fsPlus.makeTreeSync (C:\Users\***\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:372:23)
    at C:\Users\***\.atom\packages\Remote-FTP\lib\connectors\sftp.js:221:8
    at SFTPStream._transform (C:\Users\***\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\sftp.js:473:15)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (C:\Users\***\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\sftp.js:170:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at SFTPStream.Writable.write (_stream_writable.js:207:11)
    at Channel.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at Channel.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Channel.Readable.push (_stream_readable.js:110:10)
    at SSH2Stream.<anonymous> (C:\Users\***\.atom\packages\Remote-FTP\node_modules\ssh2\lib\Channel.js:146:15)
    at emitOne (events.js:77:13)
    at SSH2Stream.emit (events.js:169:7)
    at parsePacket (C:\Users\***\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:3163:10)
    at SSH2Stream._transform (C:\Users\***\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (C:\Users\***\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at SSH2Stream.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (_stream_readable.js:528:20)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "autocomplete-project-paths",
      "atom-keyboard-macros",
      "fancy-bracket-matcher"
    ],
    "themes": [
      "seti-ui",
      "monokai-dark"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-dynamic-macro, v1.2.0
atom-html-preview, v0.1.19
autocomplete-paths, v1.0.2
color-picker, v2.1.1
keyboard-localization, v1.4.18
language-lua, v0.9.4
monokai-dark, v1.3.0
Remote-FTP, v0.8.3
seti-ui, v0.8.1
swackets, v0.10.0

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Duplicate to #112
