### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\d\Desktop\newproject\header902.php'

### ISSUE THREAD

**Issue by superklesk** [icetee/remote-ftp#436]
[Enter steps to reproduce below:]
1. Tryin' upload file name which exists
2. Throw that error
   so,
3. Why not "save as another name: ?" Why error?
4. Can't rename it too :((

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.8.3
### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\d\Desktop\newproject\header902.php'

```
At C:\Users\d\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:76

Error: EEXIST: file already exists, mkdir 'C:\Users\d\Desktop\newproject\header902.php'
    at Error (native)
    at fs.mkdirSync (fs.js:842:18)
    at Object.fs.mkdirSync (ATOM_SHELL_ASAR.js:592:16)
    at Function.sync (C:\Users\d\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:55:12)
    at Object.fsPlus.makeTreeSync (C:\Users\d\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:372:23)
    at C:\Users\d\.atom\packages\Remote-FTP\lib\connectors\ftp.js:175:10
    at Object.cb (C:\Users\d\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:348:5)
    at Parser.<anonymous> (C:\Users\d\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:117:20)
    at emitTwo (events.js:87:13)
    at Parser.emit (events.js:172:7)
    at Parser._write (C:\Users\d\.atom\packages\Remote-FTP\node_modules\ftp\lib\parser.js:59:10)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Parser.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (C:\Users\d\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:273:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```
### Commands

```
     -0:27.1.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -0:26.8.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  3x -0:25.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:24.2.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:20.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:20.3.0 editor:move-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
     -0:19.9.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -0:19.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:19.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:14.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-text)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
drunken-php, v0.2.1
remote-edit, v1.8.24
Remote-FTP, v0.8.3

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Duplicate to #112
