### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '$ATOM_HOME\application\library\footer_module'

### ISSUE THREAD

**Issue by Quirex** [icetee/remote-ftp#437]
[Enter steps to reproduce below:]
1. Create new folder footer_module.
2. Inside folder footer_module create file footer.php.
3. Pops up this error.
4. Remote-FTP crashes.

Next:
1. I add manually footer.php file using an external customer-ftp.
2. Re-run the .atom.
3. I go to the folder made footer_module.
4. Run the file footer.php editing - pops up an error.

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Home
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.8.3
### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\K.atom\application\library\footer_module'

```
At C:\Users\K\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:76

Error: EEXIST: file already exists, mkdir 'C:\Users\K\.atom\application\library\footer_module'
    at Error (native)
    at fs.mkdirSync (fs.js:842:18)
    at Object.fs.mkdirSync (ATOM_SHELL_ASAR.js:592:16)
    at Function.sync (C:\Users\K\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:55:12)
    at Object.fsPlus.makeTreeSync (C:\Users\K\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:372:23)
    at C:\Users\K\.atom\packages\Remote-FTP\lib\connectors\ftp.js:447:8
    at Object.cb (C:\Users\K\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:1017:13)
    at Parser.<anonymous> (C:\Users\K\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:117:20)
    at emitTwo (events.js:87:13)
    at Parser.emit (events.js:172:7)
    at Parser._write (C:\Users\K\.atom\packages\Remote-FTP\node_modules\ftp\lib\parser.js:59:10)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Parser.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (C:\Users\K\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:273:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```
### Commands

```
     -0:24.4.0 remote-ftp:add-folder (span.name.icon.icon-file-directory)
     -0:13.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.8.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -0:03.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.7.0
file-icons, v1.7.17
minimap, v4.24.7
pigments, v0.31.2
pinegrow-atom, v0.3.1
Remote-FTP, v0.8.3

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Duplicate to #112
