### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by nbdamian** [icetee/remote-ftp#447]
[Enter steps to reproduce below:]
1. Sync from local to live

**Atom Version**: 1.9.8
**System**: Ubuntu 14.04.5
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.8.4
### Stack Trace

Uncaught TypeError: Cannot read property 'apply' of undefined

```
At /home/damian/.atom/packages/Remote-FTP/lib/connectors/sftp.js:314

TypeError: Cannot read property 'apply' of undefined
    at applyProgress (/home/damian/.atom/packages/Remote-FTP/lib/connectors/sftp.js:314:15)
    at WriteStream.<anonymous> (/home/damian/.atom/packages/Remote-FTP/lib/connectors/sftp.js:321:6)
    at emitNone (events.js:85:20)
    at WriteStream.emit (events.js:179:7)
    at finishMaybe (_stream_writable.js:478:14)
    at afterWrite (_stream_writable.js:356:3)
    at onwrite (_stream_writable.js:346:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at /home/damian/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:2824:5
    at state.requests.(anonymous function).cb (/home/damian/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:941:15)
    at SFTPStream._transform (/home/damian/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:382:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/home/damian/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:170:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at SFTPStream.Writable.write (_stream_writable.js:215:11)
    at Channel.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:90:13)
    at Channel.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Channel.Readable.push (_stream_readable.js:111:10)
    at SSH2Stream.<anonymous> (/home/damian/.atom/packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:146:15)
    at emitOne (events.js:90:13)
    at SSH2Stream.emit (events.js:182:7)
    at parsePacket (/home/damian/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3163:10)
    at SSH2Stream._transform (/home/damian/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/home/damian/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at SSH2Stream.Writable.write (_stream_writable.js:215:11)
    at Socket.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)
```
### Commands

```
     -0:00.3.0 remote-ftp:sync-with-local (span.name.icon.icon-file-directory)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "guess-indent",
      "auto-indent"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-beautify",
      "sublime-block-comment",
      "api-docs"
    ]
  },
  "Remote-FTP": {
    "autoUploadOnSave": "only when connected"
  }
}
```
### Installed Packages

``` coffee
# User
api-docs, v0.0.6 (active)
atom-beautify, v0.29.10 (inactive)
atom-bootstrap3, v1.2.12 (inactive)
auto-indent, v0.5.0 (inactive)
color-picker, v2.2.2 (active)
css-specificity, v0.2.2 (active)
git-plus, v5.16.2 (inactive)
guess-indent, v0.1.0 (inactive)
jquery-snippets, v11.0.0 (active)
language-blade, v0.25.3 (active)
language-sql-mysql, v0.3.1 (active)
linter, v1.11.16 (active)
linter-bootlint, v1.0.2 (active)
linter-csslint, v1.3.2 (active)
linter-htmlhint, v1.3.0 (active)
linter-jshint, v2.1.0 (active)
linter-php, v1.2.0 (active)
local-history, v3.4.0 (active)
minimap, v4.24.7 (active)
open-on-bitbucket, v0.4.0 (inactive)
pdf-view, v0.50.0 (active)
project-manager, v2.9.7 (active)
project-viewer, v0.2.34 (active)
Remote-FTP, v0.8.4 (active)
sass-autocompile, v0.12.8 (active)
sublime-block-comment, v0.4.0 (inactive)
terminal-plus, v0.14.5 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Merged
