### ISSUE TITLE
Can't Install: "Cannot find module 'fs-plus'"

### ISSUE THREAD

**Issue by AlbertMN** [icetee/remote-ftp#461]
Atom does not let me install this package. Installing it in "settings" gives me this error;

`npm WARN optional Skipping failed optional dependency /Remote-FTP/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Users\alber\AppData\Local\atom\app-1.10.0\resources\app\apm\bin\node.exe" "C:\Users\alber\AppData\Local\atom\app-1.10.0\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\alber\.atom\.apm\.apmrc" "--userconfig" "C:\Users\alber\.atom\.apmrc" "install" "C:\Users\alber\AppData\Local\Temp\d-116731-2448-wt05yr\package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=ia32" "--global-style" "--msvs_version=2015"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! file C:\Users\alber.atom.apm\inherits\2.0.1\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: C:\Users\alber.atom.apm\inherits\2.0.1\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\alber\AppData\Local\Temp\apm-install-dir-116731-2448-8qnc6o\npm-debug.log`

^ There was no debug log (no **apm-install-dir...**) in my **Temp** folder, but I did find the "Atom Crashes" operation_log which is attached.
[operation_log.txt](https://github.com/mgrenier/remote-ftp/files/448064/operation_log.txt)

When I try to install "remote-edit" or "remote-sync", I get a similar error.

Dragging it manually in to the "_packages_" folder gives me the error below.
I have tried to reinstall Atom a few times, nothing seems to fix this. 

`Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\alber\AppData\Local\atom\app-1.10.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\alber\AppData\Local\atom\app-1.10.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.module.exports.activate (C:\Users\alber\.atom\packages\remote-ftp-master\lib\remote-ftp.js:40:9)
    at Package.module.exports.Package.activateNow (C:\Users\alber\AppData\Local\atom\app-1.10.0\resources\app.asar\src\package.js:183:20)
    at C:\Users\alber\AppData\Local\atom\app-1.10.0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\alber\AppData\Local\atom\app-1.10.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\alber\AppData\Local\atom\app-1.10.0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\alber\AppData\Local\atom\app-1.10.0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\alber\AppData\Local\atom\app-1.10.0\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\alber\AppData\Local\atom\app-1.10.0\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\alber\AppData\Local\atom\app-1.10.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\alber\AppData\Local\atom\app-1.10.0\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\alber\AppData\Local\atom\app-1.10.0\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\alber\AppData\Local\atom\app-1.10.0\resources\app.asar\src\atom-environment.js:765:28`

I use the latest version of Atom and your package.
I don't know if I have done something wrong here, but I've done everything I could think of to try and fix this problem.

Thank you in advance!

**Comment by jimmaaay** [comment]
What version of Windows are you running?

**Comment by AlbertMN** [comment]
@jimmaaay Windows 10

**Comment by jimmaaay** [comment]
Have no idea what the first error really is. I guess you could try reinstalling atom or see if you can find the package.json `C:\Users\alber.atom.apm\inherits\2.0.1\package\package.json`. Looks as though there may be an error with the json there?

However you could try adding it in manually. First you would drag the remote ftp folder into packages, then go to that directory in powershell or cmd and run `apm install`. That should fix the issue you had when you tried doing it manually.
