### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Botong** [icetee/remote-ftp#481]
The file actually exists and it is throwing error
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.8.9
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/bsui/OneDrive/CMU-MCDS/cloud_computing/project1_2/project0.pem'

```
At fs.js:584

Error: ENOENT: no such file or directory, open '/Users/bsui/OneDrive/CMU-MCDS/cloud_computing/project1_2/project0.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:158:20)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:426:29)
    at Client.module.exports.Client.doConnect (/Users/bsui/.atom/packages/Remote-FTP/lib/client.js:242:42)
    at Client.module.exports.Client.connect (/Users/bsui/.atom/packages/Remote-FTP/lib/client.js:197:9)
    at Client.<anonymous> (/Users/bsui/.atom/packages/Remote-FTP/lib/views/tree-view.js:183:28)
    at /Users/bsui/.atom/packages/Remote-FTP/lib/client.js:110:14
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.8.9 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by jimmaaay** [comment]
Could you try moving the file out of One Drive and then re reference it.

**Comment by Botong** [comment]
Yes, it works but before couple of versions ago, it works even under /onedrive, the one drive is also a local folder. Any idea why files under such directory cannot be recognized?

**Comment by jimmaaay** [comment]
Maybe the one drive folder is a system link. But that's the only reason I can think of off the top of my head

**Comment by Botong** [comment]
Thanks, but if it doesn't have access/permission to this particular folder,
how come it was working before? Has anything changed?

2016-10-09 5:35 GMT-04:00 jimmaaay notifications@github.com:

**Comment by jimmaaay** [comment]
Nothing had changed that would have affected that
