### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by daltonnyx** [icetee/remote-ftp#482]
[Enter steps to reproduce below:]

I Fixed this bug by changing this.path to this.parent.path in constructor of file.js(line 38).

**Atom Version**: 1.10.2
**Electron Version**: 1.4.1
**System**: linux 4.7.4-1-ARCH
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.8.9
### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.extname (path.js:1433:5)
    at Object.isReadmePath (/home/aquez/.atom/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:551:24)
    at new File (/home/aquez/.atom/packages/Remote-FTP/lib/file.js:41:10)
    at /home/aquez/.atom/packages/Remote-FTP/lib/directory.js:130:15
    at Array.forEach (native)
    at /home/aquez/.atom/packages/Remote-FTP/lib/directory.js:111:9
    at /home/aquez/.atom/packages/Remote-FTP/lib/client.js:411:16
    at /home/aquez/.atom/packages/Remote-FTP/lib/connectors/ftp.js:154:17
    at final (/home/aquez/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:476:11)
    at Socket.ondone (/home/aquez/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:451:7)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
### Commands

```
     -0:00.2.0 remote-ftp:connect (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-phpcs"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-uikit, v1.2.2 (inactive)
emmet, v2.4.3 (active)
es6-javascript, v1.0.0 (inactive)
highlight-selected, v0.11.2 (active)
language-cshtml, v0.2.1 (active)
linter, v1.11.16 (active)
linter-php, v1.2.0 (active)
linter-phpcs, v1.4.1 (inactive)
minimap, v4.25.0 (active)
nodejs-snippets, v2.0.2 (active)
Remote-FTP, v0.8.9 (active)
rest-client, v1.2.5 (active)
terminal-plus, v0.14.5 (active)
wordpress-api, v1.2.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by jimmaaay** [comment]
I haven't been able to reproduce this error. Would you be able to provide more details on how this error occurred?

**Comment by Fullpan** [comment]
same problem

**Comment by daltonnyx** [comment]
When I used atom on my ElemetaryOS, everything worked fine. Then i changed to arch linux 2 day ago. After installed Atom from their repositories. I installed few package i need. All package work fine except Remote-FTP and Terminal plus.

So i opened Source file of Remote-FTP and tried to debug. I noticed that in path.js file `this.path` is undefined. but `this.parent.path` has. I changed `this.path` to `this.parent.path` then everything work fine again.

**Comment by jimmaaay** [comment]
From what it sounds like though `this.parent.path` is the parent directory of the file or folder. It could be broken somewhere else and it is only throwing an error further down the line.

**Comment by 2114L3** [comment]
vbox 5.0.26 r 108824
arch 4.7.6-1
atom 1.10.2
remote-ftp 0.9.0
ftp with secure:true secureOptions:{"rejectUnauthorized": false} 
getting the same error and file listing never shows

**Comment by TiagoDanin** [comment]
Same problem :cry: 
1. Clicked in "Connect"

> Remote FTP: Connecting...
> 
> Remote FTP: Connected
> 
> ERRO LOG!
1. After 
   ![image](https://cloud.githubusercontent.com/assets/5731176/20018721/ab5fe44c-a2a7-11e6-9c2b-243297a1d363.png)

> Loop to listing

**Atom Version**: 1.10.2
**Electron Version**: 1.3.4
**System**: linux 4.7.2-1-ARCH
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.9.4

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.extname (path.js:1433:5)
    at Object.isReadmePath (/home/tiago/.atom/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:558:24)
    at new File (/home/tiago/.atom/packages/Remote-FTP/lib/file.js:41:10)
    at /home/tiago/.atom/packages/Remote-FTP/lib/directory.js:131:15
    at Array.forEach (native)
    at /home/tiago/.atom/packages/Remote-FTP/lib/directory.js:112:9
    at /home/tiago/.atom/packages/Remote-FTP/lib/client.js:475:58
    at callCompleted (/home/tiago/.atom/packages/Remote-FTP/lib/connectors/sftp.js:126:51)
    at oneDirCompleted (/home/tiago/.atom/packages/Remote-FTP/lib/connectors/sftp.js:130:22)
    at /home/tiago/.atom/packages/Remote-FTP/lib/connectors/sftp.js:196:30
    at Array.forEach (native)
    at /home/tiago/.atom/packages/Remote-FTP/lib/connectors/sftp.js:144:8
    at /home/tiago/.atom/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:1526:13
    at SFTPStream._transform (/home/tiago/.atom/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:382:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/home/tiago/.atom/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:556:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at SSH2Stream.<anonymous> (/home/tiago/.atom/packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/home/tiago/.atom/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3400:10)
    at SSH2Stream._transform (/home/tiago/.atom/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:665:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/home/tiago/.atom/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:249:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SSH2Stream.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:556:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at TCP.onread (net.js:542:20)
```

### Commands

```
     -9:48.8.0 core:copy (atom-text-editor.editor.is-focused)
     -9:46.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:45.9.0 core:paste (atom-text-editor.editor.is-focused)
     -9:31.1.0 core:save (atom-text-editor.editor.is-focused)
     -9:20.3.0 remote-ftp:connect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:35.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:35.2.0 core:save (atom-text-editor.editor.is-focused)
     -3:28.5.0 remote-ftp:connect (atom-text-editor.editor.is-focused)
     -1:16.7.0 core:undo (atom-text-editor.editor.is-focused)
     -1:15.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:03.6.0 remote-ftp:connect (div.offline)
     -0:12.6.0 remote-ftp:disconnect (atom-text-editor.editor.is-focused)
     -0:07.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "atom-beautify",
      "markdown-mindmap",
      "language-moonscript"
    ],
    "themes": [
      "one-dark-ui",
      "material-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-beautify, v0.29.13 (inactive)
beacon-ui, v0.5.0 (inactive)
language-latino, v0.2.0 (active)
language-lua, v0.9.11 (active)
language-moonscript, v1.7.1 (inactive)
markdown-mindmap, v0.2.4 (inactive)
material-syntax, v0.5.0 (active)
Remote-FTP, v0.9.4 (active)
remote-sync, v4.1.5 (active)
wakatime, v6.0.10 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

### My .ftpconfig

``` coffee
{
    "protocol": "sftp",
    "host": "~X~X~.com",
    "port": 22,
    "user": "root",
    "pass": "",
    "promptForPass": false,
    "remote": "/",
    "agent": "",
    "privatekey": "/home/tiago/.ssh/id_rsa",
    "passphrase": "~X~X~",
    "hosthash": "sha1",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": false,
    "watch": [],
    "watchTimeout": 500
}
```

**Comment by pimenlabs** [comment]
i found same error 

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 1.4.6
**System**: "Manjaro Linux"
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.9.4

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.extname (path.js:1433:5)
    at Object.isReadmePath (/home/pimen/.atom/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:558:24)
    at new File (/home/pimen/.atom/packages/Remote-FTP/lib/file.js:41:10)
    at /home/pimen/.atom/packages/Remote-FTP/lib/directory.js:131:15
    at Array.forEach (native)
    at /home/pimen/.atom/packages/Remote-FTP/lib/directory.js:112:9
    at /home/pimen/.atom/packages/Remote-FTP/lib/client.js:475:58
    at callCompleted (/home/pimen/.atom/packages/Remote-FTP/lib/connectors/sftp.js:126:51)
    at oneDirCompleted (/home/pimen/.atom/packages/Remote-FTP/lib/connectors/sftp.js:130:22)
    at /home/pimen/.atom/packages/Remote-FTP/lib/connectors/sftp.js:181:32
    at SFTPStream._transform (/home/pimen/.atom/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:496:15)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/home/pimen/.atom/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at SSH2Stream.<anonymous> (/home/pimen/.atom/packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/home/pimen/.atom/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3439:10)
    at SSH2Stream._transform (/home/pimen/.atom/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/home/pimen/.atom/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SSH2Stream.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -6:23.7.0 core:save (atom-text-editor.editor.is-focused)
     -6:20.3.0 core:close (atom-text-editor.editor.is-focused)
  2x -4:38.3.0 remote-ftp:disconnect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:25.5.0 application:open-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:23.1.0 remote-ftp:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:03.8.0 remote-ftp:disconnect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

``` json
{}
```

### Installed Packages

``` coffee
# User
Remote-FTP, v0.9.4 (active)
terminal-plus, v0.14.5 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by daltonnyx** [comment]
I added this `this.path = (this.path) ? this.path : this.parent.path;` before `if (fs.isReadmePath(this.path))` line in `file.js` file to fix this error. Although I need to keep doing it after the package update but for now It works.

**Comment by jpxd** [comment]
If this is still an issue, please re-open
