### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isExpanded' of null

### ISSUE THREAD

**Issue by olivedae** [icetee/remote-ftp#506]
Steps to reproduce:
1. Rename a folder to one that exists
2. Expand the edited folder (will still have its previous name)

When doing the same with files all seems good.

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.8.3
### Stack Trace

Uncaught TypeError: Cannot read property 'isExpanded' of null

```
At /Users/richardprotasov/.atom/packages/Remote-FTP/lib/views/directory-view.js:152

TypeError: Cannot read property 'isExpanded' of null
    at DirectoryView.module.exports.DirectoryView.setClasses (/Users/richardprotasov/.atom/packages/Remote-FTP/lib/views/directory-view.js:152:16)
    at /Users/richardprotasov/.atom/packages/Remote-FTP/lib/views/directory-view.js:55:52
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:155:30
    at Array.forEach (native)
    at Behavior.module.exports.Emitter.emitSlow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:154:47)
    at Behavior.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:107:30)
    at Behavior.module.exports.Behavior.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/behavior.js:44:38)
    at Behavior.module.exports.Signal.emitValue (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/signal.js:82:19)
    at Directory.module.exports.Model.set (/Users/richardprotasov/.atom/packages/Remote-FTP/node_modules/theorist/lib/model.js:166:21)
    at Directory.accessor.set (/Users/richardprotasov/.atom/packages/Remote-FTP/node_modules/theorist/lib/model.js:57:23)
    at DirectoryView.module.exports.DirectoryView.collapse (/Users/richardprotasov/.atom/packages/Remote-FTP/lib/views/directory-view.js:172:24)
    at DirectoryView.module.exports.DirectoryView.toggle (/Users/richardprotasov/.atom/packages/Remote-FTP/lib/views/directory-view.js:185:9)
    at space-pen-li.<anonymous> (/Users/richardprotasov/.atom/packages/Remote-FTP/lib/views/directory-view.js:85:13)
    at space-pen-li.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-li.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -5:33.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:42.7.0 remote-ftp:move-selected (span.name.icon.icon-file-directory)
     -0:41 core:copy (atom-text-editor.editor.mini.is-focused)
  5x -0:37.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:35.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:19.4.0 remote-ftp:move-selected (span.name.icon.icon-file-directory)
     -0:15.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "timecop",
      "spell-check",
      "open-on-github",
      "language-ruby-on-rails",
      "language-property-list",
      "language-objective-c",
      "language-mustache",
      "language-less",
      "autocomplete-atom-api",
      "language-ruby",
      "status-bar"
    ],
    "excludeVcsIgnoredPaths": false,
    "packagesWithKeymapsDisabled": [],
    "telemetryConsent": "no",
    "themes": [
      "one-light-ui",
      "minimal-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
aesthetic-ui, v2.0.0 (inactive)
atom-alignment, v0.12.1 (active)
atom-autocomplete-php, v0.18.9 (active)
color-picker, v2.2.2 (active)
crayon-atom, v0.2.3 (inactive)
duotone-blue-dark-syntax, v1.2.0 (inactive)
duotone-bright-sea-syntax, v1.0.0-mod.1 (inactive)
duotone-dark-syntax, v1.0.0 (inactive)
duotone-snow, v1.2.0 (inactive)
fizzy, v0.16.0 (inactive)
flatwhite-syntax, v0.7.2 (inactive)
fonts, v1.6.0 (active)
github-2016-syntax, v1.2.0 (inactive)
github-atom-light-syntax, v0.2.0 (inactive)
gruvbox, v1.0.5 (inactive)
language-haskell, v1.9.9 (active)
language-rust, v0.4.6 (active)
minimal-syntax, v0.13.2 (active)
minimap, v4.24.7 (active)
my-minimap-plugin, v0.0.0 (active)
naturepurple-dark-syntax, v0.1.0 (inactive)
princess-syntax, v0.1.3 (inactive)
Remote-FTP, v0.8.3 (active)
spacegray-light-neue-ui, v0.1.5 (inactive)
subway-barcelona, v1.1.1 (inactive)
subway-copenhagen, v1.1.1 (inactive)
svn, v0.0.12 (active)
unity-ui, v2.1.5 (inactive)
web-view, v3.0.0 (active)
Wild-Cherry, v0.7.13 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (active)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (inactive)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by jimmaaay** [comment]
Thanks for pointing this out. There should be a fix in the next release.

**Comment by olivedae** [comment]
Great, thank you!

**Comment by jimmaaay** [comment]
0.9.3 is released with the fix
