### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, mkdir '~/Documents/workspace/Creau\wp-content/themes/il...

### ISSUE THREAD

**Issue by stoefln** [icetee/remote-ftp#513]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.5
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.9.0
### Stack Trace

Uncaught Error: ENOTDIR: not a directory, mkdir '/Users/steph/Documents/workspace/Creau\wp-content/themes/illdy/CHANGELOG.txt/wp-content/themes/illdy'

```
At /Users/steph/.atom/packages/Remote-FTP/node_modules/mkdirp/index.js:74

Error: ENOTDIR: not a directory, mkdir '/Users/steph/Documents/workspace/Creau\wp-content/themes/illdy/CHANGELOG.txt/wp-content/themes/illdy'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at Function.sync (/Users/steph/.atom/packages/Remote-FTP/node_modules/mkdirp/index.js:55:12)
    at Object.fsPlus.makeTreeSync (/Users/steph/.atom/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at /Users/steph/.atom/packages/Remote-FTP/lib/connectors/ftp.js:177:10
    at Object.cb (/Users/steph/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:348:5)
    at Parser.<anonymous> (/Users/steph/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:100:13)
    at Parser.emit (events.js:185:7)
    at Parser._write (/Users/steph/.atom/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at Parser.Writable.write (_stream_writable.js:215:11)
    at Socket.ondata (/Users/steph/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)
```
### Commands

```
     -0:49.2.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  4x -0:47.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:46.1.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -0:45.4.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -0:45 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:44.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:43.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:43.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:43.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:43.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:01.3.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-text)
```
### Config

``` json
{
  "core": {
    "telemetryConsent": "no"
  },
  "Remote-FTP": {
    "multipleHosts ( Beta )": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-ternjs, v0.15.0 (active)
node-debugger, v1.7.0 (active)
pretty-json, v1.6.1 (active)
Remote-FTP, v0.9.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by jimmaaay** [comment]
See #453
