### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by karolisgrinkevicius** [icetee/remote-ftp#523]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12.1
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.9.1
### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/Karolis/.atom/packages/Remote-FTP/lib/client.js:154

TypeError: Cannot read property 'path' of undefined
    at Client.getProjectPath (/Users/Karolis/.atom/packages/Remote-FTP/lib/client.js:154:55)
    at Client.getFilePath (/Users/Karolis/.atom/packages/Remote-FTP/lib/client.js:140:32)
    at Client.getConfigPath (/Users/Karolis/.atom/packages/Remote-FTP/lib/client.js:167:19)
    at HTMLAnchorElement.<anonymous> (/Users/Karolis/.atom/packages/Remote-FTP/lib/views/tree-view.js:213:47)
    at HTMLDivElement.jQuery.event.dispatch (/Users/Karolis/.atom/packages/Remote-FTP/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/Users/Karolis/.atom/packages/Remote-FTP/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -0:08.8.0 remote-ftp:toggle (div.package-readme.native-key-bindings)
```
### Config

``` json
{
  "core": {
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angular2, v0.1.6 (active)
angularjs, v0.3.5 (active)
atom-ternjs, v0.15.0 (active)
atom-typescript, v10.1.10 (active)
linter, v1.11.18 (active)
Remote-FTP, v0.9.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by jimmaaay** [comment]
@karolisgrinkevicius The error shouldn't popup in 0.9.2 which I've just pushed out. Did you have a project folder open when you tried connecting?

**Comment by karolisgrinkevicius** [comment]
@jimmaaay thanks. No, unfortunately I did not have an open project.

**Comment by ossoen** [comment]
Yes, There is no problem in 0.9.2

**Comment by jcush** [comment]
Hi, I'm running v0.10.7 and keep receiving this error when connecting, uploading etc. (basically any action which the plugin performs between the local and remote servers.

At the time I set up the remote server I did have a project folder open.


**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: 'atom-ftp-editor' package vundefined


### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/Cush/.atom/packages/atom-ftp-editor/lib/main.js:115

TypeError: Cannot read property 'path' of undefined
    at Object.__uploadCurrent (/packages/atom-ftp-editor/lib/main.js:115:84)
    at HTMLDocument.__onsave (/packages/atom-ftp-editor/lib/main.js:95:21)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  2x -9:53.1.0 core:save (input.hidden-input)
     -9:08.6.0 remote-ftp:disconnect (div.header.list-item)
     -8:03.4.0 core:move-right (input.hidden-input)
     -8:01.4.0 core:backspace (input.hidden-input)
     -7:58.8.0 core:save (input.hidden-input)
     -7:54.6.0 remote-ftp:disconnect (div.header.list-item)
     -1:29.4.0 application:new-file (input.hidden-input)
     -0:11.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
Remote-FTP 0.10.7 
```

Thanks

JC
