### ISSUE TITLE
Opening files bugged (?)

### ISSUE THREAD

**Issue by Coocla33** [icetee/remote-ftp#525]
[Enter steps to reproduce below:]
I am not 100% sure this is why it happend...
1. Create a new folder
2. Create a new file
3. Open that file. Tadaaa

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.9.2
### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\Misha\Documents\Curse\Minecraft\Instances\Project Ozone 2 Reloaded\config\IguanaTinkerTweaks\home\pi\Bots\Statik'

```
At C:\Users\Misha\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:76

Error: EEXIST: file already exists, mkdir 'C:\Users\Misha\Documents\Curse\Minecraft\Instances\Project Ozone 2 Reloaded\config\IguanaTinkerTweaks\home\pi\Bots\Statik'
    at Error (native)
    at fs.mkdirSync (fs.js:842:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:589:16)
    at Function.sync (C:\Users\Misha\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:55:12)
    at Object.fsPlus.makeTreeSync (C:\Users\Misha\.atom\packages\Remote-FTP\node_modules\fs-plus\lib\fs-plus.js:381:23)
    at C:\Users\Misha\.atom\packages\Remote-FTP\lib\connectors\sftp.js:221:8
    at SFTPStream._transform (C:\Users\Misha\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\sftp.js:496:15)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (C:\Users\Misha\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at SFTPStream.Writable.write (_stream_writable.js:215:11)
    at Channel.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:90:13)
    at Channel.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Channel.Readable.push (_stream_readable.js:111:10)
    at SSH2Stream.<anonymous> (C:\Users\Misha\.atom\packages\Remote-FTP\node_modules\ssh2\lib\Channel.js:166:15)
    at emitOne (events.js:90:13)
    at SSH2Stream.emit (events.js:182:7)
    at parsePacket (C:\Users\Misha\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\ssh.js:3400:10)
    at SSH2Stream._transform (C:\Users\Misha\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\ssh.js:665:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (C:\Users\Misha\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\ssh.js:249:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at SSH2Stream.Writable.write (_stream_writable.js:215:11)
    at Socket.ondata (_stream_readable.js:536:20)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "closeEmptyWindows": false,
    "telemetryConsent": "limited"
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.6 (inactive)
atom-monokai, v0.10.4 (inactive)
Remote-FTP, v0.9.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by jimmaaay** [comment]
Could you try following your steps and see if you can reproduce the error as I can't seem to

**Comment by Coocla33** [comment]
Hmm, i retried to create the error. but this time it just worked normally. I only get a error when i want to do something inside the 1 folder it happend with...

Edit 1:
After some testing, i removed the folder that made the error with WinSCP, then recreated the folder called: `Statik`. It made the same error

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.9.2

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\Misha\Documents\Curse\Minecraft\Instances\Project Ozone 2 Reloaded\config\IguanaTinkerTweaks\home\pi\Bots\Statik'

```
At C:\Users\Misha\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:76

Error: EEXIST: file already exists, mkdir 'C:\Users\Misha\Documents\Curse\Minecraft\Instances\Project Ozone 2 Reloaded\config\IguanaTinkerTweaks\home\pi\Bots\Statik'
    at Error (native)
    at fs.mkdirSync (fs.js:842:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:589:16)
    at Function.sync (C:\Users\Misha\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:55:12)
    at Object.fsPlus.makeTreeSync (C:\Users\Misha\.atom\packages\Remote-FTP\node_modules\fs-plus\lib\fs-plus.js:381:23)
    at C:\Users\Misha\.atom\packages\Remote-FTP\lib\connectors\sftp.js:221:8
    at SFTPStream._transform (C:\Users\Misha\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\sftp.js:496:15)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (C:\Users\Misha\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at SFTPStream.Writable.write (_stream_writable.js:215:11)
    at Channel.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:90:13)
    at Channel.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Channel.Readable.push (_stream_readable.js:111:10)
    at SSH2Stream.<anonymous> (C:\Users\Misha\.atom\packages\Remote-FTP\node_modules\ssh2\lib\Channel.js:166:15)
    at emitOne (events.js:90:13)
    at SSH2Stream.emit (events.js:182:7)
    at parsePacket (C:\Users\Misha\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\ssh.js:3400:10)
    at SSH2Stream._transform (C:\Users\Misha\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\ssh.js:665:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (C:\Users\Misha\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\ssh.js:249:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at SSH2Stream.Writable.write (_stream_writable.js:215:11)
    at Socket.ondata (_stream_readable.js:536:20)
```

### Commands

```
     -0:16.3.0 remote-ftp:add-folder (span.name.icon.icon-file-directory)
     -0:14.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.4.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -0:10.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.6.0 remote-ftp:move-selected (span.name.icon.icon-file-text)
     -0:05.4.0 core:move-right (atom-text-editor.editor.mini.is-focused)
  2x -0:05.2.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -0:04.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:04.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "closeEmptyWindows": false,
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

``` coffee
# User
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.6 (inactive)
atom-monokai, v0.10.4 (inactive)
Remote-FTP, v0.9.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by jimmaaay** [comment]
I'll have a further look into this and let you know what I find

**Comment by jimmaaay** [comment]
I'm not really sure what to suggest as I can't reproduce this error.

**Comment by jpxd** [comment]
Duplicate to #112 
There is a local file with the same name as the remote directory in wich you're trying to edit something, wich creates a conflict. Delete the local file and it'll work.
