### ISSUE TITLE
Uncaught TypeError: path must be a string

### ISSUE THREAD

**Issue by AndreyLabro** [icetee/remote-ftp#535]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Unknown Windows Version
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.9.2

### Stack Trace

Uncaught TypeError: path must be a string

```
At fs.js:262

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.readFile (fs.js:262:11)
    at Object.fs.readFile (ELECTRON_ASAR.js:374:25)
    at Client.readConfig (C:/Users/dada/.atom/packages/Remote-FTP/lib/client.js:114:10)
    at HTMLAnchorElement.<anonymous> (C:\Users\dada\.atom\packages\Remote-FTP\lib\views\tree-view.js:208:27)
    at HTMLDivElement.jQuery.event.dispatch (C:\Users\dada\.atom\packages\Remote-FTP\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (C:\Users\dada\.atom\packages\Remote-FTP\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -0:24.2.0 tree-view:toggle (atom-pane.pane.active)
     -0:11.3.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -0:09.1.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "remote-edit",
      "atom-wordpress"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "Remote-FTP": {
    "hideLocalWhenDisplayed": true,
    "multipleHosts ( Beta )": true
  }
}
```

### Installed Packages

```coffee
# User
atom-commander, v0.8.3 (active)
atom-wordpress, v0.3.0 (inactive)
Remote-FTP, v0.9.2 (active)
wordpress-dictionary, v4.4.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by jimmaaay** [comment]
Did you get an popup saying `Remote FTP: Could not get project path` before the error was thrown?

**Comment by aschwtzr** [comment]
@jimmaaay I'm having a similar error, got that popup.

**Comment by AndreyLabro** [comment]
The error disappeared now. Without any action on my side.

UPD: Nope. it's back again. And got that popup.

**Comment by arunkumarpalaniappan** [comment]
@jimmaaay I too got that error.

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.9.4

### Stack Trace

Uncaught TypeError: path must be a string

```
At fs.js:214

TypeError: path must be a string
    at TypeError (native)
    at fs.exists (fs.js:214:11)
    at Object.fs.exists (ELECTRON_ASAR.js:346:16)
    at C:/Users/arunkumar/.atom/packages/Remote-FTP/lib/remote-ftp.js:49:12
```

### Commands

```
     -2:12.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

``` json
{
  "core": {
    "telemetryConsent": "limited"
  },
  "Remote-FTP": {
    "autoUploadOnSave": "never",
    "multipleHosts ( Beta )": true,
    "showViewOnStartup": false
  }
}
```

### Installed Packages

``` coffee
# User
atom-beautify, v0.29.13 (active)
atom-jshint, v2.0.0 (active)
auto-detect-indentation, v1.3.0 (active)
autoclose-html, v0.23.0 (active)
color-picker, v2.2.2 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.24 (active)
fonts, v1.7.0 (active)
git-plus, v5.23.2 (active)
git-time-machine, v1.5.3 (inactive)
javascript-snippets, v1.2.1 (active)
linter, v1.11.18 (active)
linter-php, v1.3.1 (active)
minimap, v4.25.6 (active)
pigments, v0.37.0 (active)
remote-edit, v1.8.24 (active)
Remote-FTP, v0.9.4 (active)
sync-settings, v0.7.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by jimmaaay** [comment]
I think this error has something to do with how the project path was chosen when multiple projects are selected and the atom update. For the meantime if you're having this issue I would suggest disabling multiple projects.

**Comment by alenb** [comment]
Had the same error before, but noticed that if I had the `.ftpconfig` file open, while clicking on the connect button, it would connect.

**Edit**: I also noticed that you must keep the `.ftpconfig` file open during the entire session. Closing the config file will throw errors when trying to edit files from the remote server.
