### ISSUE TITLE
Uncaught TypeError: Cannot read property 'open' of null

### ISSUE THREAD

**Issue by rediver** [icetee/remote-ftp#543]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Ubuntu 16.04.1
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.9.4

### Stack Trace

Uncaught TypeError: Cannot read property 'open' of null

```
At /home/wojtek/.atom/packages/Remote-FTP/lib/views/directory-view.js:190

TypeError: Cannot read property 'open' of null
    at DirectoryView.module.exports.DirectoryView.open (/home/wojtek/.atom/packages/Remote-FTP/lib/views/directory-view.js:190:12)
    at /home/wojtek/.atom/packages/Remote-FTP/lib/menus/commands.js:288:28
    at /home/wojtek/.atom/packages/Remote-FTP/lib/client.js:725:58
    at Object.cb (/home/wojtek/.atom/packages/Remote-FTP/lib/connectors/ftp.js:448:68)
    at Parser.<anonymous> (/home/wojtek/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:100:13)
    at Parser.emit (events.js:185:7)
    at Parser._write (/home/wojtek/.atom/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at Parser.Writable.write (_stream_writable.js:215:11)
    at Socket.ondata (/home/wojtek/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)
```

### Commands

```
     -0:34.1.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
 15x -0:31.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:22.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13 remote-ftp:connect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.9.4 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by agm1984** [comment]
I am just getting this today. I'm pretty sure it's due to user permissions in my case.

Here are the steps I did, just in case it helps anyone:
-setup nginx, setup vsftpd
-chmod owner of web directory to nginx
-give ftp user permission to upload into web directory
-unable to upload due to user permission error
-chmod owner of web directory to ftp user
-able to upload through ftp and remote-ftp plugin
-start getting 403 forbidden in web browser due to changing directory owner away from nginx
-created www user group
-chmod nginx:www web directory
-add ftp user and nginx to www
-change directory permissions to match, allowing ftp user to upload into web directory
-success, able to upload in ftp client
-go back to Atom, seems frozen
-files not working properly, very overt symptoms
-right click in tree view, "Disconnect"
-hit Connect and it loaded this error
-came to this URL
-closed Atom
-reopened it
-hit Connect again
-everything seems fine

My opinion is that changing the user permissions somehow detonated the plugin somewhere along the way, but I was changing settings quite a bit over the last 15 hours. There are a few sequences that could have done it, but a person might be able to reproduce the error by constantly changing user permissions related to the web directory on a server and the ftp user permissions WHILE leaving atom and this plugin running the whole time.

The plugin was working perfectly stable until sometime in the past hour or two, and then it finally detonated. Here are the last two commands I ran on my system around when it stopped working:
```
sudo find /var/www -type f -exec chmod 0660 {} \;
sudo find /var/www -type d -exec chmod 2770 {} \;
```

Thanks,
Adam

**Comment by agm1984** [comment]
Bonus Note: I just realized I restarted the ftpd several times. I bet that is simply what caused it.

Try connecting the plugin and then do on your server:
`service vsftpd restart`

Then go back to the plugin and it will be exhibiting those "overt symptoms" I was talking about. I replicated most of the anomaly again now just by restarting my ftpd, but I didnt get the same error.

Either way, you might be able to clean up the "unhappy path" a bit by addressing the ftpd restart. If nothing else, add user feedback so they know they need to cycle the plugin.

Thanks,
Adam

**Comment by agm1984** [comment]
Sorry, one last thing. This file showed up possibly due to this crash, and I cannot delete it or otherwise remove it:

![remoteftp](https://cloud.githubusercontent.com/assets/17655219/21554985/fc50cf82-cdc8-11e6-947a-5040e377de98.png)

**Comment by agm1984** [comment]
1. I just got this error again.
2. I left Atom open for a few hours;
3. Rebooted my dev box and the ftp service wasnt running;
4. Back in Atom, I motioned to delete test2.php and noticed remote-ftp wasn't connected;
5. Hit disconnect/Reconnect which failed due to no ftpd running;
6. Restarted the ftpd, reconnected remote-ftp
7. Got this error

I assume it will be reproducible with those steps. Try and delete a file while the connection is broken, and then reconnect.


**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.9.4


### Stack Trace

Uncaught TypeError: Cannot read property 'open' of null

```
At C:\Users\adam\.atom\packages\Remote-FTP\lib\views\directory-view.js:190

TypeError: Cannot read property 'open' of null
    at DirectoryView.module.exports.DirectoryView.open (C:\Users\adam\.atom\packages\Remote-FTP\lib\views\directory-view.js:190:12)
    at file:///C:/Users/adam/.atom/packages/Remote-FTP/lib/menus/commands.js:288:28
    at file:///C:/Users/adam/.atom/packages/Remote-FTP/lib/client.js:725:58
    at Object.cb (file:///C:/Users/adam/.atom/packages/Remote-FTP/lib/connectors/ftp.js:433:64)
    at Parser.<anonymous> (C:\Users\adam\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:117:20)
    at emitTwo (events.js:106:13)
    at Parser.emit (events.js:191:7)
    at Parser._write (C:\Users\adam\.atom\packages\Remote-FTP\node_modules\ftp\lib\parser.js:59:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (C:\Users\adam\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -1:22.6.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  3x -1:15.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:12.5.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:12.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:12.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:12.2.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:12.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:12.2.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:08.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:02.1.0 window:save-all (atom-text-editor.editor.is-focused)
     -0:56.6.0 remote-ftp:delete-selected (span.name.icon.icon-file-text)
     -0:49.5.0 remote-ftp:refresh-selected (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:47.2.0 remote-ftp:disconnect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.9.4 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by icetee** [comment]
Latest version has problem?

**Comment by ddon** [comment]
Yes, latest version has this problem... try dragging a file in the tree (remote) into any directory, and you will run into this error.

**Comment by Janrupf** [comment]
Just got this when trying to move __multiple__ files in remote structure, one got moved and then the error occured.
