### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages/Remote-FTP/node_modu...

### ISSUE THREAD

**Issue by michaelog** [icetee/remote-ftp#544]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.9.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/Mik/.atom/packages/Remote-FTP/node_modules/jslint/lib/jslint.js'

```
At fs.js:584

Error: ENOENT: no such file or directory, open '/Users/Mik/.atom/packages/Remote-FTP/node_modules/jslint/lib/jslint.js'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:158:20)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:426:29)
    at read (/Users/Mik/.atom/packages/Remote-FTP/node_modules/jslint/lib/nodelint.js:44:19)
    at Object.exports.load (/Users/Mik/.atom/packages/Remote-FTP/node_modules/jslint/lib/nodelint.js:63:24)
    at new LintStream_constructor (/Users/Mik/.atom/packages/Remote-FTP/node_modules/jslint/lib/lintstream.js:27:32)
    at Client.module.exports.Client.validateConfig (/Users/Mik/.atom/packages/Remote-FTP/lib/client.js:141:20)
    at /Users/Mik/.atom/packages/Remote-FTP/lib/client.js:99:13
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

### Commands

```
     -5:59.4.0 application:open (atom-text-editor.editor.is-focused)
     -5:22.5.0 remote-ftp:connect (atom-text-editor.editor.is-focused)
     -3:22.3.0 remote-ftp:disconnect (span.name.icon.icon-file-directory)
     -2:26.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-monokai-seti.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "spell-check"
    ],
    "telemetryConsent": "no",
    "themes": [
      "atom-dark-ui",
      "monokai-seti"
    ]
  },
  "Remote-FTP": {
    "hideLocalWhenDisplayed": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (inactive)
auto-detect-indentation, v1.3.0 (active)
autoclose-html, v0.23.0 (active)
highlight-selected, v0.11.2 (active)
linter, v1.11.18 (active)
linter-csslint, v1.3.3 (active)
linter-htmlhint, vundefined (active)
linter-jshint, v3.0.1 (active)
minimap, v4.25.6 (active)
minimap-highlight-selected, v4.4.0 (active)
monokai-seti, v0.7.0 (active)
open-recent, v5.0.0 (active)
project-manager, v3.3.3 (active)
Remote-FTP, v0.9.4 (active)
todo-show, v1.8.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (inactive)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by jimmaaay** [comment]
Could you try reinstalling the plugin?

**Comment by cplaiasu** [comment]
[Enter steps to reproduce below:]

1. Upgraded to 0.10.4
2. Clicked “Connect”
3. Threw this error.


**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Ubuntu 16.04.1
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.10.4


### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/cplaiasu/.atom/packages/Remote-FTP/node_modules/jslint/lib/jslint.js'

```
At fs.js:640

Error: ENOENT: no such file or directory, open '/home/cplaiasu/.atom/packages/Remote-FTP/node_modules/jslint/lib/jslint.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at read (/home/cplaiasu/.atom/packages/Remote-FTP/node_modules/jslint/lib/nodelint.js:44:19)
    at Object.exports.load (/home/cplaiasu/.atom/packages/Remote-FTP/node_modules/jslint/lib/nodelint.js:63:24)
    at new LintStream_constructor (/home/cplaiasu/.atom/packages/Remote-FTP/node_modules/jslint/lib/lintstream.js:27:32)
    at Client.validateConfig (/home/cplaiasu/.atom/packages/Remote-FTP/lib/client.js:236:26)
    at /home/cplaiasu/.atom/packages/Remote-FTP/lib/client.js:173:20
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

### Commands

```
     -2:45.1.0 remote-ftp:disconnect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:45.1.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:45 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:44.6.0 core:confirm (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "terminal-plus",
      "atom-terminal-panel",
      "terminal-panel",
      "language-smarty"
    ],
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.21.0 (active)
atom-beautify, v0.29.16 (active)
atom-fis3-smarty, v0.1.1 (inactive)
atom-html-preview, v0.1.22 (active)
atom-less, v0.1.10 (active)
atom-minify, v0.8.0 (active)
atom-terminal-panel, v4.4.4 (inactive)
atom-typescript, v10.1.13 (active)
git-control, v0.8.2 (inactive)
language-blade, v0.26.3 (active)
language-nginx, v0.6.2 (active)
language-smarty, v1.7.0 (inactive)
linter, v1.11.21 (active)
linter-less, v2.6.0 (active)
linter-php, v1.3.1 (active)
linter-sass-lint, v1.7.4 (active)
linter-tslint, v0.13.0 (active)
open-terminal-here, v2.1.4 (inactive)
pigments, v0.38.0 (active)
project-manager, v3.3.3 (active)
recent-projects, v0.13.1 (active)
Remote-FTP, v0.10.4 (active)
sass-autocompile, v0.13.2 (active)
terminal-panel, v1.14.1 (inactive)
terminal-plus, v0.14.5 (inactive)
Termrk, v0.3.1 (inactive)
typescript-modules-helper, v0.7.0 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by cplaiasu** [comment]
Something wrong with jslint version, 
a quick fix that worked for me is to run 
`npm install jslint@latest` in `~/.atom/packages/Remote-FTP/`

**Comment by hwiVeloper** [comment]
I solved this issue below..

```bash
$ cd ~/.atom/packages/RemoteFTP
$ npm install jslint@0.10.3
```

Thanks for @cplaiasu

**Comment by jpxd** [comment]
This obviously fixes it, but something other than a missing jslint is wrong at your end. The jslint dependency has been removed from the code several versions ago. Your Remote-FTP version is just not up to date. Try to remove and re-install the plugin.
