### ISSUE TITLE
Uncaught TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by victorkane** [icetee/remote-ftp#555]
[Enter steps to reproduce below:]

1. Change settings to hide local and allow multi connections
2. Close Atom
3. Re-open

**Atom Version**: 1.12.0
**Electron Version**: 1.3.6
**System**: Mac OS X 10.10.5
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.9.4

### Stack Trace

Uncaught TypeError: path must be a string or Buffer

```
At fs.js:255

TypeError: path must be a string or Buffer
    at TypeError (native)
    at fs.exists (fs.js:255:11)
    at Object.fs.exists (ELECTRON_ASAR.js:359:16)
    at /Users/victorkane/.atom/packages/Remote-FTP/lib/remote-ftp.js:49:12
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "Remote-FTP": {
    "hideLocalWhenDisplayed": true,
    "multipleHosts ( Beta )": true
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.2.2 (active)
drupal, v1.8.0 (inactive)
ex-mode, v0.13.1 (inactive)
fizzy, v0.16.0 (inactive)
javascript-snippets, v1.2.1 (active)
markdown-toc, v0.4.1 (inactive)
monokai, v0.18.0 (inactive)
Remote-FTP, v0.9.4 (active)
sync-settings, v0.7.2 (active)
vim-mode, v0.65.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (active)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.0 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.3 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by jimmaaay** [comment]
Does it work fine for you when hide local is unchecked?

**Comment by TomS-** [comment]
@I'm receiving this error, however, it's whenever multiple is enabled, even without any previous steps.

**Atom Version**: 1.12.6
**Electron Version**: 1.3.9
**System**: Microsoft Windows 10 Home
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.9.4


### Stack Trace

Uncaught TypeError: path must be a string or Buffer

```
At fs.js:631

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.open (fs.js:631:11)
    at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:195:20)
    at Object.fs.writeFile (fs.js:1313:6)
    at C:\Users\katyt\.atom\packages\Remote-FTP\node_modules\fs-plus\lib\fs-plus.js:296:21
    at C:\Users\katyt\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:38:26
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -0:03.9.0 remote-ftp:create-ftp-config (input#Remote-FTP.multipleHosts ( Beta ).)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "telemetryConsent": "no"
  },
  "Remote-FTP": {
    "hideLocalWhenDisplayed": true,
    "multipleHosts ( Beta )": true
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.9.4 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by S1ROZHA** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.5


### Stack Trace

Uncaught TypeError: path must be a string or Buffer

```
At fs.js:631

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.open (fs.js:631:11)
    at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:195:20)
    at Object.fs.writeFile (fs.js:1313:6)
    at /packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:296:21
    at /packages/Remote-FTP/node_modules/mkdirp/index.js:38:26
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -8:44.8.0 pane:split-right-and-copy-active-item (div.item-views)
     -8:43.4.0 pane:split-up-and-copy-active-item (div.item-views)
  4x -8:41.6.0 pane:close (div.item-views)
     -8:19.6.0 application:open-folder (atom-pane.pane.active)
  2x -7:47.5.0 remote-ftp:create-ftp-config (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -7:10.7.0 remote-ftp:toggle (a.btn-issue.btn.btn-error)
     -6:47.9.0 remote-ftp:create-sftp-config (atom-pane.pane.active)
  5x -5:42.6.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -4:39.6.0 tree-view:move (span.name.icon.icon-file-text)
     -4:39.4.0 core:select-all (input.hidden-input)
     -4:38.7.0 core:paste (input.hidden-input)
     -4:37.9.0 core:confirm (input.hidden-input)
     -4:27 remote-ftp:create-ftp-config (atom-pane.pane.active)
     -3:05.7.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:58.4.0 remote-ftp:create-sftp-config (atom-pane.pane.active)
     -0:20.3.0 remote-ftp:create-ftp-config (atom-pane.pane.active)
```

### Non-Core Packages

```
Remote-FTP 0.10.5 
```

**Comment by r-dave** [comment]
same for me, when I try to download a remote file I get the "Uncaught TypeError: path must be a string or Buffer" message. 

Multiconnections enabled.

1. ...
2. ...

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.10.5


### Stack Trace

Uncaught TypeError: path must be a string or Buffer

```
At fs.js:631

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.open (fs.js:631:11)
    at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:195:20)
    at WriteStream.open (fs.js:2094:6)
    at new WriteStream (fs.js:2080:10)
    at Object.fs.createWriteStream (fs.js:2035:10)
    at /Users/dave/.atom/packages/Remote-FTP/lib/connectors/ftp.js:204:33
    at Object.cb (/Users/dave/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:617:11)
    at Parser.<anonymous> (/Users/dave/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:106:13)
    at Parser.emit (events.js:191:7)
    at Parser._write (/Users/dave/.atom/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (/Users/dave/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -9:09.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -8:09.3.0 remote-ftp:connect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -6:54.3.0 core:save (input.hidden-input)
     -6:25.8.0 core:close (input.hidden-input)
  2x -4:56.9.0 remote-ftp:toggle (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:47.5.0 remote-ftp:disconnect (ul.progress.tool-panel.panel-top)
  2x -4:46.4.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -4:31.9.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:27.6.0 remote-ftp:connect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:24.6.0 remote-ftp:disconnect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:21.2.0 remote-ftp:connect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:56.4.0 remote-ftp:disconnect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:50 editor:transpose (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:40.4.0 remote-ftp:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:24 remote-ftp:connect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -0:12.3.0 core:close (div.package-detail.panels-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "spell-check",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-source",
      "language-toml",
      "language-yaml"
    ]
  },
  "Remote-FTP": {
    "multipleHosts ( Beta )": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.16 (active)
atom-minify, v0.7.5 (active)
Remote-FTP, v0.10.5 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (inactive)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by jpxd** [comment]
To resolve this error you just have to disable `multipleHosts` in your `.ftpconfig`. The feature is buggy and currently not under active development.

**Comment by jsieber** [comment]
This only occurs if you are using multipleHosts and do not have a file from the project you are working on open in the editor. If you open a local file before attempting to open the remote copy it will not error.

**Comment by icetee** [comment]
Duplicate of #535

**Comment by cagcak** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Ubuntu 17.10
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.1.4


### Stack Trace

Uncaught TypeError: path must be a string or Buffer

```
At fs.js:549

TypeError: path must be a string or Buffer
    at Object.fs.open (fs.js:549:11)
    at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:200:20)
    at Object.fs.writeFile (fs.js:1211:6)
    at /packages/remote-ftp/node_modules/fs-plus/lib/fs-plus.js:300:21
    at /packages/remote-ftp/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -0:23.7.0 remote-ftp:create-ftp-config (div.package-detail.panels-item)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-bootstrap3 1.2.12 
atom-bootstrap4 1.4.0 
autocomplete 0.47.0 
autocomplete-json 5.5.2 
autocomplete-php 0.3.7 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.18 
ide-php 0.7.14 
intentions 1.1.5 
language-blade 0.39.0 
language-htaccess 0.2.0 
language-twig 1.6.3 
language-vue 0.23.1 
laravel 0.7.1 
linter 2.2.0 
linter-js-standard 5.0.0 
linter-markdown 5.2.0 
linter-php 1.5.1 
linter-sass-lint 1.8.3 
linter-scss-lint 3.1.1 
linter-spell-javascript 0.9.0 
linter-ui-default 1.7.1 
pdf-view 0.67.0 
php-debug 0.2.6 
php-twig 4.0.0 
platformio-ide-terminal 2.8.1 
pretty-json 2.0.0 
remote-ftp 2.1.4 
teletype 0.11.0 
twig-server 0.3.0 
v-bootstrap4 0.2.2 
```
