### ISSUE TITLE
Failed to load the Remote-FTP package

### ISSUE THREAD

**Issue by negezor** [icetee/remote-ftp#563]
`Unexpected token } in JSON at position 8446 in C:\Users\negezor\.atom\packages\Remote-FTP\package.json`

![default](https://cloud.githubusercontent.com/assets/9392723/20234773/b8eac8dc-a8d5-11e6-9699-9244f6f02fa7.PNG)

`SyntaxError: Unexpected token } in JSON at position 8446
    at Object.parse (native)
    at parseObject (C:\Users\negezor\AppData\Local\atom\app-1.12.1\resources\app.asar\node_modules\season\lib\cson.js:54:19)
    at parseContentsSync (C:\Users\negezor\AppData\Local\atom\app-1.12.1\resources\app.asar\node_modules\season\lib\cson.js:68:16)
    at Object.readFileSync (C:\Users\negezor\AppData\Local\atom\app-1.12.1\resources\app.asar\node_modules\season\lib\cson.js:170:14)
    at PackageManager.module.exports.PackageManager.loadPackageMetadata (C:\Users\negezor\AppData\Local\atom\app-1.12.1\resources\app.asar\src\package-manager.js:710:29)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\negezor\AppData\Local\atom\app-1.12.1\resources\app.asar\src\package-manager.js:432:35)
    at C:\Users\negezor\AppData\Local\atom\app-1.12.1\resources\app.asar\src\package-manager.js:410:19
    at Config.module.exports.Config.transact (C:\Users\negezor\AppData\Local\atom\app-1.12.1\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\negezor\AppData\Local\atom\app-1.12.1\resources\app.asar\src\package-manager.js:405:19)
    at C:\Users\negezor\AppData\Local\atom\app-1.12.1\resources\app.asar\src\atom-environment.js:763:28
  at C:\Users\negezor\.atom\packages\Remote-FTP\package.json:1:1`

**Comment by jimmaaay** [comment]
The .ftpconfig file needs to be valid JSON. Try pasting the contents into [http://jsonlint.com/](http://jsonlint.com/). 

Do need to update the readme at some point as other people have had the same issue.

**Comment by jimmaaay** [comment]
Sorry I read this wrong. Try reinstalling the plugin.

**Comment by ghost** [comment]
### Stack Trace

Failed to load the Remote-FTP package

```
At Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.defineProperty.value [as .js] (C:\Users\masumoto.misato\AppData\Local\atom\app-1.2.0\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:/Users/masumoto.misato/.atom/packages/remote-ftp/lib/client.js:9:60)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (C:\Users\masumoto.misato\AppData\Local\atom\app-1.2.0\resources\app.asar\src\compile-cache.js:190:21)
```

**Comment by jpxd** [comment]
@misato1989 Can you please try the dev branch?

```
git clone https://github.com/mgrenier/remote-ftp.git
cd remote-ftp
git checkout dev
apm install
amp link
```
