### ISSUE TITLE
Error: Remote FTP: getConfigPath returned false, but expected a string

### ISSUE THREAD

**Issue by webternals** [icetee/remote-ftp#598]
I am having this same problem. It happens when there is  no file open.

and the stack trace

Error: Remote FTP: getConfigPath returned false, but expected a string
    at Client.readConfig (file:///C:/Users/asanf/.atom/packages/Remote-FTP/lib/client.js:118:47)
    at HTMLAnchorElement.<anonymous> (C:\Users\asanf\.atom\packages\Remote-FTP\lib\views\tree-view.js:208:27)
    at HTMLDivElement.dispatch (C:\Users\asanf\.atom\packages\Remote-FTP\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (C:\Users\asanf\.atom\packages\Remote-FTP\node_modules\jquery\dist\jquery.js:4121:28)

![image](https://cloud.githubusercontent.com/assets/9657223/20808426/2c37da36-b7c8-11e6-8f56-842dd4cc30e4.png)

**Comment by samifouad** [comment]
Can you verify you're still having this problem with the latest version?

**Comment by jpxd** [comment]
Disable `multipleHosts` to fix it temporarily.
Duplicate to #621
