### ISSUE TITLE
Could not download folder

### ISSUE THREAD

**Issue by grenierdev** [icetee/remote-ftp#6]

**Comment by hatzopoulos** [comment]
**Uncaught ReferenceError: pool is not defined**

I'm getting the same issue now using SFTP, everything else is fine like opening and saving files individually. I just can't download a folder with files and folders within it. 

[Enter steps to reproduce below:]
1. Right click on a folder to download from Remote-FTP's file tree pane
2. Click "Download"

**Atom Version**: 0.176.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.4.6

### Stack Trace

Uncaught ReferenceError: pool is not defined

```
At c:\Users\Entropy\.atom\packages\Remote-FTP\lib\connectors\sftp.js:224

ReferenceError: pool is not defined
  at n (c:\Users\Entropy\.atom\packages\Remote-FTP\lib\connectors\sftp.js:224:12)
  at c:\Users\Entropy\.atom\packages\Remote-FTP\lib\connectors\sftp.js:252:7
  at e (c:\Users\Entropy\.atom\packages\Remote-FTP\lib\connectors\sftp.js:122:17)
  at c:\Users\Entropy\.atom\packages\Remote-FTP\lib\connectors\sftp.js:144:8
  at c:\Users\Entropy\.atom\packages\Remote-FTP\node_modules\ssh2\lib\SFTP\SFTPv3.js:690:13
  at SFTP._parse (c:\Users\Entropy\.atom\packages\Remote-FTP\node_modules\ssh2\lib\SFTP\SFTPv3.js:1086:13)
  at ChannelStream.<anonymous> (c:\Users\Entropy\.atom\packages\Remote-FTP\node_modules\ssh2\lib\SFTP\SFTPv3.js:72:10)
  at ChannelStream.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:161:16)
  at ChannelStream.Readable.push (_stream_readable.js:125:10)
  at Parser.<anonymous> (c:\Users\Entropy\.atom\packages\Remote-FTP\node_modules\ssh2\lib\Channel.js:102:25)
  at Parser.emit (events.js:107:17)
  at Parser.parsePacket (c:\Users\Entropy\.atom\packages\Remote-FTP\node_modules\ssh2\lib\Parser.js:607:12)
  at Parser.execute (c:\Users\Entropy\.atom\packages\Remote-FTP\node_modules\ssh2\lib\Parser.js:249:14)
  at Socket.<anonymous> (c:\Users\Entropy\.atom\packages\Remote-FTP\node_modules\ssh2\lib\Connection.js:536:18)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:161:16)
  at Socket.Readable.push (_stream_readable.js:125:10)
  at TCP.onread (net.js:522:20)

```

### Commands

```
     -0:51.1 remote-ftp:toggle (atom-text-editor.editor)
```

### Config

``` json
{
  "core": {}
}
```

### Installed Packages

``` coffee
# User
Remote-FTP, v0.4.6

# Dev
No dev packages
```

/cc @atom/core

**Comment by hatzopoulos** [comment]
Awesome. Works nicely now!

Is it safe to assume in the context menu; `Download` will download all files regardless where as `Sync local <- or -> remote` will attempt to download only the files that are different then the target like files that don't exist, newer dated files and files of different sizes?

**Comment by grenierdev** [comment]
For the moment it's only comparing files using file size as I'm still figuring out how to work with timezone/wrong system date. I invited you to join the [discussion here](https://github.com/mgrenier/remote-ftp/issues/20).
