### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pipe' of undefined

### ISSUE THREAD

**Issue by dognie** [icetee/remote-ftp#618]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.9.4

### Stack Trace

Uncaught TypeError: Cannot read property 'pipe' of undefined

```
At /Users/dognie/.atom/packages/Remote-FTP/lib/connectors/ftp.js:261

TypeError: Cannot read property 'pipe' of undefined
    at /Users/dognie/.atom/packages/Remote-FTP/lib/connectors/ftp.js:261:29
    at /Users/dognie/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:532:14
    at /Users/dognie/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:887:7
    at Socket.<anonymous> (/Users/dognie/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:918:5)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1068:10)
```

### Commands

```
     -9:33.5.0 remote-ftp:navigate-to (ul.list)
     -9:21.8.0 remote-ftp:toggle (atom-text-editor.editor.is-focused)
  2x -9:11 remote-ftp:connect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:41.9.0 remote-ftp:download-selected (span.name.icon.icon-file-directory)
     -0:32.7.0 remote-ftp:connect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:23.1.0 remote-ftp:download-selected (span.name.icon.icon-file-directory)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "angularjs",
      "angularjs",
      "angularjs",
      "angularjs",
      "angularjs",
      "angularjs"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.1.0 (active)
angularjs, v0.3.5 (active)
atom-beautify, v0.29.13 (active)
atom-typescript, v10.1.13 (active)
atomic-chrome, v0.3.0 (active)
color-picker, v2.2.3 (active)
file-icons, v1.7.25 (active)
git-plus, v5.25.5 (active)
linter, v1.11.4 (active)
linter-ui-default, v0.0.3 (active)
markdown-preview, v0.159.1 (active)
minimap, v4.25.6 (active)
Remote-FTP, v0.9.4 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Is this reproducable for you?

**Comment by jpxd** [comment]
Or can you supply steps to reproduce this error?

**Comment by jpxd** [comment]
Closing because of inactivity and no one seems to be able to reproduce the error...

**Comment by Mr-Whyte** [comment]
Cannot read property 'pipe' of undefined

what do i do?
