### ISSUE TITLE
Uncaught Error: Remote FTP: getConfigPath returned false, but expected a string

### ISSUE THREAD

**Issue by mrsekut** [icetee/remote-ftp#621]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.1
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.9.4

### Stack Trace

Uncaught Error: Remote FTP: getConfigPath returned false, but expected a string

```
At /Users/cloudspider/.atom/packages/Remote-FTP/lib/client.js:118

Error: Remote FTP: getConfigPath returned false, but expected a string
    at Client.readConfig (/Users/cloudspider/.atom/packages/Remote-FTP/lib/client.js:118:47)
    at HTMLAnchorElement.<anonymous> (/Users/cloudspider/.atom/packages/Remote-FTP/lib/views/tree-view.js:208:27)
    at HTMLDivElement.dispatch (/Users/cloudspider/.atom/packages/Remote-FTP/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/Users/cloudspider/.atom/packages/Remote-FTP/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:01.3.0 remote-ftp:toggle (atom-pane.pane.active)
```

### Config

```json
{
  "core": {},
  "Remote-FTP": {}
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.22 (active)
emmet, v2.4.3 (active)
git-blame, v0.4.11 (inactive)
git-control, v0.8.2 (inactive)
git-history, v3.2.0 (inactive)
git-log, v0.4.1 (active)
git-plus, v7.0.3 (active)
japanese-menu, v1.9.0 (active)
merge-conflicts, v1.4.4 (active)
Remote-FTP, v0.9.4 (active)
tree-view-git-status, v1.3.0 (active)
vim-mode, v0.65.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by parazsl** [comment]
It happens when Remote-FTP can't find its .ftpconfig file. Check if you have it in your project directory.

**Comment by iopsthecloud** [comment]
@parazsl I've the same issue and .ftpconfig is in my project directory

**Comment by ruvasik** [comment]
Some bug (with second opened Atom)

**Comment by ruvasik** [comment]
[Enter steps to reproduce:]

1. Open second Atom
2. Connect without project folder OR connect with project folder & open any folder/file

**Atom**: 1.14.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.2
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.5


### Stack Trace

Uncaught Error: Remote FTP: getConfigPath returned false, but expected a string

```
At /Users/ruvasik/.atom/packages/Remote-FTP/lib/client.js:118

Error: Remote FTP: getConfigPath returned false, but expected a string
    at Client.readConfig (/packages/Remote-FTP/lib/client.js:118:47)
    at /packages/Remote-FTP/lib/views/tree-view.js:197:30)
    at HTMLDivElement.dispatch (/packages/Remote-FTP/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/Remote-FTP/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -4:18.4.0 find-and-replace:show (input.hidden-input)
     -4:17.8.0 core:confirm (input.hidden-input)
     -4:17 editor:consolidate-selections (input.hidden-input)
     -4:17 core:cancel (input.hidden-input)
  6x -4:16 core:move-right (input.hidden-input)
     -4:15 core:select-right (input.hidden-input)
     -4:14.5.0 core:save (input.hidden-input)
     -4:01.6.0 core:backspace (input.hidden-input)
  2x -4:01.3.0 core:save (input.hidden-input)
     -3:51.4.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -3:51.4.0 remote-ftp:disconnect (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -3:51.4.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -3:43.1.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -3:29 remote-ftp:delete-selected (span.name.icon.icon-file-directory)
     -3:24.6.0 core:close (input.hidden-input)
  2x -1:22.2.0 tree-view:toggle (div.offline)
```

### Non-Core Packages

```
atom-jade 0.3.0 
auto-encoding 0.6.2 
emmet 2.4.3 
jslint 1.5.1 
language-javascript-jsx 0.3.7 
language-twig 1.6.3 
Remote-FTP 0.10.5 
text-manipulation 0.6.0 
```

**Comment by jpxd** [comment]
Do you have `multipleHosts` enabled?

**Comment by iopsthecloud** [comment]
for my part the issue happen on OSX with a case-sensitive FS (sparsebundle). I had to move my project on a non case-sensitive FS to get it works.

**Comment by samifouad** [comment]
@renaudManda That's interesting. And that was the only change? 🤔

@clomaru @ruvasik Are you able to verify you're using "Journaled" and not "Case-sensitive, Journaled" as your HD format? You can check by right-click & Get Info on your primary drive in Finder.

If that's actually what's going on, [it's a bit of a process](https://support.apple.com/kb/PH22240?locale=en_US) to resolve the issue right away without waiting for a fix.

**Comment by jpxd** [comment]
This is most probably a bug introduced because of the multipleHosts flag.

**Comment by ruvasik** [comment]
@samifouad right

**Comment by jsieber** [comment]
I seem to get this error if I do not have a file from the project open and currently in focus. Once I open a local file from the project I can connect to the remote site without error.

**Comment by icetee** [comment]
Related #810

**Comment by carinlynchin** [comment]
I'm getting this too but what @jsieber-aca said worked.

**Comment by mrksdiehl** [comment]
For me it was that I had moved some files on the server but they were still open in atom. Somehow this caused this error, I guess because the remote paths don't match anymore. Closing the open files fixed it.

**Comment by wflanagan** [comment]
FYI, I just installed this plugin. I don't have any configuration or history, and have this error.

**Comment by aIIyou** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.2


### Stack Trace

Uncaught Error: Remote FTP: getConfigPath returned false, but expected a string

```
At C:\Users\yaoxin01\.atom\packages\remote-ftp\lib\client.js:220

Error: Remote FTP: getConfigPath returned false, but expected a string
    at Client.readConfig (/packages/remote-ftp/lib/client.js:220:45)
    at /packages/remote-ftp/lib/views/tree-view.js:154:30)
    at HTMLDivElement.dispatch (/packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -7:04.2.0 core:save (input.hidden-input)
     -4:54.8.0 command-palette:toggle (a.btn-issue.btn.btn-error)
     -4:49.1.0 core:move-down (input.hidden-input)
     -4:48.5.0 core:confirm (input.hidden-input)
     -4:48.5.0 remote-ftp:connect (a.btn-issue.btn.btn-error)
     -4:46.3.0 command-palette:toggle (a.btn-issue.btn.btn-error)
     -4:43.6.0 core:confirm (input.hidden-input)
     -4:43.6.0 remote-ftp:toggle (a.btn-issue.btn.btn-error)
     -4:41.8.0 command-palette:toggle (a.btn-issue.btn.btn-error)
  2x -4:40.1.0 core:move-down (input.hidden-input)
  2x -4:39.2.0 core:move-up (input.hidden-input)
     -4:38.7.0 core:move-down (input.hidden-input)
     -4:38.1.0 core:confirm (input.hidden-input)
     -4:38.1.0 remote-ftp:connect (a.btn-issue.btn.btn-error)
     -1:13.9.0 remote-ftp:toggle (atom-pane.pane.active)
```

### Non-Core Packages

```
remote-ftp 2.2.2 
split-diff 1.6.0 
```
