### ISSUE TITLE
Error on SFTPv3.js at line 602: Uncaught Buffer error

### ISSUE THREAD

**Issue by dylmye** [icetee/remote-ftp#63]
Error produced by:
- 1. Opening project, then toggling ftp sidebar
- 2. Editing + Saving .ftpconfig (file also attached, sans correct login details)
- 3. Pressing "Connect" in ftp sidebar

**Atom Version**: 0.181.0
**System**: Microsoft Windows 8.1
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.6.2
### Stack Trace

Uncaught Error: handle is not a Buffer

```
At C:\Users\dylan_000\.atom\packages\SFTP-deployment\node_modules\ssh2\lib\SFTP\SFTPv3.js:602

Error: handle is not a Buffer
  at SFTP.readdir (C:\Users\dylan_000\.atom\packages\SFTP-deployment\node_modules\ssh2\lib\SFTP\SFTPv3.js:602:11)
  at ConnectorSFTP.module.exports.ConnectorSFTP.list (C:\Users\dylan_000\.atom\packages\Remote-FTP\lib\connectors\sftp.js:151:15)
  at Client.<anonymous> (C:\Users\dylan_000\.atom\packages\Remote-FTP\lib\client.js:319:20)
  at Client.module.exports.Client._next (C:\Users\dylan_000\.atom\packages\Remote-FTP\lib\client.js:270:21)
  at Client.module.exports.Client._enqueue (C:\Users\dylan_000\.atom\packages\Remote-FTP\lib\client.js:281:9)
  at Client.<anonymous> (C:\Users\dylan_000\.atom\packages\Remote-FTP\lib\client.js:318:9)
  at Client.module.exports.Client.onceConnected (C:\Users\dylan_000\.atom\packages\Remote-FTP\lib\client.js:98:14)
  at Client.module.exports.Client.list (C:\Users\dylan_000\.atom\packages\Remote-FTP\lib\client.js:317:8)
  at Directory.module.exports.Directory.open (C:\Users\dylan_000\.atom\packages\Remote-FTP\lib\directory.js:99:10)
  at ConnectorSFTP.<anonymous> (C:\Users\dylan_000\.atom\packages\Remote-FTP\lib\client.js:196:15)
  at C:\Users\dylan_000\.atom\packages\Remote-FTP\lib\connectors\sftp.js:56:16
  at SFTP.<anonymous> (C:\Users\dylan_000\.atom\packages\SFTP-deployment\node_modules\ssh2\lib\Connection.js:836:9)
  at SFTP.g (events.js:202:16)
  at SFTP.emit (events.js:113:17)
  at SFTP._parse (C:\Users\dylan_000\.atom\packages\SFTP-deployment\node_modules\ssh2\lib\SFTP\SFTPv3.js:955:16)
  at ChannelStream.<anonymous> (C:\Users\dylan_000\.atom\packages\SFTP-deployment\node_modules\ssh2\lib\SFTP\SFTPv3.js:49:12)
  at ChannelStream.emit [as _emit] (events.js:116:17)
  at ChannelStream.emit (C:\Users\dylan_000\.atom\packages\SFTP-deployment\node_modules\ssh2\lib\Channel.js:640:12)
  at Parser.<anonymous> (C:\Users\dylan_000\.atom\packages\SFTP-deployment\node_modules\ssh2\lib\Channel.js:95:20)
  at Parser.emit (events.js:116:17)
  at Parser.parsePacket (C:\Users\dylan_000\.atom\packages\SFTP-deployment\node_modules\ssh2\lib\Parser.js:607:12)
  at Parser.execute (C:\Users\dylan_000\.atom\packages\SFTP-deployment\node_modules\ssh2\lib\Parser.js:249:14)
  at Socket.<anonymous> (C:\Users\dylan_000\.atom\packages\SFTP-deployment\node_modules\ssh2\lib\Connection.js:523:18)
  at Socket.emit (events.js:116:17)
  at readableAddChunk (_stream_readable.js:164:16)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:530:20)

```
### Commands

```
     -1:42.0 core:save (atom-text-editor.editor)
  6x -1:32.8 core:backspace (atom-text-editor.editor)
     -1:19.1 core:save (atom-text-editor.editor)
     -1:12.1 core:backspace (atom-text-editor.editor)
     -1:11.6 core:save (atom-text-editor.editor)
  4x -1:09.7 core:select-left (atom-text-editor.editor)
     -1:07.7 core:save (atom-text-editor.editor)
     -1:03.9 core:backspace (atom-text-editor.editor)
  3x -0:58.4 core:select-left (atom-text-editor.editor)
  3x -0:52.6 core:backspace (atom-text-editor.editor)
     -0:41.2 core:save (atom-text-editor.editor)
     -0:35.9 core:undo (atom-text-editor.editor)
     -0:35.3 core:save (atom-text-editor.editor)
     -0:03.4 application:new-file (atom-text-editor.editor)
     -0:02.5 core:paste (atom-text-editor.editor.is-focused)
     -0:00.9 core:undo (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "graphite-ui",
      "seti-syntax"
    ],
    "projectHome": "C:\\Users\\dylan_000\\.atom",
    "audioBeep": false
  }
}
```
### Installed Packages

``` coffee
# User
graphite-ui, v0.14.1
Remote-FTP, v0.6.2
seti-syntax, v0.3.3

# Dev
No dev packages
```

**Comment by dylmye** [comment]
.ftpconfig file: (the symbols used in the user field are the only ones used in the username)

```
{
    "protocol": "sftp",
    "host": "ssh.phx.nearlyfreespeech.net",
    "port": 22,
    "user": "correct_user-here",
    "pass": "pASSWORD",
    "remote": "/",
    "agent": "",
    "privatekey": "",
    "passphrase": "",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000
}
```

**Comment by dylmye** [comment]
When I go straight from restarting Atom, and trying this again, without editing the ftpconfig file, I don't get an error, just a notification instantly going from "Connecting" to "Connection Closed".

Additionally, the settings work in ftp, and as sftp in WinSCP

**Comment by grenierdev** [comment]
Can not reproduce. Please manually download master version and try again.
