### ISSUE TITLE
Uncaught TypeError: Cannot read property 'item' of undefined (remote-ftp.js:333)

### ISSUE THREAD

**Issue by nemeth-it** [icetee/remote-ftp#64]
[Enter steps to reproduce below:]
1. Rightclick CSS file
2. Select "Sync Local -> Remote"
3. Get error message

Manual upload work. Download, too.
But I need such sync feature. :(

OS: Win 8.1

**Atom Version**: 0.188.0
**System**: WINDOWS
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.6.2
### Stack Trace

Uncaught TypeError: Cannot read property 'item' of undefined

```
At C:\Users\User\.atom\packages\Remote-FTP\lib\remote-ftp.js:333

TypeError: Cannot read property 'item' of undefined
  at C:\Users\User\.atom\packages\Remote-FTP\lib\remote-ftp.js:333:20
  at e (C:\Users\User\.atom\packages\Remote-FTP\lib\client.js:490:18)
  at n (C:\Users\User\.atom\packages\Remote-FTP\lib\client.js:497:16)
  at C:\Users\User\.atom\packages\Remote-FTP\lib\client.js:522:7
  at e (C:\Users\User\.atom\packages\Remote-FTP\lib\client.js:381:14)
  at C:\Users\User\.atom\packages\Remote-FTP\lib\client.js:387:13
  at FSReqWrap.oncomplete (fs.js:100:15)

```
### Commands

```
     -9:10.3 sass-watch:watch (atom-text-editor.editor)
     -8:59.7 core:confirm (atom-text-editor.editor.mini)
     -8:46.6 command-palette:toggle (atom-text-editor.editor)
     -8:43.7 core:move-down (atom-text-editor.editor.mini)
     -8:38.8 core:move-up (atom-text-editor.editor.mini)
     -8:38.6 core:confirm (atom-text-editor.editor.mini)
     -8:38.5 sass-watch:list (atom-text-editor.editor)
  3x -8:29.8 core:save (atom-text-editor.editor)
     -3:42.3 remote-ftp:connect (ul.progress.tool-panel.panel-top)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "SFTP-deployment",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-shellscript",
      "language-toml",
      "language-yaml",
      "language-mustache"
    ]
  },
  "Remote-FTP": {
    "hideLocalWhenDisplayed": true
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v2.7.0
autocomplete-snippets, v1.2.0
color-picker, v1.5.0
keyboard-localization, v1.1.6
linter, v0.12.0
linter-php, v0.0.11
linter-phpcs, v0.0.12
minimap, v4.6.0
project-manager, v1.15.5
Remote-FTP, v0.6.2
sass-watch, v0.2.0
save-session, v0.12.4
wordpress-api, v1.2.0

# Dev
No dev packages
```

**Comment by grenierdev** [comment]
Fixed `Sync remote -> local` in 1625496e73186223eb2093478fb87975bd9fbdff

I cant reproduce this problem after the fix.
