### ISSUE TITLE
Uncaught TypeError: Cannot read property 'collapse' of undefined

### ISSUE THREAD

**Issue by shuntakeuch1** [icetee/remote-ftp#640]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.9.4

### Stack Trace

Uncaught TypeError: Cannot read property 'collapse' of undefined

```
At /Users/takeuchishun/.atom/packages/Remote-FTP/lib/views/tree-view.js:421

TypeError: Cannot read property 'collapse' of undefined
    at TreeView.module.exports.TreeView.remoteKeyboardNavigationLeft (/Users/takeuchishun/.atom/packages/Remote-FTP/lib/views/tree-view.js:421:15)
    at TreeView.module.exports.TreeView.remoteKeyboardNavigation (/Users/takeuchishun/.atom/packages/Remote-FTP/lib/views/tree-view.js:369:10)
    at HTMLOListElement.<anonymous> (/Users/takeuchishun/.atom/packages/Remote-FTP/lib/views/tree-view.js:224:47)
    at HTMLOListElement.dispatch (/Users/takeuchishun/.atom/packages/Remote-FTP/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (/Users/takeuchishun/.atom/packages/Remote-FTP/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  3x -1:26.5.0 remote-ftp:delete-selected (span.name.icon.icon-file-text)
     -0:00.1.0 pane:show-previous-item (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [],
    "telemetryConsent": "limited",
    "themes": [
      "native-ui",
      "monokai"
    ]
  },
  "Remote-FTP": {
    "hideLocalWhenDisplayed": true
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v1.3.9 (inactive)
atom-monokai-dark, v0.4.0 (inactive)
auto-encoding, v0.6.2 (active)
browser-plus, v0.0.87 (active)
browser-refresh, v0.9.0 (active)
cakephp-snippets, v0.6.1 (active)
color-picker, v2.2.4 (active)
dark-monokai-batch, v0.5.0 (inactive)
emmet, v2.4.3 (active)
file-icons, v2.0.9 (active)
flex-tool-bar, v0.11.0 (active)
highlight-line, v0.12.0 (active)
highlight-selected, v0.12.0 (active)
japanese-menu, v1.9.0 (active)
minimap, v4.26.6 (active)
minimap-autohide, v0.10.1 (active)
monokai, v0.18.0 (active)
native-ui, v0.20.3 (active)
project-manager, v3.3.3 (active)
Remote-FTP, v0.9.4 (active)
spacegray-monokai-ui, v1.0.0 (inactive)
sync-settings, v0.8.1 (active)
tag, v0.4.0 (active)
tool-bar, v1.0.1 (active)
wrap-guide, v0.39.0 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (active)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Can you reproduce the error (and how?) or has this just been a one time error?

**Comment by samifouad** [comment]
@shuntakeuchi For troubleshooting, can you disable any other package and theme that could be effecting treeview? If something is modifying the structure or changing the naming conventions, it could explain your error.

I would also recommend upgrading to the latest version before trying to replicate the problem

**Comment by shuntakeuch1** [comment]
Hi mgrenier!! remote-ftp 0.10.6 version, good after updating.
remote-ftp great packege!!  Without this it will not job
Thank you for your concern.

2017-02-22 15:07 GMT+09:00 Sami Fouad <notifications@github.com>:
