### ISSUE TITLE
upgrade failed - windows 10

### ISSUE THREAD

**Issue by wenjonsommers** [icetee/remote-ftp#673]
[Enter steps to reproduce below:]

1. Upgraded to 0.10.4
2. Clicked “Connect”
3. Threw this error.

**Atom Version**: 1.4.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.10.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\Name\.atom\packages\Remote-FTP\node_modules\jslint\lib\jslint.js'

```
At fs.js:549

Error: ENOENT: no such file or directory, open 'C:\Users\Name\.atom\packages\Remote-FTP\node_modules\jslint\lib\jslint.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at read (C:\Users\Name\.atom\packages\Remote-FTP\node_modules\jslint\lib\nodelint.js:44:19)
    at Object.exports.load (C:\Users\Name\.atom\packages\Remote-FTP\node_modules\jslint\lib\nodelint.js:63:24)
    at new LintStream_constructor (C:\Users\Name\.atom\packages\Remote-FTP\node_modules\jslint\lib\lintstream.js:27:32)
    at Client.validateConfig (C:/Users/Name/.atom/packages/remote-ftp/lib/client.js:182:11)
    at C:/Users/Name/.atom/packages/remote-ftp/lib/client.js:123:19
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

### Commands

```
     -4:41.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "Remote-FTP": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-wordpress-hooks, v0.2.2
project-manager, v2.7.5
Remote-FTP, v0.10.4

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Did you try to restart Atom? The newest version of Remote-FTP doesn't depend on jslint anymore an removed the dependency. But after updating, the old version is probably still loaded in the active window and you have to restart Atom in order to reload the packages.
