### ISSUE TITLE
Synk Local <-- Remote

### ISSUE THREAD

**Issue by kutepovea** [icetee/remote-ftp#681]
**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Unknown Windows Version
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.10.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir 'C:\Users\Kentasso\PhpstormProjects\sweetepil\sweet-epil.ru_old\public_html\kontakty'

```
At fs.js:951

Error: ENOENT: no such file or directory, scandir 'C:\Users\Kentasso\PhpstormProjects\sweetepil\sweet-epil.ru_old\public_html\kontakty'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Client.traverseTree (file:///C:/Users/Kentasso/.atom/packages/Remote-FTP/lib/client.js:586:31)
    at file:///C:/Users/Kentasso/.atom/packages/Remote-FTP/lib/client.js:637:18
    at callCompleted (file:///C:/Users/Kentasso/.atom/packages/Remote-FTP/lib/connectors/sftp.js:134:54)
    at oneDirCompleted (file:///C:/Users/Kentasso/.atom/packages/Remote-FTP/lib/connectors/sftp.js:138:25)
    at file:///C:/Users/Kentasso/.atom/packages/Remote-FTP/lib/connectors/sftp.js:202:36
    at Array.forEach (native)
    at file:///C:/Users/Kentasso/.atom/packages/Remote-FTP/lib/connectors/sftp.js:152:12
    at C:\Users\Kentasso\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\sftp.js:1583:13
    at SFTPStream._transform (C:\Users\Kentasso\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\sftp.js:382:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (C:\Users\Kentasso\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at SSH2Stream.<anonymous> (C:\Users\Kentasso\.atom\packages\Remote-FTP\node_modules\ssh2\lib\Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (C:\Users\Kentasso\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\ssh.js:3439:10)
    at SSH2Stream._transform (C:\Users\Kentasso\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (C:\Users\Kentasso\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\ssh.js:251:15)
```

### Commands

```
     -0:03.5.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-directory)
```

### Config

```json
{
  "core": {
    "projectHome": "C:\\Users\\Kentasso\\PhpstormProjects\\",
    "telemetryConsent": "no",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
auto-encoding, v0.6.2 (active)
highlight-selected, v0.12.0 (active)
minimap, v4.26.8 (active)
minimap-highlight-selected, v4.5.0 (active)
Remote-FTP, v0.10.5 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (active)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (active)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by samifouad** [comment]
What sort of troubleshooting steps have you done already?

If you're trying to pull down all your remote code into the local directory, have you tried deleting the local cache? Changing the local directory? Etc?

**Comment by samifouad** [comment]
I submitted a pull request to help resolve this issue. If you wanted to implement it yourself it can be found here: #697

**Comment by jpxd** [comment]
Should be resolved in the next update (thanks to @samifouad's PR #697)
