### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir 'D:/Dergi\fbedergiftp\classes\author\form\submi...

### ISSUE THREAD

**Issue by ertekinsoft** [icetee/remote-ftp#688]
[Enter steps to reproduce:]

1. Install remote ftp
2. create local directory and local .ftpconfig file
3. connect ftp server
4. download ftp server
5 chance one of the files
5 left click that file and click update
6 get an error.

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.5

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir 'D:\Dergi\fbedergiftp\classes\author\form\submit\AuthorSubmitStep5Form.inc.php'

```
At fs.js:951

Error: ENOTDIR: not a directory, scandir 'D:\Dergi\fbedergiftp\classes\author\form\submit\AuthorSubmitStep5Form.inc.php'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Client.traverseTree (/packages/Remote-FTP/lib/client.js:586:31)
    at /packages/Remote-FTP/lib/client.js:699:18
    at tryApply (/packages/Remote-FTP/lib/connectors/ftp.js:16:14)
    at error (/packages/Remote-FTP/lib/connectors/ftp.js:125:13)
    at /packages/Remote-FTP/lib/connectors/ftp.js:147:33
    at final (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:476:11)
    at Object.cb (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:513:11)
    at /packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:106:13)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -0:25.2.0 remote-ftp:sync-with-local (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
Remote-FTP 0.10.5 
```

**Comment by samifouad** [comment]
I submitted a pull request to help resolve this issue. Link to it is above if you wanted to implement it yourself.

**Comment by jpxd** [comment]
Should be resolved in the next update (thanks to @samifouad's PR #697)
