### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir '/app/design/frontend/PB/Ma...

### ISSUE THREAD

**Issue by thinkontheclock** [icetee/remote-ftp#689]
[Enter steps to reproduce:]

1. Right click local file and sync Local -> Remote
2. Receive error

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.2
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.5

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir '/app/design/frontend/PB/Main/Magento_Contact/web/css/source/module/_contact.less'

```
At fs.js:951

Error: ENOTDIR: not a directory, scandir '/app/design/frontend/PB/Main/Magento_Contact/web/css/source/module/_contact.less'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Client.traverseTree (/packages/Remote-FTP/lib/client.js:586:31)
    at /packages/Remote-FTP/lib/client.js:699:18
    at callCompleted (/packages/Remote-FTP/lib/connectors/sftp.js:134:54)
    at /packages/Remote-FTP/lib/connectors/sftp.js:147:25
    at reread (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:1570:16)
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:410:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3439:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
```

### Commands

```
     -0:32.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-electron-highlighter-syntax.theme-one-dark-ui)
     -0:20.3.0 remote-ftp:sync-with-local (span.name.icon.css3-icon.dark-blue)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-clock 0.1.3 
atom-minify 0.8.0 
Atom-Syntax-highlighting-for-Sass 0.5.0 
atom-wrap-in-tag 0.6.0 
autocomplete-php 0.3.7 
autocomplete-wordpress-hooks 0.2.2 
electron-highlighter-syntax 1.7.0 
emmet 2.4.3 
file-icons 2.0.15 
github-atom-dark-syntax 0.3.2 
language-csv 1.1.2 
language-markdown 0.19.1 
linter 1.11.21 
magento-tools 0.0.3 
markdown-writer 2.6.3 
newbound-dark-syntax 1.1.0 
newton-dark-syntax 1.1.5 
newton-dark-ui 1.1.0 
one-dark-vivid-syntax 1.7.1 
open-recent 5.0.0 
pain-split 1.4.0 
pigments 0.39.0 
pinned-tabs 0.4.2 
platformio-ide-terminal 2.2.3 
Remote-FTP 0.10.5 
seti-syntax 1.1.2 
term3 0.22.1 
todo-show 1.9.0 
uglify 1.3.0 
wordpress-api 1.2.2 
wp-snippets 0.2.10 
```

**Comment by thinkontheclock** [comment]
The sync Local -> Remote command does seem to work on a directory, just not on individual files. Is this expected behaviour? The directory sync works for me right now, but sometimes I'd like to just be able to keep individual files in sync. Hopefully that's possible. Thanks! Great plugin.

**Comment by thinkontheclock** [comment]
Pull request by @samifouad fixed this issue for me - great work, thank you!

**Comment by jpxd** [comment]
Should be resolved in the next update (thanks to @samifouad's PR #697)
