### ISSUE TITLE
Remote FTP: Could not get project path

### ISSUE THREAD

**Issue by lukecywon** [icetee/remote-ftp#690]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.5

### Stack Trace

Failed to activate the Remote-FTP package

```
At Cannot create icon-node for empty path

TypeError: Cannot create icon-node for empty path
    at Function.forElement (/packages/file-icons/lib/service/icon-node.js:163:11)
    at addIconToElement (/packages/file-icons/lib/service/icon-service.js:43:19)
    at DirectoryView.module.exports.DirectoryView.initialize (/packages/Remote-FTP/lib/views/directory-view.js:49:29)
    at /packages/Remote-FTP/node_modules/space-pen/lib/space-pen.js:184:25)
    at /packages/Remote-FTP/lib/views/directory-view.js:14:41)
    at TreeView.module.exports.TreeView.initialize (/packages/Remote-FTP/lib/views/tree-view.js:128:17)
    at /packages/Remote-FTP/node_modules/space-pen/lib/space-pen.js:184:25)
    at /packages/Remote-FTP/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at /packages/Remote-FTP/lib/views/tree-view.js:46:36)
    at Main.activate (/packages/Remote-FTP/lib/remote-ftp.js:33:21)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:439:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:69:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:303:11)
    at /app.asar/src/buffered-process.js:333:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -7:18.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.use-animations.theme-atom-material-syntax.theme-atom-material-ui)
     -6:14.1.0 remote-ftp:toggle (input.hidden-input)
     -5:39.5.0 remote-ftp:create-sftp-config (input.hidden-input)
     -5:29.7.0 editor:consolidate-selections (input.hidden-input)
     -5:29.7.0 core:cancel (input.hidden-input)
     -4:00.1.0 settings-view:open (div.offline)
  2x -3:02.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.3 
atom-material-syntax 1.0.2 
atom-material-syntax-light 0.4.6 
atom-material-ui 1.3.9 
file-icons 2.0.12 
git-control 0.8.2 
octophus 0.1.1 
remote-edit 1.8.24 
Remote-FTP 0.10.5 
```

**Comment by miguelroboso** [comment]
I get the same error. Just installed on Mac OS 10.12. I cannot edit config files.

**Comment by samifouad** [comment]
What does your **.ftpconfig** file look like?

**Comment by lukecywon** [comment]
I'm not getting this anymore.

**Comment by samifouad** [comment]
@lukecywon glad the issue is gone!

@miguelroboso If you're still dealing with this problem, please make an Issue (green button at the top right of this page) and post the problem details

**Comment by icetee** [comment]
Reproduce:
1. Start empty folder (without .ftpconfig)
2. Disable and enable this package

**Comment by icetee** [comment]
The next release will included repair.
