### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir '~/Documents/web_projects/cec/crowdequitycapita...

### ISSUE THREAD

**Issue by dariozac** [icetee/remote-ftp#691]
[Enter steps to reproduce:]

1. ...I tried to upload the local file to the remote because I wasn't sure that it had sync my last changes and it threw the error.
2. ... Thank you for the great package REMOTE-FTP this has been my 1st issue in 3 months

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.1
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.5

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir '/home/dario/Documents/web_projects/cec/crowdequitycapital.com/portal/application/views/raises/view.php'

```
At fs.js:951

Error: ENOTDIR: not a directory, scandir '/home/dario/Documents/web_projects/cec/crowdequitycapital.com/portal/application/views/raises/view.php'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Client.traverseTree (/packages/Remote-FTP/lib/client.js:586:31)
    at /packages/Remote-FTP/lib/client.js:699:18
    at tryApply (/packages/Remote-FTP/lib/connectors/ftp.js:16:14)
    at error (/packages/Remote-FTP/lib/connectors/ftp.js:125:13)
    at /packages/Remote-FTP/lib/connectors/ftp.js:147:33
    at final (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:476:11)
    at Object.cb (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:513:11)
    at /packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:106:13)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -0:12 remote-ftp:sync-with-local (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
atom-typescript 10.1.13 
emmet 2.4.3 
language-javascript-jsx 0.3.7 
linter 1.11.21 
Remote-FTP 0.10.5 
```

**Comment by samifouad** [comment]
I submitted a pull request to help resolve this issue. Link to it is above if you wanted to implement it yourself.

**Comment by jpxd** [comment]
Should be resolved in the next update (thanks to @samifouad's PR #697)
