### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir '~/Documents/www/DoualaFacile.com/admin.php'

### ISSUE THREAD

**Issue by Yamentou** [icetee/remote-ftp#692]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.5

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir '/Users/Home/Documents/www/DoualaFacile.com/admin.php'

```
At fs.js:951

Error: ENOTDIR: not a directory, scandir '/Users/Home/Documents/www/DoualaFacile.com/admin.php'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Client.traverseTree (/packages/Remote-FTP/lib/client.js:586:31)
    at /packages/Remote-FTP/lib/client.js:637:18
    at ConnectorFTP.list (/packages/Remote-FTP/lib/connectors/ftp.js:117:21)
    at /packages/Remote-FTP/lib/client.js:630:26)
    at Client._next (/packages/Remote-FTP/lib/client.js:489:43)
    at Client._enqueue (/packages/Remote-FTP/lib/client.js:499:59)
    at /packages/Remote-FTP/lib/client.js:627:14)
    at Client.onceConnected (/packages/Remote-FTP/lib/client.js:237:19)
    at Client.syncRemoteLocal (/packages/Remote-FTP/lib/client.js:626:12)
    at /packages/Remote-FTP/lib/menus/commands.js:490:18
    at Array.forEach (native)
    at /packages/Remote-FTP/lib/menus/commands.js:487:17)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1164:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:333:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:10.9.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
Remote-FTP 0.10.5 
```

**Comment by samifouad** [comment]
I submitted a pull request to help resolve this issue. Link to it is above if you wanted to implement it yourself.

**Comment by Yamentou** [comment]
Thanks @samifouad !

**Comment by jpxd** [comment]
Should be resolved in the next update (thanks to @samifouad's PR #697)
