### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by bartaferi** [icetee/remote-ftp#693]
[Enter steps to reproduce:]

1. After Saving a file

**Atom**: 1.14.1 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.5

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At C:\Users\Asus\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\ssh.js:3395

TypeError: Cannot read property '0' of undefined
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3395:21)
    at onNEWKEYS (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3334:11)
    at /packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:208:35)
    at emitNone (events.js:86:13)
    at SSH2Stream.emit (events.js:185:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3762:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SSH2Stream.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -0:58.3.0 editor:newline (input.hidden-input)
     -0:57.4.0 core:save (input.hidden-input)
     -0:32.5.0 core:paste (input.hidden-input)
     -0:29.5.0 snippets:next-tab-stop (input.hidden-input)
     -0:29.5.0 snippets:expand (input.hidden-input)
     -0:29.5.0 editor:indent (input.hidden-input)
     -0:23.2.0 core:backspace (input.hidden-input)
     -0:22.4.0 core:move-up (input.hidden-input)
  2x -0:20.8.0 core:move-down (input.hidden-input)
     -0:20.3.0 autocomplete-plus:confirm (input.hidden-input)
     -0:20.3.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
 11x -0:19.5.0 core:move-left (input.hidden-input)
     -0:17.7.0 snippets:next-tab-stop (input.hidden-input)
     -0:17.7.0 snippets:expand (input.hidden-input)
     -0:17.7.0 editor:indent (input.hidden-input)
     -0:06.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-bootstrap3 1.2.12 
color-picker 2.2.5 
css-color-name 0.4.0 
Remote-FTP 0.10.5 
```

**Comment by samifouad** [comment]
It's hard to pinpoint exactly what's causing this without taking some troubleshooting steps.

Best place to start would probably be the SSH keys you're using. I would ask that you verify they're properly referenced in **.ftpconfig** and then use any other SSH/SFTP/SCP client to verify your keys are not an issue and this would also verify server connection with your keys work.

After that, there are a few other steps you could take but I would start there.

**Comment by jpxd** [comment]
Sorry, but this is no bug in Remote-FTP but in the packet parsing routine from the ssh2-streams module and we can't really do anything about it here. Please open a new issue in the `ssh2-streams` repository (https://github.com/mscdex/ssh2-streams/issues), @mscdex will surely be able to help you.
