### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir '~/Documents\WEB\css\style.css'

### ISSUE THREAD

**Issue by ghost** [icetee/remote-ftp#694]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.5

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir 'C:\Users\stagiaire\Documents\WEB\css\style.css'

```
At fs.js:951

Error: ENOTDIR: not a directory, scandir 'C:\Users\stagiaire\Documents\WEB\css\style.css'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Client.traverseTree (/packages/Remote-FTP/lib/client.js:586:31)
    at /packages/Remote-FTP/lib/client.js:699:18
    at tryApply (/packages/Remote-FTP/lib/connectors/ftp.js:16:14)
    at error (/packages/Remote-FTP/lib/connectors/ftp.js:125:13)
    at /packages/Remote-FTP/lib/connectors/ftp.js:147:33
    at final (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:476:11)
    at Socket.ondone (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:451:7)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -5:14.3.0 core:save (input.hidden-input)
     -5:11.2.0 remote-ftp:sync-with-local (span.name.icon.icon-file-directory)
     -4:05.5.0 core:copy (input.hidden-input)
     -3:59.7.0 find-and-replace:show (input.hidden-input)
     -3:49 core:undo (input.hidden-input)
     -3:34.3.0 core:backspace (input.hidden-input)
     -3:34 core:save (input.hidden-input)
     -3:30.9.0 remote-ftp:sync-with-local (span.name.icon.icon-file-directory)
     -3:21.9.0 core:save (input.hidden-input)
     -3:18.6.0 remote-ftp:sync-with-local (span.name.icon.icon-file-directory)
     -2:49.5.0 core:save (input.hidden-input)
     -2:47 remote-ftp:sync-with-local (div.header.list-item)
     -2:09.0 core:save (input.hidden-input)
  4x -2:04.0 remote-ftp:sync-with-local (span.name.icon.icon-file-directory)
     -0:12.4.0 editor:consolidate-selections (input.hidden-input)
     -0:12.4.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-bootstrap4 1.4.0 
atom-clock 0.1.3 
atom-wrap-in-tag 0.6.0 
atomic-chrome 0.3.0 
color-picker 2.2.5 
git-plus 7.2.2 
javascript-snippets 1.2.1 
linter 1.11.22 
Remote-FTP 0.10.5 
sass-autocompile 0.13.3 
sync-settings 0.8.1 
```

**Comment by samifouad** [comment]
I submitted a pull request to help resolve this issue. Link to it is above if you wanted to implement it yourself.

**Comment by ghost** [comment]
Thank you!

OB.

Olivier.

<https://www.linkedin.com/in/olivierbaudouin>
<https://twitter.com/obaudouin61>

2017-02-15 6:01 GMT+01:00 Sami Fouad <notifications@github.com>:

**Comment by jpxd** [comment]
Should be resolved in the next update (thanks to @samifouad's PR #697)
