### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir '~/Documents\GitHub\chatroom-server2\framework\...

### ISSUE THREAD

**Issue by nicholascgilpin** [icetee/remote-ftp#695]
[Enter steps to reproduce:]
0. Connect via:
{
    "protocol": "sftp",
    "host": "lenss-comp4.cse.school.edu",
    "port": 22,
    "user": "username",
    "pass": "username",
    "promptForPass": false,
    "remote": "/home/username/chatroom-server2",
    "local": "",
    "secure": false,
    "secureOptions": null,
    "connTimeout": 10000,
    "pasvTimeout": 10000,
    "keepalive": 10000,
    "watch": [],
    "watchTimeout": 500
}
1. Right-click a file in the file tree
2. Select Sync  remote --> local

###Notes
The file referenced was verified to exist on the remote server

**Atom**: 1.14.1 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 8.1
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.5

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir 'C:\Users\nick\Documents\GitHub\chatroom-server2\framework\route_guide\route_guide_client.cc'

```
At fs.js:951

Error: ENOTDIR: not a directory, scandir 'C:\Users\nick\Documents\GitHub\chatroom-server2\framework\route_guide\route_guide_client.cc'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Client.traverseTree (/packages/Remote-FTP/lib/client.js:586:31)
    at /packages/Remote-FTP/lib/client.js:637:18
    at callCompleted (/packages/Remote-FTP/lib/connectors/sftp.js:134:54)
    at /packages/Remote-FTP/lib/connectors/sftp.js:147:25
    at reread (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:1570:16)
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:410:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3439:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SSH2Stream.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -7:02.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:46.4.0 tree-view:toggle (input.hidden-input)
     -5:07.1.0 docblockr:parse-enter (input.hidden-input)
     -5:07.1.0 editor:newline (input.hidden-input)
     -4:58.9.0 core:backspace (input.hidden-input)
     -4:57.3.0 core:save (input.hidden-input)
     -1:08.7.0 editor:fold-all (input.hidden-input)
     -1:07.1.0 find-and-replace:show (input.hidden-input)
  3x -1:05.5.0 core:backspace (input.hidden-input)
  3x -1:04.3.0 core:confirm (input.hidden-input)
     -0:56.2.0 core:select-left (input.hidden-input)
     -0:55.1.0 core:copy (input.hidden-input)
     -0:09.2.0 remote-ftp:sync-with-remote (span.name.icon.cpp-icon.medium-blue)
```

### Non-Core Packages

```
achievements 0.9.0 
atom-beautify 0.29.17 
atom-clock 0.1.3 
atom-html-preview 0.1.22 
atom-python-run 0.7.3 
atom-typescript 10.1.14 
atomic-chrome 0.3.0 
autoclose-html 0.23.0 
autocomplete-python 1.8.52 
color-picker 2.2.5 
copy-as-rtf 0.9.3 
docblockr 0.9.1 
file-icons 2.0.15 
highlight-selected 0.12.0 
language-ini 1.17.0 
language-latex 1.0.0 
language-protobuf 0.7.1 
language-x86-64-assembly 2.2.8 
latex 0.42.3 
linter 1.11.23 
linter-csslint 1.3.3 
linter-gcc 0.7.1 
linter-pep8 1.3.2 
linter-pycodestyle 2.0.0 
linter-write-good 0.8.0 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-bookmarks 0.4.2 
open-in-browsers 0.0.19 
open-recent 5.0.0 
pigments 0.39.0 
python-tools 0.6.9 
Remote-FTP 0.10.5 
```

**Comment by samifouad** [comment]
I submitted a pull request to help resolve this issue. Link to it is above if you wanted to implement it yourself.

**Comment by jpxd** [comment]
Should be resolved in the next update (thanks to @samifouad's PR #697)
