### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir 'C:/xampp\htdocs\freedommar\public_htm...

### ISSUE THREAD

**Issue by jackymint** [icetee/remote-ftp#699]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir 'C:\xampp\htdocs\freedommar\public_html\polyherb\local\app\Http\Controllers\Admins\promotionController.php'

```
At fs.js:951

Error: ENOENT: no such file or directory, scandir 'C:\xampp\htdocs\freedommar\public_html\polyherb\local\app\Http\Controllers\Admins\promotionController.php'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Client.traverseTree (/packages/Remote-FTP/lib/client.js:586:31)
    at /packages/Remote-FTP/lib/client.js:637:18
    at ConnectorFTP.list (/packages/Remote-FTP/lib/connectors/ftp.js:117:21)
    at /packages/Remote-FTP/lib/client.js:630:26)
    at Client._next (/packages/Remote-FTP/lib/client.js:489:43)
    at Client._enqueue (/packages/Remote-FTP/lib/client.js:499:59)
    at /packages/Remote-FTP/lib/client.js:627:14)
    at Client.onceConnected (/packages/Remote-FTP/lib/client.js:237:19)
    at Client.syncRemoteLocal (/packages/Remote-FTP/lib/client.js:626:12)
    at /packages/Remote-FTP/lib/menus/commands.js:490:18
    at Array.forEach (native)
    at /packages/Remote-FTP/lib/menus/commands.js:487:17)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1170:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:333:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -5:33.5.0 remote-edit:show-open-files (atom-pane.pane.active)
     -5:29.7.0 remote-edit:browse (atom-pane.pane.active)
     -5:26.2.0 remote-edit:new-host-ftp (atom-pane.pane.active)
     -5:16.5.0 settings-view:open (atom-pane.pane.active)
  3x -5:07.6.0 core:backspace (input.hidden-input)
     -5:06.2.0 core:confirm (input.hidden-input)
     -0:16.5.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
angularjs 0.4.0 
artisan 0.2.0 
atom-autocomplete-php 0.21.0 
atom-beautify 0.29.17 
atom-bootstrap3 1.2.12 
atom-karaf-terminal 0.25.0 
autoclose-html 0.23.0 
build 0.67.0 
build-cmd 0.3.3 
busy 0.7.0 
compare-files 0.8.0 
emmet 2.4.3 
git-control 0.8.2 
git-plus 7.2.2 
hacking-the-kernel 1.6.2 
hacking-the-kernel-ui 1.6.2 
html-to-javascript 0.2.0 
jquery-snippets 11.0.0 
language-blade 0.27.1 
language-vue-component 0.5.0 
minimap 4.26.8 
minimap-git-diff 4.3.1 
php-cs-fixer 4.1.0 
platformio-ide-terminal 2.2.2 
remote-edit 1.8.24 
Remote-FTP 0.10.5 
vue-autocomplete 0.1.1 
vue-format 0.4.0 
```

**Comment by samifouad** [comment]
If you're in fact having issues with manually pressing sync either on the remote treeview or local treeview, then you are experiencing the same problem others have reported. I see the command "sync-with-remote" listed, but if you can clarify that would be the best confirmation.

If you are having this same problem, I submitted a pull request to help resolve this issue. Link to it is above (issue 697) if you wanted to implement it yourself.

**Comment by jpxd** [comment]
Should be resolved in the next update (thanks to @samifouad's PR #697)
