### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir 'D:/workspace\develop'

### ISSUE THREAD

**Issue by hikoyoshi** [icetee/remote-ftp#705]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.6

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'D:\workspace\develop'

```
At C:\Users\yanliang\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:76

Error: EEXIST: file already exists, mkdir 'D:\workspace\develop'
    at Error (native)
    at fs.mkdirSync (fs.js:922:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:665:16)
    at sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:55:12)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:61:24)
    at Object.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at /packages/Remote-FTP/lib/connectors/sftp.js:233:12
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:496:15)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3439:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SSH2Stream.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -8:08.2.0 core:confirm (input.hidden-input)
     -7:57.7.0 remote-ftp:create-sftp-config (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -7:37.4.0 snippets:next-tab-stop (input.hidden-input)
     -7:37.4.0 snippets:expand (input.hidden-input)
     -7:37.4.0 editor:indent (input.hidden-input)
     -7:36 core:backspace (input.hidden-input)
     -7:16.1.0 core:save (input.hidden-input)
     -7:11.7.0 remote-ftp:connect (input.hidden-input)
     -6:59.8.0 window:toggle-menu-bar (input.hidden-input)
     -6:39.2.0 pane:reopen-closed-item (ul.list-inline.tab-bar.inset-panel)
     -3:28.5.0 window:toggle-menu-bar (input.hidden-input)
     -3:09.2.0 remote-ftp:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -2:46.6.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-directory)
     -1:24.8.0 remote-ftp:connect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:50.6.0 remote-ftp:toggle (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:37.4.0 remote-ftp:disconnect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-runner 2.7.1 
cht-menu 0.2.2 
emmet 2.4.3 
git-plus 7.3.2 
git-time-machine 1.5.6 
highlight-selected 0.12.0 
minimap 4.26.8 
pigments 0.39.0 
Remote-FTP 0.10.6 
sync-settings 0.8.1 
```

**Comment by samifouad** [comment]
Are you able to provide a description about what was going on when this error occurred? And if it was a one-time problem or if you can duplicate it? There's a lot of commands listed so it'll help narrow down what's going on.

**Comment by jpxd** [comment]
This is caused because there is a file named 'develop' in your local directory and you want do download something from the remote *directory* 'develop' and these two names collide. Delete the local file to resolve this issue. This should be a notification instead of an exception. See #112
