### ISSUE TITLE
Uncaught Error: EMFILE: too many open files, scandir '~/workspace/mht/yowbow'

### ISSUE THREAD

**Issue by mht-yu-iimura** [icetee/remote-ftp#712]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: EMFILE: too many open files, scandir '/Users/MBPU/workspace/mht/yowbow'

```
At fs.js:951

Error: EMFILE: too many open files, scandir '/Users/MBPU/workspace/mht/yowbow'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Client.traverseTree (/packages/Remote-FTP/lib/client.js:616:48)
    at /packages/Remote-FTP/lib/client.js:791:20
    at callCompleted (/packages/Remote-FTP/lib/connectors/sftp.js:147:54)
    at /packages/Remote-FTP/lib/connectors/sftp.js:163:37
    at /packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:1583:13
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:382:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3439:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
```

### Commands

```
  2x -7:59.1.0 remote-ftp:create-sftp-config (input.hidden-input)
  2x -5:49 core:paste (input.hidden-input)
  5x -5:25.5.0 core:backspace (input.hidden-input)
     -4:30.5.0 core:paste (input.hidden-input)
     -4:15.4.0 core:save (input.hidden-input)
     -3:54.8.0 remote-ftp:connect (input.hidden-input)
     -3:30.2.0 core:save (input.hidden-input)
     -3:24 remote-ftp:connect (input.hidden-input)
  6x -3:15.8.0 core:backspace (input.hidden-input)
     -2:36 core:paste (input.hidden-input)
     -2:35 core:save (input.hidden-input)
     -0:37.2.0 remote-ftp:sync-with-local (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
Remote-FTP 0.10.7 
```

**Comment by icetee** [comment]
Related #112
