### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir '~/Desktop/Work/peterandpauldev/lb.peterandpaul...

### ISSUE THREAD

**Issue by TomS-** [icetee/remote-ftp#715]
[Enter steps to reproduce:]

1. Sync a folder that doesn't exist on local yet

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir '/Users/mac2/Desktop/Work/peterandpauldev/lb.peterandpauldev.co.uk/site/templates'

```
At fs.js:951

Error: ENOTDIR: not a directory, scandir '/Users/mac2/Desktop/Work/peterandpauldev/lb.peterandpauldev.co.uk/site/templates'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Client.traverseTree (/packages/Remote-FTP/lib/client.js:596:31)
    at /packages/Remote-FTP/lib/client.js:672:18
    at tryApply (/packages/Remote-FTP/lib/connectors/ftp.js:16:14)
    at error (/packages/Remote-FTP/lib/connectors/ftp.js:125:13)
    at /packages/Remote-FTP/lib/connectors/ftp.js:147:33
    at final (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:476:11)
    at Socket.ondone (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:451:7)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:24.7.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
Remote-FTP 0.10.7 
seti-icons 1.3.4 
```

**Comment by icetee** [comment]
Related issue #112
