### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Documents\Atom Workspace\...

### ISSUE THREAD

**Issue by eyemiru** [icetee/remote-ftp#723]
[Enter steps to reproduce:]

1. Install Laravel (newest)
2. php artistan make:auth
3. Try to open /resources/views/auth/ any file here

**Atom**: 1.14.4 ia32
**Electron**: 1.3.13
**OS**: DESKTOP-IL0O748
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\....\Documents\Atom Workspace\....\resources\views\auth'

```
At C:\Users\.....\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\....\Documents\Atom Workspace\.....\resources\views\auth'
    at Error (native)
    at fs.mkdirSync (fs.js:922:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:665:16)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
    at Object.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at /packages/Remote-FTP/lib/connectors/sftp.js:233:12
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:496:15)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3439:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SSH2Stream.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -2:01.4.0 remote-ftp:copy-name (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
autoclose-html 0.23.0 
file-icons 2.0.17 
language-blade 0.28.1 
linter 1.11.23 
linter-php 1.3.1 
project-plus 0.9.0 
Remote-FTP 0.10.7 
symbols-tree-view 0.13.2 
typo3 0.7.0 
```

**Comment by icetee** [comment]
Related #112
