### ISSUE TITLE
Uncaught TypeError: atom.project.remoteftp.getConfigPath is not a function

### ISSUE THREAD

**Issue by GarageLabHACKERS** [icetee/remote-ftp#727]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught TypeError: atom.project.remoteftp.getConfigPath is not a function

```
At /Users/byteport/.atom/packages/Remote-FTP/lib/views/tree-view.js:202

TypeError: atom.project.remoteftp.getConfigPath is not a function
    at /packages/Remote-FTP/lib/views/tree-view.js:202:50)
    at HTMLDivElement.dispatch (/packages/Remote-FTP/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/Remote-FTP/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -2:17.4.0 ftp-editor:create (input.hidden-input)
     -0:17.3.0 remote-ftp:toggle (div.package-detail.panels-item)
```

### Non-Core Packages

```
atom-ftp-editor 0.5.0 
language-gherkin-german 0.5.2 
line-length-break 0.4.0 
Remote-FTP 0.10.7 
Userlite-Remote-FTP 0.9.1 
```

**Comment by icetee** [comment]
Related #621
