### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir '~/Desktop\eqftp\내컴_맥도날드_175\5'

### ISSUE THREAD

**Issue by eungom** [icetee/remote-ftp#728]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir 'C:\Users\woogi\Desktop\eqftp\내컴_맥도날드_175\5'

```
At fs.js:951

Error: ENOTDIR: not a directory, scandir 'C:\Users\woogi\Desktop\eqftp\내컴_맥도날드_175\5'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Client.traverseTree (/packages/Remote-FTP/lib/client.js:596:31)
    at /packages/Remote-FTP/lib/client.js:672:18
    at callCompleted (/packages/Remote-FTP/lib/connectors/sftp.js:134:54)
    at /packages/Remote-FTP/lib/connectors/sftp.js:147:25
    at reread (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:1570:16)
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:410:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3439:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SSH2Stream.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
  2x -3:40 tree-view:toggle (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -2:03.9.0 remote-ftp:toggle (input.hidden-input)
     -1:46.3.0 remote-ftp:sync-with-remote (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:46.2.0 core:save (input.hidden-input)
     -0:37.4.0 remote-ftp:add-file (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:34.3.0 core:confirm (input.hidden-input)
     -0:31.9.0 core:save (input.hidden-input)
     -0:21.8.0 remote-ftp:sync-with-remote (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
atom-html-preview 0.1.22 
jshint 1.8.6 
linter 1.11.23 
linter-jshint 3.0.3 
linter-sass-lint 1.7.4 
project-manager 3.3.3 
Remote-FTP 0.10.7 
sync-settings 0.8.1 
w3c-validation 0.4.0 
```

**Comment by icetee** [comment]
Related issue #112
