### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, mkdir '/Users/guilhermeramos/Dropbox/htdocs/CamoEngine/app/controllers/home.php/www/private.musicristo.pt/app/controllers'

### ISSUE THREAD

**Issue by xbitres** [icetee/remote-ftp#73]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.6.2
### Stack Trace

Uncaught Error: ENOTDIR: not a directory, mkdir '/Users/guilhermeramos/Dropbox/htdocs/CamoEngine/app/controllers/home.php/www/private.musicristo.pt/app/controllers'

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/node_modules/mkdirp/index.js:74

Error: ENOTDIR: not a directory, mkdir '/Users/guilhermeramos/Dropbox/htdocs/CamoEngine/app/controllers/home.php/www/private.musicristo.pt/app/controllers'
  at Error (native)
  at Object.fs.mkdirSync (fs.js:791:18)
  at Function.sync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/node_modules/mkdirp/index.js:55:12)
  at Object.fsPlus.makeTreeSync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:310:23)
  at /Users/guilhermeramos/.atom/packages/Remote-FTP/lib/connectors/ftp.js:170:10
  at Object.cb (/Users/guilhermeramos/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:348:5)
  at Parser.<anonymous> (/Users/guilhermeramos/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
  at emitTwo (events.js:87:13)
  at Parser.emit (events.js:169:7)
  at Parser._write (/Users/guilhermeramos/.atom/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at Parser.Writable.write (_stream_writable.js:210:11)
  at Socket.ondata (/Users/guilhermeramos/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at TCP.onread (net.js:517:20)

```
### Commands

```
     -1:02.7 docblockr:parse-tab (atom-text-editor.editor)
     -1:02.7 editor:indent (atom-text-editor.editor)
     -1:00.1 core:save (atom-text-editor.editor)
  2x -0:51.8 core:backspace (atom-text-editor.editor)
     -0:49.7 core:move-left (atom-text-editor.editor)
     -0:49.4 core:backspace (atom-text-editor.editor)
     -0:47.9 core:save (atom-text-editor.editor)
     -0:20.3 snippets:next-tab-stop (atom-text-editor.editor)
     -0:20.3 snippets:expand (atom-text-editor.editor)
     -0:20.3 docblockr:parse-tab (atom-text-editor.editor)
     -0:20.3 editor:indent (atom-text-editor.editor)
     -0:18.2 snippets:next-tab-stop (atom-text-editor.editor)
     -0:18.2 snippets:expand (atom-text-editor.editor)
     -0:18.2 docblockr:parse-tab (atom-text-editor.editor)
     -0:18.2 editor:indent (atom-text-editor.editor)
     -0:10.4 core:save (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.6.2
autocomplete-plus, v2.9.0
docblockr, v0.6.3
language-prolog, v0.9.0
project-manager, v1.15.5

# Dev
No dev packages
```

**Comment by grenierdev** [comment]
Fixed in commit 1625496e73186223eb2093478fb87975bd9fbdff
