### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Documents/php_projects/thegrape.co.kr/publi...

### ISSUE THREAD

**Issue by ggunojang** [icetee/remote-ftp#730]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir '/Users/ggunojang/Documents/php_projects/thegrape.co.kr/public_html/application/views/admin/maker'

```
At /Users/ggunojang/.atom/packages/Remote-FTP/node_modules/mkdirp/index.js:76

Error: EEXIST: file already exists, mkdir '/Users/ggunojang/Documents/php_projects/thegrape.co.kr/public_html/application/views/admin/maker'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:55:12)
    at Object.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at /packages/Remote-FTP/lib/connectors/sftp.js:233:12
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:496:15)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3439:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SSH2Stream.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -2:53.2.0 core:paste (input.hidden-input)
  4x -2:50.6.0 core:save (input.hidden-input)
     -1:38.6.0 core:copy (input.hidden-input)
     -1:37.8.0 core:paste (input.hidden-input)
  2x -1:34.1.0 core:save (input.hidden-input)
     -0:48 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -0:45.2.0 core:confirm (input.hidden-input)
     -0:39 remote-ftp:delete-selected (span.name.icon.icon-file-text)
     -0:33.8.0 remote-ftp:add-folder (span.name.icon.icon-file-directory)
     -0:32 core:confirm (input.hidden-input)
     -0:24 core:select-all (input.hidden-input)
     -0:23.4.0 core:copy (input.hidden-input)
     -0:20.8.0 core:select-all (input.hidden-input)
     -0:20.4.0 core:paste (input.hidden-input)
     -0:15.6.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -0:10.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.22.0 
atom-beautify 0.29.17 
atom-bootstrap3 1.2.12 
atom-clock 0.1.6 
atom-linter-node-dependencies 1.5.0 
atom-material-syntax 1.0.2 
atom-monokai 0.10.9 
atom-runner 2.7.1 
aurora-theme 1.2.2 
autoclose-html 0.23.0 
emmet 2.4.3 
highlight-selected 0.12.0 
linter 1.11.23 
linter-csslint 1.3.4 
linter-eslint 8.1.3 
linter-jshint 3.0.3 
minimap 4.26.8 
project-manager 3.3.3 
Remote-FTP 0.10.7 
sync-settings 0.8.1 
terminal-plus 0.14.5 
```

**Comment by icetee** [comment]
Related #112
