### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Google Drive\WEB\siomapp\area_cristian\incl...

### ISSUE THREAD

**Issue by santiagoCorreaE** [icetee/remote-ftp#747]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\tiago\Google Drive\WEB\siomapp\area_cristian\includes'

```
At C:\Users\tiago\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\tiago\Google Drive\WEB\siomapp\area_cristian\includes'
    at Error (native)
    at fs.mkdirSync (fs.js:922:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:665:16)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
    at Object.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at /packages/Remote-FTP/lib/connectors/ftp.js:183:18
    at /packages/Remote-FTP/lib/connectors/ftp.js:214:18
    at Object.cb (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:348:5)
    at /packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:106:13)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -3:06.1.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:19.2.0 tree-view:remove (span.name.icon.icon-file-directory)
     -1:04.5.0 tree-view:remove-project-folder (div.header.list-item.project-root-header)
     -1:04.4.0 remote-ftp:disconnect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:04.4.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:36.8.0 remote-ftp:disconnect (atom-pane.pane.active)
     -0:12.5.0 remote-ftp:refresh-selected (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
Remote-FTP 0.10.7 
```

**Comment by icetee** [comment]
Related #112
