### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir 'D:/Atom\drowtheme\wp-content\themes\drowtheme...

### ISSUE THREAD

**Issue by Cuuki** [icetee/remote-ftp#748]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: DROW-R2-P4
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'D:\Atom\drowtheme\wp-content\themes\drowtheme\lib\Drow\Widget\Image-Alignment\tpl'

```
At C:\Users\p.soellner\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:76

Error: EEXIST: file already exists, mkdir 'D:\Atom\drowtheme\wp-content\themes\drowtheme\lib\Drow\Widget\Image-Alignment\tpl'
    at Error (native)
    at fs.mkdirSync (fs.js:922:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:665:16)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:55:12)
    at Object.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at /packages/Remote-FTP/lib/connectors/sftp.js:233:12
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:496:15)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3439:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SSH2Stream.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -2:21.9.0 core:save (input.hidden-input)
     -2:02.2.0 intentions:highlight (input.hidden-input)
     -2:02.1.0 core:cut (input.hidden-input)
     -2:00.4.0 core:backspace (input.hidden-input)
     -1:58.8.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -1:58.7.0 docblockr:parse-enter (input.hidden-input)
     -1:58.7.0 editor:newline (input.hidden-input)
     -1:58.7.0 intentions:highlight (input.hidden-input)
     -1:58.6.0 core:paste (input.hidden-input)
     -1:58.4.0 core:save (input.hidden-input)
     -1:53 intentions:highlight (input.hidden-input)
  2x -1:52.8.0 editor:move-to-beginning-of-word (input.hidden-input)
     -1:49.1.0 intentions:highlight (input.hidden-input)
     -1:48.9.0 core:save (input.hidden-input)
     -1:19.7.0 intentions:highlight (input.hidden-input)
     -1:19.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
angularjs 0.4.0 
atom-beautify 0.29.17 
atom-clock 0.1.6 
atom-css-unit-converter 1.1.1 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
autoclose-html 0.23.0 
autoprefixer 3.6.1 
busy-signal 1.3.0 
color-picker 2.2.5 
docblockr 0.9.4 
emmet 2.4.3 
file-icons 2.1.2 
highlight-selected 0.13.1 
intentions 1.1.2 
language-htaccess 0.1.1 
language-smarty 1.8.0 
linter 2.1.2 
linter-csslint 1.3.4 
linter-htmlhint 1.3.2 
linter-jshint 3.0.3 
linter-less 2.6.0 
linter-php 1.3.2 
linter-scss-lint 3.1.0 
linter-ui-default 1.2.2 
minimap 4.27.0 
minimap-highlight-selected 4.5.0 
minimap-split-diff 0.3.7 
open-recent 5.0.0 
php-cs-fixer 4.1.0 
pigments 0.39.1 
qolor 0.4.1 
Remote-FTP 0.10.7 
split-diff 1.3.0 
sync-settings 0.8.1 
todo-show 1.11.0 
```

**Comment by icetee** [comment]
Related #112
