### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '$ATOM_HOME/vbs.bisonsystems.org\style_update\...

### ISSUE THREAD

**Issue by spetering** [icetee/remote-ftp#750]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\Sam Petering\.atom\vbs.bisonsystems.org\style_update\admin'

```
At C:\Users\Sam Petering\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:76

Error: EEXIST: file already exists, mkdir 'C:\Users\Sam Petering\.atom\vbs.bisonsystems.org\style_update\admin'
    at Error (native)
    at fs.mkdirSync (fs.js:922:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:665:16)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:55:12)
    at Object.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at /packages/Remote-FTP/lib/connectors/ftp.js:183:18
    at /packages/Remote-FTP/lib/connectors/ftp.js:214:18
    at Object.cb (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:348:5)
    at /packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:106:13)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -0:41.1.0 remote-ftp:disconnect (input.hidden-input)
     -0:37.5.0 remote-ftp:connect (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.1.22 
autoclose-html 0.23.0 
goto-definition 1.3.0 
highlight-selected 0.13.1 
hyperclick 0.0.40 
less-than-slash 0.16.0 
minimap 4.26.8 
php-integrator-navigation 1.1.2 
pigments 0.39.1 
Remote-FTP 0.10.7 
```

**Comment by icetee** [comment]
Related #112
