### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open 'F:/mailcloud\work space\Разнопраздник\са...

### ISSUE THREAD

**Issue by ekam230** [icetee/remote-ftp#751]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'F:\mailcloud\work space\Разнопраздник\сайт верстка\var\www\domains\raznoprazdnik.ru\wp-content\themes\theme1'

```
At fs.js:640

Error: ENOENT: no such file or directory, open 'F:\mailcloud\work space\Разнопраздник\сайт верстка\var\www\domains\raznoprazdnik.ru\wp-content\themes\theme1'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Client.traverseTree (/packages/Remote-FTP/lib/client.js:593:27)
    at /packages/Remote-FTP/lib/client.js:672:18
    at callCompleted (/packages/Remote-FTP/lib/connectors/sftp.js:134:54)
    at oneDirCompleted (/packages/Remote-FTP/lib/connectors/sftp.js:138:25)
    at /packages/Remote-FTP/lib/connectors/sftp.js:202:36
    at Array.forEach (native)
    at /packages/Remote-FTP/lib/connectors/sftp.js:152:12
    at /packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:1583:13
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:382:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3439:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SSH2Stream.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -9:11.6.0 tree-view:remove (span.name.icon.icon-file-directory)
     -7:46 settings-view:install-packages-and-themes (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  7x -7:43.7.0 core:backspace (input.hidden-input)
     -7:28.9.0 core:confirm (input.hidden-input)
     -6:26.3.0 remote-ftp:toggle (div.package-detail.panels-item)
     -5:19.8.0 tree-view:add-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:10.1.0 core:confirm (input.hidden-input)
  5x -5:09.0 core:paste (input.hidden-input)
     -4:02.1.0 core:undo (input.hidden-input)
     -3:51.1.0 core:paste (input.hidden-input)
     -3:48 core:save (input.hidden-input)
  2x -3:06.5.0 find-and-replace:show (input.hidden-input)
     -2:24.8.0 core:confirm (input.hidden-input)
     -0:27 remote-ftp:sync-with-remote (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-bootstrap3 1.2.12 
atom-compile-less-pw 0.2.0 
color-picker 2.2.5 
emmet 2.4.3 
less-autocompile 1.0.0 
minimap 4.26.8 
minimap-pigments 0.2.2 
open-in-browsers 0.0.19 
Remote-FTP 0.10.7 
sync-settings 0.8.1 
```

**Comment by icetee** [comment]
Related #112
