### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/Projects/DevCC/new_cc/cc/bin/xdiggerd'

### ISSUE THREAD

**Issue by sghosh-rvbd2016** [icetee/remote-ftp#752]
[Enter steps to reproduce:]

1. Right click project directory with symlinks to other files (also in the project directory). Hit Upload. .ftpconfig already configured and connected to remote.

It appears any symlinked file is getting this error. I checked the permissions on the files and they are persmissive enough for Atom to handle.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/SAGHOSH/Projects/DevCC/new_cc/cc/bin/xdiggerd'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat '/Users/SAGHOSH/Projects/DevCC/new_cc/cc/bin/xdiggerd'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at Client.traverseTree (/packages/Remote-FTP/lib/client.js:602:30)
    at /packages/Remote-FTP/lib/client.js:756:18
    at callCompleted (/packages/Remote-FTP/lib/connectors/sftp.js:134:54)
    at /packages/Remote-FTP/lib/connectors/sftp.js:147:25
    at reread (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:1570:16)
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:410:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3439:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SSH2Stream.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
```

### Commands

```
     -7:13.2.0 application:open (input.hidden-input)
     -7:10.1.0 application:add-project-folder (input.hidden-input)
     -6:52.8.0 atom-ctags:toggle-file-symbols (input.hidden-input)
     -6:51 editor:consolidate-selections (input.hidden-input)
     -6:51 core:cancel (input.hidden-input)
     -5:14.8.0 remote-ftp:upload-selected (span.name.icon.icon-repo)
     -5:14.8.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -5:14.3.0 remote-ftp:upload-selected (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -4:16.4.0 remote-ftp:connect (input.hidden-input)
     -3:57.1.0 remote-ftp:sync-with-local (div.header.list-item.project-root-header)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-ctags 5.0.0 
atom-handlebars 1.3.0 
fold-functions 0.5.0 
git-plus 7.2.0 
highlight-selected 0.12.0 
linter 1.11.21 
linter-handlebars 2.3.4 
linter-perl 0.8.0 
merge-conflicts 1.4.4 
refactor 0.11.3 
Remote-FTP 0.10.7 
```

**Comment by icetee** [comment]
Duplicate #751
