### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir 'S:/Google Drive\WORK\-=LINUX=-\[T] mirta\certs'

### ISSUE THREAD

**Issue by frosty939** [icetee/remote-ftp#755]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir 'S:\Google Drive\WORK\-=LINUX=-\[T] mirta\certs'

```
At fs.js:951

Error: ENOTDIR: not a directory, scandir 'S:\Google Drive\WORK\-=LINUX=-\[T] mirta\certs'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Client.traverseTree (/packages/Remote-FTP/lib/client.js:596:31)
    at /packages/Remote-FTP/lib/client.js:672:18
    at callCompleted (/packages/Remote-FTP/lib/connectors/sftp.js:134:54)
    at oneDirCompleted (/packages/Remote-FTP/lib/connectors/sftp.js:138:25)
    at /packages/Remote-FTP/lib/connectors/sftp.js:202:36
    at Array.forEach (native)
    at /packages/Remote-FTP/lib/connectors/sftp.js:152:12
    at /packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:1583:13
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:382:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3439:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
```

### Commands

```
     -1:19.9.0 core:move-left (input.hidden-input)
  2x -1:19.3.0 core:backspace (input.hidden-input)
     -1:18.9.0 core:paste (input.hidden-input)
     -1:18.2.0 core:move-down (input.hidden-input)
  4x -1:17.3.0 core:backspace (input.hidden-input)
  2x -1:15.2.0 core:move-down (input.hidden-input)
  4x -1:14.7.0 core:move-right (input.hidden-input)
  5x -1:13.7.0 core:delete (input.hidden-input)
     -1:10.6.0 core:move-down (input.hidden-input)
  2x -1:10.1.0 core:move-left (input.hidden-input)
     -0:51.8.0 core:save (input.hidden-input)
  2x -0:48 remote-ftp:toggle (input.hidden-input)
     -0:43.4.0 core:save (input.hidden-input)
     -0:41.7.0 remote-ftp:connect (input.hidden-input)
     -0:38.5.0 core:confirm (input.hidden-input)
     -0:22.6.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-html-preview 0.1.22 
autoclose-html 0.23.0 
file-icons 2.1.2 
highlight-selected 0.13.1 
minimap 4.27.0 
minimap-highlight-selected 4.6.0 
Remote-FTP 0.10.7 
xml-formatter 0.10.0 
```

**Comment by icetee** [comment]
Related issue #112
