### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Jordan/DeuxiemeAvis/_global/js/_trans'

### ISSUE THREAD

**Issue by Dalanir** [icetee/remote-ftp#756]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir '/Users/lorho_j/Jordan/DeuxiemeAvis/_global/js/_trans'

```
At /Users/lorho_j/.atom/packages/Remote-FTP/node_modules/mkdirp/index.js:92

Error: EEXIST: file already exists, mkdir '/Users/lorho_j/Jordan/DeuxiemeAvis/_global/js/_trans'
  at Error (native)
  at Object.fs.mkdirSync (fs.js:922:18)
  at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
  at Object.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
  at /packages/Remote-FTP/lib/connectors/ftp.js:222:39
  at /packages/Remote-FTP/lib/connectors/ftp.js:254:19
  at Object.cb (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:348:5)
  at /packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
  at emitTwo (events.js:106:13)
  at Parser.emit (events.js:191:7)
  at Parser._write (/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
  at doWrite (_stream_writable.js:307:12)
  at writeOrBuffer (_stream_writable.js:293:5)
  at Parser.Writable.write (_stream_writable.js:220:11)
  at Socket.ondata (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at readableAddChunk (_stream_readable.js:176:18)
  at Socket.Readable.push (_stream_readable.js:134:10)
  at TCP.onread (net.js:543:20)

```

### Commands

```
  2x -5:10 core:save (input.hidden-input)
     -4:24.2.0 editor:select-line (input.hidden-input)
     -2:36.9.0 remote-ftp:add-file (div.header.list-item)
     -2:34.4.0 core:confirm (input.hidden-input)
     -2:29.4.0 remote-ftp:delete-selected (span.name.icon.icon-file-text)
     -2:25.8.0 remote-ftp:add-folder (div.header.list-item)
     -2:24 core:confirm (input.hidden-input)
     -2:20.3.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -2:13.1.0 core:confirm (input.hidden-input)
     -1:55.5.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -1:50.4.0 core:backspace (input.hidden-input)
     -1:47.7.0 core:confirm (input.hidden-input)
     -1:35.1.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
  2x -1:33.5.0 core:backspace (input.hidden-input)
     -1:26.5.0 core:confirm (input.hidden-input)
     -0:18.6.0 remote-ftp:connect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
file-header 1.13.3 
file-types 0.5.5 
nuclide 0.158.0 
php-twig 4.0.0 
quit-control 1.0.0 
Remote-FTP 0.10.7 
```

**Comment by tobinfekkes** [comment]
Just started getting this same error this morning as well. If I create a new directory via "Add Folder", then "Add File", then try to open that file, the error occurs.


**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\my_incognito_user\Desktop\project\wp-content\plugins\awesome_plugin\templates\myaccount'

```
At C:\Users\my_incognito_user\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:76

Error: EEXIST: file already exists, mkdir 'C:\Users\my_incognito_user\Desktop\project\wp-content\plugins\awesome_plugin-farms\templates\myaccount'
    at Error (native)
    at fs.mkdirSync (fs.js:922:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:665:16)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:55:12)
    at Object.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at /packages/Remote-FTP/lib/connectors/sftp.js:233:12
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:496:15)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3439:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SSH2Stream.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -0:33.6.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -0:30.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autohide-tree-view 0.25.1 
busy-signal 1.3.0 
color-picker 2.2.5 
intentions 1.1.2 
linter 2.1.2 
linter-php 1.3.2 
linter-ui-default 1.2.2 
Remote-FTP 0.10.7 
Sublime-Style-Column-Selection 1.7.4 
twilight-syntax 0.8.0 
```

**Comment by tobinfekkes** [comment]
The root of the problem: deleting a file from the remote tree doesn't also delete the corresponding file in the local tree. So when you go to open that file back up (or create a new file in the remote that still exists in the local from before), it finds two files with the same name (hence the error message) with different content. 

You can fix it by navigating to the directory in Finder/Explorer and removing the duplicate files. Then at least Atom will open the file from the server, and create a new file on your local. But it will happen again when you delete a file from the remote tree.

**Comment by icetee** [comment]
Related #112
