### ISSUE TITLE
Failed to activate the Remote-FTP package

### ISSUE THREAD

**Issue by michaelcarwile** [icetee/remote-ftp#76]
[Enter steps to reproduce below:]
1. Attempt to install via Install window in Atom.
2. Activation fails.

**Atom Version**: 0.192.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.2
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.6.2
### Stack Trace

Failed to activate the Remote-FTP package

```
At undefined is not a function

TypeError: undefined is not a function
  at Object.module.exports.activate (/Users/mlc/.atom/packages/Remote-FTP/lib/remote-ftp.js:30:19)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:222:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:203:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:147:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:195:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:434:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:303:19
  at /Applications/Atom.app/Contents/Resources/app/src/config.js:559:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:721:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:536:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:220:14)
  at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:330:12)
  at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app/src/package.js:132:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:132:14)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:213:27)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```
### Commands

```
     -7:08.9 remote-ftp:create-sftp-config (div.settings-view.pane-item)
     -6:34.2 window:install-shell-commands (div.settings-view.pane-item)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.6.2

# Dev
No dev packages
```

**Comment by michaelcarwile** [comment]
I think I deduced that this was caused by a bad .vimrc symlink. Seems to be functioning properly now. Sorry to be a bother.

**Comment by fseminario** [comment]
I am getting this error. How do I fix it?

**Comment by fseminario** [comment]
getting this still in 0.7.1

undefined is not a function
Hide Stack Trace
TypeError: undefined is not a function
  at Object.module.exports.activate (/Users/fjs/.atom/packages/Remote-FTP/lib/remote-ftp.js:30:19)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:313:19
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:343:12)
  at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:142:14)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:310:27)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

**Comment by fseminario** [comment]
had to uninstall and reinstall now its working but an inconvenience.

**Comment by diex01** [comment]
update "remote-FTP" - ok

**Comment by JasonRaveling** [comment]
I just downloaded and installed the latest version of Atom and then downloaded the `remote-ftp` zip. All the latest version. When I uninstall, it just deletes the package. It says the following and directs me to this issue. I guess I don't see what the fix was sorry.

> Cannot find module 'fs-plus'

**Comment by JasonRaveling** [comment]
Okay. After a couple times of uninstalling, then re-installing it works. I just can't save my config file... it crashes Atom. But that's a different issue and may be related to another package.

**Comment by o2relax** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.4

### Stack Trace

Failed to activate the Remote-FTP package

```
At Cannot find module 'jslint'

Error: Cannot find module 'jslint'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Atom\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Администратор\.atom\packages\Remote-FTP\lib\client.js:9:15)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\Atom\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
```

### Commands

```
     -0:56.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:52.8.0 core:copy (atom-text-editor.editor.mini.is-focused)
     -0:51.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:50.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {}
}
```

### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.4

# Dev
No dev packages
```

**Comment by pablobb** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Microsoft Windows 8.1
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.4

### Stack Trace

Failed to activate the Remote-FTP package

```
At Cannot find module 'jslint'

Error: Cannot find module 'jslint'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Paweł\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Paweł\.atom\packages\Remote-FTP\lib\client.js:9:15)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\Paweł\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autocomplete-ruby",
      "ruby-block",
      "ruby-block-converter",
      "remote-edit",
      "script"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-material-ui, v0.6.1
autoclose-html, v0.19.0
jquery-snippets, v11.0.0
jslint, v1.4.0
Remote-FTP, v0.7.4
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by jpxd** [comment]
I guess you are on Windows and have non-Latin characters in your Username (or `%userprofile%` path in general). This issue is Atom's and not Remote-FTPs fault. Please have a look into atom/atom#8891

**Comment by pablobb** [comment]
That's the issue ;/
I Have an "Ł" in profile path, thx, looks like i need to wait for solution!
Cheers!

**Comment by webhacking** [comment]
update your `remote-FTP `

**Comment by xorinzor** [comment]
After uninstall / reinstall of the package, don't forget to restart Atom, then it will work

**Comment by ascarpello** [comment]
Same Issue here on Windows
Fixed with reinstal Remote-FTP and restart Atom
