### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir '~/Documents/Study/CS354/xinu-spring2017/lib'

### ISSUE THREAD

**Issue by avirbhaw** [icetee/remote-ftp#769]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir '/Users/Avi/Documents/Study/CS354/xinu-spring2017/lib'

```
At fs.js:951

Error: ENOTDIR: not a directory, scandir '/Users/Avi/Documents/Study/CS354/xinu-spring2017/lib'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Client.traverseTree (/packages/Remote-FTP/lib/client.js:596:31)
    at /packages/Remote-FTP/lib/client.js:672:18
    at callCompleted (/packages/Remote-FTP/lib/connectors/sftp.js:134:54)
    at oneDirCompleted (/packages/Remote-FTP/lib/connectors/sftp.js:138:25)
    at /packages/Remote-FTP/lib/connectors/sftp.js:202:36
    at Array.forEach (native)
    at /packages/Remote-FTP/lib/connectors/sftp.js:152:12
    at /packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:1583:13
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:382:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3439:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
```

### Commands

```
     -1:35.2.0 tree-view:remove (span.name.icon.icon-file-directory)
     -1:23.1.0 tree-view:show-in-file-manager (span.name.icon.icon-file-directory)
     -1:07.8.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-directory)
     -0:38.9.0 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:34.1.0 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:33.7.0 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:30.1.0 tree-view:open-selected-entry (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:28.2.0 core:close (input.hidden-input)
     -0:27.3.0 core:move-up (input.hidden-input)
     -0:23.3.0 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  5x -0:21.4.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:19.8.0 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:17.8.0 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:10.2.0 core:save (input.hidden-input)
     -0:07.4.0 remote-ftp:connect (input.hidden-input)
     -0:03.8.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
native-ui 0.20.4 
remote-atom 1.3.10 
remote-edit 1.9.0 
Remote-FTP 0.10.7 
```

**Comment by icetee** [comment]
Related issue #112
