### ISSUE TITLE
Cannot find module 'fs-plus'

### ISSUE THREAD

**Issue by yangshare** [icetee/remote-ftp#771]
Error: Cannot find module 'fs-plus'
  at Module._resolveFilename (module.js:455:15)
  at Module._resolveFilename (D:\Program Files\Atom x64\resources\electron.asar\common\reset-search-paths.js:35:12)
  at Function.Module._resolveFilename (D:\Program Files\Atom x64\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:403:25)
  at Module.require (module.js:483:17)
  at require (D:\Program Files\Atom x64\resources\app.asar\src\native-compile-cache.js:50:27)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\remote-ftp\lib\remote-ftp.js:11:15)
  at Module._compile (D:\Program Files\Atom x64\resources\app.asar\src\native-compile-cache.js:109:30)
  at Object.value [as .js] (D:\Program Files\Atom x64\resources\app.asar\src\compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (D:\Program Files\Atom x64\resources\app.asar\src\native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (D:\Program Files\Atom x64\resources\app.asar\src\package.js:796:27)
  at D:\Program Files\Atom x64\resources\app.asar\src\package.js:123:28
  at Package.module.exports.Package.measure (D:\Program Files\Atom x64\resources\app.asar\src\package.js:96:15)
  at Package.module.exports.Package.load (D:\Program Files\Atom x64\resources\app.asar\src\package.js:110:12)
  at PackageManager.module.exports.PackageManager.loadPackage (D:\Program Files\Atom x64\resources\app.asar\src\package-manager.js:468:14)
  at D:\Program Files\Atom x64\resources\app.asar\src\package-manager.js:412:19
  at Config.module.exports.Config.transact (D:\Program Files\Atom x64\resources\app.asar\src\config.js:312:16)
  at PackageManager.module.exports.PackageManager.loadPackages (D:\Program Files\Atom x64\resources\app.asar\src\package-manager.js:407:19)
  at D:\Program Files\Atom x64\resources\app.asar\src\atom-environment.js:792:28

**Comment by yangshare** [comment]
Cannot find module 'fs-plus‘’

**Comment by icetee** [comment]
Try reinstall remote-ftp!

**Comment by binxChen** [comment]
npm(apm) install

**Comment by yangshare** [comment]
Chinese garbled
