### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open 'D:/DEVELOP\Projects\ME_bitrix\bitrix\tem...

### ISSUE THREAD

**Issue by iron-cherep** [icetee/remote-ftp#773]
[Enter steps to reproduce:]

1. Connected to remote FTP
2. Selected Download button on one of remote directories
3. After some time of interacting with ftp Atom thrown error

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Windows 7
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'D:\DEVELOP\Projects\ME_bitrix\bitrix\templates'

```
At fs.js:640

Error: ENOENT: no such file or directory, open 'D:\DEVELOP\Projects\ME_bitrix\bitrix\templates'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Client.traverseTree (/packages/Remote-FTP/lib/client.js:593:27)
    at /packages/Remote-FTP/lib/client.js:672:18
    at tryApply (/packages/Remote-FTP/lib/connectors/ftp.js:16:14)
    at error (/packages/Remote-FTP/lib/connectors/ftp.js:125:13)
    at /packages/Remote-FTP/lib/connectors/ftp.js:147:33
    at final (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:476:11)
    at Object.cb (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:513:11)
    at /packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:106:13)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -9:42.5.0 core:backspace (input.hidden-input)
 10x -9:42.4.0 core:delete (input.hidden-input)
     -9:25.5.0 core:backspace (input.hidden-input)
  2x -9:21.2.0 core:delete (input.hidden-input)
     -9:16.7.0 core:backspace (input.hidden-input)
  5x -9:14.2.0 core:delete (input.hidden-input)
     -9:04.1.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -9:02.3.0 core:confirm (input.hidden-input)
     -9:00.7.0 core:save (input.hidden-input)
     -8:29.5.0 remote-ftp:sync-with-remote (div.header.list-item)
     -8:11.1.0 remote-ftp:download-selected (div.header.list-item)
     -3:35.2.0 remote-ftp:disconnect (div.header.list-item)
     -2:58.7.0 encoding-selector:show (atom-text-editor.editor)
     -2:54.3.0 core:confirm (input.hidden-input)
     -2:29.3.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-directory)
     -0:00.1.0 tree-view:add-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
editorconfig 2.2.2 
emmet 2.4.3 
git-diff-details 1.4.0 
git-time-machine 1.5.9 
platformio-ide-terminal 2.5.0 
Remote-FTP 0.10.7 
```

**Comment by icetee** [comment]
Duplicate #751
