### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by quakeboy** [icetee/remote-ftp#778]
[Enter steps to reproduce:]

1. ...Right click any sub-folder on the remote, and click on sync remote to local.
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.5
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, 

```
At fs.js:640

Error: ENOENT: no such file or directory, 
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Client.traverseTree (/packages/Remote-FTP/lib/client.js:593:27)
    at /packages/Remote-FTP/lib/client.js:672:18
    at callCompleted (/packages/Remote-FTP/lib/connectors/sftp.js:134:54)
    at /packages/Remote-FTP/lib/connectors/sftp.js:150:37
    at /packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:1583:13
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:382:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3439:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
```

### Commands

```
     -0:20.9.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
Remote-FTP 0.10.7 
```

**Comment by icetee** [comment]
Duplicate #751
