### ISSUE TITLE
Fail to install Remote-FTP 0.10.7

### ISSUE THREAD

**Issue by lautinghang** [icetee/remote-ftp#781]
Just show this error, although uninstall atom and reinstall it, installation of Remote-FTP 0.10.7 is also show this error. Please check. Thanks a lot.

SyntaxError: Invalid or unexpected token
    at Module._compile (C:\Users\Andy\AppData\Local\atom\app-1.16.0\resources\app.asar\src\native-compile-cache.js:79:40)
    at Object.value [as .js] (C:\Users\Andy\AppData\Local\atom\app-1.16.0\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\Andy\AppData\Local\atom\app-1.16.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Andy\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package.js:796:27)
    at C:\Users\Andy\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package.js:123:28
    at Package.module.exports.Package.measure (C:\Users\Andy\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package.js:96:15)
    at Package.module.exports.Package.load (C:\Users\Andy\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Andy\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package-manager.js:468:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Andy\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package-manager.js:548:30)
    at C:\Users\Andy\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:484:29
    at exit (C:\Users\Andy\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:99:16)
    at triggerExitCallback (C:\Users\Andy\AppData\Local\atom\app-1.16.0\resources\app.asar\src\buffered-process.js:322:11)
    at ChildProcess.<anonymous> (C:\Users\Andy\AppData\Local\atom\app-1.16.0\resources\app.asar\src\buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by icetee** [comment]
I'm not sure this is a bug package. Try up-to-date Atom and Remote-FTP.
