### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir '~/Dropbox/Maksimer/Tasks/002-Simp/live/wp-cont...

### ISSUE THREAD

**Issue by zethzeth** [icetee/remote-ftp#782]
[Enter steps to reproduce:]

1. Connect to remote server
2. Choose folder, right-click it and choose 'Sync local <- remote'
... And then it appears. 
On my local machine, then it creates a _file_ with the name of the folder. Hmm... 

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir '/Users/[USERNAME]/[path]/[to]/[project]/wp-content/plugins/mcb-three-column'

```
At fs.js:951

Error: ENOTDIR: not a directory, scandir '/Users/[USERNAME]/[path]/[to]/[project]/wp-content/plugins/mcb-three-column'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Client.traverseTree (/packages/Remote-FTP/lib/client.js:596:31)
    at /packages/Remote-FTP/lib/client.js:672:18
    at callCompleted (/packages/Remote-FTP/lib/connectors/sftp.js:134:54)
    at oneDirCompleted (/packages/Remote-FTP/lib/connectors/sftp.js:138:25)
    at /packages/Remote-FTP/lib/connectors/sftp.js:202:36
    at Array.forEach (native)
    at /packages/Remote-FTP/lib/connectors/sftp.js:152:12
    at /packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:1583:13
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:382:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3439:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SSH2Stream.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -9:31.4.0 core:confirm (input.hidden-input)
     -8:05.1.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -8:04.8.0 vim-mode-plus:search (input.hidden-input)
     -8:04.4.0 core:paste (input.hidden-input)
     -8:03.9.0 core:confirm (input.hidden-input)
     -8:02.9.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -8:01.9.0 vim-mode-plus:move-down-screen (input.hidden-input)
  2x -7:59.2.0 vim-mode-plus:delete (input.hidden-input)
     -7:58.1.0 vim-mode-plus:move-down-screen (input.hidden-input)
     -7:57.7.0 vim-mode-plus:move-up-screen (input.hidden-input)
  2x -7:57.4.0 vim-mode-plus:delete (input.hidden-input)
     -7:57 vim-mode-plus:move-up-screen (input.hidden-input)
  4x -7:56.9.0 vim-mode-plus:delete (input.hidden-input)
     -7:55 vim-mode-plus:move-up-screen (input.hidden-input)
     -7:54.7.0 core:save (input.hidden-input)
     -0:13.1.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
autoclose-html 0.23.0 
busy-signal 1.4.0 
emmet 2.4.3 
intentions 1.1.2 
language-haml 0.24.1 
linter 2.1.4 
linter-rubocop 2.1.1 
linter-ui-default 1.2.3 
merge-conflicts 1.4.4 
Remote-FTP 0.10.7 
vim-mode-plus 0.91.0 
```

**Comment by icetee** [comment]
Related issue #112
