### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir 'D:/01_Atom-Space\bpa-security\website-work\the...

### ISSUE THREAD

**Issue by gitstray** [icetee/remote-ftp#786]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir 'D:\01_Atom-Space\bpa-security\website-work\themes\HumanRights'

```
At fs.js:951

Error: ENOTDIR: not a directory, scandir 'D:\01_Atom-Space\bpa-security\website-work\themes\HumanRights'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Client.traverseTree (/packages/Remote-FTP/lib/client.js:596:31)
    at /packages/Remote-FTP/lib/client.js:672:18
    at tryApply (/packages/Remote-FTP/lib/connectors/ftp.js:16:14)
    at error (/packages/Remote-FTP/lib/connectors/ftp.js:125:13)
    at /packages/Remote-FTP/lib/connectors/ftp.js:147:33
    at final (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:476:11)
    at Socket.ondone (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:451:7)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -2:57.9.0 remote-ftp:connect (input.hidden-input)
     -2:48.6.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-directory)
     -0:05.5.0 core:paste (input.hidden-input)
     -0:04.3.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.22 
Remote-FTP 0.10.7 
```

**Comment by icetee** [comment]
Related issue #112
