### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open 'D:/01_Atom-Space\ccontrolsys\website-wor...

### ISSUE THREAD

**Issue by gitstray** [icetee/remote-ftp#793]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'D:\01_Atom-Space\ccontrolsys\website-work-(5-11-17)\plugins\pressapps-knowledge-base'

```
At fs.js:640

Error: ENOENT: no such file or directory, open 'D:\01_Atom-Space\ccontrolsys\website-work-(5-11-17)\plugins\pressapps-knowledge-base'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Client.traverseTree (/packages/Remote-FTP/lib/client.js:593:27)
    at /packages/Remote-FTP/lib/client.js:672:18
    at tryApply (/packages/Remote-FTP/lib/connectors/ftp.js:16:14)
    at error (/packages/Remote-FTP/lib/connectors/ftp.js:125:13)
    at /packages/Remote-FTP/lib/connectors/ftp.js:147:33
    at final (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:476:11)
    at Socket.ondone (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:451:7)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -2:59.9.0 application:open-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:22.1.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-beautify 0.29.22 
Remote-FTP 0.10.7 
```

**Comment by icetee** [comment]
Duplicate #751
