### ISSUE TITLE
Uncaught Error: ENOSPC: no space left on device, mkdir '/run/media/florin/Arhiva/Proiecte/firstlo...

### ISSUE THREAD

**Issue by crackerica** [icetee/remote-ftp#807]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: linux 4.9.29-28.lts
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: ENOSPC: no space left on device, mkdir '/run/media/florin/Arhiva/Proiecte/firstlook/home/firstlook/public_html/application/view'

```
At /home/florin/.atom/packages/Remote-FTP/node_modules/mkdirp/index.js:90

Error: ENOSPC: no space left on device, mkdir '/run/media/florin/Arhiva/Proiecte/firstlook/home/firstlook/public_html/application/view'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:77:24)
    at Object.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at /packages/Remote-FTP/lib/connectors/ftp.js:183:18
    at /packages/Remote-FTP/lib/connectors/ftp.js:214:18
    at Object.cb (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:348:5)
    at /packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:106:13)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -0:30.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:28.3.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-clock 0.1.7 
busy-signal 1.4.1 
file-icons 2.1.6 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.5.4 
linter-xo 0.23.0 
pigments 0.39.1 
qolor 0.4.1 
Remote-FTP 0.10.7 
tool-bar 1.1.0 
tool-bar-basic 1.3.0 
```

**Comment by icetee** [comment]
How to replicate this issue?
Do you have free space?

**Comment by tihhanovski** [comment]
I had same error just now. It occurs when you try open file larger than local filesystem can take.
