### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '/Users/Programer/Documents/workspace/schoolware/src/Template/Schooladmin/Users'

### ISSUE THREAD

**Issue by ghost** [icetee/remote-ftp#81]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.6.2
### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir '/Users/Programer/Documents/workspace/schoolware/src/Template/Schooladmin/Users'

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:76

Error: EEXIST: file already exists, mkdir '/Users/Programer/Documents/workspace/schoolware/src/Template/Schooladmin/Users'
  at Error (native)
  at Object.fs.mkdirSync (fs.js:791:18)
  at Function.sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:55:12)
  at Object.fsPlus.makeTreeSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:304:23)
  at /Users/Programer/Dropbox/.atom/packages/Remote-FTP/lib/connectors/sftp.js:195:9
  at SFTPStream._transform (/Users/Programer/Dropbox/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:435:15)
  at SFTPStream.Transform._read [as __read] (_stream_transform.js:167:10)
  at SFTPStream._read (/Users/Programer/Dropbox/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:160:15)
  at SFTPStream.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at SFTPStream.Writable.write (_stream_writable.js:210:11)
  at Channel.ondata (_stream_readable.js:524:20)
  at emitOne (events.js:77:13)
  at Channel.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Channel.Readable.push (_stream_readable.js:109:10)
  at SSH2Stream.<anonymous> (/Users/Programer/Dropbox/.atom/packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:140:15)
  at emitOne (events.js:77:13)
  at SSH2Stream.emit (events.js:166:7)
  at parsePacket (/Users/Programer/Dropbox/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3107:10)
  at SSH2Stream._transform (/Users/Programer/Dropbox/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:555:13)
  at SSH2Stream.Transform._read [as __read] (_stream_transform.js:167:10)
  at SSH2Stream._read (/Users/Programer/Dropbox/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:213:15)
  at SSH2Stream.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at SSH2Stream.Writable.write (_stream_writable.js:210:11)
  at Socket.ondata (_stream_readable.js:524:20)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at TCP.onread (net.js:517:20)

```
### Commands

```
     -4:17.4.0 docblockr:parse-enter (atom-text-editor.editor)
     -4:17.4.0 editor:newline (atom-text-editor.editor)
     -3:11 core:undo (atom-text-editor.editor)
 16x -2:07.3.0 core:confirm (atom-text-editor.editor.mini)
     -0:16.2.0 remote-ftp:disconnect (ul.progress.tool-panel.panel-top)
     -0:12.3.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-light-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "project-manager"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.6.2
autocomplete-html, v0.5.0
autocomplete-plus, v2.12.0
docblockr, v0.6.3
file-icons, v1.5.4
icon-font-picker, v0.0.1
language-sql-mysql, v0.3.1
linter, v0.12.1
linter-php, v0.0.12
minimap, v4.7.6
minimap-bookmarks, v0.1.0
minimap-color-highlight, v4.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.1
minimap-selection, v4.2.0

# Dev
No dev packages
```

**Comment by grenierdev** [comment]
Fixed in commit 1625496e73186223eb2093478fb87975bd9fbdff and 9f8d00017a38b86b828c4f612e2e9459efd2c702
