### ISSUE TITLE
Uncaught TypeError: editor.getPath is not a function

### ISSUE THREAD

**Issue by mamamamaY** [icetee/remote-ftp#810]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.1 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught TypeError: editor.getPath is not a function

```
At C:\Users\xxxxxxx\.atom\packages\Remote-FTP\lib\menus\commands.js:462

TypeError: editor.getPath is not a function
    at /packages/Remote-FTP/lib/menus/commands.js:462:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.1/resources/app/src/command-registry.js:265:1)
    at ~/AppData/Local/atom/app-1.17.1/resources/app/src/command-registry.js:3:1
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.17.1/resources/app/node_modules/command-palette/lib/command-palette-view.js:106:1)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.17.1/resources/app/node_modules/atom-select-list/src/select-list-view.js:313:1)
    at HTMLDivElement.core:confirm (~/AppData/Local/atom/app-1.17.1/resources/app/node_modules/atom-select-list/src/select-list-view.js:81:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.1/resources/app/src/command-registry.js:265:1)
    at ~/AppData/Local/atom/app-1.17.1/resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.17.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.17.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.17.1/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.17.1/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -3:43.4.0 find-and-replace:show (input.hidden-input)
     -3:43.1.0 core:paste (input.hidden-input)
     -3:41.8.0 core:confirm (input.hidden-input)
     -3:30.9.0 application:add-project-folder (span.name.icon.icon-file-text)
     -3:23.5.0 tree-view:open-selected-entry-up (span.name.icon.icon-file-text)
     -2:54.9.0 remote-ftp:refresh-selected (span.name.icon.icon-file-text)
     -2:43.6.0 command-palette:toggle (div.tool-panel.tree-view)
     -2:33.9.0 core:move-down (input.hidden-input)
     -2:25.8.0 command-palette:toggle (div.tool-panel.tree-view)
     -2:21.6.0 core:move-down (input.hidden-input)
     -2:19.8.0 core:confirm (input.hidden-input)
     -2:19.8.0 remote-ftp:upload-selected (div.tool-panel.tree-view)
     -2:10.7.0 command-palette:toggle (div.tool-panel.tree-view)
     -2:08.4.0 core:confirm (input.hidden-input)
     -2:08.4.0 remote-ftp:upload-active (div.tool-panel.tree-view)
     -2:07.3.0 core:move-down (div.tool-panel.tree-view)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
busy-signal 1.4.1 
chary-tree-view 0.2.13 
color-picker 2.2.5 
custom-title 1.0.1 
git-control 0.9.0 
git-history 3.3.0 
git-plus 7.9.2 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.6.0 
live-archive 0.1.15 
minimap 4.28.2 
pigments 0.39.1 
project-manager 3.3.4 
Remote-FTP 0.10.7 
save-session 0.15.7 
smart-tab-name 1.0.5 
split-diff 1.4.0 
tree-view-copy-relative-path 1.2.0 
vim-mode 0.66.0 
```

**Comment by radarsu** [comment]
Same problem when using ctrl+shift+p, then Remote Ftp: Upload Active option.
