### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir

### ISSUE THREAD

**Issue by boy672820** [icetee/remote-ftp#811]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.1 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 

```
At C:\Users\ESJ\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir
    at Error (native)
    at fs.mkdirSync (fs.js:922:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:665:16)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
    at Object.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at /packages/Remote-FTP/lib/connectors/ftp.js:401:14
    at Object.cb (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:1017:13)
    at /packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:106:13)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
  2x -0:48.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:35.5.0 remote-ftp:toggle (atom-pane.pane.active)
     -0:25.6.0 remote-ftp:delete-selected (div.header.list-item)
     -0:22.2.0 remote-ftp:add-folder (span.name.icon.icon-file-directory)
     -0:21 core:confirm (input.hidden-input)
     -0:17.5.0 remote-ftp:add-file (span.name.icon.default-icon)
 13x -0:15.7.0 core:backspace (input.hidden-input)
     -0:13.7.0 core:confirm (input.hidden-input)
     -0:09.0 remote-ftp:refresh-selected (span.name.icon.default-icon)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-runner 2.7.1 
busy-signal 1.4.0 
emmet 2.4.3 
file-icons 2.0.15 
highlight-selected 0.12.0 
intentions 1.1.2 
language-asp 1.0.0 
language-ejs 0.4.0 
linter 2.1.4 
linter-csslint 1.3.4 
linter-eslint 8.1.6 
linter-htmlhint 1.3.3 
linter-jshint 3.0.3 
linter-php 1.3.2 
linter-ui-default 1.2.3 
markdown-preview-plus 2.4.9 
node-debugger 1.10.1 
php-cs-fixer 4.1.0 
react 0.16.2 
Remote-FTP 0.10.7 
```

**Comment by marvinpoo** [comment]
This can be solved by deleting/moving the file from your computer and re-opening Atom & the file on the server.

I had the same problem at https://github.com/mgrenier/remote-ftp/issues/827 Issue

**Comment by icetee** [comment]
Related #112
