### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Desktop\ubuntu\node_modules\.bin\babel'

### ISSUE THREAD

**Issue by JJH2** [icetee/remote-ftp#818]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\hoon\Desktop\ubuntu\node_modules\.bin\babel'

```
At C:\Users\hoon\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\hoon\Desktop\ubuntu\node_modules\.bin\babel'
    at Error (native)
    at fs.mkdirSync (fs.js:922:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:665:16)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
    at Object.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at /packages/Remote-FTP/lib/connectors/ftp.js:183:18
    at /packages/Remote-FTP/lib/connectors/ftp.js:214:18
    at Object.cb (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:348:5)
    at /packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:106:13)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -1:32.5.0 core:save (input.hidden-input)
     -1:16.8.0 core:backspace (input.hidden-input)
     -1:14.8.0 core:move-down (input.hidden-input)
  2x -1:14.6.0 core:move-left (input.hidden-input)
     -1:14.3.0 core:move-down (input.hidden-input)
  9x -1:14.3.0 core:move-left (input.hidden-input)
  2x -1:12.3.0 core:backspace (input.hidden-input)
     -1:11 core:undo (input.hidden-input)
     -1:10.5.0 core:move-down (input.hidden-input)
  3x -1:10 core:move-right (input.hidden-input)
  4x -1:09.0 core:backspace (input.hidden-input)
     -1:06.4.0 core:move-down (input.hidden-input)
     -1:06.3.0 core:move-right (input.hidden-input)
  4x -1:05.8.0 core:backspace (input.hidden-input)
     -0:51.8.0 core:save (input.hidden-input)
     -0:46.2.0 remote-ftp:sync-with-remote (div.header.list-item)
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
atom-material-ui 1.3.10 
emmet 2.4.3 
file-icons 2.1.3 
fonts 2.0.0 
highlight-selected 0.13.1 
indent-guide-improved 1.4.12 
minimap 4.27.1 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
nuance-dark-syntax 0.2.0 
nuance-dark-ui 0.27.0 
open-in-browser 0.5.0 
Remote-FTP 0.10.7 
```

**Comment by marvinpoo** [comment]
This can be solved by deleting/moving the file from your computer and re-opening Atom & the file on the server.

I had the same problem at #827 Issue

**Comment by icetee** [comment]
Related issue #112
