### ISSUE TITLE
Sync remote -> Local doesn't work

### ISSUE THREAD

**Issue by schuelli238** [icetee/remote-ftp#821]
Atom @ Windows newest version
remote-ftp 0.10.17

Issues:
**Command: sync local <- remote** on Project Folder
New folders on remote are not synced to local

**Command: sync local <- remote** on one of the new folders i get the following error
and a local file with the name of the folder was created

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: LAPTOP-UTTVET31
**Thrown From**: [remote-ftp](https://github.com/mgrenier/remote-ftp) package undefined

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir 'C:\htdocs\prv_Trailrun_Anmeldung\test'

```
At fs.js:951

Error: ENOTDIR: not a directory, scandir 'C:\htdocs\prv_Trailrun_Anmeldung\test'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Client.traverseTree (/packages/remote-ftp/lib/client.js:596:31)
    at /packages/remote-ftp/lib/client.js:672:18
    at callCompleted (/packages/remote-ftp/lib/connectors/sftp.js:134:54)
    at oneDirCompleted (/packages/remote-ftp/lib/connectors/sftp.js:138:25)
    at /packages/remote-ftp/lib/connectors/sftp.js:202:36
    at Array.forEach (native)
    at /packages/remote-ftp/lib/connectors/sftp.js:152:12
    at /packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:1583:13
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:382:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3439:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SSH2Stream.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -8:47.3.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-directory)
     -8:23.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -8:00.7.0 tree-view:add-folder (li.file.entry.list-item.selected)
     -7:56.2.0 core:confirm (input.hidden-input)
  2x -7:17.2.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-directory)
     -3:33.1.0 remote-ftp:add-folder (span.name.icon.icon-file-directory)
     -3:31.3.0 core:confirm (input.hidden-input)
     -3:27.4.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-directory)
     -1:02.6.0 remote-ftp:download-selected (span.name.icon.icon-file-directory)
     -0:54.4.0 tree-view:remove (span.name.icon.icon-file-directory)
     -0:50.4.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -0:43.6.0 core:backspace (input.hidden-input)
     -0:43.2.0 core:confirm (input.hidden-input)
     -0:39.6.0 remote-ftp:download-selected (span.name.icon.icon-file-directory)
     -0:30.3.0 tree-view:remove (span.name.icon.icon-file-directory)
     -0:26.2.0 remote-ftp:sync-with-remote (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
autoclose-html 0.23.0 
busy-signal 1.4.1 
hyperclick 0.0.40 
hyperclick-php 0.2.1 
intentions 1.1.2 
less-than-slash 0.16.0 
linter 2.1.4 
linter-php 1.3.2 
linter-ui-default 1.6.0 
php-cs-fixer 4.1.0 
Remote-FTP 0.10.7 
```

**Comment by jbelien** [comment]
Same issue here !
When I try to `Sync local <- remote` on a folder, it creates a file and fails.

`fs.js:951`

```
Error: ENOTDIR: not a directory, scandir 'C:\Users\jbe\Atom\Ansible\.git'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Client.traverseTree (file:///C:/Users/jbe/.atom/packages/remote-ftp/lib/client.js:596:31)
    at file:///C:/Users/jbe/.atom/packages/remote-ftp/lib/client.js:672:18
    at callCompleted (file:///C:/Users/jbe/.atom/packages/remote-ftp/lib/connectors/sftp.js:134:54)
    at file:///C:/Users/jbe/.atom/packages/remote-ftp/lib/connectors/sftp.js:150:37
    at C:\Users\jbe\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\sftp.js:1583:13
    at SFTPStream._transform (C:\Users\jbe\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\sftp.js:382:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (C:\Users\jbe\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at SSH2Stream.<anonymous> (C:\Users\jbe\.atom\packages\Remote-FTP\node_modules\ssh2\lib\Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (C:\Users\jbe\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\ssh.js:3439:10)
    at SSH2Stream._transform (C:\Users\jbe\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (C:\Users\jbe\.atom\packages\Remote-FTP\node_modules\ssh2-streams\lib\ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SSH2Stream.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

**Comment by icetee** [comment]
Related issue #112
