### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir 'C:/0-DEV\php\marvli\user\pages\99.job\_cleared'

### ISSUE THREAD

**Issue by marvinpoo** [icetee/remote-ftp#827]
[Enter steps to reproduce:]

1. connecting to FTP-Server
2. trailing down the file
3. opening file
4. get's error

**Atom**: 1.17.2 ia32
**Electron**: 1.3.15
**OS**: YCARUS-PC
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\0-DEV\php\marvli\user\pages\99.job\_cleared'

```
At C:\Users\ycarus\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\0-DEV\php\marvli\user\pages\99.job\_cleared'
    at Error (native)
    at fs.mkdirSync (fs.js:922:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:665:16)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
    at Object.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at /packages/Remote-FTP/lib/connectors/ftp.js:183:18
    at /packages/Remote-FTP/lib/connectors/ftp.js:214:18
    at Object.cb (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:348:5)
    at /packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:106:13)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -0:17.9.0 remote-ftp:delete-selected (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
busy-signal 1.4.1 
file-type-icons 1.3.4 
highlight-line 0.12.0 
intentions 1.1.2 
linter 2.1.4 
linter-csslint 1.3.4 
linter-ui-default 1.5.4 
monokai 0.24.0 
moonbeam-syntax 0.8.1 
language-twig 1.6.3 
Remote-FTP 0.10.7 
seti-ui 1.8.0 
webbox-color 0.5.9 
```

**Comment by marvinpoo** [comment]
Could be solved by deleting the file on the computer and re-open Atom and the file.
Can be closed.
