### ISSUE TITLE
Uncaught TypeError: q.drain is not a function

### ISSUE THREAD

**Issue by ganeshgore** [icetee/remote-ftp#831]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0-beta3 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Education
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 0.10.7

### Stack Trace

Uncaught TypeError: q.drain is not a function

```
At C:\Users\Ganesh\.atom\packages\Remote-FTP\node_modules\async\lib\async.js:909

TypeError: q.drain is not a function
    at /packages/Remote-FTP/node_modules/async/lib/async.js:909:23
    at /packages/Remote-FTP/node_modules/async/lib/async.js:44:16
    at /packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:438:24
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -4:52.2.0 remote-sync:upload-folder (div.header.list-item)
     -4:40.6.0 core:confirm (input.hidden-input)
     -2:25.6.0 remote-sync:upload-folder (div.header.list-item)
     -2:21.9.0 intentions:highlight (input.hidden-input)
     -2:21.7.0 go-to-line:toggle (input.hidden-input)
     -2:20.5.0 core:confirm (input.hidden-input)
     -2:15.2.0 core:copy (span.syntax--punctuation.syntax--definition.syntax--arguments.syntax--begin.syntax--bracket.syntax--round.syntax--js)
```

### Non-Core Packages

```
animated-page-scroll 1.0.1 
atom-beautify 0.29.24 
atom-bootstrap3 1.2.12 
atom-django 0.3.2 
atom-python-run 0.7.3 
atom-touch-events 0.23.0 
atom-wrap-in-tag 0.6.0 
auto-fold 0.4.0 
autoclose-html 0.23.0 
autocomplete-python 1.8.63 
busy-signal 1.4.1 
highlight-selected 0.13.1 
indent-guide-improved 1.4.12 
intentions 1.1.2 
language-docker 1.1.7 
last-cursor-position 0.9.2 
less-autocompile 1.0.0 
linter 2.1.4 
linter-docker 0.2.0 
linter-gcc 0.7.1 
linter-jshint 3.1.1 
linter-pep8 1.3.2 
linter-pycodestyle 2.0.2 
linter-pylama 0.8.19 
linter-python-pep8 0.2.0 
linter-ui-default 1.2.4 
merge-conflicts 1.4.4 
minimap 4.28.2 
minimap-git-diff 4.3.1 
monokai 0.24.0 
python-autopep8 0.1.3 
python-debugger 0.2.0 
python-indent 1.0.2 
python-tools 0.6.9 
Remote-FTP 0.10.7 
remote-sync 4.1.4 
revert-buffer 0.5.0 
sequential-number 0.5.0 
simple-drag-drop-text 0.3.4 
svg-preview 0.11.0 
sync-settings 0.8.1 
todo-show 1.11.0 
unsaved-changes 0.1.0 
```

**Comment by icetee** [comment]
Hi @ganeshgore!

Please check 1.19.0-beta and update Remote-FTP 1.0.0.
