### ISSUE TITLE
Uncaught TypeError: atom.workspace.getActivePaneItem(...).getFileName is not a function

### ISSUE THREAD

**Issue by eNdiD** [icetee/remote-ftp#840]
[Enter steps to reproduce:]

1. The issue happens only if autosave is enabled. (which save file on focus bluring, or closing). It can be enabled in Preferences - Packeges - search for "autosave" - check "enabled"
2. Open any file
3. Make some changes
4. Open the Preferences pane by hotkey
5. And get the issue

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 17.04
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 1.0.0

### Stack Trace

Uncaught TypeError: atom.workspace.getActivePaneItem(...).getFileName is not a function

```
At /usr/share/atom/resources/app/src/pane.js:1095

TypeError: atom.workspace.getActivePaneItem(...).getFileName is not a function
    at Main.fileSaved (/packages/Remote-FTP/lib/remote-ftp.js:111:62)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1142:33)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:25)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app/src/text-editor.js:925:32)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app/src/pane.js:780:24)
    at Pane.saveItem (/usr/share/atom/resources/app/src/pane.js:3:65)
    at Object.autosavePaneItem (/usr/share/atom/resources/app/node_modules/autosave/lib/autosave.js:78:27)
    at /usr/share/atom/resources/app/node_modules/autosave/lib/autosave.js:40:32
    at atom-text-editor.TextEditorElement.inputNodeBlurred (/usr/share/atom/resources/app/src/text-editor-element.js:244:21)
    at atom-pane.PaneElement.activeItemChanged (/usr/share/atom/resources/app/src/pane-element.js:158:25)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app/src/pane.js:316:28)
    at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:471:27)
    at Workspace.<anonymous> (/usr/share/atom/resources/app/src/workspace.js:1161:20)
    at next (<anonymous>)
    at step (/usr/share/atom/resources/app/src/workspace.js:11:279)
```

### Commands

```
     -0:48.3.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -0:47.9.0 core:paste (input.hidden-input)
     -0:46.2.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:46.2.0 editor:newline (input.hidden-input)
  3x -0:45.6.0 core:backspace (input.hidden-input)
     -0:44.2.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:44.2.0 editor:newline (input.hidden-input)
     -0:36.6.0 core:backspace (input.hidden-input)
     -0:33.5.0 core:cut (input.hidden-input)
     -0:31.8.0 core:paste (input.hidden-input)
  2x -0:25.6.0 core:backspace (input.hidden-input)
     -0:25 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -0:24.8.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:20 core:paste (input.hidden-input)
  6x -0:18.3.0 core:backspace (input.hidden-input)
     -0:11.6.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
caniuse 0.9.2 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.7 
language-babel 2.66.0 
Remote-FTP 1.0.0 
Stylus 3.1.1 
```

**Comment by icetee** [comment]
I've reproduce, fix will be coming soon.
Thanks for steps!

Related [#837](https://github.com/mgrenier/remote-ftp/issues/837#issuecomment-309229588) comment.

**Comment by AlexNodex** [comment]
I had this error.

The package bindings needed rebuilding.

There was a little red bug on the bottom status bar, I clicked it and it asked me to rebuild them, I clicked Yes, it did its thing, atom restarted, job done.

**Comment by icetee** [comment]
> I had this error.
> 
> The package bindings needed rebuilding.
> 
> There was a little red bug on the bottom status bar, I clicked it and it asked me to rebuild them, I clicked Yes, it did its thing, atom restarted, job done.

I think is different issue. You write issue: #839
