### ISSUE TITLE
Uncaught Error: Unable to build data connection: Operation not permitted in events.js:160 

### ISSUE THREAD

**Issue by StefanBoettcherASMB** [icetee/remote-ftp#843]
Uncaught Error: Unable to build data connection: Operation not permitted
```
events.js:160
Hide Stack Trace
Error: Unable to build data connection: Operation not permitted
    at makeError (/Users/sboettc1/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:1067:13)
    at Parser.<anonymous> (/Users/sboettc1/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:113:25)
    at emitTwo (events.js:106:13)
    at Parser.emit (events.js:191:7)
    at Parser._write (/Users/sboettc1/.atom/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at TLSSocket.ondata (/Users/sboettc1/.atom/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:543:20)
```

**Comment by icetee** [comment]
Hi, you try IPv6?
Maybe related #949
