### ISSUE TITLE
Uncaught Error: Remote FTP: getConfigPath returned false, but expected a string

### ISSUE THREAD

**Issue by grayko** [icetee/remote-ftp#850]
**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 1.0.0

### Stack Trace

Uncaught Error: Remote FTP: getConfigPath returned false, but expected a string

```
At C:\Users\OEM\.atom\packages\Remote-FTP\lib\client.js:122

Error: Remote FTP: getConfigPath returned false, but expected a string
    at Client.readConfig (/packages/remote-ftp/lib/client.js:122:47)
    at /packages/remote-ftp/lib/views/tree-view.js:212:30)
    at HTMLDivElement.dispatch (/packages/atom-html-preview/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/atom-html-preview/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -3:50.6.0 remote-ftp:toggle (div.recent-projects-view.pane-item)
     -0:11.2.0 remote-ftp:create-ftp-config (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-bootstrap3 1.2.12 
atom-bootstrap4 1.4.0 
atom-commander 0.9.0 
atom-css-clean 2.20.5 
atom-html-preview 0.1.22 
atom-sync 0.7.3 
autoclose-html 0.23.0 
autocomplete-modules 1.6.10 
brackets 0.5.0 
color-picker 2.2.5 
css-snippets 1.1.0 
css-spy 0.6.0 
csscomb 0.3.1 
emmet 2.4.3 
expose 0.14.0 
file-icons 2.1.7 
find-and-replace-under-cursor 0.3.0 
ftp-remote-edit 0.11.7 
highlight-selected 0.13.1 
html-to-css 0.2.2 
htmlhint 1.1.4 
keybinding-mode 0.1.3 
language-markdown 0.23.0 
merge-conflicts 1.4.5 
minimap 4.28.2 
package-sync 1.1.0 
php-twig 4.0.0 
pigments 0.39.1 
project-manager 3.3.5 
recent-projects 0.13.1 
remote-atom 1.3.10 
Remote-FTP 1.0.0 
remote-sync 4.1.5 
todo-show 1.11.0 
zentabs 0.8.8 
```

**Comment by icetee** [comment]
Related #621
