### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remote' of null

### ISSUE THREAD

**Issue by ghost** [icetee/remote-ftp#854]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'remote' of null

```
At C:\Users\Admin\.atom\packages\Remote-FTP\lib\client.js:471

TypeError: Cannot read property 'remote' of null
    at Client.toRemote (/packages/remote-ftp/lib/client.js:471:18)
    at /packages/remote-ftp/lib/menus/commands.js:550:33
    at Array.forEach (native)
    at /packages/remote-ftp/lib/menus/commands.js:547:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -3:38.2.0 core:save (input.hidden-input)
     -3:11.9.0 core:copy (input.hidden-input)
     -3:11.1.0 core:paste (input.hidden-input)
     -3:10 core:backspace (input.hidden-input)
     -3:09.7.0 core:save (input.hidden-input)
     -2:48.8.0 settings-view:uninstall-packages (input.hidden-input)
     -2:05.9.0 core:backspace (input.hidden-input)
  3x -2:05.1.0 core:save (input.hidden-input)
     -1:34.8.0 core:copy (input.hidden-input)
     -1:32.7.0 core:paste (input.hidden-input)
  3x -1:32.4.0 core:save (input.hidden-input)
     -1:25.7.0 core:undo (input.hidden-input)
     -1:20.7.0 tree-view:remove (span.name.icon.database-icon.medium-yellow)
     -1:10.8.0 settings-view:uninstall-packages (input.hidden-input)
  2x -0:59.2.0 core:confirm (input.hidden-input)
     -0:06.7.0 remote-ftp:sync-with-local (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
file-icons 2.1.7 
indent-guide-improved 1.4.12 
pigments 0.39.1 
Remote-FTP 1.0.0 
```

**Comment by zackzhangkai** [comment]
i have the same issue

**Comment by icetee** [comment]
Does the latest version also have a bug?

**Comment by zackzhangkai** [comment]
sometimes

**Comment by webhacking** [comment]
I got same problems

**Comment by webhacking** [comment]
From latest version

**Comment by srivatsshankar** [comment]
So I realise that this problem arises for some people when they update Remote-FTP. Some old configuration files, which may have worked earlier are no longer supported.

Just try to change the configuration file in order to include options, which may otherwise seem useless. Also, remember to remove the "," at the end of the `.ftpconfig`

The configuration that worked for me
```
{
    "protocol": "sftp",
    "host": "example.com",
    "port": 22,
    "user": "root",
    "pass": "",
    "remote": "/",
    "agent": "pageant",
    "privatekey": "",
    "passphrase": "",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000,
    "promptForPass": false,
    "keyboardInteractive": false,
    "keyboardInteractiveForPass": false,
    "watchTimeout":500
}
```

Edit: This of course addressed the error for me. If this works for anyone else, we can close this issue
