### ISSUE TITLE
Uncaught Error: Remote FTP: getConfigPath returned false, but expected a string

### ISSUE THREAD

**Issue by grantand** [icetee/remote-ftp#863]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Enterprise 2016 LTSB
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 1.0.0

### Stack Trace

Uncaught Error: Remote FTP: getConfigPath returned false, but expected a string

```
At C:\Users\User\.atom\packages\Remote-FTP\lib\client.js:122

Error: Remote FTP: getConfigPath returned false, but expected a string
    at Client.readConfig (/packages/remote-ftp/lib/client.js:122:47)
    at /packages/remote-ftp/lib/views/tree-view.js:212:30)
    at HTMLDivElement.dispatch (/packages/sass-autocompile/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/sass-autocompile/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:36.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:26.4.0 application:open-folder (atom-pane.pane)
     -0:23.7.0 remote-ftp:toggle (atom-pane.pane)
```

### Non-Core Packages

```
atom-html-templates 0.1.3 
autoprefixer 3.7.1 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.8 
less-autocompile 1.0.0 
livereload 0.4.4 
remote-edit 1.9.0 
Remote-FTP 1.0.0 
remote-sync 4.1.5 
sass-autocompile 0.13.3 
split-diff 1.4.3 
```

**Comment by icetee** [comment]
Related #621
