### ISSUE TITLE
Uncaught Error: Remote FTP: getConfigPath returned false, but expected a string

### ISSUE THREAD

**Issue by doing27** [icetee/remote-ftp#865]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 1.0.0

### Stack Trace

Uncaught Error: Remote FTP: getConfigPath returned false, but expected a string

```
At C:\Users\user\.atom\packages\Remote-FTP\lib\client.js:122

Error: Remote FTP: getConfigPath returned false, but expected a string
    at Client.readConfig (/packages/remote-ftp/lib/client.js:122:47)
    at /packages/remote-ftp/lib/views/tree-view.js:212:30)
    at HTMLDivElement.dispatch (/packages/Remote-FTP/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/Remote-FTP/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:43.5.0 remote-ftp:connect (input.hidden-input)
     -0:36 remote-ftp:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
autoclose-html 0.23.0 
busy-signal 1.4.3 
code-peek 1.4.20 
emmet 2.4.3 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.2.0 
linter-ui-default 1.6.2 
minimap 4.28.2 
minimap-cursorline 0.2.0 
pigments 0.39.1 
Remote-FTP 1.0.0 
sort-lines 0.14.0 
```

**Comment by icetee** [comment]
Related #621
