### ISSUE TITLE
Uncaught Error: Remote FTP: getConfigPath returned false, but expected a string

### ISSUE THREAD

**Issue by grantand** [icetee/remote-ftp#866]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Enterprise 2016 LTSB
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 1.0.0

### Stack Trace

Uncaught Error: Remote FTP: getConfigPath returned false, but expected a string

```
At C:\Users\User\.atom\packages\Remote-FTP\lib\client.js:122

Error: Remote FTP: getConfigPath returned false, but expected a string
    at Client.readConfig (/packages/remote-ftp/lib/client.js:122:47)
    at /packages/remote-ftp/lib/menus/commands.js:140:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1314:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:43.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:08.8.0 remote-ftp:connect (input.hidden-input)
```

### Non-Core Packages

```
atom-html-templates 0.1.3 
autoprefixer 3.7.1 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.8 
less-autocompile 1.0.0 
livereload 0.4.4 
remote-edit 1.9.0 
Remote-FTP 1.0.0 
remote-sync 4.1.5 
sass-autocompile 0.13.3 
split-diff 1.4.3 
```

**Comment by icetee** [comment]
Related #621
