### ISSUE TITLE
Uncaught TypeError: atom.workspace.getActivePaneItem(...).getFileName is not a function

### ISSUE THREAD

**Issue by fit-or27** [icetee/remote-ftp#868]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 1.0.0

### Stack Trace

Uncaught TypeError: atom.workspace.getActivePaneItem(...).getFileName is not a function

```
At /usr/share/atom/resources/app/src/pane.js:1095

TypeError: atom.workspace.getActivePaneItem(...).getFileName is not a function
    at Main.fileSaved (/packages/Remote-FTP/lib/remote-ftp.js:111:62)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1142:33)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:25)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app/src/text-editor.js:925:32)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app/src/pane.js:780:24)
    at Pane.saveItem (/usr/share/atom/resources/app/src/pane.js:3:65)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app/src/pane.js:763:25)
    at Workspace.saveActivePaneItem (/usr/share/atom/resources/app/src/workspace.js:1548:46)
    at atom-workspace.core:save (/usr/share/atom/resources/app/src/register-default-commands.js:236:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at /usr/share/atom/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -9:19.5.0 core:move-down (div.tool-panel.tree-view)
  2x -8:48.2.0 core:save (input.hidden-input)
     -6:18 core:copy (span.syntax--text.syntax--plain.syntax--null-grammar)
     -5:22.4.0 remote-ftp:disconnect (div.tool-panel.tree-view)
     -5:10.2.0 tree-view:remove (span.name.icon.icon-file-text)
  3x -4:57.4.0 remote-ftp:toggle (div.offline)
     -4:37.6.0 remote-ftp:create-ftp-config (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:58.7.0 core:paste (input.hidden-input)
     -0:57.2.0 core:save (input.hidden-input)
     -0:54.8.0 remote-ftp:connect (input.hidden-input)
     -0:26.2.0 core:paste (input.hidden-input)
     -0:23.6.0 core:save (input.hidden-input)
     -0:21.6.0 remote-ftp:connect (input.hidden-input)
     -0:15.5.0 remote-ftp:toggle (input.hidden-input)
     -0:06.7.0 core:save (div.tool-panel.tree-view)
```

### Non-Core Packages

```
Remote-FTP 1.0.0 
```

**Comment by icetee** [comment]
Related #840. Please wait for new version or check this commit [2de3389](https://github.com/icetee/remote-ftp/commit/2de3389be2f4dd3d0cf25fe2cdae4375976f1b17)
