### ISSUE TITLE
Uncaught TypeError: atom.workspace.getActivePaneItem(...).getFileName is not a function

### ISSUE THREAD

**Issue by sorokin-vladimir** [icetee/remote-ftp#869]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 1.0.0

### Stack Trace

Uncaught TypeError: atom.workspace.getActivePaneItem(...).getFileName is not a function

```
At /usr/share/atom/resources/app/src/pane.js:1095

TypeError: atom.workspace.getActivePaneItem(...).getFileName is not a function
    at Main.fileSaved (/packages/Remote-FTP/lib/remote-ftp.js:111:62)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1142:33)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:25)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app/src/text-editor.js:925:32)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app/src/pane.js:780:24)
    at Pane.saveItem (/usr/share/atom/resources/app/src/pane.js:3:65)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app/src/pane.js:763:25)
    at Workspace.saveActivePaneItem (/usr/share/atom/resources/app/src/workspace.js:1548:46)
    at atom-workspace.core:save (/usr/share/atom/resources/app/src/register-default-commands.js:236:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at /usr/share/atom/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -2:11.7.0 core:save (input.hidden-input)
     -2:04.8.0 intentions:highlight (input.hidden-input)
  9x -2:04.1.0 core:undo (input.hidden-input)
     -1:59.8.0 core:save (input.hidden-input)
     -1:41.5.0 intentions:highlight (input.hidden-input)
     -1:41.1.0 core:copy (input.hidden-input)
     -1:40.5.0 intentions:highlight (input.hidden-input)
     -1:40 project-find:show (input.hidden-input)
     -1:38.5.0 core:move-right (input.hidden-input)
     -1:38.2.0 core:backspace (input.hidden-input)
     -1:37.9.0 core:confirm (input.hidden-input)
     -1:13.6.0 intentions:highlight (input.hidden-input)
     -1:13.4.0 core:save (input.hidden-input)
     -1:06.8.0 editor:consolidate-selections (input.hidden-input)
     -1:06.8.0 core:cancel (input.hidden-input)
     -0:37.4.0 core:save (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-beautify 0.30.1 
atom-material-syntax 1.0.6 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.7 
git-log 0.4.1 
git-plus 7.9.3 
highlight-selected 0.13.1 
intentions 1.1.2 
language-babel 2.66.0 
linter 2.2.0 
linter-jshint 3.1.2 
linter-ui-default 1.6.1 
merge-conflicts 1.4.5 
minimap 4.28.2 
Remote-FTP 1.0.0 
todo-show 1.11.0 
```

**Comment by icetee** [comment]
Related #840. Please wait for new version or check this commit [2de3389](https://github.com/icetee/remote-ftp/commit/2de3389be2f4dd3d0cf25fe2cdae4375976f1b17)
