### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Documents\_EXOOP\plugins'

### ISSUE THREAD

**Issue by KingCreeperDJ** [icetee/remote-ftp#870]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 1.0.0

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\123ki\Documents\_EXOOP\plugins'

```
At C:\Users\123ki\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\123ki\Documents\_EXOOP\plugins'
    at Error (native)
    at fs.mkdirSync (fs.js:922:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:665:16)
    at sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:77:24)
    at Object.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at /packages/Remote-FTP/lib/connectors/ftp.js:183:18
    at /packages/Remote-FTP/lib/connectors/ftp.js:214:18
    at Object.cb (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:348:5)
    at /packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:106:13)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.12 
cssbeautify 1.3.0 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
open-in-browser 0.5.2 
Remote-FTP 1.0.0 
sync-settings 0.8.2 
```

**Comment by icetee** [comment]
Duplicate #112
