### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remote' of null

### ISSUE THREAD

**Issue by rajat-rs** [icetee/remote-ftp#873]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.10
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'remote' of null

```
At /home/opencubicles-4/.atom/packages/Remote-FTP/lib/client.js:471

TypeError: Cannot read property 'remote' of null
    at Client.toRemote (/packages/Remote-FTP/lib/client.js:471:18)
    at /packages/Remote-FTP/lib/menus/commands.js:550:33
    at Array.forEach (native)
    at /packages/Remote-FTP/lib/menus/commands.js:547:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:08.6.0 remote-ftp:sync-with-local (span.name.icon.icon-repo)
```

### Non-Core Packages

```
Remote-FTP 1.0.0 
```

**Comment by icetee** [comment]
Duplicate #854
