### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Desktop\WORK\world star\themes\main'

### ISSUE THREAD

**Issue by windysmile** [icetee/remote-ftp#878]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.1.0

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\admin\Desktop\WORK\world star\themes\main'

```
At C:\Users\admin\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\admin\Desktop\WORK\world star\themes\main'
    at Error (native)
    at fs.mkdirSync (fs.js:922:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:665:16)
    at sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
    at sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:77:24)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:77:24)
    at Object.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at /packages/remote-ftp/lib/connectors/ftp.js:176:18
    at /packages/remote-ftp/lib/connectors/ftp.js:207:18
    at Object.cb (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:348:5)
    at /packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:111:20)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-beautify 0.29.17 
color-picker 2.2.5 
git-plus 7.8.0 
material-monokai-syntax 1.0.1 
Remote-FTP 1.1.0 
script 3.14.1 
```

**Comment by icetee** [comment]
Related #112
