### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir 'Z:\home\site\www\thediewi.bget.ru\public_html\info\index.html'

### ISSUE THREAD

**Issue by diex01** [icetee/remote-ftp#89]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.196.0
**System**: Unknown Windows Version
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.6.2
### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'Z:\home\site\www\thediewi.bget.ru\public_html\info\index.html'

```
At C:\Users\Irina\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:76

Error: EEXIST: file already exists, mkdir 'Z:\home\site\www\thediewi.bget.ru\public_html\info\index.html'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:791:18)
    at Function.sync (C:\Users\Irina\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:55:12)
    at Object.fsPlus.makeTreeSync (C:\Users\Irina\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:304:23)
    at C:\Users\Irina\.atom\packages\Remote-FTP\lib\connectors\ftp.js:170:10
    at Object.cb (C:\Users\Irina\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:348:5)
    at Parser.<anonymous> (C:\Users\Irina\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:117:20)
    at emitTwo (events.js:87:13)
    at Parser.emit (events.js:169:7)
    at Parser._write (C:\Users\Irina\.atom\packages\Remote-FTP\node_modules\ftp\lib\parser.js:59:10)
```
### Commands

```
  2x -7:00.5.0 core:copy (atom-text-editor.editor)
 14x -1:40.4.0 find-and-replace:select-next (atom-text-editor.editor)
     -1:08.4.0 editor:consolidate-selections (atom-text-editor.editor)
  2x -1:08.4.0 core:cancel (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-css, v0.6.0
autocomplete-snippets, v1.2.0
javascript-snippets, v1.0.0
open-recent, v2.2.0
Remote-FTP, v0.6.2

# Dev
No dev packages
```

**Comment by grenierdev** [comment]
Looks like you tried to create a folder `index.html` where there was already a file with that same name.
