### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Dropbox/work/dev/arkleboyce/site/templates/...

### ISSUE THREAD

**Issue by TomS-** [icetee/remote-ftp#896]
[Enter steps to reproduce:]

1. Create a file called home (for example).
2. Delete file and create a folder called home.
(You'll notice it will have a file icon rather than a folder icon) 
3. Trying to add any files to that folder will create an error however it may display.
4. Trying to open that file will create this error. 

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.3
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.1.2

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir '/Users/mac2/Dropbox/work/dev/arkleboyce/site/templates/inc/home'

```
At /Users/mac2/.atom/packages/Remote-FTP/node_modules/mkdirp/index.js:92

Error: EEXIST: file already exists, mkdir '/Users/mac2/Dropbox/work/dev/arkleboyce/site/templates/inc/home'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
    at Object.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:381:23)
    at /packages/remote-ftp/lib/connectors/ftp.js:186:20
    at /packages/remote-ftp/lib/connectors/ftp.js:218:20
    at Object.cb (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:348:5)
    at /packages/Remote-FTP/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:111:20)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -0:32.8.0 application:open (input.hidden-input)
     -0:28.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:24 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:20.6.0 remote-ftp:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:07.5.0 remote-ftp:refresh-selected (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
file-icons 2.1.8 
Remote-FTP 1.1.2 
```

**Comment by icetee** [comment]
Check this #839

**Comment by icetee** [comment]
Related #112

Thanks for correct steps! I have reproduced.

**Comment by TomS-** [comment]
This is marked as closed, but is still a bug.
