### ISSUE TITLE
Uncaught Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by kevingatera** [icetee/remote-ftp#921]
**Error Log**

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 17.04
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.1.3

### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:160

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:286:12)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3443:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:668:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SSH2Stream.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-sync 0.7.3 
autoclose-html 0.23.0 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
git-plus 7.9.3 
html-template-generator 0.3.0 
intentions 1.1.2 
language-babel 2.68.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-jshint 3.1.5 
linter-ui-default 1.6.3 
nuclide 0.241.0 
playyoutube 1.3.0 
Remote-FTP 1.1.3 
script 3.15.0 
```

**Comment by icetee** [comment]
I think this is a server side problem, not a package issue. Your server drops the socket connection.

**Comment by kevingatera** [comment]
Thank you, it appears I had made a typo in the config file.
