### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Desktop\Project\RayFung Development\razysys...

### ISSUE THREAD

**Issue by RayFungHK** [icetee/remote-ftp#924]
[Enter steps to reproduce:]

1. Double Click on remote-FTP file
2. It happened.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: WIndows 10
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.1.4

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\RayFung\Desktop\Project\RayFung Development\razysystem\module\operation\stockmapping\controller'

```
At C:\Users\RayFung\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:92

Error: EEXIST: file already exists, mkdir 'C:\Users\RayFung\Desktop\Project\RayFung Development\razysystem\module\operation\stockmapping\controller'
    at Error (native)
    at fs.mkdirSync (fs.js:922:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:665:16)
    at Function.sync (/packages/Remote-FTP/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at ConnectorFTP._getFile (/packages/remote-ftp/lib/connectors/ftp.js:200:8)
    at /packages/remote-ftp/lib/connectors/ftp.js:342:14
    at /packages/remote-ftp/lib/connectors/ftp.js:192:7
    at tryApply (/packages/remote-ftp/lib/connectors/ftp.js:12:14)
    at /packages/remote-ftp/lib/connectors/ftp.js:175:7
    at Object.cb (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:526:13)
    at /packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:117:22)
    at emitTwo (events.js:111:20)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/parser.js:61:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:290:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
```

### Non-Core Packages

```
Remote-FTP 1.1.4 
```

**Comment by RayFungHK** [comment]
Ok, there is a bug that you do following procedure
1. "Create File" call abc
2. Delete abc file
3. "Create Folder" call abc
4. Failed on FS.makeTreeSync, because the local folder has created a abc file, conflict with abc folder on server side.

Solve:
delete the abc file in your local poject folder

**Comment by icetee** [comment]
Related of #923
