### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pipe' of undefined

### ISSUE THREAD

**Issue by pastorcreative** [icetee/remote-ftp#946]
[Enter steps to reproduce:]

1. Connect to a remote ftp in a local machine (Connection OK)
2. Click in a remote-folder to download 
3. Error

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 17.04
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.1.3

### Stack Trace

Uncaught TypeError: Cannot read property 'pipe' of undefined

```
At /home/paco/.atom/packages/Remote-FTP/lib/connectors/ftp.js:274

TypeError: Cannot read property 'pipe' of undefined
    at /packages/Remote-FTP/lib/connectors/ftp.js:274:31
    at /packages/Remote-FTP/node_modules/ftp/lib/connection.js:532:14
    at /packages/Remote-FTP/node_modules/ftp/lib/connection.js:887:7
    at /packages/Remote-FTP/node_modules/ftp/lib/connection.js:918:5)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1068:10)
```

### Commands

```
  2x -8:09.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:52.9.0 remote-ftp:toggle (div.tool-panel.tree-view)
     -7:33 remote-ftp:download-selected (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-bootstrap3 1.2.12 
atom-jade 0.3.0 
atom-pug 0.2.0 
codeigniter 0.3.2 
file-icons 2.1.8 
language-pug 0.0.21 
language-stylus 0.2.0 
language-vue 0.23.0 
language-vue-component 0.5.0 
materialize-css 0.3.0 
minimap 4.29.0 
Remote-FTP 1.1.3 
```

**Comment by ecwio** [comment]
i have the same issue

**Comment by rasmus0201** [comment]
Same problem here

**Comment by shaneshuford** [comment]
yup.. same issue.

**Comment by DomenicoRichichi** [comment]
Any solution?

**Comment by xMarcoX** [comment]
My issue was solved by deleting all local files and let atom sync again, I think that Google Drive was trying to access the files to sync them on my google drive folder.

Also, I turned off off Koala my scss compiler to start it after the sync complete

**Comment by 05D0** [comment]
Same here. Updated to latest Pulsar 1.3.1.1 solved the pipe-error.
