### ISSUE TITLE
Uncaught TypeError: path must be a string

### ISSUE THREAD

**Issue by semlette** [icetee/remote-ftp#95]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.199.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.6.2
### Stack Trace

Uncaught TypeError: path must be a string

```
At fs.js:535

TypeError: path must be a string
  at TypeError (native)
  at Object.fs.open (fs.js:535:11)
  at Object.module.(anonymous function) [as open] (ATOM_SHELL_ASAR.js:144:20)
  at WriteStream.open (fs.js:1821:6)
  at new WriteStream (fs.js:1811:10)
  at Object.fs.createWriteStream (fs.js:1777:10)
  at C:\Users\Andi\.atom\packages\Remote-FTP\lib\connectors\ftp.js:193:22
  at Object.cb (C:\Users\Andi\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:617:11)
  at Parser.<anonymous> (C:\Users\Andi\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:117:20)
  at emitTwo (events.js:87:13)
  at Parser.emit (events.js:169:7)
  at Parser._write (C:\Users\Andi\.atom\packages\Remote-FTP\node_modules\ftp\lib\parser.js:59:10)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at Parser.Writable.write (_stream_writable.js:210:11)
  at Socket.ondata (C:\Users\Andi\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:273:20)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at TCP.onread (net.js:517:20)

```
### Commands

```
     -0:34.8.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -0:28.3.0 remote-ftp:connect (atom-text-editor.editor.is-focused)
     -0:14.8.0 tree-view:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "seti-monokai"
    ],
    "disabledPackages": [
      "remote-edit"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-color-highlight, v3.0.9
color-picker, v1.7.0
css-color-highlight, v0.3.0
file-icons, v1.5.5
linter, v0.12.2
Remote-FTP, v0.6.2
seti-monokai, v0.3.1

# Dev
No dev packages
```

**Comment by grenierdev** [comment]
Can you update to v0.7 and try again?
