### ISSUE TITLE
Uncaught TypeError: "string" must be a string, Buffer, or ArrayBuffer

### ISSUE THREAD

**Issue by maxswjeon** [icetee/remote-ftp#962]
I am using 8192 bit key with Google Authenticator.
So AutheticationMethod is publickey,keyboard-interactive
I can access to sftp with Bitvise SSH Client

Please Help..

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Windows 10 Pro 10.0.15063 build 15063
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.1.3

### Stack Trace

Uncaught TypeError: "string" must be a string, Buffer, or ArrayBuffer

```
At buffer.js:362

TypeError: "string" must be a string, Buffer, or ArrayBuffer
    at Function.byteLength (buffer.js:362:11)
    at SSH2Stream.authInfoRes (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:1826:34)
    at /packages/Remote-FTP/node_modules/ssh2/lib/client.js:495:24
    at /packages/remote-ftp/lib/connectors/sftp.js:100:9)
    at emitMany (events.js:127:13)
    at Client.emit (events.js:201:7)
    at SSH2Stream.onUSERAUTH_INFO_REQUEST (/packages/Remote-FTP/node_modules/ssh2/lib/client.js:489:10)
    at emitMany (events.js:127:13)
    at SSH2Stream.emit (events.js:201:7)
    at parse_USERAUTH (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:4292:12)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:4018:12)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:668:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SSH2Stream.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Non-Core Packages

```
Remote-FTP 1.1.3 
```

### .ftpconfig File

```
{
    "protocol": "sftp",
    "host": "$HOSTNAME",
    "port": 227,
    "user": "$USER",
    "pass": "",
    "promptForPass": false,
    "remote": "/",
    "local": "",
    "agent": "",
    "privatekey": "C:/Users/maxsw/Desktop/Server/Development/id_rsa",
    "passphrase": "**********",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": true,
    "remoteCommand": "",
    "remoteShell": "",
    "watch": [],
    "watchTimeout": 500
}
```

**Comment by maxswjeon** [comment]
Bug found and breakthrough is setting the pass to keyboard-interactive password.
I think it should ask the keyboard-interactive password individually, as the user that uses ssh AuthenticationMethod is password,keyboard-interactive.

**Comment by icetee** [comment]
I install a droplet (VPS) with Google Authenticator and look the issue.
I ask for your patience.

**Comment by icetee** [comment]
The error message will really come.

I solved this by:
`"promptForPass": true,`

**Comment by maxswjeon** [comment]
No.. You should not patch like that.
Using promptForPass edits passphrase of the publicKey or the password.
It makes problems that users use SSH AuthenticationMethods publickey,keyboard-interactive or password,keyboard-interactive.
We should prompt a new window for keyboard-interactive only.

**Comment by maxswjeon** [comment]
Posting the fix I made.
I couldn't Test the fix so could you test it for me?
The keyboard-interactive vertification code should saved as vertifyCode and promt dialog only for keyboard-interactive method.

**Comment by maxswjeon** [comment]
Made a fix.
Added a dialog (I copied prompt-pass-dialog and made a little change)

**Comment by icetee** [comment]
It's work! But no best way duplicate file with a minimum difference.
I do no thinks so there's new setting because it always changes.

Do you know how to look at this? https://github.com/icetee/remote-ftp/commit/8f442823ed63a1289bdaf27fe49ddd7297806501

**Comment by maxswjeon** [comment]
No, it effects users that uses authentication method password **with** keyboard-interactive. I think using the PromptForPassword is good, but editing the password should be sublimated.

**Comment by icetee** [comment]
I changed https://github.com/icetee/remote-ftp/commit/0a2a737d2d27efa56ee003c8305ee2e10acc7c59, thanks for the help.

**Comment by maxswjeon** [comment]
That was the right thing to do! Thank you so much listening to my bug report!
