### ISSUE TITLE
Uncaught TypeError: Cannot read property 'list' of null

### ISSUE THREAD

**Issue by siteleas** [icetee/remote-ftp#981]
[Enter steps to reproduce:]

1. Right clicked the panel, chose disconnect
2. Closed the panel and BAM!

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Linux Mint
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.1.3

### Stack Trace

Uncaught TypeError: Cannot read property 'list' of null

```
At /home/ampps/.atom/packages/Remote-FTP/lib/connectors/ftp.js:129

TypeError: Cannot read property 'list' of null
    at /packages/Remote-FTP/lib/connectors/ftp.js:129:21)
    at /packages/Remote-FTP/lib/connectors/ftp.js:140:21
    at Array.forEach (native)
    at /packages/Remote-FTP/lib/connectors/ftp.js:133:21
    at final (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:476:11)
    at Socket.ondone (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:451:7)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
  3x -2:19.7.0 core:move-up (input.hidden-input)
     -2:13.8.0 core:confirm (input.hidden-input)
     -2:13.8.0 settings-view:view-installed-themes (input.hidden-input)
     -1:52.3.0 command-palette:toggle (button.btn.icon.enablement.icon-playback-pause)
  2x -1:46.9.0 editor:select-to-first-character-of-line (input.hidden-input)
  4x -1:30.7.0 core:backspace (input.hidden-input)
     -0:56.6.0 command-palette:toggle (div.tool-panel.tree-view)
     -0:50.4.0 core:move-down (input.hidden-input)
  2x -0:49.8.0 core:move-up (input.hidden-input)
     -0:48.9.0 core:confirm (input.hidden-input)
     -0:48.9.0 settings-view:install-packages-and-themes (div.tool-panel.tree-view)
     -0:29.1.0 remote-ftp:download-selected-local (span.name.icon.icon-file-text)
     -0:29.1.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-always.theme-duotone-dark-space-syntax.theme-atom-material-ui)
     -0:27.8.0 remote-ftp:download-selected-local (atom-workspace.workspace.scrollbars-visible-always.theme-duotone-dark-space-syntax.theme-atom-material-ui)
  2x -0:23.7.0 remote-ftp:toggle (div.tool-panel.tree-view)
     -0:15.5.0 remote-ftp:disconnect (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
aligner undefined 
aligner-javascript 1.3.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.5 
atom-css-clean 2.23.0 
atom-css-comb 3.3.1 
atom-live-server 2.1.2 
atom-material-ui 2.0.4 
atom-minify 0.8.0 
atom-runner 2.7.1 
atom-silverstripe 3.3.0 
atom-ternjs 0.18.3 
autohide-tree-view 0.25.1 
bottom-dock 0.4.4 
browser-plus 0.0.98 
busy-signal 1.4.3 
change-case 0.6.5 
chary-tree-view 0.2.13 
close-unmodified-tabs 1.0.1 
color-picker 2.2.5 
css-skeleton-maker 0.1.4 
custom-folds 1.9.5 
docblockr 0.11.0 
duotone-dark-space-syntax 2.1.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.12 
filesize 3.0.0 
fold-navigator 0.0.620 
git-clone 0.2.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
grunt-manager 0.1.16 
grunt-snippets 0.1.1 
highlight-line 0.12.0 
highlight-selected 0.13.1 
hyperclick-php 0.2.1 
intentions 1.1.5 
javascript-snippets 1.2.1 
jumpy 3.1.3 
keybinding-cheatsheet 0.1.1 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-php 1.5.1 
linter-sass-lint 1.8.0 
linter-tidy 2.3.1 
linter-ui-default 1.6.10 
markdown-mindmap 0.4.1 
maximize-panes 0.2.0 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-autohide 0.10.1 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.1 
open-in-browser 0.5.2 
open-terminal-here 2.3.1 
package-list 0.1.2 
php-cs-fixer 4.1.1 
php-debug 0.2.5 
pigments 0.40.2 
pinned-tabs 1.3.0 
print-code 0.7.1 
prisma-ui 1.0.5 
project-view 0.6.2 
project-viewer 1.2.0 
rainbow-tabs 2.5.1 
react-redux-atom-snippets 0.7.2 
remote-edit 1.9.0 
Remote-FTP 1.1.3 
rest-client 1.3.1 
restart-atom 0.2.0 
scaffolding 1.1.0 
set-syntax 0.4.0 
seti-ui 1.9.0 
silverstripe-bundle 0.3.0 
silverstripe-syntax-and-snippets 0.4.0 
simple-drag-drop-text 0.3.6 
snippet-generator 0.3.2 
sort-lines 0.15.0 
sphinx-preview 0.1.1 
split-diff 1.5.1 
sync-settings 0.8.3 
tabs-closer 0.16.0 
tidy-tabs 0.4.0 
todo 0.6.0 
todo-manager 0.2.10 
todo-show 2.0.0 
tokamak-terminal 10.0.1 
tree-view-autoresize 2.2.0 
tree-view-copy-relative-path 1.2.0 
tree-view-extended 2.0.0 
turbo-javascript 1.4.0 
wakatime 7.0.3 
which-key 0.3.3 
```

**Comment by icetee** [comment]
Related of https://github.com/icetee/remote-ftp/issues/183#issuecomment-289021153
