### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mkdir' of null

### ISSUE THREAD

**Issue by nadyshalaby** [icetee/remote-ftp#988]
[Enter steps to reproduce:]

1. select folder
2. add file

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.1.3

### Stack Trace

Uncaught TypeError: Cannot read property 'mkdir' of null

```
At /Users/corecave/.atom/packages/Remote-FTP/lib/connectors/ftp.js:420

TypeError: Cannot read property 'mkdir' of null
    at /packages/remote-ftp/lib/connectors/ftp.js:420:21
    at final (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:476:11)
    at Socket.ondone (/packages/Remote-FTP/node_modules/ftp/lib/connection.js:451:7)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
  2x -7:22.7.0 core:select-right (input.hidden-input)
     -7:22 core:backspace (input.hidden-input)
     -7:16.4.0 core:paste (input.hidden-input)
     -7:08.0 core:copy (input.hidden-input)
     -7:02.6.0 core:paste (input.hidden-input)
     -4:41 core:move-left (input.hidden-input)
     -4:37.5.0 core:delete (input.hidden-input)
     -4:36.2.0 core:move-right (input.hidden-input)
     -4:29.2.0 core:copy (input.hidden-input)
     -4:26.9.0 core:paste (input.hidden-input)
     -1:26.7.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -1:22.4.0 core:confirm (input.hidden-input)
     -0:26.8.0 remote-ftp:disconnect (span.name.icon.icon-file-directory)
     -0:15.3.0 remote-ftp:add-file (span.name.icon.icon-file-directory)
  2x -0:12.6.0 core:backspace (input.hidden-input)
     -0:09.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
angularjs 0.4.0 
atom-autocomplete-php 0.25.6 
atom-typescript 11.0.9 
auto-indent 0.5.0 
autocomplete-js-import 1.4.0 
autocomplete-php 0.3.7 
blade-snippets 0.2.0 
blade-spacer 0.4.2 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.11.0 
emmet 2.4.3 
hyperclick 0.1.5 
intentions 1.1.5 
ionic-framework-snippets 1.2.1 
js-hyperclick 1.11.1 
language-blade 0.36.0 
language-vue 0.23.1 
language-vue-component 0.5.0 
laravel 0.7.1 
laravel-5-snippets 0.8.0 
linter 2.2.0 
linter-eslint 8.3.2 
linter-php 1.5.1 
linter-ui-default 1.6.10 
open-terminal-here 2.3.1 
php-hyperclick 1.2.1 
php-integrator-annotations 1.2.0 
php-integrator-autocomplete-plus 1.6.0 
php-integrator-base 3.0.1 
php-integrator-call-tips-legacy-php56 1.2.3 
php-integrator-linter-legacy-php56 1.3.1 
php-integrator-navigation 1.2.1 
php-integrator-refactoring 1.4.1 
php-integrator-tooltips-legacy-php56 1.1.6 
platformio-ide-terminal 2.7.0 
project-manager 3.3.5 
Remote-FTP 1.1.3 
vue2-autocomplete 0.1.0-alpha.4 
vuejs2-snippets 0.12.1 
```

**Comment by icetee** [comment]
Changed the file, is it in the new version?

**Comment by icetee** [comment]
There was no reply.
