### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by jluisfa** [icetee/remote-ftp#993]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.2.1

### Stack Trace

Uncaught TypeError: Cannot convert undefined or null to object

```
At /Users/joseluisfreitasandrade/.atom/packages/Remote-FTP/lib/views/permission-view.js:218

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at PermissionView.initialize (/packages/remote-ftp/lib/views/permission-view.js:218:12)
    at /packages/Remote-FTP/node_modules/space-pen/lib/space-pen.js:184:25)
    at /packages/remote-ftp/lib/views/permission-view.js:7:21)
    at HTMLElement.command (/packages/remote-ftp/lib/menus/commands.js:691:28)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1354:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:348:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -4:28.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -4:17.1.0 remote-ftp:permission-selected (span.name.icon.gear-icon.medium-red)
     -0:56.9.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
emmet 2.4.3 
file-icons 2.1.12 
Remote-FTP 1.2.1 
```

**Comment by icetee** [comment]
Can you tell me what the server service name is? Example: vsFTPd, ProFTPd, PureFTPd, etc...
It is likely that the server will not return these values.

**Comment by jluisfa** [comment]
ftpconfig:
    "protocol": "sftp",
    "host": "ftp.joseluisandrade.com",
    "port": 29,
    "user": "*********",
    "pass": "*********",
    "promptForPass": false,
    "remote": "/home/joseluis/public_html",
    "local": "",
    "agent": "",
    "privatekey": "",
    "passphrase": "",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": false,
    "remoteCommand": "",
    "remoteShell": "",
    "watch": [],
    "watchTimeout": 500

**Comment by icetee** [comment]
Yep, in SFTP no implemented. In the new version, you'll get a notification for the moment.
Thanks for report!

**Comment by lewismoten** [comment]
I had the same problem today. A quick fix was to log into the host with ssh and use `sudo chmode` on the remote folder to fix the permissions. Afterwards this package worked great.
