### ISSUE TITLE
I have not access when i upgrade the latest version

### ISSUE THREAD

**Issue by ycyusuf** [icetee/remote-ftp#995]
`[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /Users/.../.atom/packages/Remote-FTP/lib/connectors/ftp.js:176

TypeError: Cannot read property 'indexOf' of undefined
    at ConnectorFTP.type (/packages/remote-ftp/lib/connectors/ftp.js:176:36)
    at ConnectorFTP.get (/packages/remote-ftp/lib/connectors/ftp.js:369:10)
    at /packages/remote-ftp/lib/client.js:611:26)
    at Client._next (/packages/remote-ftp/lib/client.js:549:41)
    at Client._enqueue (/packages/remote-ftp/lib/client.js:559:58)
    at /packages/remote-ftp/lib/client.js:610:14)
    at Client.onceConnected (/packages/remote-ftp/lib/client.js:315:19)
    at Client.download (/packages/remote-ftp/lib/client.js:609:12)
    at File.open (/packages/remote-ftp/lib/file.js:43:12)
    at FileView.open (/packages/remote-ftp/lib/views/file-view.js:104:15)
    at /packages/remote-ftp/lib/views/file-view.js:88:12)
    at HTMLLIElement.dispatch (/packages/Remote-FTP/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLLIElement.elemData.handle (/packages/Remote-FTP/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:22.1.0 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-csslint 2.0.0 
linter-php 1.5.1 
linter-tidy 2.3.1 
linter-ui-default 1.6.10 
Remote-FTP 1.2.0 
```

`

**Comment by icetee** [comment]
See new version.

**Comment by ycyusuf** [comment]
Thank's
