### ISSUE TITLE
Uncaught TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by cotumaccio** [icetee/remote-ftp#998]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: [Remote-FTP](https://github.com/icetee/remote-ftp) package 1.2.3

### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At /Users/gianfranco/.atom/packages/Remote-FTP/lib/connectors/sftp.js:406

TypeError: Cannot read property 'message' of undefined
    at /packages/remote-ftp/lib/connectors/sftp.js:406:33)
    at emitOne (events.js:101:20)
    at WriteStream.emit (events.js:188:7)
    at /packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:2853:12
    at SFTPStream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:415:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SFTPStream.Writable.write (_stream_writable.js:245:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:3444:10)
    at SSH2Stream._transform (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/Remote-FTP/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SSH2Stream.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -0:27.6.0 core:save (input.hidden-input)
     -0:19.3.0 remote-ftp:upload-selected (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.4 
atom-monokai 0.10.9 
color-picker 2.2.5 
color-tabs 0.1.8 
editorconfig 2.2.2 
es6-javascript 1.0.0 
isotope-ui 2.8.5 
javascript-snippets 1.2.1 
jQuery 1.2.5 
jquery-snippets 11.0.0 
lessc-on-save 0.4.0 
material-ui 1.0.10 
native-ui 0.23.0 
pigments 0.40.2 
quick-query 0.12.1 
remote-atom 1.3.11 
remote-edit 1.9.0 
Remote-FTP 1.2.3 
SFTP-deployment 1.0.2 
turbo-javascript 1.4.0 
unity-ui 2.1.11 
```

**Comment by Barulin** [comment]
Had the same issue today. The problem was with the permissions to files I tried to edit. So, I'd reccomend firstly to check files permissions and ownership.

**Comment by icetee** [comment]
Related of https://github.com/icetee/remote-ftp/issues/993#issuecomment-334456224

(Soon it will arrive to SFTP.)

**Comment by jeromystewart** [comment]
I've setup 6 servers and even made the FTP user owner of the entire directory structure for my project and set all permissions to 777 .. in each and every case I get this same error. It's hard to place any blame on a free product but geesh, how can this not work for me when everyone else seems to be using it with no issues.
