### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by samuelesantoni** [icetee/remote-ftp#999]
If i try to upload files in remote ftp (version 1.2.4) with drag and drop i have this issue.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package undefined

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /packages/remote-ftp/lib/views/directory-view.js:140:30)
    at HTMLLIElement.dispatch (/packages/Remote-FTP/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLLIElement.elemData.handle (/packages/Remote-FTP/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -8:36.4.0 application:open (ul.list-inline.tab-bar.inset-panel)
     -7:46.4.0 pane:split-right-and-copy-active-item (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -7:37.2.0 application:open (atom-pane.pane.active)
     -7:19.1.0 pane:close (div.item-views)
  2x -6:23.2.0 remote-ftp:toggle (div.header.list-item)
     -5:24.6.0 application:open (atom-pane.pane.active)
     -4:13.3.0 pane:split-up-and-copy-active-item (div.header.list-item)
```

### Non-Core Packages

```
auto-indent 0.5.0 
autoclose-html 0.23.0 
Delete-Whitelines 0.6.3 
doont-spotify 0.1.0 
file-icons 2.1.12 
grammar-tab-colors 0.2.8 
highlight-selected 0.13.1 
pigments 0.40.2 
Remote-FTP 1.2.4 
uikit-atom 0.2.2 
```

**Comment by bashbers** [comment]
Getting the same error when trying to move a file into a ftp folder.
No non-core packages installed.

**Comment by yetbad** [comment]
@bashbers How do I resolve this issue? Do I have to install some packets?

**Comment by Jorge4ugusto** [comment]
help i dont understand this post

**Comment by samuelesantoni** [comment]
For now is impossible upload or download files with drag and drop. I don't know if there are some package for solve this problem. I hope the developer of Remote FTP help us.

**Comment by samuelesantoni** [comment]
News for upload file with drag and drop?

**Comment by 1andee** [comment]
+1

**Comment by fearmyflames** [comment]
+1

**Comment by littleread** [comment]
+1

**Comment by gymnae** [comment]
+1

**Comment by icetee** [comment]
I will try to solve it soon. I'm welcome to pull request! 🙊

**Comment by KyNorthstar** [comment]
I have this issue when drag-dropping a file onto the remote tree
